using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Astronomy.MediaFactory.ProductionAdapters;
using FluentAssertions;

namespace Astronomy.MediaFactory.Tests.ProductionAdapters;
public sealed class DocumentarySceneDependencyResolverTests
{
 [Fact] public async Task Empty_visual_set_is_rejected(){var r=DocumentarySceneCompositionTestFixtures.Request([]);var result=await new DocumentarySceneDependencyResolver(new DocumentaryPhysicalArtifactRegistry()).ResolveAsync(r,Workspace(),default);result.Failure!.Code.Should().Be(DocumentaryProductionFailureCode.SourceArtifactMissing);}
 [Fact] public async Task Missing_visual_is_rejected(){var result=await new DocumentarySceneDependencyResolver(new DocumentaryPhysicalArtifactRegistry()).ResolveAsync(DocumentarySceneCompositionTestFixtures.Request(),Workspace(),default);result.Failure!.Code.Should().Be(DocumentaryProductionFailureCode.SourceArtifactMissing);}
 [Fact] public async Task Finalized_visuals_are_stably_ordered_and_inputs_are_not_mutated(){using var temp=new Temp();var a=await temp.File("a.jpg");var b=await temp.File("b.png");var registry=new DocumentaryPhysicalArtifactRegistry();await registry.RegisterAsync(DocumentarySceneCompositionTestFixtures.Descriptor("b",b,"image/png"),DocumentaryPhysicalArtifactKind.VisualImage,default);await registry.RegisterAsync(DocumentarySceneCompositionTestFixtures.Descriptor("a",a,"image/jpeg"),DocumentaryPhysicalArtifactKind.VisualImage,default);var visuals=new[]{DocumentarySceneCompositionTestFixtures.Asset("b",DocumentaryMediaAssetType.VisualImage,DocumentaryMediaAssetFormat.Png,DocumentaryMediaAssetStatus.Generated),DocumentarySceneCompositionTestFixtures.Asset("a",DocumentaryMediaAssetType.VisualImage,DocumentaryMediaAssetFormat.Jpeg,DocumentaryMediaAssetStatus.Generated)};var request=DocumentarySceneCompositionTestFixtures.Request(visuals);var before=request.ToString();var result=await new DocumentarySceneDependencyResolver(registry).ResolveAsync(request,temp.Workspace,default);result.Succeeded.Should().BeTrue();result.Dependencies!.VisualArtifacts.Select(x=>x.AssetId).Should().Equal("b","a");request.ToString().Should().Be(before);}
 [Fact] public async Task Silent_scene_uses_explicit_duration(){using var temp=new Temp();var path=await temp.File("v.png");var registry=new DocumentaryPhysicalArtifactRegistry();await registry.RegisterAsync(DocumentarySceneCompositionTestFixtures.Descriptor("visual",path,"image/png"),DocumentaryPhysicalArtifactKind.VisualImage,default);var result=await new DocumentarySceneDependencyResolver(registry).ResolveAsync(DocumentarySceneCompositionTestFixtures.Request(),temp.Workspace,default);result.Succeeded.Should().BeTrue();result.Dependencies!.NarrationArtifact.Should().BeNull();result.Dependencies.SceneDurationMilliseconds.Should().Be(2000);}
 static DocumentaryProductionWorkspace Workspace(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));return new(root,root,Path.Combine(root,"variants"),Path.Combine(root,"attempts"),Path.Combine(root,"diagnostics"));}
 sealed class Temp:IDisposable{public string Root{get;}=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));public DocumentaryProductionWorkspace Workspace=>new(Root,Root,Path.Combine(Root,"variants"),Path.Combine(Root,"attempts"),Path.Combine(Root,"diagnostics"));public Temp()=>Directory.CreateDirectory(Root);public async Task<string> File(string name){var p=Path.Combine(Root,name);await System.IO.File.WriteAllBytesAsync(p,[1]);return p;}public void Dispose()=>Directory.Delete(Root,true);}
}
