using Astronomy.MediaFactory.Core.DocumentaryBlueprint;using Astronomy.MediaFactory.ProductionAdapters;using Microsoft.Extensions.Options;using Xunit;
namespace Astronomy.MediaFactory.Tests.ProductionAdapters;
public sealed class DocumentaryMediaVerificationEvaluatorTests {
 [Fact] public void Valid_narration_audio_is_verified(){var r=new DocumentaryMediaVerificationRequest("a",DocumentaryMediaAssetType.NarrationAudio,DocumentaryMediaAssetFormat.Wav,DocumentaryPhysicalArtifactKind.NarrationAudio,"c",1,ExpectedDurationMilliseconds:1000,ExpectedAudioSampleRate:48000,ExpectedAudioChannelCount:1,RequireAudio:true,AllowAudio:true);var x=Evaluate(r,new(true,1000,false,true,false,AudioSampleRate:48000,AudioChannelCount:1,ContainerFormat:"wav"));Assert.True(x.Verified);Assert.Equal(DocumentaryMediaVerificationPolicyIds.NarrationAudioVerificationV1,x.Evidence.VerificationPolicyId);}
 [Fact] public void Valid_scene_video_is_verified(){var r=Video(DocumentaryPhysicalArtifactKind.SceneVideo,DocumentaryMediaAssetType.SceneVideo);Assert.True(Evaluate(r,Probe()).Verified);}
 [Fact] public void Valid_variant_video_is_verified(){var r=Video(DocumentaryPhysicalArtifactKind.VariantVideo,DocumentaryMediaAssetType.VariantVideo);Assert.True(Evaluate(r,Probe()).Verified);}
 [Fact] public void Violations_have_deterministic_policy_order(){var r=Video(DocumentaryPhysicalArtifactKind.SceneVideo,DocumentaryMediaAssetType.SceneVideo);var x=Evaluate(r,new(true,0,false,false,false,ContainerFormat:"wav"));Assert.Equal(new[]{"container","video-stream","audio-stream-required","duration","width","height","frame-rate"},x.Evidence.Violations.Select(v=>v.RuleId));}
 static DocumentaryMediaVerificationRequest Video(DocumentaryPhysicalArtifactKind k,DocumentaryMediaAssetType t)=>new("a",t,DocumentaryMediaAssetFormat.Mp4,k,"c",1,ExpectedDurationMilliseconds:1000,ExpectedWidth:1920,ExpectedHeight:1080,ExpectedFrameRate:30,ExpectedAudioSampleRate:48000,ExpectedAudioChannelCount:2,RequireVideo:true,RequireAudio:true);
 static DocumentaryMediaProbeResult Probe()=>new(true,1000,true,true,false,1920,1080,30,48000,2,"mov,mp4,m4a,3gp,3g2,mj2");
 static DocumentaryMediaVerificationEvaluation Evaluate(DocumentaryMediaVerificationRequest r,DocumentaryMediaProbeResult p){var policy=new DocumentaryMediaVerificationPolicyResolver().Resolve(r);var a=new DocumentaryPhysicalArtifactDescriptor(r.AssetId,"sha256:"+new string('a',64),"/final/media",r.ExpectedContentType??"video/mp4",1,new string('a',64),null,null,null,null,null,null,"provider",1,r.CorrelationId);return new DocumentaryMediaVerificationEvaluator(Options.Create(new DocumentaryMediaVerificationAdapterOptions())).Evaluate(r,a,p,policy);}
}
