using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Astronomy.MediaFactory.ProductionAdapters;
using FluentAssertions;
namespace Astronomy.MediaFactory.Tests.ProductionAdapters;
public sealed class DocumentarySceneCompositionResultMapperTests
{
 [Fact] public void Success_maps_certified_descriptor_without_mutating_request(){var request=DocumentarySceneCompositionTestFixtures.Request();var before=request.ToString();var d=new DocumentaryPhysicalArtifactDescriptor("scene-video","sha256:abc","/final.mp4","video/mp4",42,"abc",2000,1920,1080,30,null,null,"provider",2,DocumentarySceneCompositionTestFixtures.Correlation);var source=DocumentaryProductionSceneCompositionAdapterResult.Success(d,"provider","scene-1","LongEnglish",2000,1920,1080,30,true,DocumentarySceneSubtitleMode.None,"diag");var result=new DocumentarySceneCompositionResultMapper().Map(request,source);result.Status.Should().Be(DocumentaryMediaAssetStatus.Generated);result.AssetResult.Should().BeEquivalentTo(new{AssetId="scene-video",AssetType=DocumentaryMediaAssetType.SceneVideo,AssetFormat=DocumentaryMediaAssetFormat.Mp4,ProviderId="provider",ContentIdentity="sha256:abc",ContentLength=42L,DurationMilliseconds=2000L,Width=1920,Height=1080,FrameRate=30,Checksum="abc",AttemptCount=2,CorrelationId=DocumentarySceneCompositionTestFixtures.Correlation});request.ToString().Should().Be(before);}
 [Fact] public void Failure_preserves_safe_code_attempt_and_correlation(){var request=DocumentarySceneCompositionTestFixtures.Request();var source=DocumentaryProductionSceneCompositionAdapterResult.Failed(new(DocumentaryProductionFailureCode.ProviderRejectedRequest,"safe"),"scene-1","LongEnglish",DocumentarySceneSubtitleMode.None);var result=new DocumentarySceneCompositionResultMapper().Map(request,source);result.Status.Should().Be(DocumentaryMediaAssetStatus.Failed);result.AssetResult.FailureCode.Should().Be("ProviderRejectedRequest");result.AssetResult.FailureMessage.Should().Be("safe");result.AssetResult.AttemptCount.Should().Be(request.Attempt);result.AssetResult.CorrelationId.Should().Be(request.CorrelationId);}
}
