using Astronomy.MediaFactory.Contracts;using Astronomy.MediaFactory.ProductionAdapters;using Astronomy.MediaFactory.Rendering;using Microsoft.Extensions.Configuration;using Microsoft.Extensions.DependencyInjection;using Microsoft.Extensions.Options;using Xunit;
namespace Astronomy.MediaFactory.Tests.ProductionAdapters;
public sealed class DocumentaryMediaVerificationDiTests {
 static ServiceProvider Provider(){var c=new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string,string?>{{"Rendering:FfprobePath","never-run"}}).Build();var s=new ServiceCollection();s.AddLogging();s.AddSingleton<IAzureSpeechClient,FakeAzure>();s.AddSingleton<ISsmlBuilder,FakeSsml>();s.AddSingleton<IProcessRunner,A39RecordingProcessRunner>();s.AddDocumentaryProductionBridge(c);return s.BuildServiceProvider(new ServiceProviderOptions{ValidateScopes=false,ValidateOnBuild=false});}
 [Fact] public void Bridge_registers_all_media_verification_services(){using var p=Provider();using var scope=p.CreateScope();var s=scope.ServiceProvider;Assert.NotNull(s.GetRequiredService<IDocumentaryFfprobeResultParser>());Assert.NotNull(s.GetRequiredService<IDocumentaryFfprobeProbe>());Assert.NotNull(s.GetRequiredService<IDocumentaryMediaProbe>());Assert.NotNull(s.GetRequiredService<IDocumentaryMediaVerificationPolicyResolver>());Assert.NotNull(s.GetRequiredService<IDocumentaryMediaVerificationEvaluator>());Assert.NotNull(s.GetRequiredService<IDocumentaryMediaVerificationProviderBinding>());Assert.NotNull(s.GetRequiredService<IDocumentaryProductionMediaVerificationAdapter>());Assert.NotNull(s.GetRequiredService<IDocumentaryMediaVerificationResultMapper>());Assert.NotNull(s.GetRequiredService<IDocumentaryProductionAdapterRegistry>());}
 [Fact] public void Adapter_registry_exposes_media_verification(){using var p=Provider();using var scope=p.CreateScope();var r=scope.ServiceProvider.GetRequiredService<IDocumentaryProductionAdapterRegistry>();Assert.NotNull(r.MediaVerification);Assert.True(r.IsAvailable(DocumentaryProductionOperationKind.MediaVerification));}
 [Fact] public void Media_verification_is_disabled_by_default(){using var p=Provider();Assert.False(p.GetRequiredService<IOptions<DocumentaryMediaVerificationAdapterOptions>>().Value.Enabled);}
 [Fact] public void Production_bridge_uses_real_ffprobe_probe_by_default(){using var p=Provider();Assert.IsType<ExistingFfprobeDocumentaryMediaProbe>(p.GetRequiredService<IDocumentaryMediaProbe>());Assert.Same(p.GetRequiredService<IDocumentaryMediaProbe>(),p.GetRequiredService<IDocumentaryFfprobeProbe>());}
 [Fact] public async Task Duplicate_media_verification_provider_bindings_are_rejected_deterministically(){await using var f=await DocumentaryMediaVerificationAdapterFixture.NarrationAudio();var second=new FakeMediaVerificationProviderBinding();var a=new DocumentaryProductionMediaVerificationAdapter(Options.Create(new DocumentaryMediaVerificationAdapterOptions{Enabled=true}),f.Registry,new DocumentaryPhysicalArtifactDescriptorValidator(f.ContentIdentityFactory),f.ChecksumService,new DocumentaryMediaVerificationPolicyResolver(),[f.ProviderBinding,second],new DocumentaryMediaVerificationEvaluator(Options.Create(new DocumentaryMediaVerificationAdapterOptions())),f.DiagnosticsWriter,new DocumentarySafeFileNameGenerator(),new DocumentaryProductionFailureNormalizer());var x=await a.VerifyAsync(f.Request,f.ExecutionContext,f.AttemptContext,f.Workspace,default);Assert.Equal(DocumentaryProductionFailureCode.AdapterUnavailable,x.Failure!.Code);Assert.Equal(0,f.ProviderBinding.InvocationCount);Assert.Equal(0,second.InvocationCount);}
 sealed class FakeAzure:IAzureSpeechClient{public Task<byte[]> SynthesizeMp3Async(string text,AzureSpeechOptions o,CancellationToken t)=>Task.FromResult(Array.Empty<byte>());public Task<byte[]> SynthesizeWavSsmlAsync(string s,AzureSpeechOptions o,CancellationToken t)=>Task.FromResult(Array.Empty<byte>());} sealed class FakeSsml:ISsmlBuilder{public string BuildSsml(string t,string v,SsmlNarrationProfile? p=null,string? r=null,string? pitchOverride=null)=>t;}
}
