using Astronomy.MediaFactory.ProductionAdapters;
using Astronomy.MediaFactory.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Astronomy.MediaFactory.Tests.ProductionAdapters;

public sealed class DocumentaryNarrationArchitectureTests
{
    [Fact] public void Adapter_has_no_prohibited_or_subtitle_dependencies(){var parameters=typeof(ExistingAzureSpeechDocumentaryNarrationAdapter).GetConstructors().Single().GetParameters().Select(x=>x.ParameterType.FullName!).ToArray();Assert.DoesNotContain(parameters,x=>x.Contains("Subtitle",StringComparison.OrdinalIgnoreCase));Assert.DoesNotContain(parameters,x=>x.Contains("SceneRenderer",StringComparison.OrdinalIgnoreCase)||x.Contains("VariantRenderer",StringComparison.OrdinalIgnoreCase)||x.Contains("Storage",StringComparison.OrdinalIgnoreCase)||x.Contains("Publishing",StringComparison.OrdinalIgnoreCase)||x.Contains("FFprobe",StringComparison.OrdinalIgnoreCase));}
    [Fact] public void Provider_id_and_typed_registry_contract_are_stable(){Assert.Equal("AzureSpeech",DocumentaryNarrationProviderIds.AzureSpeech);Assert.Equal(typeof(IDocumentaryProductionNarrationAdapter),typeof(IDocumentaryProductionAdapterRegistry).GetProperty(nameof(IDocumentaryProductionAdapterRegistry.NarrationSynthesis))!.PropertyType);}
    [Fact] public void Narration_source_has_no_blocking_async_patterns(){var root=FindRepositoryRoot();var source=File.ReadAllText(Path.Combine(root,"Backend/src/Astronomy.MediaFactory.ProductionAdapters/NarrationAdapter.cs"));foreach(var pattern in new[]{".Result",".Wait(",".GetAwaiter().GetResult(","Task.Run("})Assert.DoesNotContain(pattern,source,StringComparison.Ordinal);}
    [Fact] public void Core_project_does_not_reference_production_adapters(){var root=FindRepositoryRoot();var project=File.ReadAllText(Path.Combine(root,"Backend/src/Astronomy.MediaFactory.Core/Astronomy.MediaFactory.Core.csproj"));Assert.DoesNotContain("ProductionAdapters",project,StringComparison.Ordinal);}
    [Fact] public void Service_collection_resolves_narration_graph_without_enabling_it(){var values=new Dictionary<string,string?>();var configuration=new ConfigurationBuilder().AddInMemoryCollection(values).Build();var services=new ServiceCollection();services.AddLogging();services.AddSingleton<IAzureSpeechClient,newFakeClient>();services.AddSingleton<ISsmlBuilder,FakeSsmlBuilder>();services.AddDocumentaryProductionBridge(configuration);using var provider=services.BuildServiceProvider();using var scope=provider.CreateScope();Assert.NotNull(scope.ServiceProvider.GetRequiredService<IDocumentaryNarrationVoiceResolver>());Assert.NotNull(scope.ServiceProvider.GetRequiredService<IDocumentaryNarrationAudioInspector>());Assert.NotNull(scope.ServiceProvider.GetRequiredService<IDocumentaryNarrationAudioNormalizer>());Assert.NotNull(scope.ServiceProvider.GetRequiredService<IDocumentaryNarrationProviderBinding>());Assert.NotNull(scope.ServiceProvider.GetRequiredService<IDocumentaryProductionNarrationAdapter>());Assert.NotNull(scope.ServiceProvider.GetRequiredService<IDocumentaryNarrationSynthesisResultMapper>());Assert.True(scope.ServiceProvider.GetRequiredService<IDocumentaryProductionAdapterRegistry>().IsAvailable(DocumentaryProductionOperationKind.NarrationSynthesis));Assert.False(scope.ServiceProvider.GetRequiredService<IOptions<DocumentaryNarrationAdapterOptions>>().Value.Enabled);}
    private sealed class newFakeClient : IAzureSpeechClient { public Task<byte[]> SynthesizeMp3Async(string text,Astronomy.MediaFactory.Contracts.AzureSpeechOptions options,CancellationToken token)=>Task.FromResult(Array.Empty<byte>());public Task<byte[]> SynthesizeWavSsmlAsync(string ssml,Astronomy.MediaFactory.Contracts.AzureSpeechOptions options,CancellationToken token)=>Task.FromResult(Array.Empty<byte>());}
    private static string FindRepositoryRoot(){var current=new DirectoryInfo(AppContext.BaseDirectory);while(current is not null&&!Directory.Exists(Path.Combine(current.FullName,"Backend","src")))current=current.Parent;return current?.FullName??throw new DirectoryNotFoundException();}
}
