using Astronomy.MediaFactory.Core.DocumentaryBlueprint;using Astronomy.MediaFactory.ProductionAdapters;using Xunit;
namespace Astronomy.MediaFactory.Tests.ProductionAdapters;
public sealed class DocumentaryMediaVerificationFullAdapterTests {
 [Fact] public async Task Valid_narration_audio_is_verified(){await using var f=await DocumentaryMediaVerificationAdapterFixture.NarrationAudio();var before=await f.Registry.GetAllAsync("verification-correlation",default);var x=await f.Adapter.VerifyAsync(f.Request,f.ExecutionContext,f.AttemptContext,f.Workspace,default);Assert.True(x.Succeeded);Assert.True(x.Verified);Assert.Equal("NarrationAudioVerificationV1",x.VerificationPolicyId);Assert.Equal(1,f.ProviderBinding.InvocationCount);Assert.Single(Directory.GetFiles(f.Workspace.DiagnosticsDirectory));Assert.Equal(before,await f.Registry.GetAllAsync("verification-correlation",default));Assert.Equal(DocumentaryMediaAssetStatus.Verified,new DocumentaryMediaVerificationResultMapper().Map(f.Request,x).Status);}
 [Fact] public async Task Valid_scene_video_is_verified(){await using var f=await DocumentaryMediaVerificationAdapterFixture.SceneVideo();f.ProviderBinding.Response=new(true,new(true,2000,true,true,false,1920,1080,30,48000,2,"mov,mp4,m4a,3gp,3g2,mj2"),null);Assert.True((await f.Adapter.VerifyAsync(f.Request,f.ExecutionContext,f.AttemptContext,f.Workspace,default)).Verified);}
 [Fact] public async Task Valid_silent_scene_video_is_verified_when_audio_is_not_required(){await using var f=await DocumentaryMediaVerificationAdapterFixture.SceneVideo();f.ProviderBinding.Response=new(true,new(true,2000,true,false,false,1920,1080,30,ContainerFormat:"mp4"),null);Assert.True((await f.Adapter.VerifyAsync(f.Request,f.ExecutionContext,f.AttemptContext,f.Workspace,default)).Verified);}
 [Fact] public async Task Valid_variant_video_is_verified(){await using var f=await DocumentaryMediaVerificationAdapterFixture.VariantVideo();f.ProviderBinding.Response=new(true,new(true,6000,true,false,false,1920,1080,30,ContainerFormat:"mp4"),null);var x=await f.Adapter.VerifyAsync(f.Request,f.ExecutionContext,f.AttemptContext,f.Workspace,default);Assert.True(x.Verified);Assert.Equal("VariantVideoVerificationV1",x.VerificationPolicyId);}
 [Fact] public async Task Provider_exception_normalization_is_safe(){foreach(var pair in new (Exception,DocumentaryProductionFailureCode)[]{(new TimeoutException("private"),DocumentaryProductionFailureCode.ProviderTimeout),(new IOException("private"),DocumentaryProductionFailureCode.FileSystemFailure),(new InvalidOperationException("private"),DocumentaryProductionFailureCode.ProviderRejectedRequest)}){await using var f=await DocumentaryMediaVerificationAdapterFixture.NarrationAudio();f.ProviderBinding.Exception=pair.Item1;var x=await f.Adapter.VerifyAsync(f.Request,f.ExecutionContext,f.AttemptContext,f.Workspace,default);Assert.Equal(pair.Item2,x.Failure!.Code);Assert.DoesNotContain("private",x.Failure.Message);}}
 [Fact] public async Task Provider_cancellation_propagates_through_media_verification_adapter(){await using var f=await DocumentaryMediaVerificationAdapterFixture.NarrationAudio();var bytes=await File.ReadAllBytesAsync(f.Descriptor.PhysicalPath);f.ProviderBinding.WaitForCancellation=true;using var cts=new CancellationTokenSource();var t=f.Adapter.VerifyAsync(f.Request,f.ExecutionContext,f.AttemptContext,f.Workspace,cts.Token);while(f.ProviderBinding.InvocationCount==0)await Task.Yield();cts.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>t);Assert.Equal(1,f.ProviderBinding.InvocationCount);Assert.Equal(bytes,await File.ReadAllBytesAsync(f.Descriptor.PhysicalPath));Assert.Empty(Directory.GetFiles(f.Workspace.DiagnosticsDirectory));}
 [Fact] public async Task Diagnostics_cancellation_propagates_through_media_verification_adapter(){await using var f=await DocumentaryMediaVerificationAdapterFixture.NarrationAudio();f.DiagnosticsWriter=new CancellingDiagnostics();f.Rebuild();using var cts=new CancellationTokenSource();var t=f.Adapter.VerifyAsync(f.Request,f.ExecutionContext,f.AttemptContext,f.Workspace,cts.Token);cts.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>t);}
 [Fact] public async Task Diagnostics_io_failure_is_normalized_to_FileSystemFailure(){await using var f=await DocumentaryMediaVerificationAdapterFixture.NarrationAudio();f.DiagnosticsWriter=new ThrowingDiagnostics();f.Rebuild();var x=await f.Adapter.VerifyAsync(f.Request,f.ExecutionContext,f.AttemptContext,f.Workspace,default);Assert.Equal(DocumentaryProductionFailureCode.FileSystemFailure,x.Failure!.Code);}
 [Fact] public async Task Verification_diagnostic_is_written_and_sanitized(){await using var f=await DocumentaryMediaVerificationAdapterFixture.NarrationAudio();var x=await f.Adapter.VerifyAsync(f.Request,f.ExecutionContext,f.AttemptContext,f.Workspace,default);var json=await File.ReadAllTextAsync(Path.Combine(f.Workspace.DiagnosticsDirectory,x.ProviderDiagnosticsReference!));foreach(var field in new[]{"executionId","correlationId","assetId","artifactKind","verificationPolicyId","providerId","physicalContentIdentity","checksum","passedChecks","violations","outcome"})Assert.Contains(field,json,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain(f.Descriptor.PhysicalPath,json);Assert.DoesNotContain("authorization",json,StringComparison.OrdinalIgnoreCase);}
 [Fact] public async Task Media_verification_does_not_invoke_generation_or_composition_adapters(){var parameters=typeof(DocumentaryProductionMediaVerificationAdapter).GetConstructors().Single().GetParameters().Select(x=>x.ParameterType).ToArray();Assert.DoesNotContain(parameters,x=>x.Name is "IDocumentaryProductionVisualAdapter" or "IDocumentaryProductionNarrationAdapter" or "IDocumentaryProductionSubtitleAdapter" or "IDocumentaryProductionSceneCompositionAdapter" or "IDocumentaryProductionVariantCompositionAdapter");await using var f=await DocumentaryMediaVerificationAdapterFixture.NarrationAudio();Assert.True((await f.Adapter.VerifyAsync(f.Request,f.ExecutionContext,f.AttemptContext,f.Workspace,default)).Verified);}
 sealed class ThrowingDiagnostics:IDocumentaryProductionDiagnosticsWriter{public Task WriteAsync(string d,string f,object v,CancellationToken t)=>throw new IOException("private");}
 sealed class CancellingDiagnostics:IDocumentaryProductionDiagnosticsWriter{public async Task WriteAsync(string d,string f,object v,CancellationToken t)=>await Task.Delay(Timeout.InfiniteTimeSpan,t);}
}
