using Astronomy.MediaFactory.ProductionAdapters;using Xunit;
namespace Astronomy.MediaFactory.Tests.ProductionAdapters;
public sealed class DocumentaryMediaVerificationArchitectureTests {
 [Fact] public void Adapter_is_disabled_by_default_and_provider_id_is_stable(){Assert.False(new DocumentaryMediaVerificationAdapterOptions().Enabled);Assert.Equal("ExistingFFprobeMediaVerifier",DocumentaryMediaVerificationProviderIds.ExistingFFprobeMediaVerifier);}
 [Fact] public void Media_verification_does_not_invoke_generation_or_composition_adapters(){var names=typeof(DocumentaryProductionMediaVerificationAdapter).GetConstructors().Single().GetParameters().Select(x=>x.ParameterType.Name);Assert.DoesNotContain(names,x=>x.Contains("Visual")||x.Contains("NarrationAdapter")||x.Contains("SubtitleAdapter")||x.Contains("SceneComposition")||x.Contains("VariantComposition")||x.Contains("Storage")||x.Contains("Publishing")||x.Contains("Ffmpeg"));}
 [Fact] public void Media_verification_source_has_no_mutation_shell_or_blocking_async(){var root=FindRoot();var source=File.ReadAllText(Path.Combine(root,"Backend/src/Astronomy.MediaFactory.ProductionAdapters/MediaVerificationAdapter.cs"));foreach(var forbidden in new[]{".Wait(",".GetAwaiter().GetResult(","Task.Run(","Process.Start(","cmd.exe","powershell.exe","/bin/sh","bash -c","FinalizeArtifactAsync(","RegisterAsync("})Assert.DoesNotContain(forbidden,source,StringComparison.OrdinalIgnoreCase);}
 [Fact] public void Core_does_not_reference_production_adapters(){var root=FindRoot();foreach(var file in Directory.GetFiles(Path.Combine(root,"Backend/src/Astronomy.MediaFactory.Core"),"*.cs",SearchOption.AllDirectories))Assert.DoesNotContain("Astronomy.MediaFactory.ProductionAdapters",File.ReadAllText(file));}
 static string FindRoot(){var d=new DirectoryInfo(AppContext.BaseDirectory);while(d is not null&&!Directory.Exists(Path.Combine(d.FullName,"Backend")))d=d.Parent;return d?.FullName??throw new DirectoryNotFoundException();}
}
