using System.Text.Json;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Astronomy.MediaFactory.ProductionAdapters;
using FluentAssertions;

namespace Astronomy.MediaFactory.Tests.ProductionAdapters;
public sealed class DocumentaryVariantCompositionFullAdapterTests
{
 [Fact] public async Task Variant_composition_does_not_generate_or_render_upstream_assets(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var r=await f.ComposeAsync();r.Succeeded.Should().BeTrue();f.ProviderBinding.InvocationCount.Should().Be(1);(await f.Variants()).Should().ContainSingle();(await f.Registry.GetAllAsync(DocumentaryVariantCompositionAdapterFixture.Correlation,default)).Count(x=>x.AssetId.StartsWith("scene-")).Should().Be(3);}
 [Fact] public async Task One_variant_request_produces_one_variant_video(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();(await f.ComposeAsync()).Succeeded.Should().BeTrue();f.ProviderBinding.InvocationCount.Should().Be(1);(await f.Variants()).Should().ContainSingle();Directory.GetFiles(f.Workspace.DiagnosticsDirectory,"*.json").Should().ContainSingle();Directory.GetFiles(f.Workspace.ExecutionRoot,"provider-variant.mp4",SearchOption.AllDirectories).Should().BeEmpty();}
 [Fact] public async Task Finalized_scenes_are_composed_in_certified_sequence_order(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();f.Request=f.Request with{SceneAssets=f.Request.SceneAssets.Reverse().ToArray()};(await f.ComposeAsync()).Succeeded.Should().BeTrue();f.ProviderBinding.CapturedRequest!.OrderedSceneMetadata.Select(x=>x.AssetId).Should().Equal("scene-1","scene-2","scene-3");f.ProviderBinding.CapturedRequest.OrderedScenePaths.Select(Path.GetFileName).Should().Equal("scene-1.mp4","scene-2.mp4","scene-3.mp4");}
 [Fact] public async Task Variant_is_finalized_hashed_registered_and_mapped(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var r=await f.ComposeAsync();r.Succeeded.Should().BeTrue();r.SceneCount.Should().Be(3);r.HasVideo.Should().BeTrue();r.HasAudio.Should().BeTrue();r.MeasuredDurationMilliseconds.Should().Be(6000);r.MeasuredWidth.Should().Be(1920);r.MeasuredHeight.Should().Be(1080);r.MeasuredFrameRate.Should().Be(30);r.Artifact!.Checksum.Should().MatchRegex("^[0-9a-f]{64}$");r.Artifact.ContentIdentity.Should().Be("sha256:"+r.Artifact.Checksum);r.Artifact.ProviderId.Should().Be(DocumentaryVariantCompositionProviderIds.ExistingFFmpegVariantComposer);File.Exists(r.Artifact.PhysicalPath).Should().BeTrue();r.Artifact.PhysicalPath.Should().NotStartWith(f.Workspace.AttemptsDirectory);new DocumentaryVariantCompositionResultMapper().Map(f.Request,r).Status.Should().Be(DocumentaryMediaAssetStatus.Generated);}
 [Fact] public async Task Portrait_variant_preserves_1080_by_1920_profile(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync(portrait:true);var r=await f.ComposeAsync();r.Succeeded.Should().BeTrue();f.ProviderBinding.CapturedRequest!.Width.Should().Be(1080);f.ProviderBinding.CapturedRequest.Height.Should().Be(1920);f.ProviderBinding.CapturedRequest.VideoProfile.Should().Be("ShortsFinal");r.Artifact!.Width.Should().Be(1080);r.Artifact.Height.Should().Be(1920);}
 [Fact] public async Task Landscape_variant_preserves_1920_by_1080_profile(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();(await f.ComposeAsync()).Succeeded.Should().BeTrue();f.ProviderBinding.CapturedRequest!.Width.Should().Be(1920);f.ProviderBinding.CapturedRequest.Height.Should().Be(1080);f.ProviderBinding.CapturedRequest.VideoProfile.Should().Be("YouTubeLongFinal");}
 [Fact] public async Task Video_only_variant_succeeds_without_output_audio(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync(audio:false);var r=await f.ComposeAsync();r.Succeeded.Should().BeTrue();r.HasAudio.Should().BeFalse();f.ProviderBinding.CapturedRequest!.AudioPolicy.Should().Be(DocumentaryVariantAudioPolicy.VideoOnly);(await f.Variants()).Should().ContainSingle();}
 [Fact] public async Task Required_audio_variant_succeeds_when_output_has_audio(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var r=await f.ComposeAsync();r.Succeeded.Should().BeTrue();r.HasAudio.Should().BeTrue();f.ProviderBinding.CapturedRequest!.AudioPolicy.Should().Be(DocumentaryVariantAudioPolicy.RequireAudio);}
 [Fact] public async Task Required_audio_variant_without_output_audio_is_rejected(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();f.VariantInspector.Output=f.VariantInspector.Output with{HasAudio=false};var r=await f.ComposeAsync();r.Failure!.Code.Should().Be(DocumentaryProductionFailureCode.AudioStreamMissing);(await f.Variants()).Should().BeEmpty();}
 [Theory][InlineData(typeof(TimeoutException),DocumentaryProductionFailureCode.ProviderTimeout)][InlineData(typeof(IOException),DocumentaryProductionFailureCode.FileSystemFailure)][InlineData(typeof(InvalidOperationException),DocumentaryProductionFailureCode.ProviderRejectedRequest)] public async Task Inspector_exceptions_are_normalized(Type type,DocumentaryProductionFailureCode code){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();f.VariantInspector.Exception=(Exception)Activator.CreateInstance(type,"private detail")!;var r=await f.ComposeAsync();r.Failure!.Code.Should().Be(code);r.Failure.Message.Should().NotContain("private detail");}
 [Fact] public async Task Provider_cancellation_propagates_through_variant_adapter(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();f.ProviderBinding.WaitForCancellation=true;using var cts=new CancellationTokenSource();var task=f.ComposeAsync(cts.Token);while(f.ProviderBinding.InvocationCount==0)await Task.Yield();cts.Cancel();await FluentActions.Awaiting(()=>task).Should().ThrowAsync<OperationCanceledException>();f.VariantInspector.InvocationCount.Should().Be(0);(await f.Variants()).Should().BeEmpty();}
 [Fact] public async Task Inspector_cancellation_propagates_through_variant_adapter(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();f.VariantInspector.WaitForCancellation=true;using var cts=new CancellationTokenSource();var task=f.ComposeAsync(cts.Token);while(f.VariantInspector.InvocationCount==0)await Task.Yield();cts.Cancel();await FluentActions.Awaiting(()=>task).Should().ThrowAsync<OperationCanceledException>();(await f.Variants()).Should().BeEmpty();}
 [Fact] public async Task Provider_output_outside_attempt_directory_is_rejected(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var path=Path.Combine(f.Workspace.ExecutionRoot,"external.mp4");await File.WriteAllBytesAsync(path,"external"u8.ToArray());f.ProviderBinding.Output=new(path);var r=await f.ComposeAsync();r.Failure!.Code.Should().Be(DocumentaryProductionFailureCode.ProviderInvalidResponse);f.VariantInspector.InvocationCount.Should().Be(0);}
 [Fact] public async Task Success_diagnostic_is_written_and_sanitized(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();(await f.ComposeAsync()).Succeeded.Should().BeTrue();var json=await File.ReadAllTextAsync(Directory.GetFiles(f.Workspace.DiagnosticsDirectory).Single());using var doc=JsonDocument.Parse(json);doc.RootElement.GetProperty("outcome").GetString().Should().Be("Succeeded");json.Should().Contain("orderedSceneAssetIds").And.Contain("sanitizedStandardErrorHash").And.NotContain("authorization").And.NotContain("ffmpeg command");}
 [Fact] public async Task Same_variant_content_replay_is_idempotent(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var a=await f.ComposeAsync();var b=await f.ComposeAsync();b.Succeeded.Should().BeTrue();b.Artifact!.Checksum.Should().Be(a.Artifact!.Checksum);(await f.Variants()).Should().ContainSingle();}
 [Fact] public async Task Full_variant_adapter_does_not_mutate_request_or_contexts(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var before=JsonSerializer.Serialize((f.Request,f.ExecutionContext,f.AttemptContext));(await f.ComposeAsync()).Succeeded.Should().BeTrue();JsonSerializer.Serialize((f.Request,f.ExecutionContext,f.AttemptContext)).Should().Be(before);}
}
