using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Astronomy.MediaFactory.ProductionAdapters;

namespace Astronomy.MediaFactory.Tests.ProductionAdapters;

public sealed class DocumentaryNarrationSynthesisResultMapperTests
{
    [Fact] public void Successful_descriptor_fields_are_preserved(){var r=DocumentaryNarrationTestFixtures.Request();var d=Descriptor();var mapped=new DocumentaryNarrationSynthesisResultMapper().Map(r,DocumentaryProductionNarrationAdapterResult.Success(d,"en-US-JennyNeural",r.Language,r.AssetFormat,false));Assert.Equal(DocumentaryMediaAssetStatus.Generated,mapped.Status);Assert.Equal(d.ProviderId,mapped.AssetResult.ProviderId);Assert.Equal(d.ContentIdentity,mapped.AssetResult.ContentIdentity);Assert.Equal(d.Checksum,mapped.AssetResult.Checksum);Assert.Equal(d.DurationMilliseconds,mapped.MeasuredDurationMilliseconds);Assert.Equal(d.AudioSampleRate,mapped.AssetResult.SampleRate);Assert.Equal(d.AudioChannelCount,mapped.AssetResult.ChannelCount);Assert.Equal(d.AttemptCount,mapped.AssetResult.AttemptCount);Assert.Equal(d.CorrelationId,mapped.AssetResult.CorrelationId);}
    [Fact] public void Failure_and_request_are_preserved(){var request=DocumentaryNarrationTestFixtures.Request();var before=request;var failure=new DocumentaryProductionFailure(DocumentaryProductionFailureCode.ProviderTimeout,"timed out");var mapped=new DocumentaryNarrationSynthesisResultMapper().Map(request,DocumentaryProductionNarrationAdapterResult.Failed(failure,request.Language,request.AssetFormat));Assert.Equal(DocumentaryMediaAssetStatus.Failed,mapped.Status);Assert.Equal("ProviderTimeout",mapped.FailureCode);Assert.Equal("timed out",mapped.FailureMessage);Assert.Equal(1,mapped.AssetResult.AttemptCount);Assert.Equal(before,request);}
    internal static DocumentaryPhysicalArtifactDescriptor Descriptor(string? checksum=null,string correlation=DocumentaryNarrationTestFixtures.Correlation){checksum??=new string('a',64);return new("narration-asset","sha256:"+checksum,Path.GetFullPath("narration.wav"),"audio/wav",100,checksum,100,null,null,null,24000,1,DocumentaryNarrationProviderIds.AzureSpeech,1,correlation);}
}

public sealed class DocumentaryNarrationRegistryIntegrationTests
{
    [Fact] public async Task Registration_is_idempotent_and_snapshot_is_immutable(){var registry=new DocumentaryPhysicalArtifactRegistry();var d=DocumentaryNarrationSynthesisResultMapperTests.Descriptor();await registry.RegisterAsync(d,DocumentaryPhysicalArtifactKind.NarrationAudio,default);await registry.RegisterAsync(d,DocumentaryPhysicalArtifactKind.NarrationAudio,default);Assert.Same(d,await registry.GetAsync(d.AssetId,default));var all=await registry.GetAllAsync(d.CorrelationId,default);Assert.Single(all);Assert.IsAssignableFrom<IReadOnlyCollection<DocumentaryPhysicalArtifactDescriptor>>(all);Assert.Throws<NotSupportedException>(()=>((IList<DocumentaryPhysicalArtifactDescriptor>)all).Add(d));}
    [Fact] public async Task Different_checksum_conflicts(){var registry=new DocumentaryPhysicalArtifactRegistry();await registry.RegisterAsync(DocumentaryNarrationSynthesisResultMapperTests.Descriptor(),DocumentaryPhysicalArtifactKind.NarrationAudio,default);await Assert.ThrowsAsync<InvalidOperationException>(()=>registry.RegisterAsync(DocumentaryNarrationSynthesisResultMapperTests.Descriptor(new string('b',64)),DocumentaryPhysicalArtifactKind.NarrationAudio,default));}
    [Fact] public async Task Different_correlation_conflicts(){var registry=new DocumentaryPhysicalArtifactRegistry();var d=DocumentaryNarrationSynthesisResultMapperTests.Descriptor();await registry.RegisterAsync(d,DocumentaryPhysicalArtifactKind.NarrationAudio,default);await Assert.ThrowsAsync<InvalidOperationException>(()=>registry.GetAllAsync("other",default));}
}
