using System.Text.Json;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Astronomy.MediaFactory.ProductionAdapters;
using Xunit;

namespace Astronomy.MediaFactory.Tests.ProductionAdapters;

public sealed class DocumentaryVariantDependencyResolverTests
{
 [Fact] public async Task One_finalized_scene_is_resolved(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var request=f.Request with{SceneAssets=[f.Request.SceneAssets[0]],AssetPlan=f.Request.AssetPlan with{Dependencies=[f.Request.AssetPlan.Dependencies[0]]}};var x=await Resolve(f,request);Assert.True(x.Succeeded);var s=Assert.Single(x.Dependencies!.OrderedScenes);Assert.Equal("scene-1",s.AssetId);Assert.Equal(2000,s.DurationMilliseconds);Assert.Equal(1920,s.Width);Assert.Equal(1080,s.Height);Assert.Equal(30,s.FrameRate);Assert.Matches("^[0-9a-f]{64}$",s.Checksum);Assert.Equal("sha256:"+s.Checksum,s.ContentIdentity);}
 [Fact] public async Task Multiple_finalized_scenes_are_ordered_by_sequence_then_asset_id(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var assets=f.Request.SceneAssets;var deps=new[]{f.Request.AssetPlan.Dependencies[0] with{SourceAssetId="scene-2",Sequence=1},f.Request.AssetPlan.Dependencies[1] with{SourceAssetId="scene-1",Sequence=1},f.Request.AssetPlan.Dependencies[2]};var q=f.Request with{SceneAssets=[assets[2],assets[1],assets[0]],AssetPlan=f.Request.AssetPlan with{Dependencies=deps}};var x=await Resolve(f,q);Assert.Equal(new[]{"scene-1","scene-2","scene-3"},x.Dependencies!.OrderedScenes.Select(s=>s.AssetId));}
 [Fact] public async Task Explicit_variant_duration_takes_precedence(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var x=await Resolve(f,f.Request with{AssetPlan=f.Request.AssetPlan with{ExpectedDurationMilliseconds=7000}});Assert.Equal(7000,x.Dependencies!.ExpectedDurationMilliseconds);}
 [Fact] public async Task Scene_duration_sum_is_used_when_plan_duration_is_zero(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var x=await Resolve(f,f.Request with{AssetPlan=f.Request.AssetPlan with{ExpectedDurationMilliseconds=0}});Assert.Equal(6000,x.Dependencies!.ExpectedDurationMilliseconds);}
 [Fact] public async Task No_scene_assets_returns_SourceArtifactMissing(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();await Invalid(f,f.Request with{SceneAssets=[]},DocumentaryProductionFailureCode.SourceArtifactMissing);}
 [Fact] public async Task Missing_registered_scene_returns_SourceArtifactMissing(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var registry=new DocumentaryPhysicalArtifactRegistry();var x=await new DocumentaryVariantDependencyResolver(registry,new DocumentaryContentIdentityFactory()).ResolveAsync(f.Request,f.Workspace,default);Assert.Equal(DocumentaryProductionFailureCode.SourceArtifactMissing,x.Failure?.Code);Assert.Null(x.Dependencies);}
 [Fact] public async Task Duplicate_scene_asset_id_returns_SourceArtifactInvalid(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();await Invalid(f,f.Request with{SceneAssets=[f.Request.SceneAssets[0],f.Request.SceneAssets[0]]});}
 [Fact] public async Task Missing_dependency_sequence_returns_SourceArtifactInvalid(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();await Invalid(f,f.Request with{AssetPlan=f.Request.AssetPlan with{Dependencies=f.Request.AssetPlan.Dependencies.Skip(1).ToArray()}});}
 [Fact] public async Task Ambiguous_dependency_sequence_returns_SourceArtifactInvalid(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();await Invalid(f,f.Request with{AssetPlan=f.Request.AssetPlan with{Dependencies=[..f.Request.AssetPlan.Dependencies,f.Request.AssetPlan.Dependencies[0]]}});}
 [Fact] public async Task Scene_not_present_in_variant_returns_SourceArtifactInvalid(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var deps=f.Request.AssetPlan.Dependencies.Select((d,i)=>i==0?d with{Sequence=99}:d).ToArray();await Invalid(f,f.Request with{AssetPlan=f.Request.AssetPlan with{Dependencies=deps}});}
 [Fact] public async Task Wrong_scene_asset_type_returns_SourceArtifactInvalid(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var a=f.Request.SceneAssets[0] with{AssetType=DocumentaryMediaAssetType.VisualImage};await Invalid(f,f.Request with{SceneAssets=[a,..f.Request.SceneAssets.Skip(1)]});}
 [Fact] public async Task Wrong_scene_asset_format_returns_SourceArtifactInvalid(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var a=f.Request.SceneAssets[0] with{AssetFormat=DocumentaryMediaAssetFormat.Png};await Invalid(f,f.Request with{SceneAssets=[a,..f.Request.SceneAssets.Skip(1)]});}
 [Fact] public async Task Source_result_correlation_mismatch_returns_SourceArtifactInvalid(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var a=f.Request.SceneAssets[0] with{CorrelationId="wrong"};await Invalid(f,f.Request with{SceneAssets=[a,..f.Request.SceneAssets.Skip(1)]});}
 [Fact] public async Task Request_plan_correlation_mismatch_returns_SourceArtifactInvalid(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();await Invalid(f,f.Request with{AssetPlan=f.Request.AssetPlan with{CorrelationId="wrong"}});}
 [Fact] public async Task Request_variant_correlation_mismatch_returns_SourceArtifactInvalid(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();await Invalid(f,f.Request with{CorrelationId="wrong",AssetPlan=f.Request.AssetPlan with{CorrelationId="wrong"}});}
 [Fact] public async Task Non_hex_checksum_is_rejected(){await DescriptorInvalid(d=>d with{Checksum=new string('z',64),ContentIdentity="sha256:"+new string('z',64)});}
 [Fact] public async Task Content_identity_must_match_descriptor_checksum(){await DescriptorInvalid(d=>d with{ContentIdentity="sha256:"+new string('b',64)});}
 [Theory] [InlineData("content")] [InlineData("correlation")] [InlineData("missing-file")] [InlineData("empty")] [InlineData("attempt")] [InlineData("duration-null")] [InlineData("duration-zero")] [InlineData("width-null")] [InlineData("width-zero")] [InlineData("height-null")] [InlineData("height-zero")] [InlineData("rate-null")] [InlineData("rate-zero")] [InlineData("checksum")] [InlineData("identity")]
 public async Task Invalid_descriptor_returns_SourceArtifactInvalid(string field){await DescriptorInvalid(d=>field switch{"content"=>d with{ContentType="text/plain"},"correlation"=>d with{CorrelationId="wrong"},"missing-file"=>d with{PhysicalPath=d.PhysicalPath+".missing"},"empty"=>WithFile(d,"empty.mp4",[]),"attempt"=>WithFile(d,Path.Combine("attempts","bad.mp4"),[1]),"duration-null"=>d with{DurationMilliseconds=null},"duration-zero"=>d with{DurationMilliseconds=0},"width-null"=>d with{Width=null},"width-zero"=>d with{Width=0},"height-null"=>d with{Height=null},"height-zero"=>d with{Height=0},"rate-null"=>d with{FrameRate=null},"rate-zero"=>d with{FrameRate=0},"checksum"=>d with{Checksum="bad"},_=>d with{ContentIdentity="bad"}});}
 [Fact] public async Task Dependency_resolver_does_not_mutate_request_or_registry_descriptors(){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var before=JsonSerializer.Serialize(f.Request);var descriptors=JsonSerializer.Serialize(await f.Registry.GetAllAsync(DocumentaryVariantCompositionAdapterFixture.Correlation,default));await Resolve(f,f.Request);Assert.Equal(before,JsonSerializer.Serialize(f.Request));Assert.Equal(descriptors,JsonSerializer.Serialize(await f.Registry.GetAllAsync(DocumentaryVariantCompositionAdapterFixture.Correlation,default)));}
 static async Task<DocumentaryVariantDependencyResolution> Resolve(DocumentaryVariantCompositionAdapterFixture f,DocumentaryVariantCompositionRequest q)=>await new DocumentaryVariantDependencyResolver(f.Registry,new DocumentaryContentIdentityFactory()).ResolveAsync(q,f.Workspace,default);
 static async Task Invalid(DocumentaryVariantCompositionAdapterFixture f,DocumentaryVariantCompositionRequest q,DocumentaryProductionFailureCode code=DocumentaryProductionFailureCode.SourceArtifactInvalid){var before=JsonSerializer.Serialize(q);var x=await Resolve(f,q);Assert.False(x.Succeeded);Assert.Null(x.Dependencies);Assert.Equal(code,x.Failure?.Code);Assert.Equal(before,JsonSerializer.Serialize(q));}
 static async Task DescriptorInvalid(Func<DocumentaryPhysicalArtifactDescriptor,DocumentaryPhysicalArtifactDescriptor> mutate){await using var f=await DocumentaryVariantCompositionAdapterFixture.CreateAsync();var original=(await f.Registry.GetAsync("scene-1",default))!;var registry=new DocumentaryPhysicalArtifactRegistry();var malformed=mutate((await f.Registry.GetAsync("scene-1",default))!);await registry.RegisterAsync(malformed,DocumentaryPhysicalArtifactKind.SceneVideo,default);var before=JsonSerializer.Serialize(original);var x=await new DocumentaryVariantDependencyResolver(registry,new DocumentaryContentIdentityFactory()).ResolveAsync(f.Request,f.Workspace,default);Assert.False(x.Succeeded);Assert.Null(x.Dependencies);Assert.Equal(DocumentaryProductionFailureCode.SourceArtifactInvalid,x.Failure?.Code);Assert.Equal(before,JsonSerializer.Serialize(original));}
 static DocumentaryPhysicalArtifactDescriptor WithFile(DocumentaryPhysicalArtifactDescriptor d,string relative,byte[] bytes){var root=Path.GetDirectoryName(Path.GetDirectoryName(d.PhysicalPath))!;var path=Path.Combine(root,relative);Directory.CreateDirectory(Path.GetDirectoryName(path)!);File.WriteAllBytes(path,bytes);return d with{PhysicalPath=path,Length=bytes.Length};}
}
