using System.ComponentModel;
using System.Text;
using Astronomy.MediaFactory.Contracts;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Astronomy.MediaFactory.ProductionAdapters;
using Astronomy.MediaFactory.Rendering;
using Microsoft.Extensions.Options;
using Xunit;

namespace Astronomy.MediaFactory.Tests.ProductionAdapters;

public sealed class ExistingFFmpegDocumentaryVariantProviderBindingTests : IDisposable
{
    readonly string root=Path.Combine(Path.GetTempPath(),"a38-provider-"+Guid.NewGuid().ToString("N"));
    readonly RenderingOptions options=new(){FfmpegPath="certified-ffmpeg",FinalLongRenderTimeoutSeconds=91,FinalShortRenderTimeoutSeconds=37};
    public ExistingFFmpegDocumentaryVariantProviderBindingTests()=>Directory.CreateDirectory(root);

    [Fact] public async Task Valid_variant_request_invokes_existing_process_runner_once(){var runner=new A38RecordingProcessRunner();var (binding,request)=Create(runner);runner.OnExecute=()=>File.WriteAllText(Path.Combine(request.OutputDirectory,"provider-variant.mp4"),"video");using var cts=new CancellationTokenSource();var result=await binding.ComposeAsync(request,cts.Token);Assert.True(result.Succeeded);Assert.Equal(1,runner.InvocationCount);Assert.Equal(options.FfmpegPath,runner.CapturedFileName);Assert.Equal(cts.Token,runner.CapturedCancellationToken);Assert.Equal(TimeSpan.FromSeconds(91),runner.CapturedTimeout);Assert.Equal("provider-variant.mp4",Path.GetFileName(result.OutputPath));Assert.StartsWith(Path.GetFullPath(request.OutputDirectory),result.OutputPath);Assert.Equal(request.CompositionMode,result.CompositionMode);Assert.Matches("^[0-9a-f]{64}$",result.SanitizedStandardErrorHash!);Assert.Contains("-f concat",runner.CapturedArguments);Assert.Contains("-movflags +faststart",runner.CapturedArguments);}
    [Fact] public async Task Landscape_variant_uses_final_long_render_timeout(){var r=new A38RecordingProcessRunner();var (b,q)=Create(r);r.OnExecute=()=>WriteOutput(q);await b.ComposeAsync(q,default);Assert.True(q.Height<=q.Width);Assert.Equal(TimeSpan.FromSeconds(91),r.CapturedTimeout);}
    [Fact] public async Task Portrait_variant_uses_final_short_render_timeout(){var r=new A38RecordingProcessRunner();var (b,q)=Create(r);q=q with{Width=1080,Height=1920};r.OnExecute=()=>WriteOutput(q);await b.ComposeAsync(q,default);Assert.True(q.Height>q.Width);Assert.Equal(TimeSpan.FromSeconds(37),r.CapturedTimeout);}
    [Fact] public async Task RequireAudio_is_forwarded_to_variant_argument_builder(){var r=new A38RecordingProcessRunner();var (b,q)=Create(r);r.OnExecute=()=>WriteOutput(q);await b.ComposeAsync(q,default);Assert.Contains("-map 0:a:0",r.CapturedArguments);Assert.DoesNotContain(" -an",r.CapturedArguments);}
    [Fact] public async Task VideoOnly_is_forwarded_to_variant_argument_builder(){var r=new A38RecordingProcessRunner();var (b,q)=Create(r);q=q with{AudioPolicy=DocumentaryVariantAudioPolicy.VideoOnly};r.OnExecute=()=>WriteOutput(q);await b.ComposeAsync(q,default);Assert.Contains(" -an",r.CapturedArguments);Assert.DoesNotContain("-map 0:a:0",r.CapturedArguments);}
    [Fact] public async Task Provider_concat_list_preserves_certified_scene_order(){var r=new A38RecordingProcessRunner();var (b,q)=Create(r);r.OnExecute=()=>WriteOutput(q);await b.ComposeAsync(q,default);var lines=await File.ReadAllLinesAsync(Path.Combine(q.OutputDirectory,"provider-scenes.txt"));Assert.Equal(q.OrderedScenePaths.Select(p=>$"file '{p}'"),lines);}
    [Fact] public async Task Same_scene_order_produces_same_concat_list_bytes(){var r=new A38RecordingProcessRunner();var (b,q)=Create(r);r.OnExecute=()=>WriteOutput(q);await b.ComposeAsync(q,default);var p=Path.Combine(q.OutputDirectory,"provider-scenes.txt");var first=await File.ReadAllBytesAsync(p);await b.ComposeAsync(q,default);var second=await File.ReadAllBytesAsync(p);Assert.Equal(first,second);Assert.False(first.AsSpan().StartsWith(Encoding.UTF8.Preamble));Assert.Equal((byte)'\n',first[^1]);}
    [Fact] public async Task Concat_list_supports_paths_with_spaces(){var r=new A38RecordingProcessRunner();var (b,q)=Create(r,"scene with spaces.mp4");r.OnExecute=()=>WriteOutput(q);await b.ComposeAsync(q,default);Assert.Contains($"file '{q.OrderedScenePaths[0]}'",await File.ReadAllTextAsync(Path.Combine(q.OutputDirectory,"provider-scenes.txt")));}
    [Fact] public async Task Concat_list_escapes_apostrophes_using_ffmpeg_concat_rules(){var r=new A38RecordingProcessRunner();var (b,q)=Create(r,"scene's.mp4");r.OnExecute=()=>WriteOutput(q);await b.ComposeAsync(q,default);Assert.Contains("scene'\\''s.mp4",await File.ReadAllTextAsync(Path.Combine(q.OutputDirectory,"provider-scenes.txt")));}
    [Theory] [InlineData("format")] [InlineData("width")] [InlineData("height")] [InlineData("rate")] [InlineData("duration")] [InlineData("scenes")] [InlineData("audio")] [InlineData("path")]
    public async Task Invalid_request_returns_ProviderRejectedRequest(string field){var r=new A38RecordingProcessRunner();var (b,q)=Create(r);q=field switch{"format"=>q with{OutputFormat=DocumentaryMediaAssetFormat.Wav},"width"=>q with{Width=0},"height"=>q with{Height=0},"rate"=>q with{FrameRate=0},"duration"=>q with{ExpectedDurationMilliseconds=0},"scenes"=>q with{OrderedScenePaths=[]},"audio"=>q with{AudioPolicy=(DocumentaryVariantAudioPolicy)999},_=>q with{OrderedScenePaths=[""]}};var x=await b.ComposeAsync(q,default);Assert.Equal(DocumentaryProductionFailureCode.ProviderRejectedRequest,x.Failure?.Code);Assert.Equal(0,r.InvocationCount);Assert.False(File.Exists(Path.Combine(q.OutputDirectory,"provider-scenes.txt")));}
    [Fact] public async Task Missing_ffmpeg_executable_returns_DependencyMissing(){await AssertFailure(new Win32Exception(),DocumentaryProductionFailureCode.DependencyMissing);}
    [Fact] public async Task Process_start_io_failure_returns_ProcessStartFailed(){await AssertFailure(new IOException("secret"),DocumentaryProductionFailureCode.ProcessStartFailed);}
    [Fact] public async Task Process_timeout_returns_ProcessTimedOut(){await AssertResultFailure(Result(timedOut:true),DocumentaryProductionFailureCode.ProcessTimedOut);}
    [Fact] public async Task Process_exception_text_returns_ProcessStartFailed(){await AssertResultFailure(Result(exception:"secret details"),DocumentaryProductionFailureCode.ProcessStartFailed);}
    [Fact] public async Task Nonzero_exit_returns_ProcessExitedWithError(){await AssertResultFailure(Result(exit:9),DocumentaryProductionFailureCode.ProcessExitedWithError);}
    [Fact] public async Task Missing_provider_output_returns_OutputArtifactMissing(){await AssertResultFailure(Result(),DocumentaryProductionFailureCode.OutputArtifactMissing);}
    [Fact] public async Task Empty_provider_output_returns_OutputArtifactEmpty(){var r=new A38RecordingProcessRunner();var (b,q)=Create(r);r.OnExecute=()=>File.WriteAllBytes(Path.Combine(q.OutputDirectory,"provider-variant.mp4"),[]);var x=await b.ComposeAsync(q,default);Assert.Equal(DocumentaryProductionFailureCode.OutputArtifactEmpty,x.Failure?.Code);Assert.Matches("^[0-9a-f]{64}$",x.SanitizedStandardErrorHash!);}
    [Fact] public async Task Caller_cancellation_propagates_from_process_runner(){var r=new A38RecordingProcessRunner{WaitForCancellation=true};var (b,q)=Create(r);using var c=new CancellationTokenSource();var task=b.ComposeAsync(q,c.Token);while(r.InvocationCount==0)await Task.Yield();c.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>task);Assert.Equal(1,r.InvocationCount);Assert.Equal(c.Token,r.CapturedCancellationToken);Assert.False(File.Exists(Path.Combine(q.OutputDirectory,"provider-variant.mp4")));}
    [Fact] public async Task Provider_ignores_external_requested_output_path_and_uses_owned_output(){var r=new A38RecordingProcessRunner();var (b,q)=Create(r);var external=Path.Combine(root,"outside.mp4");q=q with{OutputPath=external};r.OnExecute=()=>WriteOutput(q);var x=await b.ComposeAsync(q,default);Assert.Equal(Path.Combine(Path.GetFullPath(q.OutputDirectory),"provider-variant.mp4"),x.OutputPath);Assert.False(File.Exists(external));}
    [Fact] public void RetainConcatList_option_has_defined_behavior()=>Assert.Null(typeof(DocumentaryVariantCompositionAdapterOptions).GetProperty("RetainConcatList"));

    (ExistingFFmpegDocumentaryVariantProviderBinding,DocumentaryVariantCompositionProviderRequest) Create(A38RecordingProcessRunner runner,string? special=null){var dir=Path.Combine(root,"attempt");Directory.CreateDirectory(dir);var names=special is null ? new[]{"scene-1.mp4","scene-2.mp4","scene-3.mp4"} : new[]{special};var paths=names.Select(x=>Path.Combine(root,x)).ToArray();foreach(var p in paths)File.WriteAllText(p,"scene");var metadata=paths.Select((p,i)=>new DocumentaryResolvedVariantScene("asset-"+i,"scene-"+i,i+1,p,2000,1920,1080,30,true,"sha256:"+new string('a',64),new string('a',64))).ToArray();var q=new DocumentaryVariantCompositionProviderRequest("variant","instruction","long-en",DocumentaryMediaVariantType.LongEnglish,DocumentaryMediaLanguage.English,"correlation",1,dir,Path.Combine(dir,"requested.mp4"),DocumentaryMediaAssetFormat.Mp4,1920,1080,30,6000,paths,metadata,DocumentaryVariantAudioPolicy.RequireAudio,"ConcatDemuxerFinalReencode","YouTubeLongFinal","AAC");return(new(runner,new FfmpegArgumentBuilder(),Options.Create(options)),q);}
    static ProcessExecutionResult Result(int exit=0,bool timedOut=false,string exception="")=>new(exit,"","raw stderr",DateTimeOffset.UnixEpoch,DateTimeOffset.UnixEpoch.AddSeconds(1),"ffmpeg","args",exception,timedOut);
    static void WriteOutput(DocumentaryVariantCompositionProviderRequest q)=>File.WriteAllText(Path.Combine(q.OutputDirectory,"provider-variant.mp4"),"video");
    async Task AssertFailure(Exception e,DocumentaryProductionFailureCode code){var r=new A38RecordingProcessRunner{Exception=e};var (b,q)=Create(r);var x=await b.ComposeAsync(q,default);Assert.Equal(code,x.Failure?.Code);Assert.DoesNotContain("secret",x.Failure!.Message,StringComparison.OrdinalIgnoreCase);}
    async Task AssertResultFailure(ProcessExecutionResult result,DocumentaryProductionFailureCode code){var r=new A38RecordingProcessRunner{Output=result};var (b,q)=Create(r);var x=await b.ComposeAsync(q,default);Assert.Equal(code,x.Failure?.Code);Assert.DoesNotContain("raw stderr",x.Failure!.Message);Assert.Matches("^[0-9a-f]{64}$",x.SanitizedStandardErrorHash!);}
    public void Dispose(){if(Directory.Exists(root))Directory.Delete(root,true);}
}

internal sealed class A38RecordingProcessRunner : IProcessRunner
{
    public int InvocationCount{get;private set;} public string? CapturedFileName{get;private set;} public string? CapturedArguments{get;private set;} public CancellationToken CapturedCancellationToken{get;private set;} public TimeSpan? CapturedTimeout{get;private set;}
    public ProcessExecutionResult Output{get;set;}=new(0,"","diagnostic",DateTimeOffset.UnixEpoch,DateTimeOffset.UnixEpoch.AddMilliseconds(10),"","","",false); public Exception? Exception{get;set;} public bool WaitForCancellation{get;set;} public Action? OnExecute{get;set;}
    public async Task<ProcessExecutionResult> ExecuteAsync(string fileName,string arguments,CancellationToken token,TimeSpan? timeout=null){InvocationCount++;CapturedFileName=fileName;CapturedArguments=arguments;CapturedCancellationToken=token;CapturedTimeout=timeout;if(WaitForCancellation)await Task.Delay(Timeout.Infinite,token);if(Exception is not null)throw Exception;OnExecute?.Invoke();return Output;}
}
