using System.Text.Json;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Astronomy.MediaFactory.ProductionAdapters;
using Microsoft.Extensions.Options;

namespace Astronomy.MediaFactory.Tests.ProductionAdapters;

public sealed class ExistingAzureSpeechDocumentaryNarrationAdapterTests : IDisposable
{
    private readonly string root=Path.Combine(Path.GetTempPath(),"narration-adapter-"+Guid.NewGuid().ToString("N"));
    [Fact] public async Task Narration_block_is_synthesized_once_and_not_per_subtitle_segment(){var ssml=new FakeSsmlBuilder();var provider=new FakeNarrationProviderBinding();var (adapter,registry,workspace,execution,attempt)=await Create(provider,ssml);var request=DocumentaryNarrationTestFixtures.Request(text:"Mars rises in the east tonight.\nA few minutes later, Jupiter becomes visible.\nPause briefly, then look toward the southern horizon.\nThis narration would later produce several subtitle cues.");var result=await adapter.SynthesizeAsync(request,execution,attempt,workspace,default);Assert.True(result.Succeeded,result.Failure?.ToString());Assert.Equal(1,ssml.InvocationCount);Assert.Equal(request.NarrationBlock.Text,ssml.CapturedText);Assert.Equal(1,provider.InvocationCount);Assert.Single(await registry.GetAllAsync(request.CorrelationId,default));Assert.NotNull(result.Artifact);Assert.True(File.Exists(result.Artifact.PhysicalPath));Assert.False(File.Exists(provider.CapturedRequest is null?"":Path.Combine(provider.CapturedRequest.OutputDirectory,"provider-azure-speech.wav")));}
    [Fact] public async Task Hindi_block_is_one_continuous_artifact(){var ssml=new FakeSsmlBuilder();var provider=new FakeNarrationProviderBinding();var (adapter,registry,w,e,a)=await Create(provider,ssml);var request=DocumentaryNarrationTestFixtures.Request(DocumentaryMediaLanguage.Hindi);var result=await adapter.SynthesizeAsync(request,e,a,w,default);Assert.True(result.Succeeded,result.Failure?.ToString());Assert.Equal("hi-IN-SwaraNeural",ssml.CapturedVoice);Assert.Equal("hi-IN",provider.CapturedRequest!.Locale);Assert.Equal(1,ssml.InvocationCount);Assert.Equal(1,provider.InvocationCount);Assert.Single(await registry.GetAllAsync(request.CorrelationId,default));Assert.Equal(DocumentaryMediaLanguage.Hindi,result.Language);}
    [Fact] public async Task Matching_wav_is_finalized_with_identity_metadata_and_diagnostic(){var provider=new FakeNarrationProviderBinding();var (adapter,registry,w,e,a)=await Create(provider,new());var request=DocumentaryNarrationTestFixtures.Request();var result=await adapter.SynthesizeAsync(request,e,a,w,default);Assert.True(result.Succeeded,result.Failure?.ToString());Assert.False(result.NormalizationApplied);Assert.Matches("^[0-9a-f]{64}$",result.Artifact!.Checksum);Assert.Equal("sha256:"+result.Artifact.Checksum,result.Artifact.ContentIdentity);Assert.Equal(24000,result.Artifact.AudioSampleRate);Assert.Equal(1,result.Artifact.AudioChannelCount);Assert.True(result.Artifact.DurationMilliseconds>0);Assert.Same(result.Artifact,await registry.GetAsync(request.AssetPlan.AssetId,default));Assert.Single(Directory.GetFiles(w.DiagnosticsDirectory,"narration-*.json"));}
    [Fact] public async Task Mismatched_audio_is_normalized_once(){var provider=new FakeNarrationProviderBinding{OutputRate=16000};var normalizer=new FakeNarrationAudioNormalizer();var (adapter,registry,w,e,a)=await Create(provider,new(),normalize:true,normalizer:normalizer);var result=await adapter.SynthesizeAsync(DocumentaryNarrationTestFixtures.Request(),e,a,w,default);Assert.True(result.Succeeded,result.Failure?.ToString());Assert.True(result.NormalizationApplied);Assert.Equal(1,normalizer.InvocationCount);Assert.Equal(24000,normalizer.Profile!.SampleRate);Assert.Single(await registry.GetAllAsync(DocumentaryNarrationTestFixtures.Correlation,default));}
    [Fact] public async Task Mismatch_without_normalization_is_not_registered(){var provider=new FakeNarrationProviderBinding{OutputChannels=2};var (adapter,registry,w,e,a)=await Create(provider,new());var result=await adapter.SynthesizeAsync(DocumentaryNarrationTestFixtures.Request(),e,a,w,default);Assert.False(result.Succeeded);Assert.Equal(DocumentaryProductionFailureCode.OutputFormatInvalid,result.Failure!.Code);Assert.Empty(await registry.GetAllAsync(DocumentaryNarrationTestFixtures.Correlation,default));}
    [Fact] public async Task Disabled_adapter_is_unavailable(){var (adapter,registry,w,e,a)=await Create(new(),new(),enabled:false);var result=await adapter.SynthesizeAsync(DocumentaryNarrationTestFixtures.Request(),e,a,w,default);Assert.Equal(DocumentaryProductionFailureCode.AdapterUnavailable,result.Failure!.Code);Assert.Empty(await registry.GetAllAsync(DocumentaryNarrationTestFixtures.Correlation,default));}
    [Fact] public async Task Missing_or_duplicate_binding_is_deterministic(){foreach(var bindings in new IDocumentaryNarrationProviderBinding[][]{[],[new FakeNarrationProviderBinding(),new FakeNarrationProviderBinding()]}){var (adapter,_,w,e,a)=await Create(new(),new(),bindings:bindings);var result=await adapter.SynthesizeAsync(DocumentaryNarrationTestFixtures.Request(),e,a,w,default);Assert.Equal(DocumentaryProductionFailureCode.AdapterUnavailable,result.Failure!.Code);}}
    [Fact] public async Task Provider_failure_is_preserved(){var failure=new DocumentaryProductionFailure(DocumentaryProductionFailureCode.ProviderRateLimited,"limited");var (adapter,registry,w,e,a)=await Create(new(){Failure=failure},new());var result=await adapter.SynthesizeAsync(DocumentaryNarrationTestFixtures.Request(),e,a,w,default);Assert.Same(failure,result.Failure);Assert.Empty(await registry.GetAllAsync(DocumentaryNarrationTestFixtures.Correlation,default));}
    [Theory] [InlineData(typeof(TimeoutException),DocumentaryProductionFailureCode.ProviderTimeout)] [InlineData(typeof(IOException),DocumentaryProductionFailureCode.FileSystemFailure)] [InlineData(typeof(UnauthorizedAccessException),DocumentaryProductionFailureCode.FileSystemFailure)] [InlineData(typeof(InvalidOperationException),DocumentaryProductionFailureCode.ProviderRejectedRequest)]
    public async Task Provider_exceptions_are_normalized(Type exceptionType,DocumentaryProductionFailureCode expected){var provider=new FakeNarrationProviderBinding{Exception=(Exception)Activator.CreateInstance(exceptionType,"boom")!};var (adapter,_,w,e,a)=await Create(provider,new());var result=await adapter.SynthesizeAsync(DocumentaryNarrationTestFixtures.Request(),e,a,w,default);Assert.Equal(expected,result.Failure!.Code);}
    [Fact] public async Task Successful_normalizer_with_null_path_is_rejected(){var (adapter,registry,w,e,a)=await Create(new(){OutputRate=16000},new(),normalize:true,normalizer:new(){ReturnNull=true});var result=await adapter.SynthesizeAsync(DocumentaryNarrationTestFixtures.Request(),e,a,w,default);Assert.Equal(DocumentaryProductionFailureCode.ProviderInvalidResponse,result.Failure!.Code);Assert.Empty(await registry.GetAllAsync(DocumentaryNarrationTestFixtures.Correlation,default));}
    [Fact] public async Task Provider_cancellation_propagates_without_certification(){var provider=new FakeNarrationProviderBinding{WaitForCancellation=true};var (adapter,registry,w,e,a)=await Create(provider,new());using var cts=new CancellationTokenSource();var task=adapter.SynthesizeAsync(DocumentaryNarrationTestFixtures.Request(),e,a,w,cts.Token);cts.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>task);Assert.Empty(await registry.GetAllAsync(DocumentaryNarrationTestFixtures.Correlation,default));Assert.Empty(Directory.GetFiles(w.DiagnosticsDirectory));}
    [Fact] public async Task Normalizer_cancellation_propagates_without_certification(){var normalizer=new FakeNarrationAudioNormalizer{WaitForCancellation=true};var (adapter,registry,w,e,a)=await Create(new(){OutputRate=16000},new(),normalize:true,normalizer:normalizer);using var cts=new CancellationTokenSource();var task=adapter.SynthesizeAsync(DocumentaryNarrationTestFixtures.Request(),e,a,w,cts.Token);cts.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>task);Assert.Empty(await registry.GetAllAsync(DocumentaryNarrationTestFixtures.Correlation,default));}
    [Fact] public async Task Request_graph_and_provider_response_are_not_mutated(){var request=DocumentaryNarrationTestFixtures.Request();var snapshot=JsonSerializer.Serialize(request);var provider=new FakeNarrationProviderBinding();var (adapter,_,w,e,a)=await Create(provider,new());await adapter.SynthesizeAsync(request,e,a,w,default);Assert.Equal(snapshot,JsonSerializer.Serialize(request));Assert.Equal(request.NarrationBlock.Text,provider.CapturedRequest!.NarrationText);}

    private async Task<(ExistingAzureSpeechDocumentaryNarrationAdapter,DocumentaryPhysicalArtifactRegistry,DocumentaryProductionWorkspace,DocumentaryProductionExecutionContext,DocumentaryProductionAttemptContext)> Create(FakeNarrationProviderBinding provider,FakeSsmlBuilder ssml,bool enabled=true,bool normalize=false,FakeNarrationAudioNormalizer? normalizer=null,IDocumentaryNarrationProviderBinding[]? bindings=null)
    {var checksum=new DocumentaryChecksumService();var identities=new DocumentaryContentIdentityFactory();var workspaces=new DocumentaryProductionWorkspaceManager(new DocumentarySafeFileNameGenerator(),checksum);var execution=new DocumentaryProductionExecutionContext("execution",DocumentaryNarrationTestFixtures.Correlation,DocumentaryProductionExecutionMode.Shadow,root,DateTimeOffset.UnixEpoch,new Dictionary<string,string>());var workspace=await workspaces.CreateAsync(execution,default);var attempt=new DocumentaryProductionAttemptContext("execution",DocumentaryNarrationTestFixtures.Correlation,DocumentaryProductionOperationKind.NarrationSynthesis,"narration-asset",null,"scene",1,DocumentaryNarrationProviderIds.AzureSpeech,DateTimeOffset.UnixEpoch,TimeSpan.FromSeconds(10));var registry=new DocumentaryPhysicalArtifactRegistry();var adapter=new ExistingAzureSpeechDocumentaryNarrationAdapter(Options.Create(new DocumentaryNarrationAdapterOptions{Enabled=enabled,NormalizeAudio=normalize}),new DocumentaryNarrationVoiceResolver(Options.Create(DocumentaryNarrationTestFixtures.SpeechOptions())),bindings??[provider],ssml,new DocumentaryNarrationAudioInspector(),normalizer??new(),workspaces,new DocumentaryPhysicalArtifactInspector(checksum,identities,new NullDocumentaryMediaProbe()),new DocumentaryPhysicalArtifactDescriptorValidator(identities),registry,new DocumentaryProductionDiagnosticsWriter(),new DocumentaryProductionFailureNormalizer());return(adapter,registry,workspace,execution,attempt);}
    public void Dispose(){if(Directory.Exists(root))Directory.Delete(root,true);}
}
