using System.ComponentModel;using Astronomy.MediaFactory.Contracts;using Astronomy.MediaFactory.ProductionAdapters;using Microsoft.Extensions.Options;using Xunit;
namespace Astronomy.MediaFactory.Tests.ProductionAdapters;
public sealed class ExistingFfprobeDocumentaryMediaProbeTests {
 static ExistingFfprobeDocumentaryMediaProbe Create(A39RecordingProcessRunner r)=>new(r,new DocumentaryFfprobeResultParser(),Options.Create(new RenderingOptions{FfprobePath="cert-ffprobe"}),Options.Create(new DocumentaryMediaVerificationAdapterOptions{ProbeTimeoutSeconds=60}));
 [Fact] public async Task Valid_ffprobe_json_is_parsed_through_existing_process_runner(){var r=new A39RecordingProcessRunner();using var cts=new CancellationTokenSource();var x=await Create(r).ProbeAsync("/tmp/a path.wav",cts.Token);Assert.True(x.Succeeded);Assert.Equal(1,r.InvocationCount);Assert.Equal("cert-ffprobe",r.CapturedFileName);Assert.Equal(cts.Token,r.CapturedCancellationToken);Assert.Equal(TimeSpan.FromSeconds(60),r.CapturedTimeout);foreach(var a in new[]{"-v error","-show_format","-show_streams","-of json","\"/tmp/a path.wav\""})Assert.Contains(a,r.CapturedArguments);Assert.Equal(1000,x.DurationMilliseconds);Assert.Equal(48000,x.AudioSampleRate);}
 [Fact] public async Task Missing_ffprobe_executable_returns_DependencyMissing(){var r=new A39RecordingProcessRunner{Exception=new Win32Exception()};Assert.Equal(DocumentaryProductionFailureCode.DependencyMissing,(await Create(r).ProbeAsync("x",default)).Failure!.Code);}
 [Theory][InlineData("io",DocumentaryProductionFailureCode.ProcessStartFailed)][InlineData("timeout",DocumentaryProductionFailureCode.ProcessTimedOut)][InlineData("exception",DocumentaryProductionFailureCode.ProcessStartFailed)][InlineData("exit",DocumentaryProductionFailureCode.ProcessExitedWithError)][InlineData("empty",DocumentaryProductionFailureCode.ProviderInvalidResponse)][InlineData("json",DocumentaryProductionFailureCode.ProviderInvalidResponse)] public async Task Process_failure_matrix_is_safe(string mode,DocumentaryProductionFailureCode code){var r=new A39RecordingProcessRunner();if(mode=="io")r.Exception=new IOException("private");if(mode=="timeout")r.Output=A39RecordingProcessRunner.Result(timedOut:true);if(mode=="exception")r.Output=A39RecordingProcessRunner.Result(exception:"private command");if(mode=="exit")r.Output=A39RecordingProcessRunner.Result(exit:2,stderr:"secret");if(mode=="empty")r.Output=A39RecordingProcessRunner.Result();if(mode=="json")r.Output=A39RecordingProcessRunner.Result("{");var x=await Create(r).ProbeAsync("secret-path",default);Assert.Equal(code,x.Failure!.Code);Assert.DoesNotContain("private",x.Failure.Message);Assert.DoesNotContain("secret",x.Failure.Message);}
 [Fact] public async Task Caller_cancellation_propagates_from_ffprobe_process(){var r=new A39RecordingProcessRunner{WaitForCancellation=true};using var cts=new CancellationTokenSource();var task=Create(r).ProbeAsync("x",cts.Token);cts.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>task);Assert.Equal(1,r.InvocationCount);Assert.Equal(cts.Token,r.CapturedCancellationToken);}
 [Fact] public async Task Attempt_timeout_limits_configured_probe_timeout(){var r=new A39RecordingProcessRunner();await Create(r).ProbeAsync("x",TimeSpan.FromSeconds(5),default);Assert.Equal(TimeSpan.FromSeconds(5),r.CapturedTimeout);}
 [Fact] public async Task Configured_timeout_is_used_when_attempt_timeout_is_longer(){var r=new A39RecordingProcessRunner();await Create(r).ProbeAsync("x",default);Assert.Equal(TimeSpan.FromSeconds(60),r.CapturedTimeout);}
}
