using System.ComponentModel;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Astronomy.MediaFactory.ProductionAdapters;
using Astronomy.MediaFactory.Rendering;
using FluentAssertions;
using Microsoft.Extensions.Options;

namespace Astronomy.MediaFactory.Tests.ProductionAdapters;

public sealed class ExistingFFmpegDocumentarySceneProviderBindingTests
{
    [Fact] public async Task Successful_composition_invokes_one_process_and_owns_deterministic_output()
    { using var temp=new Temp();var runner=new RecordingProcessRunner{OnExecute=(_,_)=>File.WriteAllBytesAsync(Path.Combine(temp.Path,"provider-scene.mp4"),[1,2,3])};var sut=Create(runner,17);using var cts=new CancellationTokenSource();var result=await sut.ComposeAsync(DocumentarySceneCompositionTestFixtures.ProviderRequest(temp.Path,DocumentarySceneSubtitleMode.BurnIn),cts.Token);result.Succeeded.Should().BeTrue();result.OutputPath.Should().Be(Path.Combine(temp.Path,"provider-scene.mp4"));runner.InvocationCount.Should().Be(1);runner.CapturedCancellationToken.Should().Be(cts.Token);runner.CapturedTimeout.Should().Be(TimeSpan.FromSeconds(17));runner.CapturedArguments.Should().Contain("one.png").And.Contain("two.jpg").And.Contain("narration.wav").And.Contain("subtitle.srt"); }
    [Fact] public async Task Silent_scene_omits_audio_and_subtitles(){using var t=new Temp();var runner=new RecordingProcessRunner{OnExecute=(_,_)=>File.WriteAllBytesAsync(Path.Combine(t.Path,"provider-scene.mp4"),[1])};var r=DocumentarySceneCompositionTestFixtures.ProviderRequest(t.Path) with{NarrationAudioPath=null};await Create(runner).ComposeAsync(r,default);runner.CapturedArguments.Should().NotContain("-c:a").And.NotContain("subtitles=");}
    [Theory]
    [InlineData("format")][InlineData("width")][InlineData("height")][InlineData("fps")][InlineData("duration")][InlineData("visuals")][InlineData("muxed")]
    public async Task Invalid_profiles_are_rejected_without_process(string defect){using var t=new Temp();var runner=new RecordingProcessRunner();var r=DocumentarySceneCompositionTestFixtures.ProviderRequest(t.Path);r=defect switch{"format"=>r with{OutputFormat=DocumentaryMediaAssetFormat.Wav},"width"=>r with{Width=0},"height"=>r with{Height=0},"fps"=>r with{FrameRate=0},"duration"=>r with{DurationMilliseconds=0},"visuals"=>r with{OrderedVisualPaths=[]},_=>r with{SubtitleMode=DocumentarySceneSubtitleMode.Muxed}};var result=await Create(runner).ComposeAsync(r,default);result.Failure!.Code.Should().Be(DocumentaryProductionFailureCode.ProviderRejectedRequest);runner.InvocationCount.Should().Be(0);}
    [Fact] public async Task Burn_in_requires_subtitle(){using var t=new Temp();var r=DocumentarySceneCompositionTestFixtures.ProviderRequest(t.Path) with{SubtitleMode=DocumentarySceneSubtitleMode.BurnIn,SubtitlePath=null};(await Create(new()).ComposeAsync(r,default)).Failure!.Code.Should().Be(DocumentaryProductionFailureCode.SubtitleMissing);}
    [Theory][InlineData(1,false,"",DocumentaryProductionFailureCode.ProcessExitedWithError)][InlineData(0,true,"",DocumentaryProductionFailureCode.ProcessTimedOut)][InlineData(0,false,"boom",DocumentaryProductionFailureCode.ProcessStartFailed)]
    public async Task Process_failures_are_stable(int exit,bool timeout,string exception,DocumentaryProductionFailureCode code){using var t=new Temp();var runner=new RecordingProcessRunner{Output=RecordingProcessRunner.Result(exit,timeout,exception)};var result=await Create(runner).ComposeAsync(DocumentarySceneCompositionTestFixtures.ProviderRequest(t.Path),default);result.Failure!.Code.Should().Be(code);}
    [Fact] public async Task Missing_and_empty_outputs_are_rejected(){using var t=new Temp();var missing=await Create(new()).ComposeAsync(DocumentarySceneCompositionTestFixtures.ProviderRequest(t.Path),default);missing.Failure!.Code.Should().Be(DocumentaryProductionFailureCode.OutputArtifactMissing);var runner=new RecordingProcessRunner{OnExecute=(_,_)=>File.WriteAllBytesAsync(Path.Combine(t.Path,"provider-scene.mp4"),[])};(await Create(runner).ComposeAsync(DocumentarySceneCompositionTestFixtures.ProviderRequest(t.Path),default)).Failure!.Code.Should().Be(DocumentaryProductionFailureCode.OutputArtifactEmpty);}
    [Theory][InlineData(typeof(Win32Exception),DocumentaryProductionFailureCode.DependencyMissing)][InlineData(typeof(IOException),DocumentaryProductionFailureCode.ProcessStartFailed)] public async Task Start_exceptions_are_normalized(Type type,DocumentaryProductionFailureCode code){using var t=new Temp();var runner=new RecordingProcessRunner{Exception=(Exception)Activator.CreateInstance(type)!};(await Create(runner).ComposeAsync(DocumentarySceneCompositionTestFixtures.ProviderRequest(t.Path),default)).Failure!.Code.Should().Be(code);}
    [Fact] public async Task Caller_cancellation_propagates(){using var t=new Temp();using var cts=new CancellationTokenSource();var runner=new RecordingProcessRunner{WaitForCancellation=true};var task=Create(runner).ComposeAsync(DocumentarySceneCompositionTestFixtures.ProviderRequest(t.Path),cts.Token);cts.Cancel();await FluentActions.Awaiting(()=>task).Should().ThrowAsync<OperationCanceledException>();}
    static ExistingFFmpegDocumentarySceneProviderBinding Create(RecordingProcessRunner runner,int timeout=9)=>new(runner,new FfmpegArgumentBuilder(),Options.Create(new RenderingOptions{FfmpegPath="fake-ffmpeg",FfmpegSegmentTimeoutSeconds=timeout}));
    sealed class Temp:IDisposable{public string Path{get;}=System.IO.Path.Combine(System.IO.Path.GetTempPath(),Guid.NewGuid().ToString("N"));public Temp()=>Directory.CreateDirectory(Path);public void Dispose()=>Directory.Delete(Path,true);}
}
