using Astronomy.MediaFactory.Core.DocumentaryBlueprint;using Astronomy.MediaFactory.ProductionAdapters;using Xunit;
namespace Astronomy.MediaFactory.Tests.ProductionAdapters;
public sealed class ExistingFFprobeDocumentaryMediaVerificationProviderBindingTests {
 static DocumentaryMediaVerificationProviderRequest Request(TimeSpan? timeout=null)=>new("a",DocumentaryPhysicalArtifactKind.NarrationAudio,DocumentaryMediaAssetType.NarrationAudio,DocumentaryMediaAssetFormat.Wav,"c",1,"/final/a.wav","audio/wav","policy",timeout??TimeSpan.FromSeconds(5));
 [Fact] public async Task Provider_binding_invokes_probe_once_and_preserves_metadata(){var p=new FakeFfprobeProbe();using var cts=new CancellationTokenSource();var b=new ExistingFFprobeDocumentaryMediaVerificationProviderBinding(p);var x=await b.ProbeAsync(Request(),cts.Token);Assert.Equal("ExistingFFprobeMediaVerifier",b.ProviderId);Assert.True(x.Succeeded);Assert.Equal(1,p.InvocationCount);Assert.Equal("/final/a.wav",p.Path);Assert.Equal(cts.Token,p.Token);Assert.Equal(TimeSpan.FromSeconds(5),p.Timeout);Assert.NotNull(x.ProbeResult);Assert.True(x.ElapsedMilliseconds>=0);}
 [Fact] public async Task Probe_stable_failure_is_preserved(){var failure=new DocumentaryProductionFailure(DocumentaryProductionFailureCode.ProcessTimedOut,"safe");var p=new FakeFfprobeProbe{Result=new(false,Failure:failure)};var x=await new ExistingFFprobeDocumentaryMediaVerificationProviderBinding(p).ProbeAsync(Request(),default);Assert.Same(failure,x.Failure);}
 [Fact] public async Task Probe_success_false_without_failure_is_rejected_safely(){var p=new FakeFfprobeProbe{Result=new(false)};var x=await new ExistingFFprobeDocumentaryMediaVerificationProviderBinding(p).ProbeAsync(Request(),default);Assert.Equal(DocumentaryProductionFailureCode.ProviderInvalidResponse,x.Failure!.Code);}
 [Fact] public async Task Caller_cancellation_propagates(){var p=new FakeFfprobeProbe{WaitForCancellation=true};using var cts=new CancellationTokenSource();var t=new ExistingFFprobeDocumentaryMediaVerificationProviderBinding(p).ProbeAsync(Request(),cts.Token);cts.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>t);}
 [Fact] public void Media_verification_provider_identity_is_stable(){Assert.Equal("ExistingFFprobeMediaVerifier",new ExistingFFprobeDocumentaryMediaVerificationProviderBinding(new FakeFfprobeProbe()).ProviderId);}
}
