using System.Text;
using Astronomy.MediaFactory.ProductionAdapters;

namespace Astronomy.MediaFactory.Tests.ProductionAdapters;

public sealed class ProductionBridgeFoundationTests : IDisposable {
 readonly string root=Path.Combine(Path.GetTempPath(),"a3-"+Guid.NewGuid().ToString("N"));
 public void Dispose(){if(Directory.Exists(root))Directory.Delete(root,true);}

 [Fact] public void Options_are_safely_disabled_by_default(){var o=new DocumentaryProductionAdaptersOptions();Assert.False(o.Enabled);Assert.Equal(DocumentaryProductionExecutionMode.Legacy,o.ExecutionMode);Assert.False(o.EnableLegacyFallback);Assert.True(new DocumentaryProductionAdaptersOptionsValidator().Validate(null,o).Succeeded);}
 [Fact] public void Options_reject_invalid_enabled_and_certified_configuration(){var v=new DocumentaryProductionAdaptersOptionsValidator();Assert.True(v.Validate(null,new(){Enabled=true}).Failed);Assert.True(v.Validate(null,new(){ExecutionMode=DocumentaryProductionExecutionMode.Certified}).Failed);Assert.True(v.Validate(null,new(){CleanupTimeoutSeconds=0}).Failed);}
 [Theory][InlineData("a/b","a_b-")][InlineData("CON","CON-")][InlineData("नमस्ते","asset-")]
 public void Safe_names_are_deterministic_and_portable(string input,string prefix){var g=new DocumentarySafeFileNameGenerator();var first=g.Create(input);Assert.StartsWith(prefix,first);Assert.Equal(first,g.Create(input));Assert.DoesNotContain('/',first);}
 [Fact] public void Safe_names_disambiguate_collisions_and_bound_long_values(){var g=new DocumentarySafeFileNameGenerator();Assert.NotEqual(g.Create("a/b"),g.Create("a:b"));Assert.True(g.Create(new string('x',200)).Length<=100);}
 [Fact] public async Task Checksum_and_identity_use_known_sha256_vector(){Directory.CreateDirectory(root);var p=Path.Combine(root,"x");await File.WriteAllTextAsync(p,"abc");var hash=await new DocumentaryChecksumService().ComputeSha256Async(p,CancellationToken.None);Assert.Equal("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",hash);var f=new DocumentaryContentIdentityFactory();Assert.Equal("sha256:"+hash,f.Create(hash));Assert.True(f.IsValid("sha256:"+hash));Assert.Throws<ArgumentException>(()=>f.Create(hash.ToUpperInvariant()));}
 [Fact] public async Task Checksum_honors_cancellation_and_missing_file(){var s=new DocumentaryChecksumService();await Assert.ThrowsAsync<FileNotFoundException>(()=>s.ComputeSha256Async(Path.Combine(root,"missing"),CancellationToken.None));using var c=new CancellationTokenSource();c.Cancel();Directory.CreateDirectory(root);var p=Path.Combine(root,"x");await File.WriteAllTextAsync(p,"x");await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>s.ComputeSha256Async(p,c.Token));}
 [Fact] public async Task Workspace_finalization_is_atomic_idempotent_and_conflict_safe(){var m=Manager();var w=await Workspace(m);var tmp=m.GetAttemptDirectory(w,DocumentaryProductionOperationKind.VisualGeneration,"asset",1);Directory.CreateDirectory(tmp);var input=Path.Combine(tmp,"x.tmp");await File.WriteAllTextAsync(input,"one");var final=m.GetFinalArtifactPath(w,"long",1,DocumentaryPhysicalArtifactKind.VisualImage,"asset","png");await m.FinalizeArtifactAsync(w,input,final,false,CancellationToken.None);Assert.Equal("one",await File.ReadAllTextAsync(final));Directory.CreateDirectory(tmp);await File.WriteAllTextAsync(input,"one");await m.FinalizeArtifactAsync(w,input,final,false,CancellationToken.None);Directory.CreateDirectory(tmp);await File.WriteAllTextAsync(input,"two");await Assert.ThrowsAsync<IOException>(()=>m.FinalizeArtifactAsync(w,input,final,false,CancellationToken.None));await m.FinalizeArtifactAsync(w,input,final,true,CancellationToken.None);Assert.Equal("two",await File.ReadAllTextAsync(final));}
 [Fact] public async Task Workspace_prevents_escape_and_empty_finalization(){var m=Manager();var w=await Workspace(m);var tmp=m.GetAttemptDirectory(w,DocumentaryProductionOperationKind.Checksum,"a",1);Directory.CreateDirectory(tmp);var p=Path.Combine(tmp,"empty");File.Create(p).Dispose();await Assert.ThrowsAsync<UnauthorizedAccessException>(()=>m.FinalizeArtifactAsync(w,p,Path.Combine(root,"..","escape"),false,CancellationToken.None));await Assert.ThrowsAsync<InvalidDataException>(()=>m.FinalizeArtifactAsync(w,p,Path.Combine(w.ExecutionRoot,"x"),false,CancellationToken.None));}
 [Fact] public async Task Registry_is_ordered_idempotent_and_rejects_conflicts(){var r=new DocumentaryPhysicalArtifactRegistry();var b=Descriptor("b",'b');var a=Descriptor("a",'a');await r.RegisterAsync(b,DocumentaryPhysicalArtifactKind.VisualImage,default);await r.RegisterAsync(a,DocumentaryPhysicalArtifactKind.VisualImage,default);await r.RegisterAsync(a,DocumentaryPhysicalArtifactKind.VisualImage,default);Assert.Equal(new[]{"a","b"},(await r.GetAllAsync("cor",default)).Select(x=>x.AssetId));await Assert.ThrowsAsync<InvalidOperationException>(()=>r.RegisterAsync(a with{Checksum=new string('c',64),ContentIdentity="sha256:"+new string('c',64)},DocumentaryPhysicalArtifactKind.VisualImage,default));await r.PersistAsync(root,default);Assert.True(File.Exists(Path.Combine(root,"documentary-artifacts.json")));}
 [Fact] public void Descriptor_validation_is_pure_and_rejects_temp(){var v=new DocumentaryPhysicalArtifactDescriptorValidator(new DocumentaryContentIdentityFactory());var d=Descriptor("a",'a') with{PhysicalPath=Path.Combine(root,"tmp","a")};Assert.Contains("TemporaryPathRejected",v.Validate(d));Assert.Equal(d,v.Validate(d) is not null?d:null);}
 [Fact] public void Failure_normalizer_preserves_caller_cancellation(){var n=new DocumentaryProductionFailureNormalizer();Assert.Throws<OperationCanceledException>(()=>n.Normalize(new OperationCanceledException(),DocumentaryProductionOperationKind.VisualGeneration,true));Assert.Equal(DocumentaryProductionFailureCode.ProviderTimeout,n.Normalize(new TimeoutException(),DocumentaryProductionOperationKind.VisualGeneration,false).Code);Assert.Equal(DocumentaryProductionFailureCode.FileSystemFailure,n.Normalize(new IOException(),DocumentaryProductionOperationKind.Checksum,false).Code);}
 [Fact] public void Production_sources_contain_no_blocking_async_patterns(){var dir=FindProject();foreach(var f in Directory.GetFiles(dir,"*.cs")){var text=File.ReadAllText(f);Assert.DoesNotContain(".Result",text);Assert.DoesNotContain(".Wait()",text);Assert.DoesNotContain("GetAwaiter().GetResult()",text);}}
 DocumentaryProductionWorkspaceManager Manager()=>new(new DocumentarySafeFileNameGenerator(),new DocumentaryChecksumService());
 async Task<DocumentaryProductionWorkspace> Workspace(DocumentaryProductionWorkspaceManager m)=>await m.CreateAsync(new("exec","cor",DocumentaryProductionExecutionMode.Shadow,root,DateTimeOffset.UnixEpoch,new Dictionary<string,string>()),default);
 DocumentaryPhysicalArtifactDescriptor Descriptor(string id,char hash)=>new(id,"sha256:"+new string(hash,64),Path.GetFullPath(Path.Combine(root,id)),"image/png",1,new string(hash,64),null,null,null,null,null,null,"fake",1,"cor");
 static string FindProject(){var d=new DirectoryInfo(AppContext.BaseDirectory);while(d is not null){var p=Path.Combine(d.FullName,"src","Astronomy.MediaFactory.ProductionAdapters");if(Directory.Exists(p))return p;d=d.Parent;}throw new DirectoryNotFoundException();}
}
