using System.Collections.Immutable;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Catalog;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Contracts;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Adapters.Contracts;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Catalog;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Contracts;

namespace Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Adapters.Event;

public abstract class SemanticSourceAdapterV1Base<T>(string adapterId, string capability, string sourceId, SemanticEvidenceCategoryV1 category, SemanticEvidenceStrengthV1 strength, bool eventSpecific) : ISemanticSourceAdapterV1
{
    public string AdapterId { get; } = adapterId; public SemanticCapabilityId SupportedCapabilityId { get; } = new(capability); public string SourceId { get; } = sourceId; public SemanticEvidenceCategoryV1 EvidenceCategory { get; } = category; public SemanticEvidenceStrengthV1 MaximumEvidenceStrength { get; } = strength; public bool EventSpecific { get; } = eventSpecific; public virtual bool SupportsLocalization => true; public virtual bool SupportsUnits => true; public virtual bool SupportsProvenance => true;
    public abstract SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 context);
    protected SemanticSourceAdapterResultV1 Missing() => SemanticSourceAdapterResultV1.Reject(SupportedCapabilityId, AdapterId, SourceId, SemanticSourceAdapterStatusV1.ValueMissing, "Typed source property was not supplied.");
    protected SemanticSourceAdapterResultV1 Unavailable() => SemanticSourceAdapterResultV1.Reject(SupportedCapabilityId, AdapterId, SourceId, SemanticSourceAdapterStatusV1.SourceUnavailable, "Typed source model was not supplied.");
    protected SemanticSourceAdapterResultV1 Unverified(string path) => SemanticSourceAdapterResultV1.Reject(SupportedCapabilityId, AdapterId, SourceId, SemanticSourceAdapterStatusV1.UnverifiedValue, "Source value is not verified.", [new("UnverifiedValue","Approved source requires verified structured data.",path)]);
    protected SemanticSourceAdapterResultV1 Invalid(string msg, string path) => SemanticSourceAdapterResultV1.Reject(SupportedCapabilityId, AdapterId, SourceId, SemanticSourceAdapterStatusV1.InvalidValue, msg, [new("InvalidValue",msg,path)]);
    protected SemanticSourceAdapterResultV1 Res(T value, string path, string? speak = null, SemanticEvidenceStrengthV1? strength = null) { var p = new SemanticSourceProvenanceV1(SourceId, typeof(T).Name, path, true); var c = new SemanticSourceCandidateV1(SupportedCapabilityId, AdapterId, SourceId, new(value!, typeof(T).Name), value?.ToString() ?? "", speak, EvidenceCategory, strength ?? MaximumEvidenceStrength, .95m, [p], [], [], [], []); return SemanticSourceAdapterResultV1.Resolved(c); }
}

public sealed class EventIdentitySourceAdapterV1() : SemanticSourceAdapterV1Base<CanonicalAstronomyEventIdentity>("v1.event-identity.event-identity-context", SemanticCapabilityVocabularyV1.EventIdentity, SemanticSourcePolicyVocabularyV1.EventIdentityContext, SemanticEvidenceCategoryV1.EventIdentityContext, SemanticEvidenceStrengthV1.Strong, true) { public override SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 c) => c.EventIdentity is null ? Unavailable() : Res(c.EventIdentity, nameof(c.EventIdentity)); }
public sealed class EventWindowSourceAdapterV1() : SemanticSourceAdapterV1Base<EventWindowValue>("v1.event-window.observation-metadata", SemanticCapabilityVocabularyV1.EventWindow, SemanticSourcePolicyVocabularyV1.ObservationMetadata, SemanticEvidenceCategoryV1.VerifiedEventData, SemanticEvidenceStrengthV1.Strong, true) { public override SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 c){ if(c.ObservationMetadata is null) return Unavailable(); if(!c.ObservationMetadata.Verified) return Unverified("ObservationMetadata"); var v=c.ObservationMetadata.EventWindow; if(v is null) return Missing(); if(v.StartUtc.HasValue&&v.PeakUtc.HasValue&&v.StartUtc>v.PeakUtc || v.PeakUtc.HasValue&&v.EndUtc.HasValue&&v.PeakUtc>v.EndUtc) return Invalid("Event window chronology must satisfy Start <= Peak <= End.","ObservationMetadata.EventWindow"); return Res(v,"ObservationMetadata.EventWindow",v.LocalizedWindowDescription);} }
public sealed class AstronomicalObjectsSourceAdapterV1() : SemanticSourceAdapterV1Base<ImmutableArray<AstronomicalObjectValue>>("v1.astronomical-objects.production-event-intelligence", SemanticCapabilityVocabularyV1.AstronomicalObjects, SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence, SemanticEvidenceCategoryV1.VerifiedEventData, SemanticEvidenceStrengthV1.Strong, true) { public override SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 c){ if(c.ProductionEventIntelligence is null) return Unavailable(); var a=c.ProductionEventIntelligence.PrimaryObjects.IsDefault?[]:c.ProductionEventIntelligence.PrimaryObjects.DistinctBy(o=>o.Name,StringComparer.OrdinalIgnoreCase).ToImmutableArray(); return a.Length==0?Missing():Res(a,"ProductionEventIntelligence.PrimaryObjects"); } }
public sealed class SecondaryAstronomicalObjectsSourceAdapterV1() : SemanticSourceAdapterV1Base<ImmutableArray<AstronomicalObjectValue>>("v1.secondary-astronomical-objects.production-event-intelligence", SemanticCapabilityVocabularyV1.SecondaryAstronomicalObjects, SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence, SemanticEvidenceCategoryV1.VerifiedEventData, SemanticEvidenceStrengthV1.Strong, true) { public override SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 c){ if(c.ProductionEventIntelligence is null) return Unavailable(); var a=c.ProductionEventIntelligence.SecondaryObjects.IsDefault?[]:c.ProductionEventIntelligence.SecondaryObjects; return a.Length==0?Missing():Res(a,"ProductionEventIntelligence.SecondaryObjects"); } }
public sealed class AngularSeparationSourceAdapterV1() : SemanticSourceAdapterV1Base<AngularSeparationValue>("v1.angular-separation.production-event-intelligence", SemanticCapabilityVocabularyV1.AngularSeparation, SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence, SemanticEvidenceCategoryV1.VerifiedEventData, SemanticEvidenceStrengthV1.Strong, true) { public override SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 c){ var v=c.ProductionEventIntelligence?.AngularSeparation; if(c.ProductionEventIntelligence is null) return Unavailable(); if(v is null) return Missing(); if(v.Degrees<0||v.Degrees>180) return Invalid("Angular separation must be within [0, 180] degrees.","ProductionEventIntelligence.AngularSeparation.Degrees"); return Res(v with { },"ProductionEventIntelligence.AngularSeparation",$"{v.Degrees} degrees"); } }
public sealed class ObservationDirectionSourceAdapterV1() : SemanticSourceAdapterV1Base<ObservationDirectionValue>("v1.observation-direction.observation-metadata", SemanticCapabilityVocabularyV1.ObservationDirection, SemanticSourcePolicyVocabularyV1.ObservationMetadata, SemanticEvidenceCategoryV1.VerifiedEventData, SemanticEvidenceStrengthV1.Strong, true) { public override SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 c)=>c.ObservationMetadata is null?Unavailable():c.ObservationMetadata.ObservationDirection is null?Missing():Res(c.ObservationMetadata.ObservationDirection,"ObservationMetadata.ObservationDirection",c.ObservationMetadata.ObservationDirection.LocalizedDescription); }
public sealed class ObservationLocationSourceAdapterV1() : SemanticSourceAdapterV1Base<ObservationLocationValue>("v1.observation-location.observation-metadata", SemanticCapabilityVocabularyV1.ObservationLocation, SemanticSourcePolicyVocabularyV1.ObservationMetadata, SemanticEvidenceCategoryV1.VerifiedEventData, SemanticEvidenceStrengthV1.Strong, true) { public override SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 c){ var v=c.ObservationMetadata?.ObservationLocation; if(c.ObservationMetadata is null) return Unavailable(); if(v is null) return Missing(); if(v.Latitude is < -90 or > 90) return Invalid("Latitude must be within [-90, 90].","ObservationMetadata.ObservationLocation.Latitude"); if(v.Longitude is < -180 or > 180) return Invalid("Longitude must be within [-180, 180].","ObservationMetadata.ObservationLocation.Longitude"); if(v.ClaimsLocalTimeConversion&&string.IsNullOrWhiteSpace(v.TimeZone)) return Invalid("Time zone is required when local-time conversion is claimed.","ObservationMetadata.ObservationLocation.TimeZone"); return Res(v,"ObservationMetadata.ObservationLocation",v.LocationName);} }
public sealed class ObservationConditionsSourceAdapterV1() : SemanticSourceAdapterV1Base<ObservationConditionsValue>("v1.observation-conditions.observation-metadata", SemanticCapabilityVocabularyV1.ObservationConditions, SemanticSourcePolicyVocabularyV1.ObservationMetadata, SemanticEvidenceCategoryV1.VerifiedEventData, SemanticEvidenceStrengthV1.Strong, true) { public override SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 c)=>c.ObservationMetadata is null?Unavailable():c.ObservationMetadata.ObservationConditions is null?Missing():Res(c.ObservationMetadata.ObservationConditions with { CurrentWeather=null, CloudCover=null, Seeing=null, Transparency=null },"ObservationMetadata.ObservationConditions"); }
public sealed class MeteorActivitySourceAdapterV1() : SemanticSourceAdapterV1Base<MeteorActivityValue>("v1.meteor-activity.production-event-intelligence", SemanticCapabilityVocabularyV1.MeteorActivity, SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence, SemanticEvidenceCategoryV1.VerifiedEventData, SemanticEvidenceStrengthV1.Strong, true) { public override SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 c)=>c.ProductionEventIntelligence is null?Unavailable():c.ProductionEventIntelligence.MeteorActivity is null?Missing():Res(c.ProductionEventIntelligence.MeteorActivity,"ProductionEventIntelligence.MeteorActivity"); }
public sealed class FullMoonObservationSourceAdapterV1() : SemanticSourceAdapterV1Base<FullMoonObservationValue>("v1.full-moon-observation.observation-metadata", SemanticCapabilityVocabularyV1.FullMoonObservation, SemanticSourcePolicyVocabularyV1.ObservationMetadata, SemanticEvidenceCategoryV1.VerifiedEventData, SemanticEvidenceStrengthV1.Strong, true) { public override SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 c)=>c.ObservationMetadata is null?Unavailable():c.ObservationMetadata.FullMoonObservation is null?Missing():Res(c.ObservationMetadata.FullMoonObservation,"ObservationMetadata.FullMoonObservation"); }
public sealed class EclipseCircumstancesSourceAdapterV1() : SemanticSourceAdapterV1Base<EclipseCircumstancesValue>("v1.eclipse-circumstances.production-event-intelligence", SemanticCapabilityVocabularyV1.EclipseCircumstances, SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence, SemanticEvidenceCategoryV1.VerifiedEventData, SemanticEvidenceStrengthV1.Strong, true) { public override SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 c){ var v=c.ProductionEventIntelligence?.EclipseCircumstances; if(c.ProductionEventIntelligence is null) return Unavailable(); if(v is null) return Missing(); if(v.Magnitude is < 0 or > 2 || v.Obscuration is < 0 or > 1) return Invalid("Eclipse numeric ranges are invalid.","ProductionEventIntelligence.EclipseCircumstances"); if(v.Start.HasValue&&v.Maximum.HasValue&&v.Start>v.Maximum || v.Maximum.HasValue&&v.End.HasValue&&v.Maximum>v.End) return Invalid("Eclipse chronology must satisfy start <= maximum <= end.","ProductionEventIntelligence.EclipseCircumstances"); return Res(v,"ProductionEventIntelligence.EclipseCircumstances",v.EclipseType); } }
public sealed class OccultationContactsSourceAdapterV1() : SemanticSourceAdapterV1Base<OccultationContactsValue>("v1.occultation-contacts.production-event-intelligence", SemanticCapabilityVocabularyV1.OccultationContacts, SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence, SemanticEvidenceCategoryV1.VerifiedEventData, SemanticEvidenceStrengthV1.Strong, true) { public override SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 c){ var v=c.ProductionEventIntelligence?.OccultationContacts; if(c.ProductionEventIntelligence is null) return Unavailable(); if(v is null) return Missing(); var times=new[]{v.Ingress,v.Maximum,v.Egress,v.Reappearance}.Where(x=>x.HasValue).Select(x=>x!.Value).ToArray(); if(times.Zip(times.Skip(1)).Any(p=>p.First>p.Second)) return Invalid("Occultation contacts must be chronological.","ProductionEventIntelligence.OccultationContacts"); return Res(v,"ProductionEventIntelligence.OccultationContacts"); } }
public sealed class SafetyGuidanceEventSourceAdapterV1() : SemanticSourceAdapterV1Base<SafetyGuidanceValue>("v1.safety-guidance.production-event-intelligence", SemanticCapabilityVocabularyV1.SafetyGuidance, SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence, SemanticEvidenceCategoryV1.VerifiedEventData, SemanticEvidenceStrengthV1.Strong, true) { public override SemanticSourceAdapterResultV1 TryExtract(SemanticSourceAdapterContextV1 c)=>c.ProductionEventIntelligence is null?Unavailable():c.ProductionEventIntelligence.SafetyGuidance is null?Missing():Res(c.ProductionEventIntelligence.SafetyGuidance,"ProductionEventIntelligence.SafetyGuidance"); }
