using System.Collections.Immutable;
using Astronomy.MediaFactory.Core.ExecutionContracts;

namespace Astronomy.MediaFactory.Core.ExecutionValidation;

public sealed record ExecutionValidationIssue
{
    public ExecutionValidationIssue(ExecutionValidationIssueCode IssueCode, string RequirementId, FamilyValidationBoundary Boundary, FamilyValidationSeverity Severity, ExecutionRequirementOutcome Outcome, string Message, string? Expected = null, string? Actual = null, string? SourceKey = null, ImmutableArray<string> Evidence = default, ImmutableDictionary<string,string>? Metadata = null)
    { this.IssueCode = IssueCode; this.RequirementId = ValidationGuard.RequireNonEmpty(RequirementId, nameof(RequirementId)); this.Boundary = Boundary; this.Severity = Severity; this.Outcome = Outcome; this.Message = ValidationGuard.RequireNonEmpty(Message, nameof(Message)); this.Expected = ValidationGuard.Optional(Expected); this.Actual = ValidationGuard.Optional(Actual); this.SourceKey = ValidationGuard.Optional(SourceKey); this.Evidence = ValidationGuard.Array(Evidence); this.Metadata = ValidationGuard.Metadata(Metadata); }
    public ExecutionValidationIssueCode IssueCode { get; init; } public string RequirementId { get; init; } public FamilyValidationBoundary Boundary { get; init; } public FamilyValidationSeverity Severity { get; init; } public ExecutionRequirementOutcome Outcome { get; init; } public string Message { get; init; } public string? Expected { get; init; } public string? Actual { get; init; } public string? SourceKey { get; init; } public ImmutableArray<string> Evidence { get; init; } public ImmutableDictionary<string,string> Metadata { get; init; }
}
public sealed record ExecutionRequirementEvaluation
{
    public ExecutionRequirementEvaluation(string RequirementId, FamilyValidationBoundary Boundary, ExecutionRequirementOutcome Outcome, FamilyValidationSeverity Severity, bool IsBlocking, string? SourceKey = null, ImmutableArray<ExecutionValidationIssue> Issues = default, ImmutableDictionary<string,string>? Metadata = null)
    { this.RequirementId = ValidationGuard.RequireNonEmpty(RequirementId, nameof(RequirementId)); this.Boundary = Boundary; this.Outcome = Outcome; this.Severity = Severity; this.IsBlocking = IsBlocking; this.SourceKey = ValidationGuard.Optional(SourceKey); this.Issues = ValidationGuard.Array(Issues); this.Metadata = ValidationGuard.Metadata(Metadata); }
    public string RequirementId { get; init; } public FamilyValidationBoundary Boundary { get; init; } public ExecutionRequirementOutcome Outcome { get; init; } public FamilyValidationSeverity Severity { get; init; } public bool IsBlocking { get; init; } public string? SourceKey { get; init; } public ImmutableArray<ExecutionValidationIssue> Issues { get; init; } public ImmutableDictionary<string,string> Metadata { get; init; }
}
public sealed record ExecutionValidationResult
{
    public ExecutionValidationResult(string ExecutionId, string DomainId, string FamilyId, string ContractVersion, FamilyValidationBoundary Boundary, ImmutableArray<ExecutionRequirementEvaluation> Evaluations, DateTimeOffset StartedUtc, DateTimeOffset CompletedUtc, ImmutableArray<string> ValidatorIds = default, ImmutableDictionary<string,string>? Metadata = null)
    { this.ExecutionId = ValidationGuard.RequireNonEmpty(ExecutionId, nameof(ExecutionId)); this.DomainId = ValidationGuard.RequireNonEmpty(DomainId, nameof(DomainId)); this.FamilyId = ValidationGuard.RequireNonEmpty(FamilyId, nameof(FamilyId)); this.ContractVersion = ValidationGuard.RequireNonEmpty(ContractVersion, nameof(ContractVersion)); this.Boundary = Boundary; this.Evaluations = OrderEvaluations(ValidationGuard.Array(Evaluations)); this.Issues = OrderIssues(this.Evaluations.SelectMany(e => e.Issues).ToImmutableArray()); this.Status = HasBlocking(Issues) ? ExecutionValidationStatus.Invalid : Issues.Any(i => i.Severity == FamilyValidationSeverity.Warning) ? ExecutionValidationStatus.ValidWithWarnings : ExecutionValidationStatus.Valid; this.StartedUtc = StartedUtc; this.CompletedUtc = CompletedUtc; this.ValidatorIds = ValidationGuard.Array(ValidatorIds); this.Metadata = ValidationGuard.Metadata(Metadata); }
    public string ExecutionId { get; init; } public string DomainId { get; init; } public string FamilyId { get; init; } public string ContractVersion { get; init; } public FamilyValidationBoundary Boundary { get; init; } public ExecutionValidationStatus Status { get; init; } public ImmutableArray<ExecutionRequirementEvaluation> Evaluations { get; init; } public ImmutableArray<ExecutionValidationIssue> Issues { get; init; } public DateTimeOffset StartedUtc { get; init; } public DateTimeOffset CompletedUtc { get; init; } public ImmutableArray<string> ValidatorIds { get; init; } public ImmutableDictionary<string,string> Metadata { get; init; }
    public bool HasBlockingIssues => BlockingIssueCount > 0; public int BlockingIssueCount => Issues.Count(i => i.Severity == FamilyValidationSeverity.Blocking); public int WarningCount => Issues.Count(i => i.Severity == FamilyValidationSeverity.Warning); public int InformationCount => Issues.Count(i => i.Severity == FamilyValidationSeverity.Information);
    private static bool HasBlocking(IEnumerable<ExecutionValidationIssue> issues) => issues.Any(i => i.Severity == FamilyValidationSeverity.Blocking);
    internal static ImmutableArray<ExecutionValidationIssue> OrderIssues(ImmutableArray<ExecutionValidationIssue> issues) => issues.OrderBy(i => i.Boundary).ThenByDescending(i => i.Severity == FamilyValidationSeverity.Blocking).ThenBy(i => i.RequirementId, StringComparer.OrdinalIgnoreCase).ThenBy(i => i.IssueCode).ThenBy(i => i.Message, StringComparer.Ordinal).ToImmutableArray();
    internal static ImmutableArray<ExecutionRequirementEvaluation> OrderEvaluations(ImmutableArray<ExecutionRequirementEvaluation> evaluations) => evaluations.OrderBy(e => e.Boundary).ThenBy(e => e.RequirementId, StringComparer.OrdinalIgnoreCase).ThenBy(e => e.SourceKey, StringComparer.OrdinalIgnoreCase).ToImmutableArray();
}
public sealed record ExecutionValidationRequest
{
    public ExecutionValidationRequest(DomainExecutionContract DomainContract, FamilyExecutionContract FamilyContract, FamilyExecutionContext Context, FamilyValidationBoundary Boundary, bool IncludeOptionalRequirements = false, bool EvaluateConditionalRequirements = true, DateTimeOffset? StartedUtc = null, ImmutableDictionary<string,string>? Metadata = null)
    { this.DomainContract = DomainContract ?? throw new ArgumentNullException(nameof(DomainContract)); this.FamilyContract = FamilyContract ?? throw new ArgumentNullException(nameof(FamilyContract)); this.Context = Context ?? throw new ArgumentNullException(nameof(Context)); this.Boundary = Boundary; this.IncludeOptionalRequirements = IncludeOptionalRequirements; this.EvaluateConditionalRequirements = EvaluateConditionalRequirements; this.StartedUtc = StartedUtc; this.Metadata = ValidationGuard.Metadata(Metadata); }
    public DomainExecutionContract DomainContract { get; init; } public FamilyExecutionContract FamilyContract { get; init; } public FamilyExecutionContext Context { get; init; } public FamilyValidationBoundary Boundary { get; init; } public bool IncludeOptionalRequirements { get; init; } public bool EvaluateConditionalRequirements { get; init; } public DateTimeOffset? StartedUtc { get; init; } public ImmutableDictionary<string,string> Metadata { get; init; }
}
