using Astronomy.MediaFactory.Core.KnowledgeFoundation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Extensions;
using Astronomy.MediaFactory.Core.AstronomyDomain.Taxonomy;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Coordinates;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Events;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Measurements;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Observational;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Orbital;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Positional;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Temporal;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.CrossDomain;

public static class AstronomyCrossDomainValidationCodes
{
    public const string EntityReferenceMismatch = "cross-domain.entity.reference-mismatch";
    public const string EntityReferenceMissing = "cross-domain.entity.reference-missing";
    public const string EpochMismatch = "cross-domain.epoch.mismatch";
    public const string EpochIncompatible = "cross-domain.epoch.incompatible";
    public const string ReferenceFrameMismatch = "cross-domain.reference-context.frame-mismatch";
    public const string ReferenceOriginMismatch = "cross-domain.reference-context.origin-mismatch";
    public const string CoordinateSystemMismatch = "cross-domain.reference-context.coordinate-system-mismatch";
    public const string ObserverContextMismatch = "cross-domain.reference-context.observer-context-mismatch";
    public const string MeasurementDimensionConflict = "cross-domain.measurement.dimension-conflict";
    public const string ClassificationSubjectMismatch = "cross-domain.classification.subject-mismatch";
    public const string EventParticipantMissingKnowledge = "cross-domain.event-participant.missing-knowledge";
    public const string EventParticipantIdentityMismatch = "cross-domain.event-participant.identity-mismatch";
    public const string EventTemporalExtentConflict = "cross-domain.event-temporal.extent-conflict";
    public const string EventOccurrenceMismatch = "cross-domain.event-temporal.occurrence-mismatch";
    public const string ObservationVisibilityContextMismatch = "cross-domain.observation-visibility.context-mismatch";
    public const string ObservationTimeOutsideVisibilityWindow = "cross-domain.observation-visibility.observation-time-outside-window";
    public const string OrbitalPositionEntityMismatch = "cross-domain.orbital-positional.entity-mismatch";
    public const string OrbitalPositionEpochMismatch = "cross-domain.orbital-positional.epoch-mismatch";
    public const string OrbitalPositionReferenceMismatch = "cross-domain.orbital-positional.reference-mismatch";
}

public enum AstronomyCrossDomainRelationshipKind
{
    EntityIdentity,
    Epoch,
    ReferenceContext,
    Measurement,
    ClassificationSubject,
    EventParticipantKnowledgeRequired,
    EventTemporalApplicability,
    EventTemporalOccurrence,
    ObservationVisibilityWindow,
    OrbitalPositional
}

public sealed record AstronomyCrossDomainRelationship(int LeftPayloadIndex, int RightPayloadIndex, AstronomyCrossDomainRelationshipKind Kind)
{
    public int LeftPayloadIndex { get; } = LeftPayloadIndex >= 0 ? LeftPayloadIndex : throw new ArgumentOutOfRangeException(nameof(LeftPayloadIndex));
    public int RightPayloadIndex { get; } = RightPayloadIndex >= 0 ? RightPayloadIndex : throw new ArgumentOutOfRangeException(nameof(RightPayloadIndex));
    public AstronomyCrossDomainRelationshipKind Kind { get; } = Enum.IsDefined(Kind) ? Kind : throw new ArgumentOutOfRangeException(nameof(Kind));
}

public sealed record AstronomyCrossDomainValidationSet
{
    public AstronomyCrossDomainValidationSet(IReadOnlyList<ITypedAstronomyKnowledgePayload> payloads)
    {
        ArgumentNullException.ThrowIfNull(payloads);
        Payloads = Array.AsReadOnly(payloads.Select(p => p ?? throw new ArgumentException("Payload collection cannot contain null entries.", nameof(payloads))).ToArray());
    }
    public IReadOnlyList<ITypedAstronomyKnowledgePayload> Payloads { get; }
}

public sealed record AstronomyCrossDomainValidationContext
{
    public AstronomyCrossDomainValidationContext(AstronomyKnowledgeValidationRunId validationRunId, DateTimeOffset referenceInstantUtc, AstronomyKnowledgeValidationMode mode = AstronomyKnowledgeValidationMode.Standard, AstronomyKnowledgeValidationSeverity minimumSeverity = AstronomyKnowledgeValidationSeverity.Information, AstronomyEntityReference? entityScope = null, IReadOnlyList<AstronomyCrossDomainRelationship>? relationships = null)
    { if (!validationRunId.IsValid) throw new ArgumentException("Validation run ID is required.", nameof(validationRunId)); if(referenceInstantUtc.Offset!=TimeSpan.Zero) throw new ArgumentException("Reference instant must be UTC.", nameof(referenceInstantUtc)); ValidationRunId=validationRunId; ReferenceInstantUtc=referenceInstantUtc; Mode=mode; MinimumSeverity=minimumSeverity; EntityScope=entityScope; Relationships=Array.AsReadOnly((relationships ?? Array.Empty<AstronomyCrossDomainRelationship>()).Select(r => r ?? throw new ArgumentException("Relationships cannot contain null entries.", nameof(relationships))).ToArray()); }
    public AstronomyKnowledgeValidationRunId ValidationRunId { get; }
    public DateTimeOffset ReferenceInstantUtc { get; }
    public AstronomyKnowledgeValidationMode Mode { get; }
    public AstronomyKnowledgeValidationSeverity MinimumSeverity { get; }
    public AstronomyEntityReference? EntityScope { get; }
    public IReadOnlyList<AstronomyCrossDomainRelationship> Relationships { get; }
}

public interface IAstronomyCrossDomainValidationRule { string RuleId { get; } int Order { get; } IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set, AstronomyCrossDomainValidationContext context); }
public sealed record AstronomyCrossDomainValidationRuleDescriptor(string RuleId, Type RuleType, int Order);
public interface IAstronomyCrossDomainValidationRuleRegistry { IReadOnlyList<AstronomyCrossDomainValidationRuleDescriptor> Descriptors { get; } }
public sealed class AstronomyCrossDomainValidationRuleRegistry : IAstronomyCrossDomainValidationRuleRegistry
{ public AstronomyCrossDomainValidationRuleRegistry(IEnumerable<AstronomyCrossDomainValidationRuleDescriptor> descriptors){Descriptors=Array.AsReadOnly((descriptors??throw new ArgumentNullException(nameof(descriptors))).Distinct().OrderBy(d=>d.Order).ThenBy(d=>d.RuleId,StringComparer.Ordinal).ToArray()); if(Descriptors.GroupBy(d=>d.RuleId,StringComparer.Ordinal).Any(g=>g.Count()>1)) throw new ArgumentException("Duplicate cross-domain rule ID.",nameof(descriptors));} public IReadOnlyList<AstronomyCrossDomainValidationRuleDescriptor> Descriptors{get;} }
public interface IAstronomyCrossDomainValidator { AstronomyKnowledgeValidationResult Validate(AstronomyCrossDomainValidationSet set, AstronomyCrossDomainValidationContext context); }
public sealed class AstronomyCrossDomainValidator : IAstronomyCrossDomainValidator
{ private readonly IReadOnlyList<IAstronomyCrossDomainValidationRule> rules; public AstronomyCrossDomainValidator(IEnumerable<IAstronomyCrossDomainValidationRule> rules){this.rules=(rules??throw new ArgumentNullException(nameof(rules))).GroupBy(r=>r.RuleId,StringComparer.Ordinal).Select(g=>g.First()).OrderBy(r=>r.Order).ThenBy(r=>r.RuleId,StringComparer.Ordinal).ToArray();} public AstronomyKnowledgeValidationResult Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext context){ArgumentNullException.ThrowIfNull(set); ArgumentNullException.ThrowIfNull(context); var issues=rules.SelectMany(r=>r.Validate(set,context)).Where(i=>i.Severity>=context.MinimumSeverity); return new AstronomyKnowledgeValidationResult(issues);} }

public abstract class AstronomyCrossDomainRuleBase : IAstronomyCrossDomainValidationRule
{
    public abstract string RuleId { get; }
    public abstract int Order { get; }
    public abstract IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set, AstronomyCrossDomainValidationContext context);
    protected static AstronomyKnowledgeValidationIssue Issue(string code, AstronomyKnowledgeValidationSeverity s, string msg, string path, string rule, AstronomyKnowledgeDomain d, AstronomyKnowledgePayloadFamily f) => new(code, s, msg, path, rule, d, f);
    protected static bool SameEntity(AstronomyEntityReference a, AstronomyEntityReference b) => StringComparer.Ordinal.Equals(a.EntityId, b.EntityId) && a.EntityKind == b.EntityKind;
    protected static IEnumerable<(int RelIndex, int Left, ITypedAstronomyKnowledgePayload LeftPayload, int Right, ITypedAstronomyKnowledgePayload RightPayload)> Pairs(AstronomyCrossDomainValidationSet set, AstronomyCrossDomainValidationContext c, AstronomyCrossDomainRelationshipKind kind)
    { for (var i = 0; i < c.Relationships.Count; i++) { var r = c.Relationships[i]; if (r.Kind != kind || r.LeftPayloadIndex >= set.Payloads.Count || r.RightPayloadIndex >= set.Payloads.Count) continue; yield return (i, r.LeftPayloadIndex, set.Payloads[r.LeftPayloadIndex], r.RightPayloadIndex, set.Payloads[r.RightPayloadIndex]); } }
    protected static AstronomyEntityReference? EntityOf(ITypedAstronomyKnowledgePayload p) => p switch { AstronomyOrbitalParametersPayload o => o.ReferenceContext.CentralBody, AstronomySpatialPositionPayload x => x.Position.ReferenceContext.OriginBody, AstronomyEntityClassificationPayload c => new AstronomyEntityReference(c.TypeId.Value, c.SubjectKind), _ => null };
    protected static AstronomyEpochReference? EpochOf(ITypedAstronomyKnowledgePayload p) => p switch { AstronomyOrbitalParametersPayload o => o.ReferenceContext.Epoch, AstronomySpatialPositionPayload x => x.Position.ReferenceContext.Epoch, _ => null };
    protected static (AstronomyReferenceFrame? Frame, AstronomyReferenceOrigin? Origin, AstronomyCoordinateSystem? System, string? Observer)? RefOf(ITypedAstronomyKnowledgePayload p) => p switch { AstronomyOrbitalParametersPayload o => (o.ReferenceContext.ReferenceFrame, o.ReferenceContext.ReferenceOrigin, null, null), AstronomySpatialPositionPayload x => (x.Position.ReferenceContext.ReferenceFrame, x.Position.ReferenceContext.ReferenceOrigin, x.Position.ReferenceContext.CoordinateSystem, null), AstronomyObservationConditionsPayload o => (o.ObservationContext.ReferenceFrame, o.ObservationContext.ReferenceOrigin, o.ObservationContext.CoordinateSystem, o.ObservationContext.ObserverLocationReference), AstronomyVisibilityWindowsPayload v => (v.ObservationContext.ReferenceFrame, v.ObservationContext.ReferenceOrigin, v.ObservationContext.CoordinateSystem, v.ObservationContext.ObserverLocationReference), AstronomyEventPayload e => (e.Event.ReferenceContext.ReferenceFrame, e.Event.ReferenceContext.ReferenceOrigin, e.Event.ReferenceContext.CoordinateSystem, e.Event.ReferenceContext.ObservationContext?.ObserverLocationReference), _ => null };
    protected static IEnumerable<(string Id, AstronomyMeasurementDimension Dim, AstronomyEpochReference? Epoch)> Measurements(ITypedAstronomyKnowledgePayload p) { if (p is AstronomyOrbitalParametersPayload o) foreach (var x in o.Parameters) yield return (x.ParameterId.Value, x.Measurement.Unit.Dimension, x.Epoch); if (p is AstronomyEventPayload e) foreach (var x in e.Event.Geometry) yield return (x.QuantityId.Value, x.Measurement.Unit.Dimension, x.Epoch); }
    protected static (DateTimeOffset Start, DateTimeOffset End) Extent(AstronomyEventTemporalExtent e) => e switch { AstronomyInstantEventTemporalExtent i => (i.InstantUtc, i.InstantUtc), AstronomyIntervalEventTemporalExtent i => (i.StartUtc, i.EndUtc), _ => throw new NotSupportedException() };
}
public sealed class AstronomyEntityConsistencyValidationRule : AstronomyCrossDomainRuleBase { public const string Id = "cross-domain.entity.consistency"; public override string RuleId => Id; public override int Order => 100; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set, AstronomyCrossDomainValidationContext c) { foreach (var p in Pairs(set,c,AstronomyCrossDomainRelationshipKind.EntityIdentity)) { var a=EntityOf(p.LeftPayload); var b=EntityOf(p.RightPayload); if(a is not null && b is not null && !SameEntity(a,b)) yield return Issue(AstronomyCrossDomainValidationCodes.EntityReferenceMismatch,AstronomyKnowledgeValidationSeverity.Error,"Related payload entity identities differ.",$"$.payloads[{p.Right}]",RuleId,p.RightPayload.Domain,p.RightPayload.Family); } if(c.EntityScope is not null) for(var i=0;i<set.Payloads.Count;i++){var e=EntityOf(set.Payloads[i]); if(e is not null&&!SameEntity(e,c.EntityScope)) yield return Issue(AstronomyCrossDomainValidationCodes.EntityReferenceMismatch,AstronomyKnowledgeValidationSeverity.Error,"Entity reference does not match scoped cross-domain entity.",$"$.payloads[{i}]",RuleId,set.Payloads[i].Domain,set.Payloads[i].Family);} } }
public sealed class AstronomyClassificationConsistencyValidationRule : AstronomyCrossDomainRuleBase { public const string Id="cross-domain.classification.consistency"; public override string RuleId=>Id; public override int Order=>200; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){ foreach(var p in Pairs(set,c,AstronomyCrossDomainRelationshipKind.ClassificationSubject)){ var cls=p.LeftPayload as AstronomyEntityClassificationPayload ?? p.RightPayload as AstronomyEntityClassificationPayload; var other=ReferenceEquals(cls,p.LeftPayload)?p.RightPayload:p.LeftPayload; var e=cls is null?null:EntityOf(other); if(cls is not null&&e is not null&&!SameEntity(new AstronomyEntityReference(cls.TypeId.Value,cls.SubjectKind),e)) yield return Issue(AstronomyCrossDomainValidationCodes.ClassificationSubjectMismatch,AstronomyKnowledgeValidationSeverity.Error,"Classification subject does not match related entity knowledge.",$"$.payloads[{(ReferenceEquals(cls,p.LeftPayload)?p.Left:p.Right)}]",RuleId,cls.Domain,cls.Family); } } }
public sealed class AstronomyEpochConsistencyValidationRule : AstronomyCrossDomainRuleBase { public const string Id="cross-domain.epoch.consistency"; public override string RuleId=>Id; public override int Order=>300; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){ foreach(var p in Pairs(set,c,AstronomyCrossDomainRelationshipKind.Epoch)){ var a=EpochOf(p.LeftPayload); var b=EpochOf(p.RightPayload); if(a is not null&&b is not null&&a.Kind!=AstronomyEpochKind.Unspecified&&b.Kind!=AstronomyEpochKind.Unspecified&&a!=b) yield return Issue(AstronomyCrossDomainValidationCodes.EpochMismatch,AstronomyKnowledgeValidationSeverity.Error,"Linked payload epochs are not identical.",$"$.payloads[{p.Right}]",RuleId,p.RightPayload.Domain,p.RightPayload.Family); } } }
public sealed class AstronomyReferenceContextConsistencyValidationRule : AstronomyCrossDomainRuleBase { public const string Id="cross-domain.reference-context.consistency"; public override string RuleId=>Id; public override int Order=>400; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){ foreach(var p in Pairs(set,c,AstronomyCrossDomainRelationshipKind.ReferenceContext)){ var a=RefOf(p.LeftPayload); var b=RefOf(p.RightPayload); if(a is null||b is null) continue; if(a.Value.Frame.HasValue&&b.Value.Frame.HasValue&&a.Value.Frame!=b.Value.Frame) yield return Issue(AstronomyCrossDomainValidationCodes.ReferenceFrameMismatch,AstronomyKnowledgeValidationSeverity.Error,"Reference frames differ.",$"$.payloads[{p.Right}]",RuleId,p.RightPayload.Domain,p.RightPayload.Family); if(a.Value.Origin.HasValue&&b.Value.Origin.HasValue&&a.Value.Origin!=b.Value.Origin) yield return Issue(AstronomyCrossDomainValidationCodes.ReferenceOriginMismatch,AstronomyKnowledgeValidationSeverity.Error,"Reference origins differ.",$"$.payloads[{p.Right}]",RuleId,p.RightPayload.Domain,p.RightPayload.Family); if(a.Value.System.HasValue&&b.Value.System.HasValue&&a.Value.System!=b.Value.System) yield return Issue(AstronomyCrossDomainValidationCodes.CoordinateSystemMismatch,AstronomyKnowledgeValidationSeverity.Error,"Coordinate systems differ.",$"$.payloads[{p.Right}]",RuleId,p.RightPayload.Domain,p.RightPayload.Family); if(a.Value.Observer is not null&&b.Value.Observer is not null&&!StringComparer.Ordinal.Equals(a.Value.Observer,b.Value.Observer)) yield return Issue(AstronomyCrossDomainValidationCodes.ObserverContextMismatch,AstronomyKnowledgeValidationSeverity.Error,"Observer contexts differ.",$"$.payloads[{p.Right}]",RuleId,p.RightPayload.Domain,p.RightPayload.Family); } } }
public sealed class AstronomyMeasurementConsistencyValidationRule : AstronomyCrossDomainRuleBase { public const string Id="cross-domain.measurement.consistency"; public override string RuleId=>Id; public override int Order=>500; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){ foreach(var p in Pairs(set,c,AstronomyCrossDomainRelationshipKind.Measurement)){ foreach(var a in Measurements(p.LeftPayload)) foreach(var b in Measurements(p.RightPayload).Where(x=>StringComparer.Ordinal.Equals(x.Id,a.Id)&&x.Epoch==a.Epoch)) if(a.Dim!=b.Dim) yield return Issue(AstronomyCrossDomainValidationCodes.MeasurementDimensionConflict,AstronomyKnowledgeValidationSeverity.Error,"Shared measurement identity has conflicting dimensions.",$"$.payloads[{p.Right}]",RuleId,p.RightPayload.Domain,p.RightPayload.Family); } } }
public sealed class AstronomyOrbitalPositionalConsistencyValidationRule : AstronomyCrossDomainRuleBase { public const string Id="cross-domain.orbital-positional.consistency"; public override string RuleId=>Id; public override int Order=>600; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){ foreach(var p in Pairs(set,c,AstronomyCrossDomainRelationshipKind.OrbitalPositional)){ var o=p.LeftPayload as AstronomyOrbitalParametersPayload ?? p.RightPayload as AstronomyOrbitalParametersPayload; var x=p.LeftPayload as AstronomySpatialPositionPayload ?? p.RightPayload as AstronomySpatialPositionPayload; var path=$"$.payloads[{(ReferenceEquals(x,p.LeftPayload)?p.Left:p.Right)}]"; if(o is null||x is null) continue; if(x.Position.ReferenceContext.OriginBody is not null&&!SameEntity(o.ReferenceContext.CentralBody,x.Position.ReferenceContext.OriginBody)) yield return Issue(AstronomyCrossDomainValidationCodes.OrbitalPositionEntityMismatch,AstronomyKnowledgeValidationSeverity.Error,"Orbital central body and positional origin body differ.",path,RuleId,x.Domain,x.Family); if(o.ReferenceContext.Epoch!=x.Position.ReferenceContext.Epoch) yield return Issue(AstronomyCrossDomainValidationCodes.OrbitalPositionEpochMismatch,AstronomyKnowledgeValidationSeverity.Error,"Orbital and positional epochs differ.",path,RuleId,x.Domain,x.Family); if(o.ReferenceContext.ReferenceFrame!=x.Position.ReferenceContext.ReferenceFrame||o.ReferenceContext.ReferenceOrigin!=x.Position.ReferenceContext.ReferenceOrigin) yield return Issue(AstronomyCrossDomainValidationCodes.OrbitalPositionReferenceMismatch,AstronomyKnowledgeValidationSeverity.Error,"Orbital and positional reference contexts differ.",path,RuleId,x.Domain,x.Family); } } }
public sealed class AstronomyObservationVisibilityConsistencyValidationRule : AstronomyCrossDomainRuleBase { public const string Id="cross-domain.observation-visibility.consistency"; public override string RuleId=>Id; public override int Order=>700; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){ foreach(var p in Pairs(set,c,AstronomyCrossDomainRelationshipKind.ObservationVisibilityWindow)){ var o=p.LeftPayload as AstronomyObservationConditionsPayload ?? p.RightPayload as AstronomyObservationConditionsPayload; var v=p.LeftPayload as AstronomyVisibilityWindowsPayload ?? p.RightPayload as AstronomyVisibilityWindowsPayload; var path=$"$.payloads[{(ReferenceEquals(o,p.LeftPayload)?p.Left:p.Right)}].observationContext"; if(o is null||v is null) continue; if(o.ObservationContext.ObserverLocationReference!=v.ObservationContext.ObserverLocationReference||o.ObservationContext.ReferenceFrame!=v.ObservationContext.ReferenceFrame||o.ObservationContext.ReferenceOrigin!=v.ObservationContext.ReferenceOrigin||o.ObservationContext.CoordinateSystem!=v.ObservationContext.CoordinateSystem) yield return Issue(AstronomyCrossDomainValidationCodes.ObservationVisibilityContextMismatch,AstronomyKnowledgeValidationSeverity.Error,"Observation and visibility contexts differ.",path,RuleId,o.Domain,o.Family); if(!v.Windows.Any(w=>w.Window.StartUtc<=o.ObservationContext.ObservationTimeUtc&&o.ObservationContext.ObservationTimeUtc<=w.Window.EndUtc)) yield return Issue(AstronomyCrossDomainValidationCodes.ObservationTimeOutsideVisibilityWindow,AstronomyKnowledgeValidationSeverity.Error,"Observation time is outside supplied visibility windows.",path,RuleId,o.Domain,o.Family); } } }
public sealed class AstronomyEventParticipantConsistencyValidationRule : AstronomyCrossDomainRuleBase { public const string Id="cross-domain.event-participant.consistency"; public override string RuleId=>Id; public override int Order=>800; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){ var sev=c.Mode==AstronomyKnowledgeValidationMode.Standard?AstronomyKnowledgeValidationSeverity.Warning:AstronomyKnowledgeValidationSeverity.Error; foreach(var p in Pairs(set,c,AstronomyCrossDomainRelationshipKind.EventParticipantKnowledgeRequired)){ var ev=p.LeftPayload as AstronomyEventPayload ?? p.RightPayload as AstronomyEventPayload; var other=ReferenceEquals(ev,p.LeftPayload)?p.RightPayload:p.LeftPayload; var otherIndex=ReferenceEquals(ev,p.LeftPayload)?p.Right:p.Left; var known=EntityOf(other); if(ev is null) continue; foreach(var part in ev.Event.Participants){ if(known is null) yield return Issue(AstronomyCrossDomainValidationCodes.EventParticipantMissingKnowledge,sev,"Event participant has no supplied related entity knowledge.",$"$.relationships[{p.RelIndex}]",RuleId,ev.Domain,ev.Family); else if(!SameEntity(part.Entity,known)) yield return Issue(AstronomyCrossDomainValidationCodes.EventParticipantIdentityMismatch,AstronomyKnowledgeValidationSeverity.Error,"Event participant does not match related entity knowledge.",$"$.payloads[{otherIndex}]",RuleId,ev.Domain,ev.Family); } } } }
public sealed class AstronomyEventTemporalConsistencyValidationRule : AstronomyCrossDomainRuleBase { public const string Id="cross-domain.event-temporal.consistency"; public override string RuleId=>Id; public override int Order=>900; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){ foreach(var p in Pairs(set,c,AstronomyCrossDomainRelationshipKind.EventTemporalApplicability).Concat(Pairs(set,c,AstronomyCrossDomainRelationshipKind.EventTemporalOccurrence))){ var ev=p.LeftPayload as AstronomyEventPayload ?? p.RightPayload as AstronomyEventPayload; var temporal=p.LeftPayload as AstronomyTemporalPatternPayload ?? p.RightPayload as AstronomyTemporalPatternPayload; if(ev is null||temporal is null) continue; var (s,e)=Extent(ev.Event.TemporalExtent); var app=temporal.Pattern.Applicability; if(app is not null && ((app.FromUtc.HasValue && s<app.FromUtc.Value) || (app.ThroughUtc.HasValue && e>app.ThroughUtc.Value))) yield return Issue(AstronomyCrossDomainValidationCodes.EventTemporalExtentConflict,AstronomyKnowledgeValidationSeverity.Error,"Event extent is outside linked temporal applicability.",$"$.payloads[{(ReferenceEquals(ev,p.LeftPayload)?p.Left:p.Right)}]",RuleId,ev.Domain,ev.Family); foreach(var occ in temporal.Pattern.SuppliedOccurrences) if(p.RelIndex>=0 && (s<occ.StartUtc || e>(occ.EndUtc ?? occ.StartUtc))) yield return Issue(AstronomyCrossDomainValidationCodes.EventOccurrenceMismatch,AstronomyKnowledgeValidationSeverity.Error,"Event extent does not match linked temporal occurrence.",$"$.payloads[{(ReferenceEquals(ev,p.LeftPayload)?p.Left:p.Right)}]",RuleId,ev.Domain,ev.Family); } } }
public static class AstronomyCrossDomainValidationRegistrationExtensions
{ public static IServiceCollection AddAstronomyCrossDomainValidation(this IServiceCollection services){ArgumentNullException.ThrowIfNull(services); services.AddAstronomyKnowledgeValidation(); Add<AstronomyEntityConsistencyValidationRule>(services,AstronomyEntityConsistencyValidationRule.Id,100); Add<AstronomyClassificationConsistencyValidationRule>(services,AstronomyClassificationConsistencyValidationRule.Id,200); Add<AstronomyEpochConsistencyValidationRule>(services,AstronomyEpochConsistencyValidationRule.Id,300); Add<AstronomyReferenceContextConsistencyValidationRule>(services,AstronomyReferenceContextConsistencyValidationRule.Id,400); Add<AstronomyMeasurementConsistencyValidationRule>(services,AstronomyMeasurementConsistencyValidationRule.Id,500); Add<AstronomyOrbitalPositionalConsistencyValidationRule>(services,AstronomyOrbitalPositionalConsistencyValidationRule.Id,600); Add<AstronomyObservationVisibilityConsistencyValidationRule>(services,AstronomyObservationVisibilityConsistencyValidationRule.Id,700); Add<AstronomyEventParticipantConsistencyValidationRule>(services,AstronomyEventParticipantConsistencyValidationRule.Id,800); Add<AstronomyEventTemporalConsistencyValidationRule>(services,AstronomyEventTemporalConsistencyValidationRule.Id,900); services.TryAddSingleton<IAstronomyCrossDomainValidationRuleRegistry>(p=>new AstronomyCrossDomainValidationRuleRegistry(p.GetServices<AstronomyCrossDomainValidationRuleDescriptor>())); services.TryAddSingleton<IAstronomyCrossDomainValidator,AstronomyCrossDomainValidator>(); return services;} private static void Add<T>(IServiceCollection s,string id,int order) where T:class,IAstronomyCrossDomainValidationRule{ s.TryAddEnumerable(ServiceDescriptor.Singleton<IAstronomyCrossDomainValidationRule,T>()); var d=new AstronomyCrossDomainValidationRuleDescriptor(id,typeof(T),order); if(!s.Any(x=>x.ServiceType==typeof(AstronomyCrossDomainValidationRuleDescriptor)&&Equals(x.ImplementationInstance,d))) s.AddSingleton(d); }}
