using Astronomy.MediaFactory.Core.KnowledgeFoundation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Extensions;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Coordinates;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Events;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Measurements;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Observational;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Orbital;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Positional;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.CrossDomain;

public static class AstronomyCrossDomainValidationCodes
{
    public const string EntityReferenceMismatch = "cross-domain.entity.reference-mismatch";
    public const string EntityReferenceMissing = "cross-domain.entity.reference-missing";
    public const string EpochMismatch = "cross-domain.epoch.mismatch";
    public const string EpochIncompatible = "cross-domain.epoch.incompatible";
    public const string ReferenceFrameMismatch = "cross-domain.reference-context.frame-mismatch";
    public const string ReferenceOriginMismatch = "cross-domain.reference-context.origin-mismatch";
    public const string CoordinateSystemMismatch = "cross-domain.reference-context.coordinate-system-mismatch";
    public const string ObserverContextMismatch = "cross-domain.reference-context.observer-context-mismatch";
    public const string MeasurementDimensionConflict = "cross-domain.measurement.dimension-conflict";
    public const string ClassificationSubjectMismatch = "cross-domain.classification.subject-mismatch";
    public const string EventParticipantMissingKnowledge = "cross-domain.event-participant.missing-knowledge";
    public const string EventParticipantIdentityMismatch = "cross-domain.event-participant.identity-mismatch";
    public const string EventTemporalExtentConflict = "cross-domain.event-temporal.extent-conflict";
    public const string EventOccurrenceMismatch = "cross-domain.event-temporal.occurrence-mismatch";
    public const string ObservationVisibilityContextMismatch = "cross-domain.observation-visibility.context-mismatch";
    public const string ObservationTimeOutsideVisibilityWindow = "cross-domain.observation-visibility.observation-time-outside-window";
    public const string OrbitalPositionEntityMismatch = "cross-domain.orbital-positional.entity-mismatch";
    public const string OrbitalPositionEpochMismatch = "cross-domain.orbital-positional.epoch-mismatch";
    public const string OrbitalPositionReferenceMismatch = "cross-domain.orbital-positional.reference-mismatch";
}

public sealed record AstronomyCrossDomainValidationSet
{
    public AstronomyCrossDomainValidationSet(IReadOnlyList<ITypedAstronomyKnowledgePayload> payloads)
    {
        ArgumentNullException.ThrowIfNull(payloads);
        Payloads = Array.AsReadOnly(payloads.Select(p => p ?? throw new ArgumentException("Payload collection cannot contain null entries.", nameof(payloads))).ToArray());
    }
    public IReadOnlyList<ITypedAstronomyKnowledgePayload> Payloads { get; }
}

public sealed record AstronomyCrossDomainValidationContext
{
    public AstronomyCrossDomainValidationContext(AstronomyKnowledgeValidationRunId validationRunId, DateTimeOffset referenceInstantUtc, AstronomyKnowledgeValidationMode mode = AstronomyKnowledgeValidationMode.Standard, AstronomyKnowledgeValidationSeverity minimumSeverity = AstronomyKnowledgeValidationSeverity.Information, AstronomyEntityReference? entityScope = null)
    { if (!validationRunId.IsValid) throw new ArgumentException("Validation run ID is required.", nameof(validationRunId)); if(referenceInstantUtc.Offset!=TimeSpan.Zero) throw new ArgumentException("Reference instant must be UTC.", nameof(referenceInstantUtc)); ValidationRunId=validationRunId; ReferenceInstantUtc=referenceInstantUtc; Mode=mode; MinimumSeverity=minimumSeverity; EntityScope=entityScope; }
    public AstronomyKnowledgeValidationRunId ValidationRunId { get; }
    public DateTimeOffset ReferenceInstantUtc { get; }
    public AstronomyKnowledgeValidationMode Mode { get; }
    public AstronomyKnowledgeValidationSeverity MinimumSeverity { get; }
    public AstronomyEntityReference? EntityScope { get; }
}

public interface IAstronomyCrossDomainValidationRule { string RuleId { get; } int Order { get; } IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set, AstronomyCrossDomainValidationContext context); }
public sealed record AstronomyCrossDomainValidationRuleDescriptor(string RuleId, Type RuleType, int Order);
public interface IAstronomyCrossDomainValidationRuleRegistry { IReadOnlyList<AstronomyCrossDomainValidationRuleDescriptor> Descriptors { get; } }
public sealed class AstronomyCrossDomainValidationRuleRegistry : IAstronomyCrossDomainValidationRuleRegistry
{ public AstronomyCrossDomainValidationRuleRegistry(IEnumerable<AstronomyCrossDomainValidationRuleDescriptor> descriptors){Descriptors=Array.AsReadOnly((descriptors??throw new ArgumentNullException(nameof(descriptors))).Distinct().OrderBy(d=>d.Order).ThenBy(d=>d.RuleId,StringComparer.Ordinal).ToArray()); if(Descriptors.GroupBy(d=>d.RuleId,StringComparer.Ordinal).Any(g=>g.Count()>1)) throw new ArgumentException("Duplicate cross-domain rule ID.",nameof(descriptors));} public IReadOnlyList<AstronomyCrossDomainValidationRuleDescriptor> Descriptors{get;} }
public interface IAstronomyCrossDomainValidator { AstronomyKnowledgeValidationResult Validate(AstronomyCrossDomainValidationSet set, AstronomyCrossDomainValidationContext context); }
public sealed class AstronomyCrossDomainValidator : IAstronomyCrossDomainValidator
{ private readonly IReadOnlyList<IAstronomyCrossDomainValidationRule> rules; public AstronomyCrossDomainValidator(IEnumerable<IAstronomyCrossDomainValidationRule> rules){this.rules=(rules??throw new ArgumentNullException(nameof(rules))).GroupBy(r=>r.RuleId,StringComparer.Ordinal).Select(g=>g.First()).OrderBy(r=>r.Order).ThenBy(r=>r.RuleId,StringComparer.Ordinal).ToArray();} public AstronomyKnowledgeValidationResult Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext context){ArgumentNullException.ThrowIfNull(set); ArgumentNullException.ThrowIfNull(context); var issues=rules.SelectMany(r=>r.Validate(set,context)).Where(i=>i.Severity>=context.MinimumSeverity); return new AstronomyKnowledgeValidationResult(issues);} }

public abstract class AstronomyCrossDomainRuleBase : IAstronomyCrossDomainValidationRule
{ public abstract string RuleId{get;} public abstract int Order{get;} public abstract IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext context); protected static AstronomyKnowledgeValidationIssue Issue(string code,AstronomyKnowledgeValidationSeverity s,string msg,string path,string rule,AstronomyKnowledgeDomain d,AstronomyKnowledgePayloadFamily f)=>new(code,s,msg,path,rule,d,f); protected static IEnumerable<(int Index,AstronomyEntityReference Entity)> Entities(AstronomyCrossDomainValidationSet set){for(var i=0;i<set.Payloads.Count;i++){switch(set.Payloads[i]){case AstronomyOrbitalParametersPayload o: yield return (i,o.ReferenceContext.CentralBody); break; case AstronomySpatialPositionPayload p when p.Position.ReferenceContext.OriginBody is not null: yield return (i,p.Position.ReferenceContext.OriginBody); break; case AstronomyEventPayload e: foreach(var x in e.Event.Participants) yield return (i,x.Entity); break;}}} protected static IEnumerable<(int Index,AstronomyEpochReference Epoch,AstronomyKnowledgeDomain Domain,AstronomyKnowledgePayloadFamily Family)> Epochs(AstronomyCrossDomainValidationSet set){for(var i=0;i<set.Payloads.Count;i++){switch(set.Payloads[i]){case AstronomyOrbitalParametersPayload o: yield return (i,o.ReferenceContext.Epoch,o.Domain,o.Family); foreach(var p in o.Parameters) if(p.Epoch is not null) yield return (i,p.Epoch,o.Domain,o.Family); break; case AstronomySpatialPositionPayload p: yield return (i,p.Position.ReferenceContext.Epoch,p.Domain,p.Family); break;}}} protected static bool SameEntity(AstronomyEntityReference a,AstronomyEntityReference b)=>StringComparer.Ordinal.Equals(a.EntityId,b.EntityId)&&a.EntityKind==b.EntityKind; }
public sealed class AstronomyEntityConsistencyValidationRule: AstronomyCrossDomainRuleBase{ public const string Id="cross-domain.entity.consistency"; public override string RuleId=>Id; public override int Order=>100; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){ if(c.EntityScope is null) yield break; foreach(var e in Entities(set).Where(e=>!SameEntity(e.Entity,c.EntityScope))) yield return Issue(AstronomyCrossDomainValidationCodes.EntityReferenceMismatch,AstronomyKnowledgeValidationSeverity.Error,"Entity reference does not match scoped cross-domain entity.",$"$.payloads[{e.Index}]",RuleId,AstronomyKnowledgeDomain.Classification,AstronomyKnowledgePayloadFamily.EntityClassification); }}
public sealed class AstronomyClassificationConsistencyValidationRule: AstronomyCrossDomainRuleBase{ public const string Id="cross-domain.classification.consistency"; public override string RuleId=>Id; public override int Order=>200; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){return Array.Empty<AstronomyKnowledgeValidationIssue>();}}
public sealed class AstronomyEpochConsistencyValidationRule: AstronomyCrossDomainRuleBase{ public const string Id="cross-domain.epoch.consistency"; public override string RuleId=>Id; public override int Order=>300; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){var e=Epochs(set).Where(x=>x.Epoch.Kind!=AstronomyEpochKind.Unspecified).ToArray(); if(e.Length<2) yield break; var first=e[0]; foreach(var x in e.Skip(1).Where(x=>x.Epoch!=first.Epoch)) yield return Issue(AstronomyCrossDomainValidationCodes.EpochMismatch,AstronomyKnowledgeValidationSeverity.Error,"Linked payload epochs are not identical.",$"$.payloads[{x.Index}]",RuleId,x.Domain,x.Family);}}
public sealed class AstronomyReferenceContextConsistencyValidationRule: AstronomyCrossDomainRuleBase{ public const string Id="cross-domain.reference-context.consistency"; public override string RuleId=>Id; public override int Order=>400; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){var refs=set.Payloads.Select((p,i)=>(p,i)).Select(x=> x.p switch{AstronomyOrbitalParametersPayload o=>(x.i,o.ReferenceContext.ReferenceFrame,o.ReferenceContext.ReferenceOrigin,(AstronomyCoordinateSystem?)null,x.p.Domain,x.p.Family), AstronomySpatialPositionPayload p=>(x.i,p.Position.ReferenceContext.ReferenceFrame,p.Position.ReferenceContext.ReferenceOrigin,(AstronomyCoordinateSystem?)p.Position.ReferenceContext.CoordinateSystem,x.p.Domain,x.p.Family), AstronomyObservationConditionsPayload o=>(x.i,o.ObservationContext.ReferenceFrame,o.ObservationContext.ReferenceOrigin,o.ObservationContext.CoordinateSystem,x.p.Domain,x.p.Family), AstronomyVisibilityWindowsPayload v=>(x.i,v.ObservationContext.ReferenceFrame,v.ObservationContext.ReferenceOrigin,v.ObservationContext.CoordinateSystem,x.p.Domain,x.p.Family), _=>(-1,AstronomyReferenceFrame.Unspecified,AstronomyReferenceOrigin.Unspecified,(AstronomyCoordinateSystem?)null,x.p.Domain,x.p.Family)}).Where(r=>r.i>=0).ToArray(); if(refs.Length<2) yield break; var first=refs[0]; foreach(var r in refs.Skip(1)){ if(r.Item2!=first.Item2) yield return Issue(AstronomyCrossDomainValidationCodes.ReferenceFrameMismatch,AstronomyKnowledgeValidationSeverity.Error,"Reference frames differ.",$"$.payloads[{r.i}]",RuleId,r.Domain,r.Family); if(r.Item3!=first.Item3) yield return Issue(AstronomyCrossDomainValidationCodes.ReferenceOriginMismatch,AstronomyKnowledgeValidationSeverity.Error,"Reference origins differ.",$"$.payloads[{r.i}]",RuleId,r.Domain,r.Family); if(r.Item4.HasValue&&first.Item4.HasValue&&r.Item4!=first.Item4) yield return Issue(AstronomyCrossDomainValidationCodes.CoordinateSystemMismatch,AstronomyKnowledgeValidationSeverity.Error,"Coordinate systems differ.",$"$.payloads[{r.i}]",RuleId,r.Domain,r.Family); }}}
public sealed class AstronomyMeasurementConsistencyValidationRule: AstronomyCrossDomainRuleBase{ public const string Id="cross-domain.measurement.consistency"; public override string RuleId=>Id; public override int Order=>500; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){var m=new List<(int Index,string MeasurementId,AstronomyMeasurementDimension Dimension,AstronomyKnowledgeDomain Domain,AstronomyKnowledgePayloadFamily Family)>(); for(var i=0;i<set.Payloads.Count;i++){if(set.Payloads[i] is AstronomyOrbitalParametersPayload o)m.AddRange(o.Parameters.Select(p=>(i,p.ParameterId.Value,p.Measurement.Unit.Dimension,o.Domain,o.Family))); if(set.Payloads[i] is AstronomyEventPayload e)m.AddRange(e.Event.Geometry.Select(g=>(i,g.QuantityId.Value,g.Measurement.Unit.Dimension,e.Domain,e.Family)));} foreach(var g in m.GroupBy(x=>x.MeasurementId,StringComparer.Ordinal)) if(g.Select(x=>x.Dimension).Distinct().Count()>1) foreach(var x in g.Skip(1)) yield return Issue(AstronomyCrossDomainValidationCodes.MeasurementDimensionConflict,AstronomyKnowledgeValidationSeverity.Error,"Shared measurement identity has conflicting dimensions.",$"$.payloads[{x.Index}]",RuleId,x.Domain,x.Family);}}
public sealed class AstronomyOrbitalPositionalConsistencyValidationRule: AstronomyCrossDomainRuleBase{ public const string Id="cross-domain.orbital-positional.consistency"; public override string RuleId=>Id; public override int Order=>600; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){var o=set.Payloads.OfType<AstronomyOrbitalParametersPayload>().FirstOrDefault(); var p=set.Payloads.OfType<AstronomySpatialPositionPayload>().FirstOrDefault(); if(o is null||p is null) yield break; if(p.Position.ReferenceContext.OriginBody is not null&&!SameEntity(o.ReferenceContext.CentralBody,p.Position.ReferenceContext.OriginBody)) yield return Issue(AstronomyCrossDomainValidationCodes.OrbitalPositionEntityMismatch,AstronomyKnowledgeValidationSeverity.Error,"Orbital central body and positional origin body differ.","$.payloads[0]",RuleId,AstronomyKnowledgeDomain.Orbital,AstronomyKnowledgePayloadFamily.OrbitalParameter); if(o.ReferenceContext.Epoch!=p.Position.ReferenceContext.Epoch) yield return Issue(AstronomyCrossDomainValidationCodes.OrbitalPositionEpochMismatch,AstronomyKnowledgeValidationSeverity.Error,"Orbital and positional epochs differ.","$.payloads[0]",RuleId,AstronomyKnowledgeDomain.Orbital,AstronomyKnowledgePayloadFamily.OrbitalParameter); if(o.ReferenceContext.ReferenceFrame!=p.Position.ReferenceContext.ReferenceFrame||o.ReferenceContext.ReferenceOrigin!=p.Position.ReferenceContext.ReferenceOrigin) yield return Issue(AstronomyCrossDomainValidationCodes.OrbitalPositionReferenceMismatch,AstronomyKnowledgeValidationSeverity.Error,"Orbital and positional reference contexts differ.","$.payloads[0]",RuleId,AstronomyKnowledgeDomain.Orbital,AstronomyKnowledgePayloadFamily.OrbitalParameter);}}
public sealed class AstronomyObservationVisibilityConsistencyValidationRule: AstronomyCrossDomainRuleBase{ public const string Id="cross-domain.observation-visibility.consistency"; public override string RuleId=>Id; public override int Order=>700; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){var o=set.Payloads.OfType<AstronomyObservationConditionsPayload>().FirstOrDefault(); var v=set.Payloads.OfType<AstronomyVisibilityWindowsPayload>().FirstOrDefault(); if(o is null||v is null) yield break; if(o.ObservationContext.ObserverLocationReference!=v.ObservationContext.ObserverLocationReference) yield return Issue(AstronomyCrossDomainValidationCodes.ObservationVisibilityContextMismatch,AstronomyKnowledgeValidationSeverity.Error,"Observation and visibility observer contexts differ.","$.payloads[0]",RuleId,AstronomyKnowledgeDomain.Observational,AstronomyKnowledgePayloadFamily.ObservationCondition); if(!v.Windows.Any(w=>w.Window.StartUtc<=o.ObservationContext.ObservationTimeUtc&&o.ObservationContext.ObservationTimeUtc<=w.Window.EndUtc)) yield return Issue(AstronomyCrossDomainValidationCodes.ObservationTimeOutsideVisibilityWindow,AstronomyKnowledgeValidationSeverity.Error,"Observation time is outside supplied visibility windows.","$.payloads[0]",RuleId,AstronomyKnowledgeDomain.Observational,AstronomyKnowledgePayloadFamily.ObservationCondition);}}
public sealed class AstronomyEventParticipantConsistencyValidationRule: AstronomyCrossDomainRuleBase{ public const string Id="cross-domain.event-participant.consistency"; public override string RuleId=>Id; public override int Order=>800; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){var known=Entities(set).Select(e=>e.Entity.EntityId).ToHashSet(StringComparer.Ordinal); foreach(var e in set.Payloads.OfType<AstronomyEventPayload>().SelectMany(x=>x.Event.Participants).Where(p=>!known.Contains(p.Entity.EntityId))) yield return Issue(AstronomyCrossDomainValidationCodes.EventParticipantMissingKnowledge,c.Mode==AstronomyKnowledgeValidationMode.Standard?AstronomyKnowledgeValidationSeverity.Warning:AstronomyKnowledgeValidationSeverity.Error,"Event participant has no supplied related entity knowledge.","$.payloads[0]",RuleId,AstronomyKnowledgeDomain.Event,AstronomyKnowledgePayloadFamily.AstronomicalEvent);}}
public sealed class AstronomyEventTemporalConsistencyValidationRule: AstronomyCrossDomainRuleBase{ public const string Id="cross-domain.event-temporal.consistency"; public override string RuleId=>Id; public override int Order=>900; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyCrossDomainValidationSet set,AstronomyCrossDomainValidationContext c){return Array.Empty<AstronomyKnowledgeValidationIssue>();}}
public static class AstronomyCrossDomainValidationRegistrationExtensions
{ public static IServiceCollection AddAstronomyCrossDomainValidation(this IServiceCollection services){ArgumentNullException.ThrowIfNull(services); services.AddAstronomyKnowledgeValidation(); Add<AstronomyEntityConsistencyValidationRule>(services,AstronomyEntityConsistencyValidationRule.Id,100); Add<AstronomyClassificationConsistencyValidationRule>(services,AstronomyClassificationConsistencyValidationRule.Id,200); Add<AstronomyEpochConsistencyValidationRule>(services,AstronomyEpochConsistencyValidationRule.Id,300); Add<AstronomyReferenceContextConsistencyValidationRule>(services,AstronomyReferenceContextConsistencyValidationRule.Id,400); Add<AstronomyMeasurementConsistencyValidationRule>(services,AstronomyMeasurementConsistencyValidationRule.Id,500); Add<AstronomyOrbitalPositionalConsistencyValidationRule>(services,AstronomyOrbitalPositionalConsistencyValidationRule.Id,600); Add<AstronomyObservationVisibilityConsistencyValidationRule>(services,AstronomyObservationVisibilityConsistencyValidationRule.Id,700); Add<AstronomyEventParticipantConsistencyValidationRule>(services,AstronomyEventParticipantConsistencyValidationRule.Id,800); Add<AstronomyEventTemporalConsistencyValidationRule>(services,AstronomyEventTemporalConsistencyValidationRule.Id,900); services.TryAddSingleton<IAstronomyCrossDomainValidationRuleRegistry>(p=>new AstronomyCrossDomainValidationRuleRegistry(p.GetServices<AstronomyCrossDomainValidationRuleDescriptor>())); services.TryAddSingleton<IAstronomyCrossDomainValidator,AstronomyCrossDomainValidator>(); return services;} private static void Add<T>(IServiceCollection s,string id,int order) where T:class,IAstronomyCrossDomainValidationRule{ s.TryAddEnumerable(ServiceDescriptor.Singleton<IAstronomyCrossDomainValidationRule,T>()); var d=new AstronomyCrossDomainValidationRuleDescriptor(id,typeof(T),order); if(!s.Any(x=>x.ServiceType==typeof(AstronomyCrossDomainValidationRuleDescriptor)&&Equals(x.ImplementationInstance,d))) s.AddSingleton(d); }}
