using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation;
using Microsoft.Extensions.DependencyInjection;
namespace Astronomy.MediaFactory.Tests.KnowledgeFoundation.Validation.OrbitalAndPositional;
public sealed class AstronomyOrbitalAndPositionalValidationArchitectureTests
{
    [Fact] public void Expected_validation_directories_and_files_exist() { foreach (var file in ExpectedFiles()) { var info = new FileInfo(Path.Combine(FindRepoRoot(), file)); Assert.True(info.Exists, file); Assert.True(info.Length > 0, file); } }
    [Fact] public void Validation_sources_do_not_use_forbidden_execution_or_calculation_tokens() { var root = Path.Combine(FindRepoRoot(), "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation"); var forbidden = new[] { "DbContext", "IQueryable", "Repository", "Controller", "HttpClient", "BackgroundService", "IHostedService", "Quartz", "Hangfire", "Kafka", "RabbitMQ", "ServiceBus", "Mongo", "Cosmos", "DateTimeOffset.UtcNow", "DateTime.UtcNow", "Activator.CreateInstance", "Type.GetType", "AssemblyQualifiedName", "FormatterServices", "BinaryFormatter", "Stellarium", "Skyfield", "SPICE", "NAIF", "Astropy", "SOFA", "ERFA", "JPL", "Horizons", "PropagateOrbit", "CalculatePosition", "ComputePosition", "TransformCoordinate", "ConvertCoordinate", "ConvertFrame", "ConvertUnit", "Ephemeris", "Forecast", "Predict" }; var files = Directory.EnumerateFiles(Path.Combine(root, "Orbital"), "*.cs").Concat(Directory.EnumerateFiles(Path.Combine(root, "Positional"), "*.cs")); foreach (var file in files) { var text = File.ReadAllText(file); foreach (var token in forbidden) Assert.DoesNotContain(token, text, StringComparison.Ordinal); } }
    [Fact] public void Typed_domains_do_not_reference_validation_namespaces() { var root = Path.Combine(FindRepoRoot(), "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/TypedDomains"); foreach (var dir in new[] { "Orbital", "Positional", "Coordinates" }) foreach (var file in Directory.EnumerateFiles(Path.Combine(root, dir), "*.cs")) Assert.DoesNotContain("KnowledgeFoundation.Validation", File.ReadAllText(file), StringComparison.Ordinal); }

    [Fact] public void Expected_public_rule_ids_are_registered_exactly_once() { var services = new Microsoft.Extensions.DependencyInjection.ServiceCollection().AddAstronomyOrbitalAndPositionalValidation().AddAstronomyOrbitalAndPositionalValidation(); using var provider = services.BuildServiceProvider(); var descriptors = provider.GetRequiredService<Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.IAstronomyKnowledgeValidationRuleRegistry>().Descriptors.ToArray(); foreach (var id in new[] { Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Orbital.AstronomyOrbitalReferenceContextValidationRule.Id, Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Orbital.AstronomyKeplerianElementsValidationRule.Id, Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Orbital.AstronomyOrbitalParametersReferenceContextValidationRule.Id, Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Orbital.AstronomyOrbitalParametersValidationRule.Id, Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Positional.AstronomySpatialReferenceContextValidationRule.Id, Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Positional.AstronomyPositionValueValidationRule.Id, Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Positional.AstronomyAngularPositionValidationRule.Id, Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Positional.AstronomySphericalPositionValidationRule.Id, Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Positional.AstronomyCartesianPositionValidationRule.Id }) Assert.Equal(1, descriptors.Count(d => d.RuleId == id)); }
    private static IEnumerable<string> ExpectedFiles() => new[] { "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation/Orbital/AstronomyOrbitalValidationCodes.cs", "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation/Orbital/AstronomyOrbitalReferenceContextValidationRule.cs", "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation/Orbital/AstronomyKeplerianElementsValidationRule.cs", "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation/Orbital/AstronomyOrbitalParametersValidationRule.cs", "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation/Orbital/AstronomyOrbitalMeasurementValidator.cs", "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation/Orbital/AstronomyOrbitalValidationRegistrationExtensions.cs", "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation/Positional/AstronomyPositionalValidationCodes.cs", "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation/Positional/AstronomySpatialReferenceContextValidationRule.cs", "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation/Positional/AstronomyPositionValueValidationRule.cs", "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation/Positional/AstronomyAngularPositionValidationRule.cs", "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation/Positional/AstronomySphericalPositionValidationRule.cs", "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation/Positional/AstronomyCartesianPositionValidationRule.cs", "Backend/src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Validation/Positional/AstronomyPositionalValidationRegistrationExtensions.cs" };
    private static string FindRepoRoot() { var dir = new DirectoryInfo(Environment.CurrentDirectory); while (dir is not null && !Directory.Exists(Path.Combine(dir.FullName, "Backend"))) dir = dir.Parent; return dir?.FullName ?? Environment.CurrentDirectory; }
}
