using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.DependencyInjection;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Observational;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Visibility;
using Microsoft.Extensions.DependencyInjection;

namespace Astronomy.MediaFactory.Tests.KnowledgeFoundation.Validation.ObservationalAndVisibility;

public sealed class AstronomyObservationalAndVisibilityValidationArchitectureTests
{
    [Fact] public void Production_validation_directories_exist(){var v=Path.Combine(Root(),"Backend","src","Astronomy.MediaFactory.Core","KnowledgeFoundation","Validation");Assert.True(Directory.Exists(Path.Combine(v,"Observational")));Assert.True(Directory.Exists(Path.Combine(v,"Visibility")));}
    [Fact] public void Expected_production_files_exist_and_are_non_empty(){var v=Path.Combine(Root(),"Backend","src","Astronomy.MediaFactory.Core","KnowledgeFoundation","Validation");var files=new[]{"AstronomyObservationalAndVisibilityValidationRegistrationExtensions.cs",Path.Combine("Observational","AstronomyHorizontalCoordinatesValidationRule.cs"),Path.Combine("Observational","AstronomyObservationConditionsValidationRule.cs"),Path.Combine("Observational","AstronomyObservationContextValidationRule.cs"),Path.Combine("Observational","AstronomyObservationalMeasurementValidator.cs"),Path.Combine("Observational","AstronomyObservationalQuantityDimensionCatalog.cs"),Path.Combine("Observational","AstronomyObservationalQuantityValidationRule.cs"),Path.Combine("Observational","AstronomyObservationalValidationCodes.cs"),Path.Combine("Observational","AstronomyObservationalValidationRegistrationExtensions.cs"),Path.Combine("Visibility","AstronomyVisibilityAssessmentValidationRule.cs"),Path.Combine("Visibility","AstronomyVisibilityContextValidationRule.cs"),Path.Combine("Visibility","AstronomyVisibilityPeakValidationRule.cs"),Path.Combine("Visibility","AstronomyVisibilityValidationCodes.cs"),Path.Combine("Visibility","AstronomyVisibilityValidationRegistrationExtensions.cs"),Path.Combine("Visibility","AstronomyVisibilityWindowValidationRule.cs")};foreach(var r in files){var f=Path.Combine(v,r);Assert.True(File.Exists(f),f);Assert.True(new FileInfo(f).Length>0,f);}}
    [Fact] public void Expected_rule_ids_are_registered_once(){var s=new ServiceCollection();s.AddAstronomyTypedKnowledgePayloadDescriptors();s.AddAstronomyObservationalAndVisibilityValidation();using var p=s.BuildServiceProvider();var ids=new[]{AstronomyObservationContextValidationRule.Id,AstronomyObservationConditionsValidationRule.Id,AstronomyObservationalQuantityValidationRule.Id,AstronomyHorizontalCoordinatesValidationRule.Id,AstronomyVisibilityContextValidationRule.Id,AstronomyVisibilityWindowValidationRule.Id,AstronomyVisibilityAssessmentValidationRule.Id,AstronomyVisibilityPeakValidationRule.Id};foreach(var id in ids)Assert.Single(p.GetRequiredService<IAstronomyKnowledgeValidationRuleRegistry>().Descriptors,d=>d.RuleId==id);}
    [Fact] public void Production_validation_avoids_forbidden_dependencies(){var v=Path.Combine(Root(),"Backend","src","Astronomy.MediaFactory.Core","KnowledgeFoundation","Validation");var forbidden=new[]{"DbContext","IQueryable","Repository","Controller","HttpClient","BackgroundService","IHostedService","Quartz","Hangfire","Kafka","RabbitMQ","ServiceBus","Mongo","Cosmos","DateTimeOffset.UtcNow","DateTime.UtcNow","Activator.CreateInstance","Type.GetType","AssemblyQualifiedName","FormatterServices","BinaryFormatter","Stellarium","Skyfield","SPICE","NAIF","Astropy","SOFA","ERFA","JPL","Horizons","CalculateVisibility","ComputeVisibility","PredictVisibility","ForecastWeather","CalculateRise","CalculateSet","ComputeAltitude","TransformCoordinate","ConvertCoordinate","ConvertFrame","ConvertUnit","Ephemeris"};foreach(var f in Directory.EnumerateFiles(v,"*.cs",SearchOption.AllDirectories)){var text=File.ReadAllText(f);foreach(var term in forbidden)Assert.DoesNotContain(term,text,StringComparison.Ordinal);}}
    [Fact] public void Frozen_typed_folders_do_not_reference_validation(){var t=Path.Combine(Root(),"Backend","src","Astronomy.MediaFactory.Core","KnowledgeFoundation","TypedDomains");foreach(var dir in new[]{"Observational","Observation","Coordinates"})foreach(var f in Directory.EnumerateFiles(Path.Combine(t,dir),"*.cs",SearchOption.AllDirectories))Assert.DoesNotContain("KnowledgeFoundation.Validation",File.ReadAllText(f),StringComparison.Ordinal);}
    private static string Root(){var d=new DirectoryInfo(AppContext.BaseDirectory);while(d!=null){if(Directory.Exists(Path.Combine(d.FullName,"Backend","src","Astronomy.MediaFactory.Core")))return d.FullName;d=d.Parent;}throw new InvalidOperationException("Repository root not found.");}
}
