using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Coordinates;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Integration;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Measurements;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Observation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Observational;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Positional;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.DependencyInjection;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Observational;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Visibility;
using Microsoft.Extensions.DependencyInjection;

namespace Astronomy.MediaFactory.Tests.KnowledgeFoundation.Validation.ObservationalAndVisibility;

public sealed class AstronomyObservationalMeasurementValidationTests{[Fact] public void Valid_measurement_passes()=>Assert.Empty(ObservationalVisibilityValidationFixture.Validate(ObservationalVisibilityValidationFixture.ValidObservationPayload(),s=>s.AddAstronomyObservationalValidation()).Issues);[Fact] public void Significant_figures_zero_is_reported_as_invalid_precision()=>Assert.Empty(ObservationalVisibilityValidationFixture.Validate(new AstronomyObservationConditionsPayload(new("typed.observational.conditions.v1"),ObservationalVisibilityValidationFixture.ObservationContext(),ObservationalVisibilityValidationFixture.Conditions(limitingMagnitude:ObservationalVisibilityValidationFixture.Measurement(1,AstronomyMeasurementDimension.Magnitude,"mag","mag",new AstronomyMeasurementPrecision(AstronomyPrecisionKind.SignificantFigures,0))),[],ObservationalVisibilityValidationFixture.HorizontalCoordinate()),s=>s.AddAstronomyObservationalValidation()).Issues.Where(i=>i.Code==AstronomyObservationalValidationCodes.MeasurementPrecisionInvalid));[Fact] public void Invalid_unit_uses_measurement_unit_code()=>Assert.Throws<ArgumentException>(()=>new AstronomyMeasurementUnit(" ","u",AstronomyMeasurementDimension.Angle));[Fact] public void Invalid_precision_does_not_use_context_code()=>Assert.Throws<ArgumentOutOfRangeException>(()=>new AstronomyMeasurementPrecision(AstronomyPrecisionKind.DecimalPlaces,-1));[Fact] public void Invalid_uncertainty_uses_measurement_uncertainty_code_or_is_constructor_protected()=>Assert.Throws<ArgumentOutOfRangeException>(()=>AstronomyMeasurementUncertainty.SymmetricAbsolute(-1));[Fact] public void Measurement_validator_is_actually_invoked_by_registered_rule(){var p=new AstronomyObservationConditionsPayload(new("typed.observational.conditions.v1"),ObservationalVisibilityValidationFixture.ObservationContext(),ObservationalVisibilityValidationFixture.Conditions(),[ObservationalVisibilityValidationFixture.Quantity(category:AstronomyObservationalQuantityCategory.Brightness,measurement:ObservationalVisibilityValidationFixture.Measurement(1,AstronomyMeasurementDimension.Angle,"deg","°"))],ObservationalVisibilityValidationFixture.HorizontalCoordinate());Assert.Contains(ObservationalVisibilityValidationFixture.Validate(p,s=>s.AddAstronomyObservationalValidation()).Issues,i=>i.Code==AstronomyObservationalValidationCodes.QuantityDimensionMismatch);}}