using System.Reflection;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Coordinates;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Integration;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Measurements;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Observation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Observational;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Positional;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.DependencyInjection;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Observational;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Visibility;
using Microsoft.Extensions.DependencyInjection;

namespace Astronomy.MediaFactory.Tests.KnowledgeFoundation.Validation.ObservationalAndVisibility;


public sealed class AstronomyObservationalQuantityValidationRuleTests { static AstronomyKnowledgeValidationResult Validate(params AstronomyObservationalQuantity[] q)=>ObservationalVisibilityValidationFixture.Validate(new AstronomyObservationConditionsPayload(new("typed.observational.conditions.v1"),ObservationalVisibilityValidationFixture.ObservationContext(),ObservationalVisibilityValidationFixture.Conditions(),q,ObservationalVisibilityValidationFixture.HorizontalCoordinate()), s=>s.AddAstronomyObservationalValidation());
[Fact] public void Valid_quantity_passes()=>Assert.Empty(Validate(ObservationalVisibilityValidationFixture.Quantity()).Issues);
[Fact] public void Same_quantity_at_different_epochs_is_allowed()=>Assert.DoesNotContain(Validate(ObservationalVisibilityValidationFixture.Quantity(epoch:AstronomyEpochReference.Custom(ObservationalVisibilityValidationFixture.T0)),ObservationalVisibilityValidationFixture.Quantity(epoch:AstronomyEpochReference.Custom(ObservationalVisibilityValidationFixture.T1))).Issues,i=>i.Code==AstronomyObservationalValidationCodes.QuantityDuplicate);
[Fact] public void Duplicate_quantity_identity_is_detected_or_constructor_protected()=>Assert.Throws<ArgumentException>(()=>new AstronomyObservationConditionsPayload(new("typed.observational.conditions.v1"),ObservationalVisibilityValidationFixture.ObservationContext(),ObservationalVisibilityValidationFixture.Conditions(),[ObservationalVisibilityValidationFixture.Quantity(),ObservationalVisibilityValidationFixture.Quantity()]));
[Fact] public void Category_dimension_mismatch_is_detected(){var i=Assert.Single(Validate(ObservationalVisibilityValidationFixture.Quantity(category:AstronomyObservationalQuantityCategory.Brightness, measurement:ObservationalVisibilityValidationFixture.Measurement(1,AstronomyMeasurementDimension.Angle,"deg","°"))).Issues,x=>x.Code==AstronomyObservationalValidationCodes.QuantityDimensionMismatch);ObservationalVisibilityValidationFixture.AssertIssue(i,AstronomyObservationalValidationCodes.QuantityDimensionMismatch,AstronomyKnowledgeValidationSeverity.Error,"$.quantities[0].measurement.unit.dimension",AstronomyObservationalQuantityValidationRule.Id,AstronomyKnowledgeDomain.Observational,AstronomyKnowledgePayloadFamily.ObservationCondition);} 

[Fact] public void Exact_epoch_type_defines_quantity_duplicate_identity(){var identityType=typeof(AstronomyObservationalQuantityValidationRule).GetNestedType("QuantityIdentity",BindingFlags.NonPublic);Assert.NotNull(identityType);Assert.Contains(identityType!.GetProperties(BindingFlags.Public|BindingFlags.Instance),property=>property.Name=="Epoch"&&property.PropertyType==typeof(AstronomyEpochReference));}
[Fact] public void Quantity_note_blank_is_rejected_or_constructor_protected()=>Assert.Throws<ArgumentException>(()=>ObservationalVisibilityValidationFixture.Quantity(note:" "));
[Fact] public void Quantity_issue_path_points_to_correct_index()=>Category_dimension_mismatch_is_detected();
[Fact] public void Quantity_rule_execution_is_deterministic(){var q=ObservationalVisibilityValidationFixture.Quantity(category:AstronomyObservationalQuantityCategory.Brightness, measurement:ObservationalVisibilityValidationFixture.Measurement(1,AstronomyMeasurementDimension.Angle,"deg","°")); Assert.Equal(Validate(q).Issues,Validate(q).Issues);} 
[Fact] public void Quantity_dimension_catalog_has_explicit_policy_for_every_category(){var mapped=new[]{AstronomyObservationalQuantityCategory.Brightness,AstronomyObservationalQuantityCategory.AngularSize,AstronomyObservationalQuantityCategory.AngularSeparation,AstronomyObservationalQuantityCategory.HorizontalPosition,AstronomyObservationalQuantityCategory.Illumination};var unmapped=new[]{AstronomyObservationalQuantityCategory.SkyCondition,AstronomyObservationalQuantityCategory.AtmosphericCondition,AstronomyObservationalQuantityCategory.InstrumentCondition,AstronomyObservationalQuantityCategory.Other};Assert.Equal(Enum.GetValues<AstronomyObservationalQuantityCategory>().OrderBy(x=>x), mapped.Concat(unmapped).OrderBy(x=>x));}
[Theory][InlineData(AstronomyObservationalQuantityCategory.Brightness,AstronomyMeasurementDimension.Magnitude)][InlineData(AstronomyObservationalQuantityCategory.AngularSize,AstronomyMeasurementDimension.Angle)][InlineData(AstronomyObservationalQuantityCategory.AngularSeparation,AstronomyMeasurementDimension.Angle)][InlineData(AstronomyObservationalQuantityCategory.HorizontalPosition,AstronomyMeasurementDimension.Angle)][InlineData(AstronomyObservationalQuantityCategory.Illumination,AstronomyMeasurementDimension.Percentage)] public void Every_mapped_quantity_category_returns_expected_dimension(AstronomyObservationalQuantityCategory c,AstronomyMeasurementDimension d){var m=d==AstronomyMeasurementDimension.Angle?ObservationalVisibilityValidationFixture.Measurement(1,d,"deg","°"):ObservationalVisibilityValidationFixture.Measurement(1,d,d.ToString().ToLowerInvariant(),"u");Assert.DoesNotContain(Validate(ObservationalVisibilityValidationFixture.Quantity(category:c,measurement:m)).Issues,i=>i.Code==AstronomyObservationalValidationCodes.QuantityDimensionMismatch);}}
