using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Coordinates;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Integration;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Measurements;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Observation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Observational;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Positional;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.DependencyInjection;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Observational;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Visibility;
using Microsoft.Extensions.DependencyInjection;

namespace Astronomy.MediaFactory.Tests.KnowledgeFoundation.Validation.ObservationalAndVisibility;

public sealed class AstronomyVisibilityValidationIntegrationTests{static ServiceProvider P(){var s=new ServiceCollection();s.AddAstronomyTypedKnowledgePayloadDescriptors();s.AddAstronomyVisibilityValidation().AddAstronomyVisibilityValidation();return s.BuildServiceProvider();}static string[] Ids=>[AstronomyVisibilityContextValidationRule.Id,AstronomyVisibilityWindowValidationRule.Id,AstronomyVisibilityAssessmentValidationRule.Id,AstronomyVisibilityPeakValidationRule.Id];[Fact] public void Visibility_registration_is_idempotent(){using var p=P();foreach(var id in Ids)Assert.Single(p.GetRequiredService<IAstronomyKnowledgeValidationRuleRegistry>().Descriptors,d=>d.RuleId==id);} [Fact] public void Every_visibility_rule_is_registered_exactly_once()=>Visibility_registration_is_idempotent();[Fact] public void Descriptor_metadata_matches_runtime_rule_metadata(){using var p=P();var r=p.GetServices<IAstronomyKnowledgeValidationRule>();foreach(var d in p.GetRequiredService<IAstronomyKnowledgeValidationRuleRegistry>().Descriptors.Where(d=>Ids.Contains(d.RuleId))){var rule=Assert.Single(r,x=>x.RuleId==d.RuleId);Assert.Equal(d.RuleType,rule.GetType());Assert.Equal(d.Domain,rule.Domain);Assert.Equal(d.Family,rule.Family);Assert.Equal(d.Order,rule.Order);}}[Fact] public void Real_visibility_payload_validates_through_typed_validator(){using var p=P();Assert.Empty(p.GetRequiredService<IAstronomyTypedKnowledgeValidator>().Validate(ObservationalVisibilityValidationFixture.ValidVisibilityPayload(),ObservationalVisibilityValidationFixture.Context()).Issues);}[Fact] public void Minimum_severity_filtering_works(){using var p=P();var payload=new AstronomyVisibilityWindowsPayload(new("typed.observational.visibility-windows.v1"),ObservationalVisibilityValidationFixture.ObservationContext(),[ObservationalVisibilityValidationFixture.VisibilityWindow(),ObservationalVisibilityValidationFixture.VisibilityWindow(start:ObservationalVisibilityValidationFixture.T1,end:new DateTimeOffset(2026,8,1,3,0,0,TimeSpan.Zero),peak:ObservationalVisibilityValidationFixture.T2,note:"overlap")]);Assert.Empty(p.GetRequiredService<IAstronomyTypedKnowledgeValidator>().Validate(payload,ObservationalVisibilityValidationFixture.Context(minimumSeverity:AstronomyKnowledgeValidationSeverity.Error)).Issues);}[Fact] public void Rule_execution_is_deterministic(){using var p=P();var v=p.GetRequiredService<IAstronomyTypedKnowledgeValidator>();Assert.Equal(v.Validate(ObservationalVisibilityValidationFixture.ValidVisibilityPayload(),ObservationalVisibilityValidationFixture.Context()).Issues,v.Validate(ObservationalVisibilityValidationFixture.ValidVisibilityPayload(),ObservationalVisibilityValidationFixture.Context()).Issues);}}