using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Coordinates;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Integration;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Measurements;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Observation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Observational;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Positional;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.DependencyInjection;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Observational;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Visibility;
using Microsoft.Extensions.DependencyInjection;

namespace Astronomy.MediaFactory.Tests.KnowledgeFoundation.Validation.ObservationalAndVisibility;

public sealed class AstronomyObservationalValidationIntegrationTests{static ServiceProvider P(){var s=new ServiceCollection();s.AddAstronomyTypedKnowledgePayloadDescriptors();s.AddAstronomyObservationalValidation().AddAstronomyObservationalValidation();return s.BuildServiceProvider();}static string[] Ids=>[AstronomyObservationContextValidationRule.Id,AstronomyObservationConditionsValidationRule.Id,AstronomyObservationalQuantityValidationRule.Id,AstronomyHorizontalCoordinatesValidationRule.Id];[Fact] public void Observational_registration_is_idempotent(){using var p=P();foreach(var id in Ids)Assert.Single(p.GetRequiredService<IAstronomyKnowledgeValidationRuleRegistry>().Descriptors,d=>d.RuleId==id);} [Fact] public void Every_observational_rule_is_registered_exactly_once()=>Observational_registration_is_idempotent();[Fact] public void Descriptor_metadata_matches_runtime_rule_metadata(){using var p=P();var r=p.GetServices<IAstronomyKnowledgeValidationRule>();foreach(var d in p.GetRequiredService<IAstronomyKnowledgeValidationRuleRegistry>().Descriptors.Where(d=>Ids.Contains(d.RuleId))){var rule=Assert.Single(r,x=>x.RuleId==d.RuleId);Assert.Equal(d.RuleType,rule.GetType());Assert.Equal(d.Domain,rule.Domain);Assert.Equal(d.Family,rule.Family);Assert.Equal(d.Order,rule.Order);}}[Fact] public void Real_observation_payload_validates_through_typed_validator(){using var p=P();Assert.Empty(p.GetRequiredService<IAstronomyTypedKnowledgeValidator>().Validate(ObservationalVisibilityValidationFixture.ValidObservationPayload(),ObservationalVisibilityValidationFixture.Context()).Issues);}[Fact] public void Minimum_severity_filtering_works(){using var p=P();var payload=new AstronomyObservationConditionsPayload(new("typed.observational.conditions.v1"),ObservationalVisibilityValidationFixture.ObservationContext(),ObservationalVisibilityValidationFixture.Conditions(transparency:AstronomyTransparencyQuality.VeryPoor),[],ObservationalVisibilityValidationFixture.HorizontalCoordinate());Assert.Empty(p.GetRequiredService<IAstronomyTypedKnowledgeValidator>().Validate(payload,ObservationalVisibilityValidationFixture.Context(minimumSeverity:AstronomyKnowledgeValidationSeverity.Error)).Issues);}[Fact] public void Rule_execution_is_deterministic(){using var p=P();var v=p.GetRequiredService<IAstronomyTypedKnowledgeValidator>();Assert.Equal(v.Validate(ObservationalVisibilityValidationFixture.ValidObservationPayload(),ObservationalVisibilityValidationFixture.Context()).Issues,v.Validate(ObservationalVisibilityValidationFixture.ValidObservationPayload(),ObservationalVisibilityValidationFixture.Context()).Issues);}}