using System.Text.Json;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
namespace Astronomy.MediaFactory.Tests.DocumentaryBlueprint;
public sealed class DocumentaryMediaProjectionSerializationTests
{
 [Theory] [InlineData("orion")] [InlineData("leo")] [InlineData("conjunction")] public void Equivalent_inputs_and_outputs_have_byte_identical_web_json(string scenario)
 {DocumentaryMediaProjectionRequest Get()=>scenario=="orion"?DocumentaryMediaProjectionFixture.Orion():scenario=="leo"?DocumentaryMediaProjectionFixture.Leo():DocumentaryMediaProjectionFixture.Conjunction();var a=Get();var b=Get();Assert.Equal(DocumentaryMediaProjectionFixture.Json(a),DocumentaryMediaProjectionFixture.Json(b));Assert.Equal(DocumentaryMediaProjectionFixture.Json(new DocumentaryMediaProjector().Project(a)),DocumentaryMediaProjectionFixture.Json(new DocumentaryMediaProjector().Project(b)));Assert.Contains("-04:00",DocumentaryMediaProjectionFixture.Json(a));Assert.Contains(" projection fixture ",DocumentaryMediaProjectionFixture.Json(a));}
 [Fact] public void Every_public_projection_contract_round_trips_byte_identically()
 {var request=DocumentaryMediaProjectionFixture.Orion();var result=new DocumentaryMediaProjector().Project(request);var project=Assert.IsType<DocumentaryMediaProject>(result.MediaProject);object[] values=[request.Policy,request.Metadata,request.TopicProfile,request,..project.Variants.SelectMany(x=>x.Scenes).SelectMany(x=>x.KnowledgeReferences),..project.Variants.SelectMany(x=>x.Scenes).SelectMany(x=>x.Narration),..project.Variants.SelectMany(x=>x.Scenes).SelectMany(x=>x.SubtitleCues),..project.Variants.SelectMany(x=>x.Scenes).SelectMany(x=>x.VisualPrompts),..project.Variants.SelectMany(x=>x.Scenes).Select(x=>x.Timing),..project.Variants.SelectMany(x=>x.Scenes),..project.Variants,project,result,new DocumentaryMediaProjectionSummarizer().Summarize(project)];foreach(var value in values){var type=value.GetType();var json=JsonSerializer.Serialize(value,type,DocumentaryMediaProjectionFixture.WebJson);var copy=JsonSerializer.Deserialize(json,type,DocumentaryMediaProjectionFixture.WebJson);Assert.Equal(json,JsonSerializer.Serialize(copy,type,DocumentaryMediaProjectionFixture.WebJson));}}
}
