using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
namespace Astronomy.MediaFactory.Tests.DocumentaryBlueprint;
public sealed class DocumentaryBlueprintEnumTests
{
 [Fact] public void Enum_inventories_are_exactly_approved() { Assert.Equal(["Wonder","Recognition","Discovery","Science","History","Culture","ModernAstronomy","Clarification","Observation","Astrophotography","Inspiration"],Enum.GetNames<DocumentaryNarrativeStage>()); Assert.Equal(["OpeningHook","Orientation","RecognitionGuide","CoreDiscovery","ScientificExplanation","HistoricalContext","CulturalContext","MythologyContext","MisconceptionCorrection","PracticalObservation","AstrophotographyGuide","ReflectiveClosing"],Enum.GetNames<DocumentarySceneRole>()); Assert.Equal(["Critical","High","Medium","Optional"],Enum.GetNames<EditorialPriority>()); Assert.Equal(["LongDocumentary","ShortDocumentary","ObservationGuide","Article","Podcast","SocialVideo"],Enum.GetNames<BlueprintPublicationFormat>()); }
 [Fact] public void Scene_rejects_undefined_narrative_stage() => Assert.Throws<ArgumentOutOfRangeException>(()=>CreateScene(narrativeStage:(DocumentaryNarrativeStage)999));
 [Fact] public void Scene_rejects_undefined_scene_role() => Assert.Throws<ArgumentOutOfRangeException>(()=>CreateScene(sceneRole:(DocumentarySceneRole)999));
 [Fact] public void Scene_rejects_undefined_editorial_priority() => Assert.Throws<ArgumentOutOfRangeException>(()=>CreateScene(editorialPriority:(EditorialPriority)999));
 [Fact] public void Aggregate_rejects_undefined_publication_format() { var x=OrionDocumentaryBlueprintFixture.Create(); Assert.Throws<ArgumentOutOfRangeException>(()=>new global::Astronomy.MediaFactory.Core.DocumentaryBlueprint.DocumentaryBlueprint("b","k","s","n",(BlueprintPublicationFormat)999,"en","1",x.Metadata,x.Scenes)); }
 private static DocumentarySceneBlueprint CreateScene(DocumentaryNarrativeStage? narrativeStage=null, DocumentarySceneRole? sceneRole=null, EditorialPriority? editorialPriority=null) { var x=OrionDocumentaryBlueprintFixture.Scene(); return new DocumentarySceneBlueprint("s",1,"t",narrativeStage??x.NarrativeStage,sceneRole??x.SceneRole,x.ViewerQuestion,x.SceneObjective,x.EditorialOutcome,editorialPriority??x.EditorialPriority,x.KnowledgeReferences,x.VisualOpportunities,x.Transition,1); }
}
