using System.Text.Json;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;

namespace Astronomy.MediaFactory.Tests.DocumentaryBlueprint;

internal static class OrionDocumentaryNarrativeRevisionFixture
{
    internal const string RequestId="revision-request.orion.v1";
    internal static DocumentaryNarrativeDraft Draft()=>OrionDocumentaryNarrativeDraftValidationFixture.DraftWithPassageText("orion commands attention above the eastern winter horizon tonight");
    internal static DocumentaryNarrativeRevisionRequestMetadata RequestMetadata()=>new(DateTimeOffset.Parse("2026-01-15T14:00:00Z"),"narrative-reviewer","1","1.0","1.0","correlation-orion-revision-request-001");
    internal static DocumentaryNarrativeRevisionMetadata Metadata()=>new(DateTimeOffset.Parse("2026-01-15T15:00:00Z"),"narrative-editor","narrative-draft.orion.long.v1","1","2","1.0","correlation-orion-revision-001");
    internal static DocumentaryNarrativeRevisionRequest Request(){var d=Draft();return new DocumentaryNarrativeRevisionRequestBuilder().Build(d,new DocumentaryNarrativeDraftValidator().Validate(d),RequestId,RequestMetadata());}
    internal static DocumentaryNarrativePassageRevisionInput Input(){var r=Request();var p=Draft().Sections[0].Passages[0];return new(r.Items.Where(x=>x.RequiresPassageText&&x.PassageId==p.PassageId).Select(x=>x.RevisionItemId).ToArray(),p.PassageId,p.Text,"Orion commands attention above the eastern winter horizon tonight.");}
}

public sealed class DocumentaryNarrativeRevisionRequestMetadataTests { [Fact] public void Validates_schema_and_timestamp(){Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionRequestMetadata(default,"a","1","1.0","1.0","c"));Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionRequestMetadata(new DateTimeOffset(2026,1,1,0,0,0,TimeSpan.Zero),"a","1","1.0","2.0","c"));} }
public sealed class DocumentaryNarrativeRevisionItemTests { [Fact] public void Derives_text_requirement(){var i=new DocumentaryNarrativeRevisionItem("i",1,"DND-QUALITY-011",DocumentaryNarrativeDraftValidationSeverity.Warning,DocumentaryNarrativeRevisionAction.RevisePassageOpening,"m","d",passageId:"p");Assert.True(i.RequiresPassageText);} }
public sealed class DocumentaryNarrativeRevisionRequestTests { [Fact] public void Counts_are_derived(){var r=OrionDocumentaryNarrativeRevisionFixture.Request();Assert.True(r.RequiresRevision);Assert.Equal(r.Items.Count,r.PassageTextRevisionCount+r.ManualReviewCount);} }
public sealed class DocumentaryNarrativeRevisionRequestBuilderTests { [Fact] public void Preserves_finding_order_and_ids(){var r=OrionDocumentaryNarrativeRevisionFixture.Request();Assert.Equal(Enumerable.Range(1,r.Items.Count),r.Items.Select(x=>x.SequenceNumber));Assert.Equal(r.Items.Select(x=>$"{r.RevisionRequestId}.item.{x.SequenceNumber}"),r.Items.Select(x=>x.RevisionItemId));} }
public sealed class DocumentaryNarrativeRevisionRequestBuilderMappingTests { [Fact] public void Maps_all_rules(){var expected=new[]{DocumentaryNarrativeRevisionAction.ReviewDraftStructure,DocumentaryNarrativeRevisionAction.ReviewDraftStructure,DocumentaryNarrativeRevisionAction.CorrectPassageNumber,DocumentaryNarrativeRevisionAction.CorrectPassageNumber,DocumentaryNarrativeRevisionAction.CorrectSourceIdentity,DocumentaryNarrativeRevisionAction.CorrectSourceIdentity,DocumentaryNarrativeRevisionAction.CorrectSourceIdentity,DocumentaryNarrativeRevisionAction.RevisePassageText,DocumentaryNarrativeRevisionAction.RevisePassageText,DocumentaryNarrativeRevisionAction.RevisePassageText,DocumentaryNarrativeRevisionAction.RevisePassageOpening,DocumentaryNarrativeRevisionAction.AddTerminalPunctuation,DocumentaryNarrativeRevisionAction.DifferentiatePassageText,DocumentaryNarrativeRevisionAction.DifferentiatePassageTitle,DocumentaryNarrativeRevisionAction.CorrectPassageType,DocumentaryNarrativeRevisionAction.CorrectPassageType,DocumentaryNarrativeRevisionAction.ReviewDuration,DocumentaryNarrativeRevisionAction.ReviewDuration};Assert.Equal(expected,Enumerable.Range(1,18).Select(i=>DocumentaryNarrativeRevisionMappings.Action($"DND-QUALITY-{i:000}")));} }
public sealed class DocumentaryNarrativePassageRevisionInputTests { [Fact] public void Copies_grouped_ids(){var a=new List<string>{"i"};var x=new DocumentaryNarrativePassageRevisionInput(a,"p","old","new");a.Add("j");Assert.Single(x.RevisionItemIds);} }
public sealed class DocumentaryNarrativeRevisionMetadataTests { [Fact] public void Requires_distinct_versions(){Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionMetadata(new DateTimeOffset(2026,1,1,0,0,0,TimeSpan.Zero),"e","d","1","1","1.0","c"));} }
public sealed class DocumentaryNarrativeRevisionBindingRequestTests { [Fact] public void Copies_inputs(){var inputs=new List<DocumentaryNarrativePassageRevisionInput>();var x=new DocumentaryNarrativeRevisionBindingRequest(OrionDocumentaryNarrativeRevisionFixture.Draft(),OrionDocumentaryNarrativeRevisionFixture.Request(),OrionDocumentaryNarrativeRevisionFixture.Metadata(),inputs);inputs.Add(OrionDocumentaryNarrativeRevisionFixture.Input());Assert.Empty(x.PassageRevisionInputs);} }
public sealed class DocumentaryNarrativeRevisionChangeTests { [Fact] public void Copies_collections(){var ids=new List<string>{"i"};var x=new DocumentaryNarrativeRevisionChange(ids,["r"],"p","o","n");ids.Add("x");Assert.Single(x.RevisionItemIds);} }
public sealed class DocumentaryNarrativeRevisionResultTests { [Fact] public void Counts_are_derived(){var x=Bind();Assert.Equal(x.Changes.Count,x.AppliedChangeCount);Assert.Equal(x.UnresolvedItems.Count,x.UnresolvedItemCount);} internal static DocumentaryNarrativeRevisionResult Bind()=>new DocumentaryNarrativeRevisionBinder().Bind(new(OrionDocumentaryNarrativeRevisionFixture.Draft(),OrionDocumentaryNarrativeRevisionFixture.Request(),OrionDocumentaryNarrativeRevisionFixture.Metadata(),[OrionDocumentaryNarrativeRevisionFixture.Input()])); }
public sealed class DocumentaryNarrativeRevisionBinderTests { [Fact] public void Groups_two_findings_into_one_change(){var x=DocumentaryNarrativeRevisionResultTests.Bind();Assert.Single(x.Changes);Assert.Equal(2,x.Changes[0].RevisionItemIds.Count);Assert.Equal(DocumentaryNarrativeRevisionStatus.Revised,x.Status);} }
public sealed class DocumentaryNarrativeRevisionBinderValidationTests { [Fact] public void Rejects_stale_text(){var d=OrionDocumentaryNarrativeRevisionFixture.Draft();var r=OrionDocumentaryNarrativeRevisionFixture.Request();var good=OrionDocumentaryNarrativeRevisionFixture.Input();var bad=new DocumentaryNarrativePassageRevisionInput(good.RevisionItemIds,good.PassageId,"stale",good.RevisedText);Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionBinder().Bind(new(d,r,OrionDocumentaryNarrativeRevisionFixture.Metadata(),[bad])));} }
public sealed class DocumentaryNarrativeRevisionBinderMappingTests { [Fact] public void Changes_only_target_text_and_identity(){var d=OrionDocumentaryNarrativeRevisionFixture.Draft();var x=DocumentaryNarrativeRevisionResultTests.Bind();Assert.Equal(d.DraftId+".revision.2",x.TargetDraftId);Assert.Equal("2",x.RevisedDraft.Version);Assert.Equal(OrionDocumentaryNarrativeRevisionFixture.Input().RevisedText,x.RevisedDraft.Sections[0].Passages[0].Text);Assert.Equal(d.Sections[1].Passages[0].Text,x.RevisedDraft.Sections[1].Passages[0].Text);} }
public sealed class DocumentaryNarrativeRevisionBinderOrderingTests { [Fact] public void Change_item_order_is_request_order(){var x=DocumentaryNarrativeRevisionResultTests.Bind();Assert.Equal(x.Changes[0].RevisionItemIds.OrderBy(id=>OrionDocumentaryNarrativeRevisionFixture.Request().Items.Single(i=>i.RevisionItemId==id).SequenceNumber),x.Changes[0].RevisionItemIds);} }
public sealed class DocumentaryNarrativeRevisionBinderDeterminismTests { [Fact] public void Equivalent_binding_has_identical_json(){Assert.Equal(JsonSerializer.Serialize(DocumentaryNarrativeRevisionResultTests.Bind()),JsonSerializer.Serialize(DocumentaryNarrativeRevisionResultTests.Bind()));} }
public sealed class DocumentaryNarrativeRevisionBinderImmutabilityTests { [Fact] public void Original_is_not_mutated(){var d=OrionDocumentaryNarrativeRevisionFixture.Draft();var original=d.Sections[0].Passages[0].Text;_ = DocumentaryNarrativeRevisionResultTests.Bind();Assert.Equal(original,d.Sections[0].Passages[0].Text);} }
public sealed class DocumentaryNarrativeRevisionSerializationTests { [Fact] public void Result_round_trips_deterministically(){var json=JsonSerializer.Serialize(DocumentaryNarrativeRevisionResultTests.Bind());var copy=JsonSerializer.Deserialize<DocumentaryNarrativeRevisionResult>(json)!;Assert.Equal(json,JsonSerializer.Serialize(copy));} }
public sealed class DocumentaryNarrativeRevisionArchitectureTests { [Fact] public void Operations_are_sealed_parameterless_and_stateless(){foreach(var t in new[]{typeof(DocumentaryNarrativeRevisionRequestBuilder),typeof(DocumentaryNarrativeRevisionBinder)}){Assert.True(t.IsSealed);Assert.Empty(t.GetFields(System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.Public|System.Reflection.BindingFlags.NonPublic));Assert.NotNull(t.GetConstructor(Type.EmptyTypes));}} }
public sealed class DocumentaryNarrativeRevisionInventoryTests { [Fact] public void Enum_inventories_are_exact(){Assert.Equal(10,Enum.GetValues<DocumentaryNarrativeRevisionAction>().Length);Assert.Equal(4,Enum.GetValues<DocumentaryNarrativeRevisionStatus>().Length);} }
