using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
namespace Astronomy.MediaFactory.Tests.DocumentaryBlueprint;
public sealed class DocumentaryBlueprintContractTests
{
 [Fact] public void Valid_aggregate_preserves_supplied_contract_values() { var x=OrionDocumentaryBlueprintFixture.Create(); Assert.Equal("documentary.orion.long.v1",x.BlueprintId); Assert.Equal("1.0",x.Metadata.BlueprintSchemaVersion); Assert.Single(x.Scenes); }
 [Theory] [InlineData(null)] [InlineData("")] [InlineData(" ")] public void Aggregate_rejects_blank_required_ids(string? id) => Assert.ThrowsAny<ArgumentException>(() => new global::Astronomy.MediaFactory.Core.DocumentaryBlueprint.DocumentaryBlueprint(id!,"k","s","name",BlueprintPublicationFormat.Article,"en","1",OrionDocumentaryBlueprintFixture.Create().Metadata,[]));
 [Fact] public void Aggregate_rejects_null_state_and_duplicate_scenes() { var x=OrionDocumentaryBlueprintFixture.Create(); Assert.Throws<ArgumentNullException>(()=>new global::Astronomy.MediaFactory.Core.DocumentaryBlueprint.DocumentaryBlueprint("b","k","s","n",BlueprintPublicationFormat.Article,"en","1",null!,[])); Assert.Throws<ArgumentNullException>(()=>new global::Astronomy.MediaFactory.Core.DocumentaryBlueprint.DocumentaryBlueprint("b","k","s","n",BlueprintPublicationFormat.Article,"en","1",x.Metadata,null!)); var scene=x.Scenes[0]; Assert.Throws<ArgumentException>(()=>OrionDocumentaryBlueprintFixture.Create([scene,scene])); Assert.Throws<ArgumentException>(()=>OrionDocumentaryBlueprintFixture.Create([scene,OrionDocumentaryBlueprintFixture.Scene("other",1)])); }
 [Fact] public void Metadata_preserves_externally_supplied_created_utc() { var createdUtc=new DateTimeOffset(2026,1,15,12,0,0,TimeSpan.Zero); var metadata=new DocumentaryBlueprintMetadata(createdUtc,"a","e","k","1.0","c"); Assert.Equal(createdUtc,metadata.CreatedUtc); }
 [Fact] public void Metadata_rejects_default_created_utc() => Assert.Throws<ArgumentException>(()=>new DocumentaryBlueprintMetadata(default,"a","e","k","1.0","c"));
 [Fact] public void Metadata_rejects_invalid_schema_version_with_valid_timestamp() => Assert.Throws<ArgumentException>(()=>new DocumentaryBlueprintMetadata(new DateTimeOffset(2026,1,15,12,0,0,TimeSpan.Zero),"a","e","k","2.0","c"));
 [Fact] public void Value_objects_validate_and_preserve_values() { Assert.Equal("question",new ViewerQuestion("question").Text); Assert.Throws<ArgumentException>(()=>new ViewerQuestion(" ")); Assert.Throws<ArgumentException>(()=>new KnowledgeReference(" ","s","p",true)); Assert.Throws<ArgumentException>(()=>new SceneTransition("i"," ","d")); Assert.Throws<ArgumentException>(()=>new VisualOpportunity("d","t"," ",null,false)); }
 [Fact] public void Aggregate_rejects_null_scene_element() { var valid=OrionDocumentaryBlueprintFixture.Scene(); IReadOnlyList<DocumentarySceneBlueprint> scenes=[valid,null!]; Assert.Throws<ArgumentException>(()=>OrionDocumentaryBlueprintFixture.Create(scenes)); }
}
