using System.Reflection;
using System.Text.Json;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;

namespace Astronomy.MediaFactory.Tests.DocumentaryBlueprint;

public sealed class DocumentaryNarrativeRevisionContractCertificationTests
{
    private static readonly DateTimeOffset ExactTime = new(2026,1,15,14,0,0,123,TimeSpan.FromHours(5.5));

    [Fact] public void Request_metadata_preserves_every_value()
    {var x=new DocumentaryNarrativeRevisionRequestMetadata(ExactTime," creator "," v1 "," validation ","1.0"," correlation ");Assert.Equal(ExactTime,x.CreatedUtc);Assert.Equal(ExactTime.Offset,x.CreatedUtc.Offset);Assert.Equal(" creator ",x.CreatedBy);Assert.Equal(" v1 ",x.SourceDraftVersion);Assert.Equal(" validation ",x.ValidationSchemaVersion);Assert.Equal("1.0",x.RevisionRequestSchemaVersion);Assert.Equal(" correlation ",x.CorrelationId);}

    [Theory][InlineData("createdBy")][InlineData("sourceDraftVersion")][InlineData("validationSchemaVersion")][InlineData("correlationId")]
    public void Request_metadata_rejects_blank_required_strings(string member)
    {Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionRequestMetadata(ExactTime,member=="createdBy"?" ":"a",member=="sourceDraftVersion"?" ":"1",member=="validationSchemaVersion"?" ":"1.0","1.0",member=="correlationId"?" ":"c"));}
    [Fact] public void Request_metadata_rejects_default_time_and_wrong_schema(){Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionRequestMetadata(default,"a","1","1.0","1.0","c"));Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionRequestMetadata(ExactTime,"a","1","1.0","1.1","c"));}

    [Theory][InlineData(0)][InlineData(-1)] public void Item_rejects_nonpositive_sequence(int n)=>Assert.Throws<ArgumentOutOfRangeException>(()=>Item(sequence:n));
    [Theory][InlineData("id")][InlineData("rule")][InlineData("message")][InlineData("draft")][InlineData("section")][InlineData("passage")][InlineData("field")]
    public void Item_rejects_blank_identifiers(string member)=>Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionItem(member=="id"?" ":"i",1,member=="rule"?" ":"r",DocumentaryNarrativeDraftValidationSeverity.Error,DocumentaryNarrativeRevisionAction.RevisePassageText,member=="message"?" ":"m",member=="draft"?" ":"d",member=="section"?" ":"s",1,member=="passage"?" ":"p",1,member=="field"?" ":"Text"));
    [Fact] public void Item_rejects_undefined_enums(){Assert.Throws<ArgumentOutOfRangeException>(()=>Item(severity:(DocumentaryNarrativeDraftValidationSeverity)999));Assert.Throws<ArgumentOutOfRangeException>(()=>Item(action:(DocumentaryNarrativeRevisionAction)999));}
    [Fact] public void Item_preserves_every_value(){var x=new DocumentaryNarrativeRevisionItem("i",7,"r",DocumentaryNarrativeDraftValidationSeverity.Warning,DocumentaryNarrativeRevisionAction.RevisePassageOpening," m ","d","s",2,"p",3,"Text");Assert.Equal(("i",7,"r",DocumentaryNarrativeDraftValidationSeverity.Warning,DocumentaryNarrativeRevisionAction.RevisePassageOpening," m ","d","s",2,"p",3,"Text"),(x.RevisionItemId,x.SequenceNumber,x.RuleCode,x.Severity,x.Action,x.Message,x.DraftId,x.SectionId,x.SectionNumber,x.PassageId,x.PassageNumber,x.FieldName));Assert.True(x.RequiresPassageText);}

    [Fact] public void Passage_input_validates_and_defensively_copies(){Assert.Throws<ArgumentNullException>(()=>new DocumentaryNarrativePassageRevisionInput(null!,"p","o","n"));Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativePassageRevisionInput([],"p","o","n"));foreach(var ids in new string?[][]{[null],[" "],["i","i"]})Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativePassageRevisionInput(ids!,"p","o","n"));foreach(var values in new[]{(" ","o","n"),("p"," ","n"),("p","o"," ")})Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativePassageRevisionInput(["i"],values.Item1,values.Item2,values.Item3));var source=new List<string>{"b","a"};var x=new DocumentaryNarrativePassageRevisionInput(source,"p"," old "," new ");source.Clear();Assert.Equal(new[]{"b","a"},x.RevisionItemIds);Assert.Equal(" old ",x.OriginalText);Assert.Equal(" new ",x.RevisedText);Assert.Throws<NotSupportedException>(()=>((IList<string>)x.RevisionItemIds).Add("x"));}

    [Fact] public void Revision_metadata_validates_and_preserves_exact_values(){foreach(var member in Enumerable.Range(0,5)){var v=new[]{"by","draft","v1","v2","c"};v[member]=" ";Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionMetadata(ExactTime,v[0],v[1],v[2],v[3],"1.0",v[4]));}Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionMetadata(default,"a","d","v1","v2","1.0","c"));Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionMetadata(ExactTime,"a","d","v1","v1","1.0","c"));Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionMetadata(ExactTime,"a","d","v1","v2","2.0","c"));var x=new DocumentaryNarrativeRevisionMetadata(ExactTime," by "," d ","v1","V1","1.0"," c ");Assert.Equal((ExactTime," by "," d ","v1","V1","1.0"," c "),(x.CreatedUtc,x.CreatedBy,x.SourceDraftId,x.SourceDraftVersion,x.TargetDraftVersion,x.RevisionSchemaVersion,x.CorrelationId));}

    [Fact] public void Change_validates_copies_and_preserves_order_and_text(){Assert.Throws<ArgumentNullException>(()=>new DocumentaryNarrativeRevisionChange(null!,["r"],"p","o","n"));Assert.Throws<ArgumentNullException>(()=>new DocumentaryNarrativeRevisionChange(["i"],null!,"p","o","n"));foreach(var pair in new[]{(Array.Empty<string>(),Array.Empty<string>()),(new[]{"i"},Array.Empty<string>()),(new[]{"i", "j"},new[]{"r"})})Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionChange(pair.Item1,pair.Item2,"p","o","n"));var ids=new List<string>{"b","a"};var rules=new List<string>{"r2","r1"};var x=new DocumentaryNarrativeRevisionChange(ids,rules,"p"," old "," new ");ids.Clear();rules.Clear();Assert.Equal(new[]{"b","a"},x.RevisionItemIds);Assert.Equal(new[]{"r2","r1"},x.RuleCodes);Assert.Equal(" old ",x.OriginalText);Assert.Equal(" new ",x.RevisedText);Assert.Throws<NotSupportedException>(()=>((IList<string>)x.RuleCodes).Add("x"));}

    private static DocumentaryNarrativeRevisionItem Item(int sequence=1,DocumentaryNarrativeDraftValidationSeverity severity=DocumentaryNarrativeDraftValidationSeverity.Error,DocumentaryNarrativeRevisionAction action=DocumentaryNarrativeRevisionAction.RevisePassageText)=>new("i",sequence,"r",severity,action,"m","d","s",1,"p",1,"Text");
}

public sealed class DocumentaryNarrativeRevisionMappingCertificationTests
{
    public static TheoryData<DocumentaryNarrativeRevisionAction,bool> TextActions=>new(){
        {DocumentaryNarrativeRevisionAction.ReviewDraftStructure,false},{DocumentaryNarrativeRevisionAction.RevisePassageText,true},{DocumentaryNarrativeRevisionAction.RevisePassageOpening,true},{DocumentaryNarrativeRevisionAction.AddTerminalPunctuation,true},{DocumentaryNarrativeRevisionAction.DifferentiatePassageText,true},{DocumentaryNarrativeRevisionAction.DifferentiatePassageTitle,false},{DocumentaryNarrativeRevisionAction.CorrectPassageType,false},{DocumentaryNarrativeRevisionAction.CorrectPassageNumber,false},{DocumentaryNarrativeRevisionAction.CorrectSourceIdentity,false},{DocumentaryNarrativeRevisionAction.ReviewDuration,false}};
    [Theory][MemberData(nameof(TextActions))] public void Requires_text_inventory_is_exact(DocumentaryNarrativeRevisionAction action,bool expected)=>Assert.Equal(expected,DocumentaryNarrativeRevisionMappings.RequiresPassageText(action));
    [Fact] public void Undefined_action_and_unknown_rule_are_rejected(){Assert.Throws<ArgumentOutOfRangeException>(()=>DocumentaryNarrativeRevisionMappings.RequiresPassageText((DocumentaryNarrativeRevisionAction)99));Assert.Throws<ArgumentOutOfRangeException>(()=>DocumentaryNarrativeRevisionMappings.Action("UNKNOWN"));}
    [Fact] public void Exact_rule_action_inventory(){var expected=new[]{"ReviewDraftStructure","ReviewDraftStructure","CorrectPassageNumber","CorrectPassageNumber","CorrectSourceIdentity","CorrectSourceIdentity","CorrectSourceIdentity","RevisePassageText","RevisePassageText","RevisePassageText","RevisePassageOpening","AddTerminalPunctuation","DifferentiatePassageText","DifferentiatePassageTitle","CorrectPassageType","CorrectPassageType","ReviewDuration","ReviewDuration"};Assert.Equal(expected,Enumerable.Range(1,18).Select(n=>DocumentaryNarrativeRevisionMappings.Action($"DND-QUALITY-{n:000}").ToString()));}
    [Fact] public void Enum_names_and_order_are_exact(){Assert.Equal(new[]{"ReviewDraftStructure","RevisePassageText","RevisePassageOpening","AddTerminalPunctuation","DifferentiatePassageText","DifferentiatePassageTitle","CorrectPassageType","CorrectPassageNumber","CorrectSourceIdentity","ReviewDuration"},Enum.GetNames<DocumentaryNarrativeRevisionAction>());Assert.Equal(new[]{"NoChangesRequired","Revised","PartiallyRevised","Rejected"},Enum.GetNames<DocumentaryNarrativeRevisionStatus>());}
}

public sealed class DocumentaryNarrativeRevisionBuilderAndBinderCertificationTests
{
    [Fact] public void Builder_rejects_null_blank_and_lineage_mismatch(){var d=OrionDocumentaryNarrativeRevisionFixture.ValidDraft();var v=OrionDocumentaryNarrativeRevisionFixture.CleanValidationResult();var m=OrionDocumentaryNarrativeRevisionFixture.RequestMetadata();var b=new DocumentaryNarrativeRevisionRequestBuilder();Assert.Throws<ArgumentNullException>(()=>b.Build(null!,v,"r",m));Assert.Throws<ArgumentNullException>(()=>b.Build(d,null!,"r",m));Assert.Throws<ArgumentException>(()=>b.Build(d,v," ",m));Assert.Throws<ArgumentNullException>(()=>b.Build(d,v,"r",null!));var other=OrionDocumentaryNarrativeDraftValidationFixture.Draft(d, d.Sections);typeof(DocumentaryNarrativeDraft).GetField("<DraftId>k__BackingField",BindingFlags.Instance|BindingFlags.NonPublic)!.SetValue(other,"other");Assert.Throws<ArgumentException>(()=>b.Build(other,v,"r",m));}
    [Fact] public void Clean_request_and_binding_create_no_fake_lineage(){var request=OrionDocumentaryNarrativeRevisionFixture.NoChangeRequest();Assert.Empty(request.Items);Assert.False(request.RequiresRevision);Assert.Equal(0,request.PassageTextRevisionCount);Assert.Equal(0,request.ManualReviewCount);var binding=OrionDocumentaryNarrativeRevisionFixture.NoChangeBindingRequest();var result=new DocumentaryNarrativeRevisionBinder().Bind(binding);Assert.Equal(DocumentaryNarrativeRevisionStatus.NoChangesRequired,result.Status);Assert.Same(binding.OriginalDraft,result.RevisedDraft);Assert.Equal(result.SourceDraftId,result.TargetDraftId);Assert.Equal(result.SourceDraftVersion,result.TargetDraftVersion);Assert.Empty(result.Changes);Assert.Empty(result.UnresolvedItems);}
    [Fact] public void No_change_request_rejects_any_input(){var b=OrionDocumentaryNarrativeRevisionFixture.NoChangeBindingRequest();var p=b.OriginalDraft.Sections[0].Passages[0];var input=new DocumentaryNarrativePassageRevisionInput(["unknown"],p.PassageId,p.Text,p.Text+" revised");Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionBinder().Bind(new(b.OriginalDraft,b.RevisionRequest,b.Metadata,[input])));}
    [Fact] public void Complete_grouped_revision_preserves_order_lineage_and_inputs(){var binding=OrionDocumentaryNarrativeRevisionFixture.CompleteBindingRequest();var before=Json(binding);var result=new DocumentaryNarrativeRevisionBinder().Bind(binding);Assert.Equal(DocumentaryNarrativeRevisionStatus.Revised,result.Status);Assert.Single(result.Changes);Assert.Empty(result.UnresolvedItems);Assert.Equal(binding.PassageRevisionInputs[0].RevisionItemIds,result.Changes[0].RevisionItemIds);Assert.Equal(binding.RevisionRequest.Items.Where(x=>x.RequiresPassageText).Select(x=>x.RuleCode),result.Changes[0].RuleCodes);Assert.Equal(binding.OriginalDraft.DraftId+".revision."+binding.Metadata.TargetDraftVersion,result.TargetDraftId);Assert.Equal(result.TargetDraftId,result.RevisedDraft.DraftId);Assert.Equal(result.TargetDraftVersion,result.RevisedDraft.Version);Assert.Equal(before,Json(binding));}
    [Theory][InlineData("unknown-item",false,false)][InlineData(null,true,false)][InlineData(null,false,true)] public void Binder_rejects_unknown_case_variant_item_or_passage(string? id,bool itemCase,bool passageCase){var d=OrionDocumentaryNarrativeRevisionFixture.Draft();var r=OrionDocumentaryNarrativeRevisionFixture.Request();var good=OrionDocumentaryNarrativeRevisionFixture.Input();var ids=good.RevisionItemIds.ToArray();ids[0]=id??(itemCase?ids[0].ToUpperInvariant():ids[0]);var passage=passageCase?good.PassageId.ToUpperInvariant():good.PassageId;var input=new DocumentaryNarrativePassageRevisionInput(ids,passage,good.OriginalText,good.RevisedText);Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionBinder().Bind(new(d,r,OrionDocumentaryNarrativeRevisionFixture.Metadata(),[input])));}
    [Fact] public void Binder_rejects_missing_reversed_and_stale_grouped_items(){var d=OrionDocumentaryNarrativeRevisionFixture.Draft();var r=OrionDocumentaryNarrativeRevisionFixture.Request();var good=OrionDocumentaryNarrativeRevisionFixture.Input();foreach(var ids in new[]{good.RevisionItemIds.Take(1).ToArray(),good.RevisionItemIds.Reverse().ToArray()})Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionBinder().Bind(new(d,r,OrionDocumentaryNarrativeRevisionFixture.Metadata(),[new(ids,good.PassageId,good.OriginalText,good.RevisedText)])));foreach(var stale in new[]{good.OriginalText.ToUpperInvariant()," "+good.OriginalText,good.OriginalText+" "})Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionBinder().Bind(new(d,r,OrionDocumentaryNarrativeRevisionFixture.Metadata(),[new(good.RevisionItemIds,good.PassageId,stale,good.RevisedText)])));}
    [Fact] public void Binding_request_rejects_duplicate_passage_and_item_coverage(){var d=OrionDocumentaryNarrativeRevisionFixture.Draft();var r=OrionDocumentaryNarrativeRevisionFixture.Request();var m=OrionDocumentaryNarrativeRevisionFixture.Metadata();var i=OrionDocumentaryNarrativeRevisionFixture.Input();Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionBindingRequest(d,r,m,[i,i]));var second=new DocumentaryNarrativePassageRevisionInput(i.RevisionItemIds,"another",i.OriginalText,i.RevisedText);Assert.Throws<ArgumentException>(()=>new DocumentaryNarrativeRevisionBindingRequest(d,r,m,[i,second]));}
    [Fact] public void Binder_null_and_structural_failures_throw_never_rejected(){Assert.Throws<ArgumentNullException>(()=>new DocumentaryNarrativeRevisionBinder().Bind(null!));var ex=Record.Exception(()=>new DocumentaryNarrativeRevisionBinder().Bind(new(OrionDocumentaryNarrativeRevisionFixture.Draft(),OrionDocumentaryNarrativeRevisionFixture.Request(),OrionDocumentaryNarrativeRevisionFixture.Metadata(),[new(["unknown"],"p","o","n")])));Assert.NotNull(ex);Assert.IsNotType<DocumentaryNarrativeRevisionResult>(ex);}
    private static string Json(object value)=>JsonSerializer.Serialize(value,new JsonSerializerOptions(JsonSerializerDefaults.Web));
}

public sealed class DocumentaryNarrativeRevisionArchitectureCertificationTests
{
    public static TheoryData<Type,string[]> Contracts=>new(){
      {typeof(DocumentaryNarrativeRevisionRequestMetadata),["CreatedUtc","CreatedBy","SourceDraftVersion","ValidationSchemaVersion","RevisionRequestSchemaVersion","CorrelationId"]},
      {typeof(DocumentaryNarrativeRevisionItem),["RevisionItemId","SequenceNumber","RuleCode","Severity","Action","Message","DraftId","SectionId","SectionNumber","PassageId","PassageNumber","FieldName","RequiresPassageText"]},
      {typeof(DocumentaryNarrativeRevisionRequest),["RevisionRequestId","DraftId","DraftVersion","ValidationResult","Metadata","Items","RequiresRevision","PassageTextRevisionCount","ManualReviewCount"]},
      {typeof(DocumentaryNarrativePassageRevisionInput),["RevisionItemIds","PassageId","OriginalText","RevisedText"]},
      {typeof(DocumentaryNarrativeRevisionMetadata),["CreatedUtc","CreatedBy","SourceDraftId","SourceDraftVersion","TargetDraftVersion","RevisionSchemaVersion","CorrelationId"]},
      {typeof(DocumentaryNarrativeRevisionBindingRequest),["OriginalDraft","RevisionRequest","Metadata","PassageRevisionInputs"]},
      {typeof(DocumentaryNarrativeRevisionChange),["RevisionItemIds","RuleCodes","PassageId","OriginalText","RevisedText"]},
      {typeof(DocumentaryNarrativeRevisionResult),["RevisionRequestId","SourceDraftId","SourceDraftVersion","TargetDraftId","TargetDraftVersion","Status","RevisedDraft","Changes","UnresolvedItems","AppliedChangeCount","UnresolvedItemCount"]}};
    [Theory][MemberData(nameof(Contracts))] public void Public_property_inventory_is_exact_and_immutable(Type type,string[] expected){var properties=type.GetProperties(BindingFlags.Public|BindingFlags.Instance);Assert.Equal(expected.Order(),properties.Select(x=>x.Name).Order());Assert.All(properties,p=>Assert.False(p.SetMethod?.IsPublic??false));}
    [Theory][InlineData(typeof(DocumentaryNarrativeRevisionRequestBuilder),"Build",4)][InlineData(typeof(DocumentaryNarrativeRevisionBinder),"Bind",1)] public void Operations_are_sealed_parameterless_synchronous_stateless(Type type,string name,int parameters){Assert.True(type.IsSealed);Assert.NotNull(type.GetConstructor(Type.EmptyTypes));Assert.Empty(type.GetFields(BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic));var method=Assert.Single(type.GetMethods(BindingFlags.Public|BindingFlags.Instance|BindingFlags.DeclaredOnly));Assert.Equal(name,method.Name);Assert.Equal(parameters,method.GetParameters().Length);Assert.False(typeof(Task).IsAssignableFrom(method.ReturnType));}
    [Fact] public void Forbidden_capabilities_are_absent(){var forbidden=new[]{"Prompt","PromptText","SystemPrompt","UserPrompt","LlmResponse","RawModelResponse","ModelRequest","ModelParameters","Temperature","TopP","TokenCount","Provider","ProviderName","ModelName","AutoFix","GeneratedText","SuggestedText","CorrectedText","Ssml","Audio","AudioUrl","VoiceId","SpeechRate","Subtitle","Srt","Vtt","TtsText"};foreach(var row in Contracts)Assert.Empty(((Type)row[0]).GetProperties().Select(x=>x.Name).Intersect(forbidden,StringComparer.Ordinal));}
}

public sealed class DocumentaryNarrativeRevisionSerializationCertificationTests
{
    public static IEnumerable<object[]> Values(){var b=OrionDocumentaryNarrativeRevisionFixture.CompleteBindingRequest();var result=new DocumentaryNarrativeRevisionBinder().Bind(b);yield return [OrionDocumentaryNarrativeRevisionFixture.RequestMetadata()];yield return [b.RevisionRequest.Items[0]];yield return [b.RevisionRequest];yield return [b.PassageRevisionInputs[0]];yield return [b.Metadata];yield return [b];yield return [result.Changes[0]];yield return [result];}
    [Theory][MemberData(nameof(Values))] public void Contract_round_trip_is_deterministic(object value){var options=new JsonSerializerOptions(JsonSerializerDefaults.Web);var json=JsonSerializer.Serialize(value,value.GetType(),options);var copy=JsonSerializer.Deserialize(json,value.GetType(),options);Assert.NotNull(copy);Assert.Equal(json,JsonSerializer.Serialize(copy,copy!.GetType(),options));}
    [Fact] public void Independently_reconstructed_operations_are_deterministic(){var one=new DocumentaryNarrativeRevisionBinder().Bind(OrionDocumentaryNarrativeRevisionFixture.CompleteBindingRequest());var two=new DocumentaryNarrativeRevisionBinder().Bind(OrionDocumentaryNarrativeRevisionFixture.CompleteBindingRequest());var options=new JsonSerializerOptions(JsonSerializerDefaults.Web);Assert.Equal(JsonSerializer.Serialize(one,options),JsonSerializer.Serialize(two,options));Assert.NotSame(one.RevisedDraft,two.RevisedDraft);}
}
