namespace Astronomy.MediaFactory.Core.KnowledgeFoundation.Evidence.Validation;

using Astronomy.MediaFactory.Core.AstronomyDomain.Validation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Evidence.Confidence;

public interface IAstronomyEvidenceRecordValidator { DomainValidationResult Validate(AstronomyEvidenceRecord record); }
public interface IAstronomyKnowledgeStatementEvidenceSetValidator { DomainValidationResult Validate(AstronomyKnowledgeStatementEvidenceSet evidenceSet); }
public interface IAstronomyKnowledgeConfidenceAssessmentValidator { DomainValidationResult Validate(AstronomyKnowledgeConfidenceAssessment assessment); }
public interface IAstronomyEvidenceConfidenceConsistencyValidator { DomainValidationResult Validate(AstronomyKnowledgeConfidenceAssessment assessment, AstronomyKnowledgeStatementEvidenceSet evidenceSet); }

public sealed class AstronomyEvidenceRecordValidator : IAstronomyEvidenceRecordValidator
{
    public DomainValidationResult Validate(AstronomyEvidenceRecord record)
    {
        ArgumentNullException.ThrowIfNull(record);
        var issues = new List<DomainValidationIssue>();
        if (string.IsNullOrWhiteSpace(record.Id.Value)) Add(issues, AstronomyEvidenceValidationCodes.RecordIdMissing, "Evidence ID is required.", "id");
        if (!Enum.IsDefined(record.Type)) Add(issues, AstronomyEvidenceValidationCodes.RecordTypeUndefined, "Evidence type is not defined.", "type");
        if (!Enum.IsDefined(record.Status)) Add(issues, AstronomyEvidenceValidationCodes.RecordStatusUndefined, "Evidence status is not defined.", "status");
        ValidateSource(record.Source, issues); ValidateTemporal(record.TemporalMetadata, issues); ValidationSupport.ValidateAudit(record.Audit, issues, AstronomyEvidenceValidationCodes.RecordAuditMissing, AstronomyEvidenceValidationCodes.RecordAuditInvalid, "audit");
        ValidateAttribution(record.Attribution, issues); ValidateExternalIdentifiers(record.ExternalIdentifiers, issues); ValidateTags(record.Tags, issues); ValidateText(record.Title, AstronomyEvidenceRecord.MaxTitleLength, AstronomyEvidenceValidationCodes.RecordTitleInvalid, "title", issues); ValidateText(record.Summary, AstronomyEvidenceRecord.MaxSummaryLength, AstronomyEvidenceValidationCodes.RecordSummaryInvalid, "summary", issues);
        return DomainValidationResult.From(issues.ToArray());
    }
    private static void ValidateSource(AstronomyEvidenceSourceReference source, List<DomainValidationIssue> issues) { if (source is null) { Add(issues, AstronomyEvidenceValidationCodes.RecordSourceMissing, "Evidence source is required.", "source"); return; } if (string.IsNullOrWhiteSpace(source.SourceId)) Add(issues, AstronomyEvidenceValidationCodes.RecordSourceInvalid, "Source ID is required.", "source.sourceId"); if (!Enum.IsDefined(source.SourceType)) Add(issues, AstronomyEvidenceValidationCodes.RecordSourceInvalid, "Source type is not defined.", "source.sourceType"); if (string.IsNullOrWhiteSpace(source.DisplayName)) Add(issues, AstronomyEvidenceValidationCodes.RecordSourceInvalid, "Source display name is required.", "source.displayName"); if (source.CanonicalUri is { IsAbsoluteUri: false }) Add(issues, AstronomyEvidenceValidationCodes.RecordSourceInvalid, "Canonical URI must be absolute.", "source.canonicalUri"); if (source.CanonicalUri is { IsAbsoluteUri: true } uri) { if (uri.Scheme != Uri.UriSchemeHttps) Add(issues, AstronomyEvidenceValidationCodes.RecordSourceInvalid, "Canonical URI must use HTTPS.", "source.canonicalUri"); if (!string.IsNullOrEmpty(uri.UserInfo)) Add(issues, AstronomyEvidenceValidationCodes.RecordSourceInvalid, "Canonical URI must not contain credentials.", "source.canonicalUri"); } if (source.ExternalIdentifier is not null) ValidateExternalIdentifier(source.ExternalIdentifier, issues, "source.externalIdentifier", AstronomyEvidenceValidationCodes.RecordSourceInvalid); }
    private static void ValidateTemporal(EvidenceTemporalMetadata temporal, List<DomainValidationIssue> issues) { if (temporal is null) { Add(issues, AstronomyEvidenceValidationCodes.RecordTemporalMissing, "Temporal metadata is required.", "temporalMetadata"); return; } if (temporal.ObservedAtUtc.HasValue && temporal.ObservedAtUtc.Value.Offset != TimeSpan.Zero) Add(issues, AstronomyEvidenceValidationCodes.RecordTemporalInvalid, "Observed time must use UTC.", "temporalMetadata.observedAtUtc"); if (temporal.PublishedAtUtc.HasValue && temporal.PublishedAtUtc.Value.Offset != TimeSpan.Zero) Add(issues, AstronomyEvidenceValidationCodes.RecordTemporalInvalid, "Published time must use UTC.", "temporalMetadata.publishedAtUtc"); if (temporal.RetrievedAtUtc.HasValue && temporal.RetrievedAtUtc.Value.Offset != TimeSpan.Zero) Add(issues, AstronomyEvidenceValidationCodes.RecordTemporalInvalid, "Retrieved time must use UTC.", "temporalMetadata.retrievedAtUtc"); if (temporal.PublishedAtUtc.HasValue && temporal.RetrievedAtUtc.HasValue && temporal.RetrievedAtUtc.Value < temporal.PublishedAtUtc.Value) Add(issues, AstronomyEvidenceValidationCodes.RecordTemporalInvalid, "Retrieved time cannot precede publication time.", "temporalMetadata.retrievedAtUtc"); ValidationSupport.ValidateValidity(temporal.Applicability, issues, AstronomyEvidenceValidationCodes.RecordTemporalInvalid, "temporalMetadata.applicability"); }
    private static void ValidateAttribution(EvidenceAttribution attribution, List<DomainValidationIssue> issues) { if (attribution is null) return; if (attribution.Contributors is null) { Add(issues, AstronomyEvidenceValidationCodes.RecordAttributionInvalid, "Contributor collection is required.", "attribution.contributors"); return; } var values = new List<string>(); for (var i=0;i<attribution.Contributors.Count;i++) { var c=attribution.Contributors[i]; if (string.IsNullOrWhiteSpace(c)) Add(issues, AstronomyEvidenceValidationCodes.RecordAttributionInvalid, "Contributor cannot be blank.", $"attribution.contributors[{i}]"); else values.Add(c); } if (values.Distinct(StringComparer.Ordinal).Count()!=values.Count) Add(issues, AstronomyEvidenceValidationCodes.RecordAttributionInvalid, "Contributors must be unique.", "attribution.contributors"); }
    private static void ValidateExternalIdentifiers(IReadOnlyList<EvidenceExternalIdentifier> ids, List<DomainValidationIssue> issues) { if (ids is null) { Add(issues, AstronomyEvidenceValidationCodes.RecordExternalIdentifierMissing, "External identifier collection is required.", "externalIdentifiers"); return; } var keys=new List<string>(); for (var i=0;i<ids.Count;i++) { var id=ids[i]; if (id is null) { Add(issues, AstronomyEvidenceValidationCodes.RecordExternalIdentifierMissing, "External identifier cannot be null.", $"externalIdentifiers[{i}]"); continue; } ValidateExternalIdentifier(id, issues, $"externalIdentifiers[{i}]", AstronomyEvidenceValidationCodes.RecordExternalIdentifierMissing); if (!string.IsNullOrWhiteSpace(id.Scheme)&&!string.IsNullOrWhiteSpace(id.Value)) keys.Add(id.Scheme.ToLowerInvariant()+"\u001f"+id.Value); } if (keys.Distinct(StringComparer.Ordinal).Count()!=keys.Count) Add(issues, AstronomyEvidenceValidationCodes.RecordDuplicateExternalIdentifier, "External identifiers must be unique by normalized scheme and value.", "externalIdentifiers"); }
    private static void ValidateExternalIdentifier(EvidenceExternalIdentifier id, List<DomainValidationIssue> issues, string path, string code) { if (string.IsNullOrWhiteSpace(id.Scheme)) Add(issues, code, "External identifier scheme is required.", path + ".scheme"); if (string.IsNullOrWhiteSpace(id.Value)) Add(issues, code, "External identifier value is required.", path + ".value"); }
    private static void ValidateTags(IReadOnlyList<KnowledgeTag> tags, List<DomainValidationIssue> issues) { if (tags is null) { Add(issues, AstronomyEvidenceValidationCodes.RecordTagMissing, "Tag collection is required.", "tags"); return; } var values=new List<string>(); for (var i=0;i<tags.Count;i++) { var tag=tags[i]; if (tag is null || string.IsNullOrWhiteSpace(tag.Value)) Add(issues, AstronomyEvidenceValidationCodes.RecordTagMissing, "Tag value is required.", $"tags[{i}]"); else values.Add(tag.Value); } if (values.Distinct(StringComparer.OrdinalIgnoreCase).Count()!=values.Count) Add(issues, AstronomyEvidenceValidationCodes.RecordDuplicateTag, "Tags must be unique by normalized value.", "tags"); }
    private static void ValidateText(string? value, int max, string code, string path, List<DomainValidationIssue> issues) { if (value is null) return; if (value.Length > max || value.Any(char.IsControl)) Add(issues, code, "Text is malformed.", path); }
    private static void Add(List<DomainValidationIssue> issues, string code, string message, string path) => issues.Add(new(code, message, DomainValidationSeverity.Error, path));
}

public sealed class AstronomyKnowledgeStatementEvidenceSetValidator : IAstronomyKnowledgeStatementEvidenceSetValidator
{
    public DomainValidationResult Validate(AstronomyKnowledgeStatementEvidenceSet evidenceSet) { ArgumentNullException.ThrowIfNull(evidenceSet); var issues=new List<DomainValidationIssue>(); if (string.IsNullOrWhiteSpace(evidenceSet.KnowledgeId.Value)) Add(issues,AstronomyEvidenceValidationCodes.SetKnowledgeIdMissing,"Knowledge ID is required.","knowledgeId"); if (evidenceSet.KnowledgeVersion.Revision<1) Add(issues,AstronomyEvidenceValidationCodes.SetKnowledgeVersionInvalid,"Knowledge version must be positive.","knowledgeVersion.revision"); var associations=evidenceSet.Associations; if (associations is null) { Add(issues,AstronomyEvidenceValidationCodes.SetAssociationCollectionMissing,"Association collection is required.","associations"); return DomainValidationResult.From(issues.ToArray()); } var ids=new List<EvidenceId>(); var primary=0; for (var i=0;i<associations.Count;i++) { var a=associations[i]; var path=$"associations[{i}]"; if (a is null) { Add(issues,AstronomyEvidenceValidationCodes.SetAssociationMissing,"Association cannot be null.",path); continue; } if (string.IsNullOrWhiteSpace(a.KnowledgeId.Value)) Add(issues,AstronomyEvidenceValidationCodes.SetKnowledgeIdMissing,"Association knowledge ID is required.",path+".knowledgeId"); if (a.KnowledgeVersion.Revision<1) Add(issues,AstronomyEvidenceValidationCodes.SetKnowledgeVersionInvalid,"Association version must be positive.",path+".knowledgeVersion.revision"); if (string.IsNullOrWhiteSpace(a.EvidenceId.Value)) Add(issues,AstronomyEvidenceValidationCodes.SetEvidenceIdMissing,"Association evidence ID is required.",path+".evidenceId"); else ids.Add(a.EvidenceId); if (!Enum.IsDefined(a.Role)) Add(issues,AstronomyEvidenceValidationCodes.SetRoleUndefined,"Association role is not defined.",path+".role"); if (a.KnowledgeId != evidenceSet.KnowledgeId || a.KnowledgeVersion != evidenceSet.KnowledgeVersion) Add(issues,AstronomyEvidenceValidationCodes.SetAssociationOwnerMismatch,"Association owner must match evidence set owner.",path); if (a.Role == KnowledgeEvidenceRole.Primary) primary++; } if (ids.Distinct().Count()!=ids.Count) Add(issues,AstronomyEvidenceValidationCodes.SetDuplicateEvidence,"Evidence IDs must be unique within a set.","associations"); if (primary>1) Add(issues,AstronomyEvidenceValidationCodes.SetMultiplePrimaryEvidence,"At most one primary evidence association is allowed.","associations"); var ordered=associations.Where(a=>a is not null).OrderBy(a=>a.EvidenceId.Value,StringComparer.Ordinal).ThenBy(a=>a.Role.ToString(),StringComparer.Ordinal).ToArray(); if (!associations.Where(a=>a is not null).SequenceEqual(ordered)) Add(issues,AstronomyEvidenceValidationCodes.SetOrderingInvalid,"Associations must be in canonical order.","associations"); return DomainValidationResult.From(issues.ToArray()); }
    private static void Add(List<DomainValidationIssue> issues, string code, string message, string path) => issues.Add(new(code, message, DomainValidationSeverity.Error, path));
}

public sealed class AstronomyKnowledgeConfidenceAssessmentValidator : IAstronomyKnowledgeConfidenceAssessmentValidator
{
    public DomainValidationResult Validate(AstronomyKnowledgeConfidenceAssessment assessment)
    {
        ArgumentNullException.ThrowIfNull(assessment); var issues=new List<DomainValidationIssue>();
        if (string.IsNullOrWhiteSpace(assessment.Id.Value)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentIdMissing,"Assessment ID is required.","id");
        if (string.IsNullOrWhiteSpace(assessment.KnowledgeId.Value)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentKnowledgeIdMissing,"Knowledge ID is required.","knowledgeId");
        if (assessment.KnowledgeVersion.Revision<1) Add(issues,AstronomyEvidenceValidationCodes.AssessmentKnowledgeVersionInvalid,"Knowledge version must be positive.","knowledgeVersion.revision");
        if (!Enum.IsDefined(assessment.Level)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentLevelUndefined,"Confidence level is not defined.","level");
        if (assessment.Score is { } s && (double.IsNaN(s.Value)||double.IsInfinity(s.Value)||s.Value<0d||s.Value>1d)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentScoreInvalid,"Score must be finite and between 0 and 1.","score");
        if (!Enum.IsDefined(assessment.Method)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentMethodUndefined,"Assessment method is not defined.","method");
        ValidateAssessor(assessment.Assessor, issues); ValidationSupport.ValidateAudit(assessment.Audit, issues, AstronomyEvidenceValidationCodes.AssessmentAuditMissing, AstronomyEvidenceValidationCodes.AssessmentAuditInvalid, "audit"); ValidateEvidenceIds(assessment.EvidenceIds, issues); ValidateFactors(assessment.Factors, issues); if (assessment.Rationale is not null && (assessment.Rationale.Length>AstronomyKnowledgeConfidenceAssessment.MaxRationaleLength || assessment.Rationale.Any(char.IsControl))) Add(issues,AstronomyEvidenceValidationCodes.AssessmentRationaleInvalid,"Rationale is malformed.","rationale"); ValidatePolicy(assessment, issues); return DomainValidationResult.From(issues.ToArray());
    }
    private static void ValidateAssessor(ConfidenceAssessorReference assessor, List<DomainValidationIssue> issues) { if (assessor is null) { Add(issues,AstronomyEvidenceValidationCodes.AssessmentAssessorMissing,"Assessor is required.","assessor"); return; } if (string.IsNullOrWhiteSpace(assessor.AssessorId)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentAssessorInvalid,"Assessor ID is required.","assessor.assessorId"); if (!Enum.IsDefined(assessor.AssessorType)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentAssessorInvalid,"Assessor type is not defined.","assessor.assessorType"); if (string.IsNullOrWhiteSpace(assessor.DisplayName)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentAssessorInvalid,"Assessor display name is required.","assessor.displayName"); }
    private static void ValidateEvidenceIds(IReadOnlyList<EvidenceId> evidenceIds, List<DomainValidationIssue> issues) { if (evidenceIds is null) { Add(issues,AstronomyEvidenceValidationCodes.AssessmentEvidenceCollectionMissing,"Evidence ID collection is required.","evidenceIds"); return; } var ids=new List<EvidenceId>(); for (var i=0;i<evidenceIds.Count;i++) { var id=evidenceIds[i]; if (string.IsNullOrWhiteSpace(id.Value)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentEvidenceIdMissing,"Evidence ID is required.",$"evidenceIds[{i}]"); else ids.Add(id); } if (ids.Distinct().Count()!=ids.Count) Add(issues,AstronomyEvidenceValidationCodes.AssessmentDuplicateEvidence,"Evidence IDs must be unique.","evidenceIds"); var ordered=evidenceIds.OrderBy(id=>id.Value,StringComparer.Ordinal).ToArray(); if (!evidenceIds.SequenceEqual(ordered)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentEvidenceOrderingInvalid,"Evidence IDs must be in canonical order.","evidenceIds"); }
    private static void ValidateFactors(IReadOnlyList<ConfidenceAssessmentFactor> factors, List<DomainValidationIssue> issues) { if (factors is null) { Add(issues,AstronomyEvidenceValidationCodes.AssessmentFactorCollectionMissing,"Factor collection is required.","factors"); return; } var codes=new List<string>(); for (var i=0;i<factors.Count;i++) { var f=factors[i]; if (f is null) { Add(issues,AstronomyEvidenceValidationCodes.AssessmentFactorMissing,"Factor cannot be null.",$"factors[{i}]"); continue; } if (string.IsNullOrWhiteSpace(f.Code)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentFactorInvalid,"Factor code is required.",$"factors[{i}].code"); else codes.Add(f.Code.ToLowerInvariant()); if (!Enum.IsDefined(f.Direction)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentFactorInvalid,"Factor direction is not defined.",$"factors[{i}].direction"); } if (codes.Distinct(StringComparer.Ordinal).Count()!=codes.Count) Add(issues,AstronomyEvidenceValidationCodes.AssessmentDuplicateFactor,"Factor codes must be unique.","factors"); }
    private static void ValidatePolicy(AstronomyKnowledgeConfidenceAssessment a, List<DomainValidationIssue> issues) { if (a.Level == KnowledgeConfidenceLevel.Unknown && a.Score.HasValue) Add(issues,AstronomyEvidenceValidationCodes.AssessmentUnknownLevelHasScore,"Unknown confidence should not carry a numeric score.","score"); if (a.Level != KnowledgeConfidenceLevel.Unknown && Enum.IsDefined(a.Level)) { if (a.EvidenceIds is null || a.EvidenceIds.Count==0) Add(issues,AstronomyEvidenceValidationCodes.AssessmentNonUnknownLevelMissingEvidence,"Non-unknown confidence requires at least one evidence ID.","evidenceIds"); if ((a.Factors is null || a.Factors.Count==0) && string.IsNullOrWhiteSpace(a.Rationale)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentMissingExplanation,"Non-unknown confidence requires rationale or factors.","rationale"); } if (a.Assessor is not null && Enum.IsDefined(a.Method) && Enum.IsDefined(a.Assessor.AssessorType) && !IsCompatible(a.Method, a.Assessor.AssessorType)) Add(issues,AstronomyEvidenceValidationCodes.AssessmentMethodAssessorMismatch,"Assessment method is not compatible with assessor type.","assessor.assessorType"); }
    private static bool IsCompatible(ConfidenceAssessmentMethod m, ConfidenceAssessorType t) => m switch { ConfidenceAssessmentMethod.HumanExpertReview => t==ConfidenceAssessorType.HumanExpert, ConfidenceAssessmentMethod.HumanEditorialReview => t==ConfidenceAssessorType.HumanEditor, ConfidenceAssessmentMethod.RuleBased => t==ConfidenceAssessorType.AutomatedRule, ConfidenceAssessmentMethod.StatisticalAnalysis => t==ConfidenceAssessorType.StatisticalModel, ConfidenceAssessmentMethod.InstrumentDerived => t==ConfidenceAssessorType.InstrumentSystem, ConfidenceAssessmentMethod.Imported => t==ConfidenceAssessorType.ExternalAuthority, ConfidenceAssessmentMethod.Hybrid => t==ConfidenceAssessorType.HybridProcess, ConfidenceAssessmentMethod.SourceConsensus => t is ConfidenceAssessorType.HumanExpert or ConfidenceAssessorType.AutomatedRule or ConfidenceAssessorType.StatisticalModel or ConfidenceAssessorType.HybridProcess, _ => true };
    private static void Add(List<DomainValidationIssue> issues, string code, string message, string path) => issues.Add(new(code, message, DomainValidationSeverity.Error, path));
}

public sealed class AstronomyEvidenceConfidenceConsistencyValidator : IAstronomyEvidenceConfidenceConsistencyValidator
{
    public DomainValidationResult Validate(AstronomyKnowledgeConfidenceAssessment assessment, AstronomyKnowledgeStatementEvidenceSet evidenceSet)
    {
        ArgumentNullException.ThrowIfNull(assessment); ArgumentNullException.ThrowIfNull(evidenceSet); var issues=new List<DomainValidationIssue>();
        if (assessment.KnowledgeId != evidenceSet.KnowledgeId) Add(issues,AstronomyEvidenceValidationCodes.ConsistencyStatementOwnerMismatch,"Assessment knowledge ID must match evidence set owner.","knowledgeId");
        if (assessment.KnowledgeVersion != evidenceSet.KnowledgeVersion) Add(issues,AstronomyEvidenceValidationCodes.ConsistencyStatementOwnerMismatch,"Assessment version must match evidence set owner.","knowledgeVersion");
        var setIds = evidenceSet.Associations?.Where(a=>a is not null).Select(a=>a.EvidenceId).ToArray() ?? [];
        for (var i = 0; i < (assessment.EvidenceIds?.Count ?? 0); i++) { var id = assessment.EvidenceIds![i]; if (!setIds.Contains(id)) Add(issues,AstronomyEvidenceValidationCodes.ConsistencyReferencedEvidenceNotInSet,"Assessment references evidence absent from the evidence set.",$"evidenceIds[{i}]"); }
        if (assessment.Level != KnowledgeConfidenceLevel.Unknown && setIds.Length==0) Add(issues,AstronomyEvidenceValidationCodes.ConsistencyEvidenceSetEmpty,"Non-unknown assessment requires a non-empty evidence set when cross-validated.","evidenceSet.associations");
        var contradicting = evidenceSet.Associations?.Where(a=>a is not null && a.Role==KnowledgeEvidenceRole.Contradicting).Select(a=>a.EvidenceId).ToArray() ?? [];
        if (contradicting.Length>0 && !(assessment.EvidenceIds ?? []).Any(id=>contradicting.Contains(id))) issues.Add(new(AstronomyEvidenceValidationCodes.ConsistencyContradictingEvidenceNotReferenced,"Contradicting evidence exists but is not referenced by the assessment.",DomainValidationSeverity.Warning,"evidenceSet.associations"));
        return DomainValidationResult.From(issues.ToArray());
    }
    private static void Add(List<DomainValidationIssue> issues, string code, string message, string path) => issues.Add(new(code, message, DomainValidationSeverity.Error, path));
}

internal static class ValidationSupport
{
    public static void ValidateAudit(KnowledgeAuditMetadata audit, List<DomainValidationIssue> issues, string missingCode, string invalidCode, string path)
    { if (audit is null) { issues.Add(new(missingCode,"Audit metadata is required.",DomainValidationSeverity.Error,path)); return; } if (audit.CreatedUtc.Offset!=TimeSpan.Zero) issues.Add(new(invalidCode,"Audit creation time must use UTC.",DomainValidationSeverity.Error,path+".createdUtc")); if (audit.UpdatedUtc.HasValue && audit.UpdatedUtc.Value.Offset!=TimeSpan.Zero) issues.Add(new(invalidCode,"Audit updated time must use UTC.",DomainValidationSeverity.Error,path+".updatedUtc")); if (audit.UpdatedUtc.HasValue && audit.UpdatedUtc.Value<audit.CreatedUtc) issues.Add(new(invalidCode,"Audit updated time cannot precede creation time.",DomainValidationSeverity.Error,path+".updatedUtc")); if (audit.UpdatedUtc.HasValue != (audit.UpdatedBy is not null)) issues.Add(new(invalidCode,"Audit updated time and actor must be supplied together.",DomainValidationSeverity.Error,path+".updatedBy")); if (audit.CreatedBy is not null && string.IsNullOrWhiteSpace(audit.CreatedBy)) issues.Add(new(invalidCode,"Audit created actor cannot be blank.",DomainValidationSeverity.Error,path+".createdBy")); if (audit.UpdatedBy is not null && string.IsNullOrWhiteSpace(audit.UpdatedBy)) issues.Add(new(invalidCode,"Audit updated actor cannot be blank.",DomainValidationSeverity.Error,path+".updatedBy")); }
    public static void ValidateValidity(KnowledgeValidityRange validity, List<DomainValidationIssue> issues, string invalidCode, string path)
    { if (validity is null) { issues.Add(new(invalidCode,"Applicability range is required.",DomainValidationSeverity.Error,path)); return; } if (validity.EffectiveFromUtc.HasValue && validity.EffectiveFromUtc.Value.Offset!=TimeSpan.Zero) issues.Add(new(invalidCode,"Applicability start must use UTC.",DomainValidationSeverity.Error,path+".effectiveFromUtc")); if (validity.EffectiveToUtc.HasValue && validity.EffectiveToUtc.Value.Offset!=TimeSpan.Zero) issues.Add(new(invalidCode,"Applicability end must use UTC.",DomainValidationSeverity.Error,path+".effectiveToUtc")); if (validity.EffectiveFromUtc.HasValue && validity.EffectiveToUtc.HasValue && validity.EffectiveToUtc.Value<validity.EffectiveFromUtc.Value) issues.Add(new(invalidCode,"Applicability end cannot precede start.",DomainValidationSeverity.Error,path+".effectiveToUtc")); }
}
