using Astronomy.MediaFactory.Core.KnowledgeFoundation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Integration;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.CrossDomain;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Graph;
namespace Astronomy.MediaFactory.Core.KnowledgeFoundation.Catalog;
public sealed class AstronomyKnowledgeCatalogBuilder:IAstronomyKnowledgeCatalogBuilder
{
 readonly IAstronomyTypedPayloadRegistry payloads; readonly IAstronomyKnowledgeValidationRuleRegistry validation; readonly IAstronomyCrossDomainValidationRuleRegistry cross; readonly IAstronomyKnowledgeGraphValidationRuleRegistry graph;
 public AstronomyKnowledgeCatalogBuilder(IAstronomyTypedPayloadRegistry payloads,IAstronomyKnowledgeValidationRuleRegistry validation,IAstronomyCrossDomainValidationRuleRegistry cross,IAstronomyKnowledgeGraphValidationRuleRegistry graph){this.payloads=payloads??throw new ArgumentNullException(nameof(payloads));this.validation=validation??throw new ArgumentNullException(nameof(validation));this.cross=cross??throw new ArgumentNullException(nameof(cross));this.graph=graph??throw new ArgumentNullException(nameof(graph));}
 public AstronomyKnowledgeCatalogSnapshot Build(){ var e=new List<AstronomyKnowledgeCatalogEntry>(); e.AddRange(Domains()); e.AddRange(Families()); e.AddRange(KnowledgeTypes()); e.AddRange(Rules()); e.AddRange(CrossRules()); e.AddRange(GraphRules()); e.AddRange(Statements()); return new AstronomyKnowledgeCatalogSnapshot(e); }
 static IEnumerable<AstronomyKnowledgeCatalogEntry> Domains(){ yield return Domain(AstronomyKnowledgeDomain.Classification,"classification","Classification","Classification knowledge domain.",100); yield return Domain(AstronomyKnowledgeDomain.Physical,"physical","Physical","Physical knowledge domain.",200); yield return Domain(AstronomyKnowledgeDomain.Orbital,"orbital","Orbital","Orbital knowledge domain.",300); yield return Domain(AstronomyKnowledgeDomain.Positional,"positional","Positional","Positional knowledge domain.",400); yield return Domain(AstronomyKnowledgeDomain.Observational,"observational","Observational","Observational knowledge domain.",500); yield return Domain(AstronomyKnowledgeDomain.Event,"event","Event","Event knowledge domain.",600); yield return Domain(AstronomyKnowledgeDomain.Temporal,"temporal","Temporal","Temporal knowledge domain.",700); yield return Domain(AstronomyKnowledgeDomain.Catalog,"catalog","Catalog","Catalog knowledge domain.",800); yield return Domain(AstronomyKnowledgeDomain.Derived,"derived","Derived","Derived knowledge domain.",900); }
 static AstronomyKnowledgeCatalogEntry Domain(AstronomyKnowledgeDomain d,string c,string n,string desc,int o)=>new(new(AstronomyKnowledgeCatalogEntryKind.Domain,c),c,n,desc,o,d);
 static IEnumerable<AstronomyKnowledgeCatalogEntry> Families(){ yield return Family(AstronomyKnowledgePayloadFamily.EntityClassification,"entity-classification","Entity classification",100); yield return Family(AstronomyKnowledgePayloadFamily.PhysicalProperty,"physical-property","Physical property",200); yield return Family(AstronomyKnowledgePayloadFamily.OrbitalParameter,"orbital-parameter","Orbital parameter",300); yield return Family(AstronomyKnowledgePayloadFamily.SpatialPosition,"spatial-position","Spatial position",400); yield return Family(AstronomyKnowledgePayloadFamily.ObservationCondition,"observation-condition","Observation condition",500); yield return Family(AstronomyKnowledgePayloadFamily.VisibilityWindow,"visibility-window","Visibility window",600); yield return Family(AstronomyKnowledgePayloadFamily.AstronomicalEvent,"astronomical-event","Astronomical event",700); yield return Family(AstronomyKnowledgePayloadFamily.TemporalCycle,"temporal-cycle","Temporal cycle",800); yield return Family(AstronomyKnowledgePayloadFamily.CatalogReference,"catalog-reference","Catalog reference",900); yield return Family(AstronomyKnowledgePayloadFamily.DerivedProperty,"derived-property","Derived property",1000); }
 static AstronomyKnowledgeCatalogEntry Family(AstronomyKnowledgePayloadFamily f,string c,string n,int o)=>new(new(AstronomyKnowledgeCatalogEntryKind.PayloadFamily,c),c,n,$"{n} payload family.",o,family:f);
 IEnumerable<AstronomyKnowledgeCatalogEntry> KnowledgeTypes(){ var seen=new Dictionary<string,AstronomyTypedPayloadDescriptor>(StringComparer.Ordinal); foreach(var d in payloads.Descriptors.OrderBy(x=>x.Discriminator,StringComparer.Ordinal)){ if(!Enum.IsDefined(d.Domain)||!Enum.IsDefined(d.Family)) throw new InvalidOperationException("Undefined typed payload metadata."); if(seen.TryGetValue(d.Discriminator,out var ex)&&(ex.PayloadType!=d.PayloadType||ex.Domain!=d.Domain||ex.Family!=d.Family)) throw new InvalidOperationException("Conflicting knowledge type descriptor."); seen[d.Discriminator]=d; yield return new(new(AstronomyKnowledgeCatalogEntryKind.KnowledgeType,d.Discriminator),d.Discriminator,d.PayloadType.Name,$"Typed knowledge payload {d.Discriminator}.",1000+seen.Count,d.Domain,d.Family,new AstronomyKnowledgeTypeId(d.Discriminator),d.PayloadType,new Dictionary<string,string>{{"payloadType",d.PayloadType.FullName??d.PayloadType.Name}}); }}
 IEnumerable<AstronomyKnowledgeCatalogEntry> Rules()=>validation.Descriptors.Select(d=>Rule(AstronomyKnowledgeCatalogEntryKind.ValidationRule,d.RuleId,d.RuleType,d.Order,d.Domain,d.Family,d.PayloadType));
 IEnumerable<AstronomyKnowledgeCatalogEntry> CrossRules()=>cross.Descriptors.Select(d=>Rule(AstronomyKnowledgeCatalogEntryKind.CrossDomainValidationRule,d.RuleId,d.RuleType,d.Order,null,null,null));
 IEnumerable<AstronomyKnowledgeCatalogEntry> GraphRules()=>graph.Descriptors.Select(d=>Rule(AstronomyKnowledgeCatalogEntryKind.GraphValidationRule,d.RuleId,d.RuleType,d.Order,null,null,null));
 static AstronomyKnowledgeCatalogEntry Rule(AstronomyKnowledgeCatalogEntryKind k,string id,Type rule,int order,AstronomyKnowledgeDomain? d,AstronomyKnowledgePayloadFamily? f,Type? payload)=>new(new(k,id),id,rule.Name,$"Validation rule {id}.",Math.Max(0,order),d,f,runtimeType:rule,metadata:payload is null?null:new Dictionary<string,string>{{"payloadType",payload.FullName??payload.Name}});
 static IEnumerable<AstronomyKnowledgeCatalogEntry> Statements(){ yield return St(KnowledgeStatementKind.Scientific,"scientific","Scientific",100); yield return St(KnowledgeStatementKind.Observation,"observation","Observation",200); yield return St(KnowledgeStatementKind.Educational,"educational","Educational",300); yield return St(KnowledgeStatementKind.Historical,"historical","Historical",400); yield return St(KnowledgeStatementKind.Cultural,"cultural","Cultural",500); yield return St(KnowledgeStatementKind.Safety,"safety","Safety",600); yield return St(KnowledgeStatementKind.Terminology,"terminology","Terminology",700); yield return St(KnowledgeStatementKind.Visual,"visual","Visual",800); }
 static AstronomyKnowledgeCatalogEntry St(KnowledgeStatementKind k,string c,string n,int o)=>new(new(AstronomyKnowledgeCatalogEntryKind.StatementKind,c),c,n,$"{n} statement kind.",o,metadata:new Dictionary<string,string>{{"statementKind",((int)k).ToString(System.Globalization.CultureInfo.InvariantCulture)}});
}
