using System.Collections.ObjectModel;
using System.Security.Cryptography;
using System.Text;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Catalog;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace Astronomy.MediaFactory.Core.KnowledgeFoundation.Query;

public enum AstronomyKnowledgeQueryTarget { CatalogEntry = 1, Statement = 2 }
public enum AstronomyKnowledgeQueryMatchMode { Any = 1, All = 2 }
public enum AstronomyKnowledgeQuerySortDirection { Ascending = 1, Descending = 2 }
public enum AstronomyKnowledgeQueryNullOrder { First = 1, Last = 2 }
public enum AstronomyKnowledgeCatalogSortField { Kind = 1, Order = 2, Code = 3, Id = 4, DisplayName = 5 }
public enum AstronomyKnowledgeStatementSortField { Id = 1, Subject = 2, Kind = 3, Status = 4, Revision = 5, CreatedAt = 6, UpdatedAt = 7 }

public sealed record AstronomyKnowledgeQueryPage
{
    public const int DefaultLimit = 100;
    public const int MaximumLimit = 1000;
    public static AstronomyKnowledgeQueryPage Default { get; } = new();
    public AstronomyKnowledgeQueryPage(int offset = 0, int limit = DefaultLimit)
    { if (offset < 0) throw new ArgumentOutOfRangeException(nameof(offset)); if (limit <= 0 || limit > MaximumLimit) throw new ArgumentOutOfRangeException(nameof(limit)); Offset = offset; Limit = limit; }
    public int Offset { get; }
    public int Limit { get; }
}

public sealed record AstronomyKnowledgeCatalogOrder
{
    public AstronomyKnowledgeCatalogOrder(AstronomyKnowledgeCatalogSortField field, AstronomyKnowledgeQuerySortDirection direction, int priority = 0)
    { if (!Enum.IsDefined(field)) throw new ArgumentOutOfRangeException(nameof(field)); if (!Enum.IsDefined(direction)) throw new ArgumentOutOfRangeException(nameof(direction)); if (priority < 0) throw new ArgumentOutOfRangeException(nameof(priority)); Field = field; Direction = direction; Priority = priority; }
    public AstronomyKnowledgeCatalogSortField Field { get; }
    public AstronomyKnowledgeQuerySortDirection Direction { get; }
    public int Priority { get; }
    public static IReadOnlyList<AstronomyKnowledgeCatalogOrder> Default { get; } = Array.AsReadOnly(new AstronomyKnowledgeCatalogOrder[] { new(AstronomyKnowledgeCatalogSortField.Kind, AstronomyKnowledgeQuerySortDirection.Ascending, 0), new(AstronomyKnowledgeCatalogSortField.Order, AstronomyKnowledgeQuerySortDirection.Ascending, 1), new(AstronomyKnowledgeCatalogSortField.Code, AstronomyKnowledgeQuerySortDirection.Ascending, 2), new(AstronomyKnowledgeCatalogSortField.Id, AstronomyKnowledgeQuerySortDirection.Ascending, 3)});
}
public sealed record AstronomyKnowledgeStatementOrder
{
    public AstronomyKnowledgeStatementOrder(AstronomyKnowledgeStatementSortField field, AstronomyKnowledgeQuerySortDirection direction, int priority = 0)
    { if (!Enum.IsDefined(field)) throw new ArgumentOutOfRangeException(nameof(field)); if (!Enum.IsDefined(direction)) throw new ArgumentOutOfRangeException(nameof(direction)); if (priority < 0) throw new ArgumentOutOfRangeException(nameof(priority)); Field = field; Direction = direction; Priority = priority; }
    public AstronomyKnowledgeStatementSortField Field { get; }
    public AstronomyKnowledgeQuerySortDirection Direction { get; }
    public int Priority { get; }
    public static IReadOnlyList<AstronomyKnowledgeStatementOrder> Default { get; } = Array.AsReadOnly(new AstronomyKnowledgeStatementOrder[] { new(AstronomyKnowledgeStatementSortField.Id, AstronomyKnowledgeQuerySortDirection.Ascending, 0), new(AstronomyKnowledgeStatementSortField.Revision, AstronomyKnowledgeQuerySortDirection.Ascending, 1)});
}

public abstract class AstronomyKnowledgeFilter<T>
{
    protected AstronomyKnowledgeFilter(IEnumerable<T> values, AstronomyKnowledgeQueryMatchMode matchMode, IComparer<T> comparer, IEqualityComparer<T>? equality = null)
    { if (!Enum.IsDefined(matchMode)) throw new ArgumentOutOfRangeException(nameof(matchMode)); ArgumentNullException.ThrowIfNull(values); var arr = values.Select(v => v ?? throw new ArgumentException("Filter values cannot contain null entries.", nameof(values))).Distinct(equality).OrderBy(v => v, comparer).ToArray(); if (arr.Length == 0) throw new ArgumentException("Filter must contain at least one value.", nameof(values)); Values = Array.AsReadOnly(arr); MatchMode = matchMode; }
    public IReadOnlyList<T> Values { get; }
    public AstronomyKnowledgeQueryMatchMode MatchMode { get; }
}
public sealed class AstronomyKnowledgeDomainFilter : AstronomyKnowledgeFilter<AstronomyKnowledgeDomain> { public AstronomyKnowledgeDomainFilter(IEnumerable<AstronomyKnowledgeDomain> values, AstronomyKnowledgeQueryMatchMode matchMode = AstronomyKnowledgeQueryMatchMode.Any) : base(Check(values), matchMode, Comparer<AstronomyKnowledgeDomain>.Create((a,b)=>((int)a).CompareTo((int)b))) { } static IEnumerable<AstronomyKnowledgeDomain> Check(IEnumerable<AstronomyKnowledgeDomain> v)=> v.Select(x=>Enum.IsDefined(x)?x:throw new ArgumentOutOfRangeException(nameof(v))); }
public sealed class AstronomyKnowledgePayloadFamilyFilter : AstronomyKnowledgeFilter<AstronomyKnowledgePayloadFamily> { public AstronomyKnowledgePayloadFamilyFilter(IEnumerable<AstronomyKnowledgePayloadFamily> values, AstronomyKnowledgeQueryMatchMode matchMode = AstronomyKnowledgeQueryMatchMode.Any) : base(Check(values), matchMode, Comparer<AstronomyKnowledgePayloadFamily>.Create((a,b)=>((int)a).CompareTo((int)b))) { } static IEnumerable<AstronomyKnowledgePayloadFamily> Check(IEnumerable<AstronomyKnowledgePayloadFamily> v)=> v.Select(x=>Enum.IsDefined(x)?x:throw new ArgumentOutOfRangeException(nameof(v))); }
public sealed class AstronomyKnowledgeTypeFilter : AstronomyKnowledgeFilter<AstronomyKnowledgeTypeId> { public AstronomyKnowledgeTypeFilter(IEnumerable<AstronomyKnowledgeTypeId> typeIds, AstronomyKnowledgeQueryMatchMode matchMode = AstronomyKnowledgeQueryMatchMode.Any) : base(typeIds.Select(x=>x.IsValid?x:throw new ArgumentException("Knowledge type ID is required.", nameof(typeIds))), matchMode, Comparer<AstronomyKnowledgeTypeId>.Create((a,b)=>StringComparer.Ordinal.Compare(a.Value,b.Value))) { } }
public sealed class AstronomyKnowledgeSubjectFilter : AstronomyKnowledgeFilter<AstronomyEntityReference> { public AstronomyKnowledgeSubjectFilter(IEnumerable<AstronomyEntityReference> subjects, AstronomyKnowledgeQueryMatchMode matchMode = AstronomyKnowledgeQueryMatchMode.Any) : base(subjects, matchMode, Comparer<AstronomyEntityReference>.Create((a,b)=>StringComparer.Ordinal.Compare(a.EntityId,b.EntityId))) { } }
public sealed class AstronomyKnowledgeStatementKindFilter : AstronomyKnowledgeFilter<KnowledgeStatementKind> { public AstronomyKnowledgeStatementKindFilter(IEnumerable<KnowledgeStatementKind> values, AstronomyKnowledgeQueryMatchMode matchMode = AstronomyKnowledgeQueryMatchMode.Any) : base(Check(values), matchMode, Comparer<KnowledgeStatementKind>.Create((a,b)=>((int)a).CompareTo((int)b))) { } static IEnumerable<KnowledgeStatementKind> Check(IEnumerable<KnowledgeStatementKind> v)=> v.Select(x=>Enum.IsDefined(x)?x:throw new ArgumentOutOfRangeException(nameof(v))); }
public sealed class AstronomyKnowledgeStatusFilter : AstronomyKnowledgeFilter<KnowledgeFoundationStatus> { public AstronomyKnowledgeStatusFilter(IEnumerable<KnowledgeFoundationStatus> values, AstronomyKnowledgeQueryMatchMode matchMode = AstronomyKnowledgeQueryMatchMode.Any) : base(Check(values), matchMode, Comparer<KnowledgeFoundationStatus>.Create((a,b)=>((int)a).CompareTo((int)b))) { } static IEnumerable<KnowledgeFoundationStatus> Check(IEnumerable<KnowledgeFoundationStatus> v)=> v.Select(x=>Enum.IsDefined(x)?x:throw new ArgumentOutOfRangeException(nameof(v))); }

public sealed record AstronomyKnowledgeVersionFilter
{ public AstronomyKnowledgeVersionFilter(KnowledgeVersion? exactRevision = null, KnowledgeVersion? minimumRevision = null, KnowledgeVersion? maximumRevision = null) { if (exactRevision.HasValue && (minimumRevision.HasValue || maximumRevision.HasValue)) throw new ArgumentException("Exact revision cannot be combined with revision range.", nameof(exactRevision)); if (minimumRevision.HasValue && maximumRevision.HasValue && minimumRevision.Value > maximumRevision.Value) throw new ArgumentException("Minimum revision cannot exceed maximum revision.", nameof(minimumRevision)); ExactRevision = exactRevision; MinimumRevision = minimumRevision; MaximumRevision = maximumRevision; } public KnowledgeVersion? ExactRevision { get; } public KnowledgeVersion? MinimumRevision { get; } public KnowledgeVersion? MaximumRevision { get; } public bool IsEmpty => ExactRevision is null && MinimumRevision is null && MaximumRevision is null; }
public sealed class AstronomyKnowledgeProvenanceFilter { public AstronomyKnowledgeProvenanceFilter(IEnumerable<string>? createdBy = null) { CreatedBy = CopyStrings(createdBy, nameof(createdBy)); } public IReadOnlyList<string>? CreatedBy { get; } static IReadOnlyList<string>? CopyStrings(IEnumerable<string>? source,string n){ if(source is null) return null; var a=source.Select(s=>string.IsNullOrWhiteSpace(s)?throw new ArgumentException("Provenance actor is required.",n):s.Trim()).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray(); if(a.Length==0) throw new ArgumentException("Filter must contain at least one value.",n); return Array.AsReadOnly(a);} }

public sealed class AstronomyKnowledgeCatalogQuery
{
    public AstronomyKnowledgeCatalogQuery(IEnumerable<AstronomyKnowledgeCatalogEntryId>? entryIds = null, IEnumerable<AstronomyKnowledgeCatalogEntryKind>? entryKinds = null, IEnumerable<string>? codes = null, AstronomyKnowledgeDomainFilter? domains = null, AstronomyKnowledgePayloadFamilyFilter? families = null, AstronomyKnowledgeTypeFilter? knowledgeTypes = null, IEnumerable<AstronomyKnowledgeCatalogOrder>? ordering = null, AstronomyKnowledgeQueryPage? page = null)
    { EntryIds = CopyIds(entryIds); EntryKinds = CopyKinds(entryKinds); Codes = CopyStrings(codes, nameof(codes)); Domains = domains; Families = families; KnowledgeTypes = knowledgeTypes; Ordering = CopyOrders(ordering, AstronomyKnowledgeCatalogOrder.Default); Page = page ?? AstronomyKnowledgeQueryPage.Default; Fingerprint = AstronomyKnowledgeQueryFingerprint.Create(ToTokens()); }
    public IReadOnlyList<AstronomyKnowledgeCatalogEntryId>? EntryIds { get; } public IReadOnlyList<AstronomyKnowledgeCatalogEntryKind>? EntryKinds { get; } public IReadOnlyList<string>? Codes { get; } public AstronomyKnowledgeDomainFilter? Domains { get; } public AstronomyKnowledgePayloadFamilyFilter? Families { get; } public AstronomyKnowledgeTypeFilter? KnowledgeTypes { get; } public IReadOnlyList<AstronomyKnowledgeCatalogOrder> Ordering { get; } public AstronomyKnowledgeQueryPage Page { get; } public AstronomyKnowledgeQueryFingerprint Fingerprint { get; }
    IEnumerable<string> ToTokens(){ yield return "target=catalog"; foreach(var x in EntryIds??[]) yield return "id="+x; foreach(var x in EntryKinds??[]) yield return "kind="+(int)x; foreach(var x in Codes??[]) yield return "code="+x; yield return $"page={Page.Offset}:{Page.Limit}"; foreach(var o in Ordering) yield return $"order={(int)o.Field}:{(int)o.Direction}:{o.Priority}"; }
    static IReadOnlyList<AstronomyKnowledgeCatalogEntryId>? CopyIds(IEnumerable<AstronomyKnowledgeCatalogEntryId>? s)=> s is null?null:Array.AsReadOnly(s.OrderBy(x=>x.Kind).ThenBy(x=>x.Value,StringComparer.Ordinal).Distinct().ToArray() is var a && a.Length>0?a:throw new ArgumentException("Filter must contain at least one value.",nameof(s)));
    static IReadOnlyList<AstronomyKnowledgeCatalogEntryKind>? CopyKinds(IEnumerable<AstronomyKnowledgeCatalogEntryKind>? s)=> s is null?null:Array.AsReadOnly(s.Select(x=>Enum.IsDefined(x)?x:throw new ArgumentOutOfRangeException(nameof(s))).Distinct().OrderBy(x=>(int)x).ToArray() is var a && a.Length>0?a:throw new ArgumentException("Filter must contain at least one value.",nameof(s)));
    static IReadOnlyList<string>? CopyStrings(IEnumerable<string>? s,string n)=> s is null?null:Array.AsReadOnly(s.Select(x=>string.IsNullOrWhiteSpace(x)?throw new ArgumentException("Filter value is required.",n):x.Trim()).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray() is var a && a.Length>0?a:throw new ArgumentException("Filter must contain at least one value.",n));
    static IReadOnlyList<AstronomyKnowledgeCatalogOrder> CopyOrders(IEnumerable<AstronomyKnowledgeCatalogOrder>? s,IReadOnlyList<AstronomyKnowledgeCatalogOrder> d){ var a=(s??d).Select(x=>x??throw new ArgumentException("Ordering cannot contain null entries.",nameof(s))).OrderBy(x=>x.Priority).ThenBy(x=>x.Field).ToArray(); if(a.Length==0) throw new ArgumentException("Ordering must contain at least one value.",nameof(s)); return Array.AsReadOnly(a); }
}
public sealed class AstronomyKnowledgeStatementQuery
{
    public AstronomyKnowledgeStatementQuery(IEnumerable<KnowledgeId>? statementIds = null, AstronomyKnowledgeSubjectFilter? subjects = null, AstronomyKnowledgeDomainFilter? domains = null, AstronomyKnowledgePayloadFamilyFilter? families = null, AstronomyKnowledgeTypeFilter? knowledgeTypes = null, AstronomyKnowledgeStatementKindFilter? statementKinds = null, AstronomyKnowledgeStatusFilter? statuses = null, AstronomyKnowledgeVersionFilter? version = null, AstronomyKnowledgeProvenanceFilter? provenance = null, IEnumerable<AstronomyKnowledgeStatementOrder>? ordering = null, AstronomyKnowledgeQueryPage? page = null)
    { StatementIds=CopyIds(statementIds); Subjects=subjects; Domains=domains; Families=families; KnowledgeTypes=knowledgeTypes; StatementKinds=statementKinds; Statuses=statuses; Version=version; Provenance=provenance; Ordering=CopyOrders(ordering,AstronomyKnowledgeStatementOrder.Default); Page=page??AstronomyKnowledgeQueryPage.Default; Fingerprint=AstronomyKnowledgeQueryFingerprint.Create(ToTokens()); }
    public IReadOnlyList<KnowledgeId>? StatementIds{get;} public AstronomyKnowledgeSubjectFilter? Subjects{get;} public AstronomyKnowledgeDomainFilter? Domains{get;} public AstronomyKnowledgePayloadFamilyFilter? Families{get;} public AstronomyKnowledgeTypeFilter? KnowledgeTypes{get;} public AstronomyKnowledgeStatementKindFilter? StatementKinds{get;} public AstronomyKnowledgeStatusFilter? Statuses{get;} public AstronomyKnowledgeVersionFilter? Version{get;} public AstronomyKnowledgeProvenanceFilter? Provenance{get;} public IReadOnlyList<AstronomyKnowledgeStatementOrder> Ordering{get;} public AstronomyKnowledgeQueryPage Page{get;} public AstronomyKnowledgeQueryFingerprint Fingerprint{get;}
    IEnumerable<string> ToTokens(){ yield return "target=statement"; foreach(var x in StatementIds??[]) yield return "id="+x.Value; yield return $"page={Page.Offset}:{Page.Limit}"; foreach(var o in Ordering) yield return $"order={(int)o.Field}:{(int)o.Direction}:{o.Priority}"; }
    static IReadOnlyList<KnowledgeId>? CopyIds(IEnumerable<KnowledgeId>? s)=> s is null?null:Array.AsReadOnly(s.Where(x=>!string.IsNullOrWhiteSpace(x.Value)).Distinct().OrderBy(x=>x.Value,StringComparer.Ordinal).ToArray() is var a && a.Length>0?a:throw new ArgumentException("Filter must contain at least one value.",nameof(s)));
    static IReadOnlyList<AstronomyKnowledgeStatementOrder> CopyOrders(IEnumerable<AstronomyKnowledgeStatementOrder>? s,IReadOnlyList<AstronomyKnowledgeStatementOrder> d){ var a=(s??d).Select(x=>x??throw new ArgumentException("Ordering cannot contain null entries.",nameof(s))).OrderBy(x=>x.Priority).ThenBy(x=>x.Field).ToArray(); if(a.Length==0) throw new ArgumentException("Ordering must contain at least one value.",nameof(s)); return Array.AsReadOnly(a); }
}

public enum AstronomyKnowledgeQueryValidationCode { None = 0, EmptyFilter = 1, UndefinedValue = 2, InvalidPaging = 3, DuplicateOrderField = 4, DuplicateOrderPriority = 5, ContradictoryFilter = 6, UnsupportedCombination = 7, UnknownKnowledgeType = 8, DomainFamilyConflict = 9, DomainKnowledgeTypeConflict = 10, FamilyKnowledgeTypeConflict = 11 }
public sealed record AstronomyKnowledgeQueryValidationIssue(AstronomyKnowledgeQueryTarget Target, AstronomyKnowledgeQueryValidationCode Code, string Path, string Message);
public sealed class AstronomyKnowledgeQueryValidationResult { public AstronomyKnowledgeQueryValidationResult(IEnumerable<AstronomyKnowledgeQueryValidationIssue> issues){ ArgumentNullException.ThrowIfNull(issues); Issues=Array.AsReadOnly(issues.Select(i=>i??throw new ArgumentException("Issues cannot contain null.",nameof(issues))).OrderBy(i=>i.Path,StringComparer.Ordinal).ThenBy(i=>i.Code).ToArray()); } public IReadOnlyList<AstronomyKnowledgeQueryValidationIssue> Issues{get;} public bool IsValid=>Issues.Count==0; public static AstronomyKnowledgeQueryValidationResult Success{get;}=new([]); }
public interface IAstronomyKnowledgeQueryValidator { AstronomyKnowledgeQueryValidationResult Validate(AstronomyKnowledgeCatalogQuery query); AstronomyKnowledgeQueryValidationResult Validate(AstronomyKnowledgeStatementQuery query); }
public sealed class AstronomyKnowledgeQueryValidator : IAstronomyKnowledgeQueryValidator
{
    readonly IAstronomyKnowledgeCatalog _catalog; public AstronomyKnowledgeQueryValidator(IAstronomyKnowledgeCatalog catalog){_catalog=catalog??throw new ArgumentNullException(nameof(catalog));}
    public AstronomyKnowledgeQueryValidationResult Validate(AstronomyKnowledgeCatalogQuery query){ ArgumentNullException.ThrowIfNull(query); var issues=new List<AstronomyKnowledgeQueryValidationIssue>(); CheckOrder(query.Ordering, AstronomyKnowledgeQueryTarget.CatalogEntry, issues); CheckTypes(query.KnowledgeTypes, query.Domains, query.Families, AstronomyKnowledgeQueryTarget.CatalogEntry, issues); return new(issues); }
    public AstronomyKnowledgeQueryValidationResult Validate(AstronomyKnowledgeStatementQuery query){ ArgumentNullException.ThrowIfNull(query); var issues=new List<AstronomyKnowledgeQueryValidationIssue>(); CheckOrder(query.Ordering, AstronomyKnowledgeQueryTarget.Statement, issues); CheckTypes(query.KnowledgeTypes, query.Domains, query.Families, AstronomyKnowledgeQueryTarget.Statement, issues); if(query.StatementKinds?.MatchMode==AstronomyKnowledgeQueryMatchMode.All && query.StatementKinds.Values.Count>1) issues.Add(new(AstronomyKnowledgeQueryTarget.Statement,AstronomyKnowledgeQueryValidationCode.UnsupportedCombination,"$.statementKinds","All match mode cannot match multiple statement kinds on one statement.")); return new(issues); }
    static void CheckOrder<T>(IReadOnlyList<T> orders,AstronomyKnowledgeQueryTarget target,List<AstronomyKnowledgeQueryValidationIssue> issues) where T:notnull { var props=typeof(T).GetProperties(); var fp=props.First(p=>p.Name=="Field"); var pp=props.First(p=>p.Name=="Priority"); var idx=0; foreach(var g in orders.GroupBy(o=>fp.GetValue(o))) if(g.Count()>1) issues.Add(new(target,AstronomyKnowledgeQueryValidationCode.DuplicateOrderField,$"$.ordering[{idx}]","Duplicate ordering field.")); foreach(var g in orders.GroupBy(o=>pp.GetValue(o))) if(g.Count()>1) issues.Add(new(target,AstronomyKnowledgeQueryValidationCode.DuplicateOrderPriority,$"$.ordering[{idx}]","Duplicate ordering priority.")); }
    void CheckTypes(AstronomyKnowledgeTypeFilter? types,AstronomyKnowledgeDomainFilter? domains,AstronomyKnowledgePayloadFamilyFilter? families,AstronomyKnowledgeQueryTarget target,List<AstronomyKnowledgeQueryValidationIssue> issues){ if(types is null) return; var known=_catalog.Snapshot.KnowledgeTypes.ToDictionary<AstronomyKnowledgeCatalogEntry, string>(e => e.KnowledgeTypeId!.Value, StringComparer.Ordinal); foreach(var t in types.Values){ if(!known.TryGetValue(t.Value,out var e)){issues.Add(new(target,AstronomyKnowledgeQueryValidationCode.UnknownKnowledgeType,"$.knowledgeTypes",$"Unknown knowledge type '{t.Value}'.")); continue;} if(domains is not null && e.Domain is { } d && !domains.Values.Contains(d)) issues.Add(new(target,AstronomyKnowledgeQueryValidationCode.DomainKnowledgeTypeConflict,"$.knowledgeTypes",$"Knowledge type '{t.Value}' does not match the domain filter.")); if(families is not null && e.Family is { } f && !families.Values.Contains(f)) issues.Add(new(target,AstronomyKnowledgeQueryValidationCode.FamilyKnowledgeTypeConflict,"$.knowledgeTypes",$"Knowledge type '{t.Value}' does not match the payload-family filter.")); } }
}
public readonly record struct AstronomyKnowledgeQueryFingerprint { public AstronomyKnowledgeQueryFingerprint(string value){ if(string.IsNullOrWhiteSpace(value)) throw new ArgumentException("Fingerprint value is required.",nameof(value)); Value=value; } public string Value{get;} public static AstronomyKnowledgeQueryFingerprint Create(IEnumerable<string> tokens){ var canonical=string.Join("\n",tokens); var hash=SHA256.HashData(Encoding.UTF8.GetBytes(canonical)); return new(Convert.ToHexString(hash).ToLowerInvariant()); } public override string ToString()=>Value; }
public static class AstronomyKnowledgeQueryRegistrationExtensions { public static IServiceCollection AddAstronomyKnowledgeQueryModel(this IServiceCollection services){ ArgumentNullException.ThrowIfNull(services); services.AddAstronomyKnowledgeCatalog(); services.TryAddSingleton<IAstronomyKnowledgeQueryValidator,AstronomyKnowledgeQueryValidator>(); return services; } }
