using System.Collections.Immutable;
using Astronomy.MediaFactory.Core.ExecutionContracts;
using Astronomy.MediaFactory.Core.ExecutionValidation;
using Xunit;

namespace Astronomy.MediaFactory.Tests.ExecutionValidation;

public sealed class ExecutionValidationFrameworkTests
{
    [Fact] public void Context_rejects_required_empty_identities() { var t = DateTimeOffset.Parse("2026-01-01T00:00:00Z"); Assert.Throws<ArgumentException>(() => new FamilyExecutionContext(" ", "d", "f", "v", t)); Assert.Throws<ArgumentException>(() => new FamilyExecutionContext("e", " ", "f", "v", t)); Assert.Throws<ArgumentException>(() => new FamilyExecutionContext("e", "d", " ", "v", t)); Assert.Throws<ArgumentException>(() => new FamilyExecutionContext("e", "d", "f", " ", t)); }
    [Fact] public void Context_normalizes_defaults_and_preserves_explicit_presence() { var c = Ctx(); Assert.Empty(c.InputValues); Assert.Empty(c.SemanticValues); Assert.Empty(c.ProjectionValues); Assert.Empty(c.ArtifactValues); Assert.Empty(c.ValidationRuleValues); var zero = new ExecutionValue("zero", 0, true); var falsy = new ExecutionValue("false", false, true); var missing = new ExecutionValue("missing", null, false); Assert.True(zero.IsPresent); Assert.True(falsy.IsPresent); Assert.False(missing.IsPresent); }
    [Fact] public void Context_rejects_duplicate_case_insensitive_keys() { var b = ImmutableDictionary.CreateBuilder<string, ExecutionValue>(); b.Add("x", new ExecutionValue("x", 1, true)); b.Add("X", new ExecutionValue("X", 2, true)); Assert.Throws<ArgumentException>(() => Ctx(inputs: b.ToImmutable())); }
    [Fact] public void Required_input_present_and_missing_are_structured() { var contract = Contract(inputs: ImmutableArray.Create(new FamilyInputRequirement("r1","topic"), new FamilyInputRequirement("r2","region"))); var req = Req(contract, Ctx(inputs: D(new ExecutionValue("topic","sky",true))), FamilyValidationBoundary.PreExecution); var ev = new InputRequirementValidator().Validate(req); Assert.Contains(ev, e => e.RequirementId == "r1" && e.Outcome == ExecutionRequirementOutcome.Satisfied); Assert.Contains(ev, e => e.RequirementId == "r2" && e.IsBlocking && e.Issues.Single().IssueCode == ExecutionValidationIssueCode.RequiredInputMissing); }
    [Fact] public void Optional_input_excluded_unless_requested() { var contract = Contract(inputs: ImmutableArray.Create(new FamilyInputRequirement("r","x", Level: FamilyRequirementLevel.Optional))); Assert.Empty(new InputRequirementValidator().Validate(Req(contract, Ctx(), FamilyValidationBoundary.PreExecution))); var ev = new InputRequirementValidator().Validate(Req(contract, Ctx(), FamilyValidationBoundary.PreExecution, includeOptional:true)).Single(); Assert.False(ev.IsBlocking); Assert.Equal(ExecutionRequirementOutcome.Missing, ev.Outcome); }
    [Fact] public void Conditional_input_uses_context_metadata() { var reqr = new FamilyInputRequirement("r","x", Level: FamilyRequirementLevel.Conditional, ConditionKey:"enabled"); var contract = Contract(inputs: ImmutableArray.Create(reqr)); var falseCtx = Ctx(meta: ImmutableDictionary<string,string>.Empty.Add("condition:enabled","false")); Assert.Equal(ExecutionRequirementOutcome.ConditionalNotApplicable, new InputRequirementValidator().Validate(Req(contract, falseCtx, FamilyValidationBoundary.PreExecution)).Single().Outcome); Assert.Equal(ExecutionRequirementOutcome.NotEvaluated, new InputRequirementValidator().Validate(Req(contract, Ctx(), FamilyValidationBoundary.PreExecution)).Single().Outcome); var trueCtx = Ctx(meta: ImmutableDictionary<string,string>.Empty.Add("condition:enabled","true")); Assert.True(new InputRequirementValidator().Validate(Req(contract, trueCtx, FamilyValidationBoundary.PreExecution)).Single().IsBlocking); }
    [Fact] public void Semantic_and_projection_validators_use_neutral_keys() { var contract = Contract(semantic: ImmutableArray.Create(new FamilySemanticRequirement("s","cap")), projections: ImmutableArray.Create(new FamilyProjectionRequirement("p","cap","fact"))); Assert.Equal(ExecutionRequirementOutcome.Satisfied, new SemanticRequirementValidator().Validate(Req(contract, Ctx(semantic: D(new ExecutionValue("cap",1,true, Evidence: ImmutableArray.Create("e")))), FamilyValidationBoundary.SemanticResolution)).Single().Outcome); Assert.True(new ProjectionRequirementValidator().Validate(Req(contract, Ctx(), FamilyValidationBoundary.Projection)).Single().IsBlocking); }
    [Fact] public void Artifact_validator_checks_cardinality_and_empty_without_io() { var contract = Contract(artifacts: ImmutableArray.Create(new FamilyPhaseArtifactRequirement("a","phase","art","*.txt"))); Assert.Equal(ExecutionRequirementOutcome.Satisfied, new ArtifactRequirementValidator().Validate(Req(contract, Ctx(artifacts: A(new ExecutionArtifactValue("art", true, true, 1))), FamilyValidationBoundary.ArtifactGeneration)).Single().Outcome); Assert.Equal(ExecutionValidationIssueCode.ArtifactCardinalityInvalid, new ArtifactRequirementValidator().Validate(Req(contract, Ctx(artifacts: A(new ExecutionArtifactValue("art", true, true, 2))), FamilyValidationBoundary.ArtifactGeneration)).Single().Issues.Single().IssueCode); Assert.Equal(ExecutionValidationIssueCode.ArtifactEmpty, new ArtifactRequirementValidator().Validate(Req(contract, Ctx(artifacts: A(new ExecutionArtifactValue("art", true, false, 1))), FamilyValidationBoundary.ArtifactGeneration)).Single().Issues.Single().IssueCode); }
    [Fact] public void Rule_validator_uses_supplied_observations_only() { var contract = Contract(rules: ImmutableArray.Create(new FamilyValidationRequirement("vr","rule",FamilyValidationBoundary.PostExecution,FamilyValidationSeverity.Warning))); var result = new ExecutionValidationResult("e","d","f","v",FamilyValidationBoundary.PostExecution,new ContractValidationRuleValidator().Validate(Req(contract, Ctx(rules: R(new ExecutionRuleValue("rule", false, "bad", "good", "failed", ImmutableArray.Create("ev")))), FamilyValidationBoundary.PostExecution)), DateTimeOffset.UnixEpoch, DateTimeOffset.UnixEpoch); Assert.Equal(ExecutionValidationStatus.ValidWithWarnings, result.Status); Assert.Equal("ev", result.Issues.Single().Evidence.Single()); Assert.Equal(ExecutionRequirementOutcome.NotEvaluated, new ContractValidationRuleValidator().Validate(Req(contract, Ctx(), FamilyValidationBoundary.PostExecution)).Single().Outcome); }
    [Fact] public void Pipeline_contract_mismatch_empty_validators_duplicate_ids_and_factory() { var contract = Contract(inputs: ImmutableArray.Create(new FamilyInputRequirement("r","x"))); var domain = Domain(contract); var pipeline = new ExecutionValidationPipeline(new[]{new InputRequirementValidator()}, new FixedClock()); var result = pipeline.Validate(new ExecutionValidationRequest(domain, contract, Ctx(family:"other"), FamilyValidationBoundary.PreExecution)); Assert.Contains(result.Issues, i => i.IssueCode == ExecutionValidationIssueCode.ContractMismatch); Assert.Equal(ExecutionValidationStatus.Invalid, result.Status); Assert.Throws<ArgumentException>(() => new ExecutionValidationPipeline(new IExecutionRequirementValidator[]{new InputRequirementValidator(), new InputRequirementValidator()})); Assert.Contains(new ExecutionValidationPipeline(Array.Empty<IExecutionRequirementValidator>(), new FixedClock()).Validate(Req(contract, Ctx(), FamilyValidationBoundary.PreExecution)).Issues, i => i.IssueCode == ExecutionValidationIssueCode.UnsupportedBoundary); Assert.NotNull(ExecutionValidationPipelineFactory.CreateDefault(new FixedClock())); }
    [Fact] public void Pipeline_is_deterministic_and_boundary_filtered() { var contract = Contract(inputs: ImmutableArray.Create(new FamilyInputRequirement("b","b"), new FamilyInputRequirement("a","a")), semantic: ImmutableArray.Create(new FamilySemanticRequirement("s","cap"))); var p = ExecutionValidationPipelineFactory.CreateDefault(new FixedClock()); var r1 = p.Validate(Req(contract, Ctx(), FamilyValidationBoundary.PreExecution)); var r2 = p.Validate(Req(contract, Ctx(), FamilyValidationBoundary.PreExecution)); Assert.Equal(r1.Issues.Select(i=>i.RequirementId), r2.Issues.Select(i=>i.RequirementId)); Assert.Equal(new[]{"a","b"}, r1.Evaluations.Select(e=>e.RequirementId)); Assert.DoesNotContain(r1.ValidatorIds, id => id.Contains("semantic")); }

    static FamilyExecutionContext Ctx(string family="f", ImmutableDictionary<string,ExecutionValue>? inputs=null, ImmutableDictionary<string,ExecutionValue>? semantic=null, ImmutableDictionary<string,ExecutionValue>? projections=null, ImmutableDictionary<string,ExecutionArtifactValue>? artifacts=null, ImmutableDictionary<string,ExecutionRuleValue>? rules=null, ImmutableDictionary<string,string>? meta=null) => new("e","d",family,"v",DateTimeOffset.Parse("2026-01-01T00:00:00Z"), InputValues:inputs, SemanticValues:semantic, ProjectionValues:projections, ArtifactValues:artifacts, ValidationRuleValues:rules, Metadata:meta);
    static ImmutableDictionary<string,ExecutionValue> D(params ExecutionValue[] v) => v.ToImmutableDictionary(x=>x.Key, StringComparer.OrdinalIgnoreCase);
    static ImmutableDictionary<string,ExecutionArtifactValue> A(params ExecutionArtifactValue[] v) => v.ToImmutableDictionary(x=>x.ArtifactId, StringComparer.OrdinalIgnoreCase);
    static ImmutableDictionary<string,ExecutionRuleValue> R(params ExecutionRuleValue[] v) => v.ToImmutableDictionary(x=>x.RuleId, StringComparer.OrdinalIgnoreCase);
    static FamilyExecutionContract Contract(ImmutableArray<FamilyInputRequirement> inputs=default, ImmutableArray<FamilySemanticRequirement> semantic=default, ImmutableArray<FamilyProjectionRequirement> projections=default, ImmutableArray<FamilyPhaseArtifactRequirement> artifacts=default, ImmutableArray<FamilyValidationRequirement> rules=default) => new("f","v","Family", InputRequirements:inputs, SemanticRequirements:semantic, ProjectionRequirements:projections, ArtifactRequirements:artifacts, ValidationRequirements:rules);
    static DomainExecutionContract Domain(FamilyExecutionContract c) => new("d","dv","Domain", Families: ImmutableArray.Create(c));
    static ExecutionValidationRequest Req(FamilyExecutionContract c, FamilyExecutionContext ctx, FamilyValidationBoundary b, bool includeOptional=false) => new(Domain(c), c, ctx, b, includeOptional, true, DateTimeOffset.UnixEpoch);
    sealed class FixedClock : IExecutionClock { public DateTimeOffset UtcNow => DateTimeOffset.UnixEpoch; }
}
