using Xunit;
namespace Astronomy.MediaFactory.Tests.KnowledgeFoundation.Query;
public sealed class AstronomyKnowledgeQueryArchitectureTests
{
    static readonly string Root = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"../../../../.."));
    static string Prod => Path.Combine(Root,"src/Astronomy.MediaFactory.Core/KnowledgeFoundation/Query");
    static string Tests => Path.Combine(Root,"tests/Astronomy.MediaFactory.Tests/KnowledgeFoundation/Query");
    [Fact] public void Directories_and_required_files_exist_and_are_non_empty(){Assert.True(Directory.Exists(Prod)); foreach(var name in RequiredProductionFiles()) { var p=Path.Combine(Prod,name); Assert.True(File.Exists(p),p); Assert.True(new FileInfo(p).Length>0,p);} foreach(var name in RequiredTestFiles()) Assert.True(File.Exists(Path.Combine(Tests,name)),name);}
    [Fact] public void Production_query_files_avoid_forbidden_dependencies_and_execution(){var text=string.Join('\n',Directory.GetFiles(Prod,"*.cs").Select(File.ReadAllText)); string[] forbidden=["DbContext","DbSet","IQueryable","Expression<","Func<","Predicate<","Repository","Controller","HttpClient","BackgroundService","IHostedService","DateTime.Now","DateTime.UtcNow","DateTimeOffset.Now","DateTimeOffset.UtcNow","Activator.CreateInstance","Assembly.GetTypes","AppDomain.CurrentDomain","BuildServiceProvider","SaveChanges","JsonSerializer","Newtonsoft","ExecuteAsync","QueryAsync","SearchAsync","Compile(","DynamicInvoke","InferKnowledge","GenerateKnowledge","PredictEvent","Ephemeris","IServiceProvider"]; foreach(var f in forbidden) Assert.DoesNotContain(f,text,StringComparison.Ordinal); Assert.DoesNotContain("string field",text,StringComparison.OrdinalIgnoreCase);}
    [Fact] public void No_reverse_dependency_from_catalog_or_typed_domains_into_query(){var files=Directory.GetFiles(Path.Combine(Root,"src/Astronomy.MediaFactory.Core/KnowledgeFoundation"),"*.cs",SearchOption.AllDirectories).Where(f=>!f.Contains(Path.DirectorySeparatorChar+"Query"+Path.DirectorySeparatorChar));foreach(var f in files) Assert.DoesNotContain("KnowledgeFoundation.Query",File.ReadAllText(f),StringComparison.Ordinal);}
    static string[] RequiredProductionFiles()=>["AstronomyKnowledgeQueryTarget.cs","AstronomyKnowledgeQueryMatchMode.cs","AstronomyKnowledgeQuerySortDirection.cs","AstronomyKnowledgeQueryNullOrder.cs","AstronomyKnowledgeQueryPage.cs","AstronomyKnowledgeQueryOrder.cs","AstronomyKnowledgeCatalogQuery.cs","AstronomyKnowledgeStatementQuery.cs","AstronomyKnowledgeDomainFilter.cs","AstronomyKnowledgePayloadFamilyFilter.cs","AstronomyKnowledgeTypeFilter.cs","AstronomyKnowledgeSubjectFilter.cs","AstronomyKnowledgeStatementKindFilter.cs","AstronomyKnowledgeStatusFilter.cs","AstronomyKnowledgeVersionFilter.cs","AstronomyKnowledgeProvenanceFilter.cs","AstronomyKnowledgeQueryValidationCode.cs","AstronomyKnowledgeQueryValidationIssue.cs","AstronomyKnowledgeQueryValidationResult.cs","IAstronomyKnowledgeQueryValidator.cs","AstronomyKnowledgeQueryValidator.cs","AstronomyKnowledgeQueryFingerprint.cs","AstronomyKnowledgeQueryRegistrationExtensions.cs"];
    static string[] RequiredTestFiles()=>["KnowledgeQueryFixture.cs","AstronomyKnowledgeQueryPageTests.cs","AstronomyKnowledgeCatalogOrderTests.cs","AstronomyKnowledgeStatementOrderTests.cs","AstronomyKnowledgeDomainFilterTests.cs","AstronomyKnowledgePayloadFamilyFilterTests.cs","AstronomyKnowledgeTypeFilterTests.cs","AstronomyKnowledgeSubjectFilterTests.cs","AstronomyKnowledgeStatementKindFilterTests.cs","AstronomyKnowledgeStatusFilterTests.cs","AstronomyKnowledgeVersionFilterTests.cs","AstronomyKnowledgeProvenanceFilterTests.cs","AstronomyKnowledgeCatalogQueryTests.cs","AstronomyKnowledgeStatementQueryTests.cs","AstronomyKnowledgeQueryValidatorTests.cs","AstronomyKnowledgeQueryRegistrationTests.cs","AstronomyKnowledgeQueryIntegrationTests.cs","AstronomyKnowledgeQueryArchitectureTests.cs"];
}
