// <auto-generated />
using System;
using Astronomy.MediaFactory.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Astronomy.MediaFactory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MediaFactoryDbContext))]
    partial class MediaFactoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Astronomy.MediaFactory.Analytics.AudienceAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageWatchDuration")
                        .HasColumnType("double precision");

                    b.Property<long>("Comments")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Ctr")
                        .HasColumnType("double precision");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Shares")
                        .HasColumnType("bigint");

                    b.Property<long>("SubscribersGained")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.Property<double>("WatchTimeMinutes")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("audience_analytics", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Analytics.DailyPerformanceSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageWatchDuration")
                        .HasColumnType("double precision");

                    b.Property<long>("Comments")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Ctr")
                        .HasColumnType("double precision");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Shares")
                        .HasColumnType("bigint");

                    b.Property<long>("SubscribersGained")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("SummaryDate")
                        .HasColumnType("date")
                        .HasColumnName("summaryDate");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.Property<double>("WatchTimeMinutes")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("daily_performance_summary", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Analytics.HookPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageWatchDuration")
                        .HasColumnType("double precision");

                    b.Property<long>("Comments")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Ctr")
                        .HasColumnType("double precision");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Shares")
                        .HasColumnType("bigint");

                    b.Property<long>("SubscribersGained")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.Property<double>("WatchTimeMinutes")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("hook_performance", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Analytics.PlatformPostAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageWatchDuration")
                        .HasColumnType("double precision");

                    b.Property<long>("Comments")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Ctr")
                        .HasColumnType("double precision");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Shares")
                        .HasColumnType("bigint");

                    b.Property<long>("SubscribersGained")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.Property<double>("WatchTimeMinutes")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("platform_post_analytics", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Analytics.PlatformVideoAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageWatchDuration")
                        .HasColumnType("double precision");

                    b.Property<long>("Comments")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Ctr")
                        .HasColumnType("double precision");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Shares")
                        .HasColumnType("bigint");

                    b.Property<long>("SubscribersGained")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.Property<double>("WatchTimeMinutes")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("platform_video_analytics", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Analytics.ThumbnailPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageWatchDuration")
                        .HasColumnType("double precision");

                    b.Property<long>("Comments")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Ctr")
                        .HasColumnType("double precision");

                    b.Property<long>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Shares")
                        .HasColumnType("bigint");

                    b.Property<long>("SubscribersGained")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.Property<double>("WatchTimeMinutes")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("thumbnail_performance", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.AlertNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdUtc");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("eventId");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("regionId");

                    b.Property<DateTimeOffset>("ScheduledUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduledUtc");

                    b.Property<DateTimeOffset?>("SentUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sentUtc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriberId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedUtc");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ScheduledUtc");

                    b.HasIndex("SubscriberId", "EventId", "RegionId")
                        .IsUnique();

                    b.ToTable("alert_notifications", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.AlertPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdUtc");

                    b.Property<bool>("DailySkyGuideReminderEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("dailySkyGuideReminderEnabled");

                    b.PrimitiveCollection<string[]>("EventTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("eventTypes");

                    b.Property<double>("MinimumEventScore")
                        .HasColumnType("double precision")
                        .HasColumnName("minimumEventScore");

                    b.Property<string>("PreferredAlertTimeLocal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferredAlertTimeLocal");

                    b.Property<bool>("SpecialEventAlertsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("specialEventAlertsEnabled");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscriberId");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedUtc");

                    b.HasKey("Id");

                    b.HasIndex("SubscriberId")
                        .IsUnique();

                    b.ToTable("alert_preferences", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.AlertSubscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdUtc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PreferredChannel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preferredChannel");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("regionId");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedUtc");

                    b.HasKey("Id");

                    b.HasIndex("Email", "RegionId", "IsActive");

                    b.ToTable("alert_subscribers", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.AstronomyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AudienceInterestScore")
                        .HasColumnType("double precision")
                        .HasColumnName("audienceInterestScore");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision")
                        .HasColumnName("confidenceScore");

                    b.Property<double>("ContentOpportunityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("contentOpportunityScore");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdUtc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("endUtc");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eventId");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eventType");

                    b.Property<bool>("GlobalVisibility")
                        .HasColumnType("boolean")
                        .HasColumnName("globalVisibility");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .HasColumnType("text")
                        .HasColumnName("locationName");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("PeakUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("peakUtc");

                    b.Property<double>("RarityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("rarityScore");

                    b.Property<string>("RecommendedContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommendedContentType");

                    b.Property<string>("RegionId")
                        .HasColumnType("text")
                        .HasColumnName("regionId");

                    b.Property<string>("RelatedObjects")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relatedObjects");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startUtc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("targetDate");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<double>("TimingUrgencyScore")
                        .HasColumnType("double precision")
                        .HasColumnName("timingUrgencyScore");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedUtc");

                    b.Property<string>("VisibilityRegions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visibilityRegions");

                    b.Property<double>("VisibilityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("visibilityScore");

                    b.HasKey("Id");

                    b.HasIndex("ContentOpportunityScore");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("EventType");

                    b.HasIndex("RegionId");

                    b.HasIndex("TargetDate");

                    b.ToTable("astronomy_events", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.AstronomyEventGenerationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AstronomyEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("astronomyEventId");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contentType");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdUtc");

                    b.Property<string>("GenerationMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generationMode");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipelineRunId");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("regionId");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("targetDate");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AstronomyEventId", "RegionId", "TargetDate", "ContentType")
                        .IsUnique();

                    b.ToTable("astronomy_event_generation_history", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.ContentExperiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExperimentType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SelectedVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoId", "ExperimentType", "Status");

                    b.ToTable("content_experiments", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.ContentVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContentExperimentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Ctr")
                        .HasColumnType("double precision");

                    b.Property<double>("EngagementScore")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VariantType")
                        .HasColumnType("integer");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContentExperimentId", "IsWinner");

                    b.ToTable("content_variants", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.GeneratedScript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlternateTitlesCsv")
                        .HasColumnType("text");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstimatedDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("HookLine")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("OptimizedDescription")
                        .HasColumnType("text");

                    b.Property<string>("OptimizedHashtagsCsv")
                        .HasColumnType("text");

                    b.Property<string>("OptimizedTagsCsv")
                        .HasColumnType("text");

                    b.Property<string>("OptimizedTitle")
                        .HasColumnType("text");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromptFeedbackContextJson")
                        .HasColumnType("text");

                    b.Property<string>("ScriptBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("ScriptDate")
                        .HasColumnType("date");

                    b.Property<string>("TagsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailTextSuggestionsCsv")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("generated_scripts", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.HookOptimizationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ClarityScore")
                        .HasColumnType("double precision");

                    b.Property<double>("ClickProbability")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CuriosityScore")
                        .HasColumnType("double precision");

                    b.Property<double>("EmotionalImpactScore")
                        .HasColumnType("double precision");

                    b.Property<double>("FinalScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Hook")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecommendationReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("hook_optimization_results", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlobPath")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicUrl")
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.MonetizationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffiliateLinksJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkTypesCsv")
                        .HasColumnType("text");

                    b.Property<string>("PinnedCommentText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("uuid");

                    b.Property<string>("YouTubeVideoId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VideoId", "CreatedAt");

                    b.ToTable("monetization_records", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.PipelineJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsStale")
                        .HasColumnType("boolean");

                    b.Property<int>("JobType")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentPipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PublishToYouTube")
                        .HasColumnType("boolean");

                    b.Property<string>("RecoveryNotes")
                        .HasColumnType("text");

                    b.Property<string>("RegionId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("RunDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StaleDetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseTopicPlanner")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Status", "IsStale", "ScheduledAt");

                    b.ToTable("pipeline_jobs", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.PipelineRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionType")
                        .HasColumnType("text")
                        .HasColumnName("decisionType");

                    b.Property<string>("EventDescription")
                        .HasColumnType("text")
                        .HasColumnName("eventDescription");

                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("eventId");

                    b.Property<string>("EventTitle")
                        .HasColumnType("text")
                        .HasColumnName("eventTitle");

                    b.Property<string>("EventType")
                        .HasColumnType("text")
                        .HasColumnName("eventType");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InjectedIntoDailyGuide")
                        .HasColumnType("boolean")
                        .HasColumnName("injectedIntoDailyGuide");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutputFolder")
                        .HasColumnType("text")
                        .HasColumnName("outputFolder");

                    b.Property<bool>("PublishToYouTube")
                        .HasColumnType("boolean");

                    b.Property<string>("RegionId")
                        .HasColumnType("text")
                        .HasColumnName("regionId");

                    b.Property<bool>("ResumeSupported")
                        .HasColumnType("boolean")
                        .HasColumnName("resumeSupported");

                    b.Property<DateOnly>("RunDate")
                        .HasColumnType("date");

                    b.Property<bool>("SpecialEventGuideGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("specialEventGuideGenerated");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseTopicPlanner")
                        .HasColumnType("boolean");

                    b.Property<string>("YouTubeVideoId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "RunDate", "RegionId");

                    b.HasIndex("RegionId", "RunDate", "ContentType");

                    b.ToTable("pipeline_runs", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.PipelineStageExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiagnosticPath")
                        .HasColumnType("text");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("OutputPath")
                        .HasColumnType("text");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId", "StageName", "CreatedUtc");

                    b.ToTable("pipeline_stage_executions", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.PlatformContentAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("AffiliateBlockEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("affiliateBlockEnabled");

                    b.Property<double?>("AverageViewDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CollectedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Comments")
                        .HasColumnType("bigint");

                    b.Property<int?>("ContentCategory")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CtaVariant")
                        .HasColumnType("text")
                        .HasColumnName("ctaVariant");

                    b.Property<double?>("Ctr")
                        .HasColumnType("double precision");

                    b.Property<string>("DecisionType")
                        .HasColumnType("text")
                        .HasColumnName("decisionType");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<double?>("EngagementRate")
                        .HasColumnType("double precision");

                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("eventId");

                    b.Property<string>("EventTitle")
                        .HasColumnType("text")
                        .HasColumnName("eventTitle");

                    b.Property<string>("EventType")
                        .HasColumnType("text")
                        .HasColumnName("eventType");

                    b.Property<string>("Hashtags")
                        .HasColumnType("text");

                    b.Property<long?>("Impressions")
                        .HasColumnType("bigint");

                    b.Property<bool?>("InjectedIntoDailyGuide")
                        .HasColumnType("boolean")
                        .HasColumnName("injectedIntoDailyGuide");

                    b.Property<bool>("IsAnalyticsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<long?>("Likes")
                        .HasColumnType("bigint");

                    b.Property<string>("LocationName")
                        .HasColumnType("text");

                    b.Property<double?>("PerformanceScore")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformMediaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Reach")
                        .HasColumnType("bigint");

                    b.Property<string>("RegionId")
                        .HasColumnType("text")
                        .HasColumnName("regionId");

                    b.Property<long?>("Shares")
                        .HasColumnType("bigint");

                    b.Property<bool?>("SpecialEventGuideGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("specialEventGuideGenerated");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Views")
                        .HasColumnType("bigint");

                    b.Property<double?>("WatchTimeMinutes")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Language");

                    b.HasIndex("PipelineRunId");

                    b.HasIndex("Platform");

                    b.HasIndex("PublishedUtc");

                    b.HasIndex("RegionId");

                    b.HasIndex("Platform", "PlatformContentType", "PlatformMediaId", "CollectedUtc")
                        .IsUnique();

                    b.ToTable("platform_content_analytics", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.PlatformPublicationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExternalPostId")
                        .HasColumnType("text");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("ParentShortVideoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "ExternalPostId")
                        .IsUnique();

                    b.HasIndex("ParentShortVideoId", "Platform", "PublishedAt");

                    b.ToTable("platform_publication_records", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.PublishedVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlobUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CtaExperimentId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<string>("EventTitle")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<string>("OptimizedDescription")
                        .HasColumnType("text");

                    b.Property<string>("OptimizedTagsCsv")
                        .HasColumnType("text");

                    b.Property<string>("OptimizedTitle")
                        .HasColumnType("text");

                    b.Property<Guid?>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SelectedCtaVariantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SelectedThumbnailVariantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SelectedTitleVariantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ThumbnailExperimentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("text");

                    b.Property<bool>("ThumbnailUploadedToYouTube")
                        .HasColumnType("boolean");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TitleExperimentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YouTubeVideoId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId");

                    b.ToTable("published_videos", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.PublishingOptimizationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlatformPriorityCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendedAudienceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendedHashtagsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecommendedPublishTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecommendedTagsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("publishing_optimization_results", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.RecoveryOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PipelineJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PipelineRunId", "RequestedAt");

                    b.ToTable("recovery_operations", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.ShortVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParentVideoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YouTubeVideoId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("short_videos", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.ThumbnailOptimizationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Brightness")
                        .HasColumnType("double precision");

                    b.Property<double>("CompositionScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("HookIntensity")
                        .HasColumnType("double precision");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ObjectCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("PipelineRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("TextLength")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("thumbnail_optimization_results", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.TrendSignalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("SignalDate")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("trend_signals", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.VideoAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AverageViewDurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<long>("Comments")
                        .HasColumnType("bigint");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CtaExperimentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CtaVariantId")
                        .HasColumnType("uuid");

                    b.Property<double?>("CtrPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("DecisionType")
                        .HasColumnType("text")
                        .HasColumnName("decisionType");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<string>("EventTitle")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<string>("HookLine")
                        .HasColumnType("text");

                    b.Property<bool>("InjectedIntoDailyGuide")
                        .HasColumnType("boolean")
                        .HasColumnName("injectedIntoDailyGuide");

                    b.Property<bool>("IsShort")
                        .HasColumnType("boolean");

                    b.Property<long>("Likes")
                        .HasColumnType("bigint");

                    b.Property<string>("ParentVideoId")
                        .HasColumnType("text");

                    b.Property<Guid?>("PublishedVideoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SpecialEventGuideGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("specialEventGuideGenerated");

                    b.Property<Guid?>("ThumbnailExperimentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ThumbnailVariantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid?>("TitleExperimentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TitleVariantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PublishedVideoId", "RetrievedAt");

                    b.ToTable("video_analytics", (string)null);
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.AlertPreferences", b =>
                {
                    b.HasOne("Astronomy.MediaFactory.Core.AlertSubscriber", null)
                        .WithOne("Preferences")
                        .HasForeignKey("Astronomy.MediaFactory.Core.AlertPreferences", "SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.ContentVariant", b =>
                {
                    b.HasOne("Astronomy.MediaFactory.Core.ContentExperiment", null)
                        .WithMany("Variants")
                        .HasForeignKey("ContentExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.AlertSubscriber", b =>
                {
                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("Astronomy.MediaFactory.Core.ContentExperiment", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
