using Astronomy.MediaFactory.Core.KnowledgeFoundation.Catalog;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Query;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Query.Execution;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Integration;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.CrossDomain;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Graph;
namespace Astronomy.MediaFactory.Core.KnowledgeFoundation.Integration;
public sealed class AstronomyKnowledgeFoundationCompatibilityVerifier:IAstronomyKnowledgeFoundationCompatibilityVerifier
{ readonly IAstronomyTypedPayloadRegistry typed; readonly IAstronomyKnowledgeValidationRuleRegistry validation; readonly IAstronomyCrossDomainValidationRuleRegistry cross; readonly IAstronomyKnowledgeGraphValidationRuleRegistry graph; readonly IAstronomyKnowledgeCatalog catalog; readonly IAstronomyKnowledgeQueryValidator queryValidator; readonly IAstronomyKnowledgeCatalogQueryEngine catalogEngine; readonly IAstronomyKnowledgeStatementQueryEngine statementEngine; readonly IAstronomyKnowledgeFoundationCapabilities capabilities;
 public AstronomyKnowledgeFoundationCompatibilityVerifier(IAstronomyTypedPayloadRegistry typed,IAstronomyKnowledgeValidationRuleRegistry validation,IAstronomyCrossDomainValidationRuleRegistry cross,IAstronomyKnowledgeGraphValidationRuleRegistry graph,IAstronomyKnowledgeCatalog catalog,IAstronomyKnowledgeQueryValidator queryValidator,IAstronomyKnowledgeCatalogQueryEngine catalogEngine,IAstronomyKnowledgeStatementQueryEngine statementEngine,IAstronomyKnowledgeFoundationCapabilities capabilities){this.typed=typed??throw new ArgumentNullException(nameof(typed));this.validation=validation??throw new ArgumentNullException(nameof(validation));this.cross=cross??throw new ArgumentNullException(nameof(cross));this.graph=graph??throw new ArgumentNullException(nameof(graph));this.catalog=catalog??throw new ArgumentNullException(nameof(catalog));this.queryValidator=queryValidator??throw new ArgumentNullException(nameof(queryValidator));this.catalogEngine=catalogEngine??throw new ArgumentNullException(nameof(catalogEngine));this.statementEngine=statementEngine??throw new ArgumentNullException(nameof(statementEngine));this.capabilities=capabilities??throw new ArgumentNullException(nameof(capabilities));}
 public AstronomyKnowledgeFoundationCompatibilityReport Verify(){ var issues=new List<AstronomyKnowledgeFoundationCompatibilityIssue>(); if(typed.Descriptors.Count==0) Add(issues,"registry.missing","$.typedKnowledge.registry","Typed payload registry has no descriptors."); Dup(issues,validation.Descriptors.Select(d=>d.RuleId),"$.validation.rules"); Dup(issues,cross.Descriptors.Select(d=>d.RuleId),"$.crossDomainValidation.rules"); Dup(issues,graph.Descriptors.Select(d=>d.RuleId),"$.graphValidation.rules"); if(catalog.Snapshot.Entries.Count==0) Add(issues,"catalog.empty","$.catalog.entries","Knowledge catalog is empty."); foreach(var r in graph.Descriptors) if(!catalog.Snapshot.GraphValidationRules.Any(e=>StringComparer.Ordinal.Equals(e.Code,r.RuleId))) Add(issues,"catalog.rule-missing","$.catalog.graphValidationRules",$"Graph validation rule '{r.RuleId}' is missing from catalog."); foreach(var d in capabilities.Snapshot.Capabilities){ if(!capabilities.TryGet(d.Id,out _)) Add(issues,"capability.missing","$.capabilities",$"Capability '{d.Id.Value}' is missing."); }
 foreach(var id in Required()) if(!capabilities.TryGet(id,out _)) Add(issues,"capability.missing","$.capabilities",$"Capability '{id.Value}' is missing."); _=queryValidator; _=catalogEngine; _=statementEngine; return new(issues); }
 static IEnumerable<AstronomyKnowledgeFoundationCapabilityId> Required(){ foreach(var d in AstronomyKnowledgeFoundationCapabilityCatalog.CreateSnapshot().Capabilities) yield return d.Id; }
 static void Dup(List<AstronomyKnowledgeFoundationCompatibilityIssue> issues,IEnumerable<string> ids,string path){ foreach(var g in ids.GroupBy(x=>x,StringComparer.Ordinal).Where(g=>g.Count()>1).OrderBy(g=>g.Key,StringComparer.Ordinal)) Add(issues,"registry.duplicate-rule-id",path,$"Duplicate rule ID '{g.Key}'.");}
 static void Add(List<AstronomyKnowledgeFoundationCompatibilityIssue> i,string c,string p,string m)=>i.Add(new(c,p,m));}
