namespace Astronomy.MediaFactory.Core.KnowledgeFoundation.Integration;
public interface IAstronomyKnowledgeFoundationCompatibilityVerifier{ AstronomyKnowledgeFoundationCompatibilityReport Verify(); }
