using System.Collections.Immutable;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Resolution.V1.Collection;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Resolution.V1.Contracts;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Resolution.V1.Evaluation;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Resolution.V1.Selection;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Adapters.Contracts;
namespace Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Resolution.V1.Engine;
public interface ISemanticResolutionEngineV1 { SemanticResolutionResultV1 Resolve(SemanticResolutionRequestV1 request); }
public sealed class SemanticResolutionEngineV1(ISemanticCandidateCollectorV1 collector, ISemanticCandidateEvaluatorV1 evaluator, ISemanticConflictAnalyzerV1 conflictAnalyzer, ISemanticCandidateSelectorV1 selector) : ISemanticResolutionEngineV1
{ public SemanticResolutionResultV1 Resolve(SemanticResolutionRequestV1 r){var trace=new List<SemanticResolutionTraceEntryV1>();var col=collector.Collect(r);trace.Add(new(SemanticResolutionTraceStageV1.PolicyLoaded,"PolicyLoaded",col.SourcePolicy is null?"Policy missing":"Policy loaded"));foreach(var id in col.InvokedAdapterIds)trace.Add(new(SemanticResolutionTraceStageV1.AdapterInvoked,"AdapterInvoked","Adapter invoked",id)); if(col.SourcePolicy is null)return Finish(r,col,[],new(r.CapabilityId,[]),null,SemanticResolutionStatusV1.ArchitectureError,"ArchitectureError","No source policy.",trace); if(!col.SourcePolicy.ApprovedSources.Any(s=>s.ActiveInV1))return Finish(r,col,[],new(r.CapabilityId,[]),null,r.Required?SemanticResolutionStatusV1.NoApprovedSource:SemanticResolutionStatusV1.UnavailableOptional,"NoApprovedSource","No approved source.",trace); if(col.InvokedAdapterIds.Length==0&&col.MissingApprovedAdapterIds.Length>0)return Finish(r,col,[],new(r.CapabilityId,[]),null,r.Required?SemanticResolutionStatusV1.NoRegisteredAdapter:SemanticResolutionStatusV1.UnavailableOptional,"NoRegisteredAdapter","Approved source has no adapter.",trace); var evals=col.Candidates.Select(c=>evaluator.Evaluate(r,col.SourcePolicy,c)).ToImmutableArray(); trace.AddRange(evals.Select(e=>new SemanticResolutionTraceEntryV1(SemanticResolutionTraceStageV1.CandidateEvaluated,"CandidateEvaluated",e.Disposition.ToString(),e.AdapterId,e.CandidateId))); var conflicts=conflictAnalyzer.Analyze(col.Candidates.Where(c=>evals.Any(e=>e.Eligible&&e.AdapterId==c.AdapterId&&e.SourceId==c.SourceId))); trace.AddRange(conflicts.Conflicts.Select(c=>new SemanticResolutionTraceEntryV1(SemanticResolutionTraceStageV1.ConflictDetected,c.DiagnosticCode,c.DiagnosticMessage))); var sel=selector.Select(r,col.SourcePolicy,col.Candidates,evals,conflicts); trace.Add(new(sel.Combined?SemanticResolutionTraceStageV1.StructuredFieldsCombined:SemanticResolutionTraceStageV1.CandidateSelected,sel.DiagnosticCode??"CandidateSelected",sel.DiagnosticMessage??"Selection completed",candidateId:sel.SelectedCandidate is null?null:$"{sel.SelectedCandidate.AdapterId}|{sel.SelectedCandidate.SourceId}|{sel.SelectedCandidate.CanonicalValue}")); var status=MapStatus(r,col,evals,sel); return Finish(r,col,evals,conflicts,sel,status,sel.DiagnosticCode??status.ToString(),sel.DiagnosticMessage??status.ToString(),trace);}
 static SemanticResolutionStatusV1 MapStatus(SemanticResolutionRequestV1 r, SemanticCandidateCollectionV1 c, ImmutableArray<SemanticCandidateEvaluationV1> e, SemanticCandidateSelectionV1 s){ if(s.SelectedCandidate is not null)return s.Status; if(!r.Required)return SemanticResolutionStatusV1.UnavailableOptional; if(c.Candidates.Length==0&&c.AdapterResults.Length>0)return SemanticResolutionStatusV1.MissingRequiredValue; if(c.Rejections.Length>0&&c.Candidates.Length==0)return c.Rejections.Any(x=>x.Status==SemanticSourceAdapterStatusV1.InvalidValue)?SemanticResolutionStatusV1.InvalidRequiredValue:SemanticResolutionStatusV1.MissingRequiredValue; if(e.Length>0&&e.All(x=>x.Disposition==SemanticCandidateDispositionV1.InsufficientEvidence))return SemanticResolutionStatusV1.InsufficientEvidence; return s.Status;}
 static SemanticResolutionResultV1 Finish(SemanticResolutionRequestV1 r, SemanticCandidateCollectionV1 c, ImmutableArray<SemanticCandidateEvaluationV1> e, SemanticConflictSetV1 conflicts, SemanticCandidateSelectionV1? s, SemanticResolutionStatusV1 status,string code,string msg,List<SemanticResolutionTraceEntryV1> trace){var win=s?.SelectedCandidate;trace.Add(new(SemanticResolutionTraceStageV1.ResolutionCompleted,status.ToString(),msg));var fact=new ResolvedSemanticFactV1(r.CapabilityId,status,r.Required,win?.TypedValue,win?.CanonicalValue,win?.SpeakableValue,win is null?null:$"{win.AdapterId}|{win.SourceId}|{win.CanonicalValue}",win?.AdapterId,win?.SourceId,win?.EvidenceCategory,win?.EvidenceStrength??default,win?.Confidence??0,win?.Provenance??[],s?.Combined==true?(win?.SourceId.Split('+').ToImmutableArray()??[]):[],s?.RejectedCandidates??[],conflicts.Conflicts,c.SourcePolicy?.MultipleCandidatePolicy.ToString()??"None",s?.TieBreakReasons??[],c.CollectionWarnings,code,msg);var diag=new SemanticResolutionDiagnosticsV1(r.CapabilityId,r.Required,c.SourcePolicyVersion,c.Candidates.Length,e.Count(x=>x.Eligible),c.Rejections.Length,c.InvokedAdapterIds,c.MissingApprovedAdapterIds,e,conflicts.Conflicts, fact.WinningCandidateId,status,fact.ResolutionPolicy,fact.TieBreakReasons,status is SemanticResolutionStatusV1.Resolved or SemanticResolutionStatusV1.ResolvedByCombination or SemanticResolutionStatusV1.UnavailableOptional?[]:[code],c.CollectionWarnings,trace.ToImmutableArray());return new(fact,diag);} }
