namespace Astronomy.MediaFactory.Core.DocumentaryBlueprint;

public static class DocumentaryMediaProjectionValidator
{
    public static bool PolicyValid(DocumentaryMediaProjectionPolicy? p) => p is not null && p.PolicySchemaVersion == "1.0" && p.RequiredVariantTypes.SequenceEqual(DocumentaryMediaProjectionInventory.Variants) && p.SupportedLanguages.SequenceEqual(DocumentaryMediaProjectionInventory.Languages) && p.SupportedFormats.SequenceEqual(DocumentaryMediaProjectionInventory.Formats) && p.SupportedTopicFamilies.SequenceEqual(DocumentaryMediaProjectionInventory.TopicFamilies);
    public static bool ProjectValid(DocumentaryMediaProject? p)
    {
        if(p is null||!p.IsComplete||p.MediaProjectId!=$"{p.MaterializationId}.media-project"||p.Variants.Count!=4||!p.Variants.Select(x=>x.VariantType).SequenceEqual(DocumentaryMediaProjectionInventory.Variants))return false;
        var correlation=p.Metadata.CorrelationId;
        if(!DocumentaryMediaProjectionInventory.Eq(p.TopicProfile.CorrelationId,correlation)||!DocumentaryMediaProjectionInventory.Eq(p.MaterializationRecord.Metadata.CorrelationId,correlation))return false;
        foreach(var v in p.Variants){var map=DocumentaryMediaProjectionInventory.Mapping(v.VariantType);var min=map.Format==DocumentaryVideoFormat.Long?p.Policy.LongMinimumSceneCount:p.Policy.ShortMinimumSceneCount;var max=map.Format==DocumentaryVideoFormat.Long?p.Policy.LongMaximumSceneCount:p.Policy.ShortMaximumSceneCount;var minMs=(map.Format==DocumentaryVideoFormat.Long?p.Policy.LongMinimumDurationSeconds:p.Policy.ShortMinimumDurationSeconds)*1000L;var maxMs=(map.Format==DocumentaryVideoFormat.Long?p.Policy.LongMaximumDurationSeconds:p.Policy.ShortMaximumDurationSeconds)*1000L;if(v.Format!=map.Format||v.Language!=map.Language||v.VariantId!=$"{p.MediaProjectId}.{v.VariantType}"||v.AspectRatio!=(map.Format==DocumentaryVideoFormat.Long?"16:9":"9:16")||v.SceneCount<min||v.SceneCount>max||v.PlannedDurationMilliseconds<minMs||v.PlannedDurationMilliseconds>maxMs)return false;long start=0;for(var i=0;i<v.Scenes.Count;i++){var s=v.Scenes[i];if(s.Sequence!=i||s.SceneId!=$"{v.VariantId}.scene.{i}"||s.VariantType!=v.VariantType||s.Timing.TimingId!=$"{s.SceneId}.timing"||s.Timing.PlannedStartMilliseconds!=start||s.Narration.Any(n=>n.NarrationId!=$"{s.SceneId}.narration.{n.Sequence}"||n.Language!=v.Language||n.KnowledgeReferences.Count==0)||s.SubtitleCues.Any(c=>c.SubtitleCueId!=$"{s.SceneId}.subtitle.{c.Sequence}"||c.Language!=v.Language||!s.Narration.Any(n=>n.NarrationId==c.NarrationId)||c.Line1.Length>p.Policy.MaximumSubtitleCharactersPerLine||(c.Line2?.Length??0)>p.Policy.MaximumSubtitleCharactersPerLine)||s.VisualPrompts.Any(x=>x.VisualPromptId!=$"{s.SceneId}.visual.{x.Sequence}"||x.AspectRatio!=v.AspectRatio||x.KnowledgeReferences.Count==0)||s.KnowledgeReferences.Count==0)return false;start=s.Timing.PlannedEndMilliseconds;}}
        return p.TotalSceneCount==p.Variants.Sum(x=>x.SceneCount)&&p.TotalPlannedDurationMilliseconds==p.Variants.Sum(x=>x.PlannedDurationMilliseconds);
    }
}
