namespace Astronomy.MediaFactory.Core.DocumentaryBlueprint;

public sealed class DocumentaryMediaProjector
{
    public DocumentaryMediaProjectionResult Project(DocumentaryMediaProjectionRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);var r=request.MaterializationRecord;var reasons=new List<DocumentaryMediaProjectionRejectionReason>();
        if(!r.IsComplete)reasons.Add(DocumentaryMediaProjectionRejectionReason.MaterializationRecordNotComplete);
        if(r.MaterializationId!=$"{r.ExportSpecificationId}.materialization")reasons.Add(DocumentaryMediaProjectionRejectionReason.MaterializationIdentityMismatch);
        if(r.ExportSpecificationId!=r.ExportSpecification.ExportSpecificationId)reasons.Add(DocumentaryMediaProjectionRejectionReason.ExportSpecificationIdentityMismatch);
        if(r.CertificationId!=r.CertificationRecord.CertificationId)reasons.Add(DocumentaryMediaProjectionRejectionReason.CertificationIdentityMismatch);
        if(r.ProvenanceId!=r.ProvenanceRecord.ProvenanceId)reasons.Add(DocumentaryMediaProjectionRejectionReason.ProvenanceIdentityMismatch);
        if(r.PackageId!=r.ProductionPackage.PackageId)reasons.Add(DocumentaryMediaProjectionRejectionReason.PackageIdentityMismatch);
        var correlation=request.Metadata.CorrelationId;if(!DocumentaryMediaProjectionInventory.Eq(request.TopicProfile.CorrelationId,correlation)||!DocumentaryMediaProjectionInventory.Eq(r.Metadata.CorrelationId,correlation)||r.Payloads.Any(x=>!DocumentaryMediaProjectionInventory.Eq(x.CorrelationId,correlation)))reasons.Add(DocumentaryMediaProjectionRejectionReason.CorrelationMismatch);
        if(!DocumentaryMediaProjectionValidator.PolicyValid(request.Policy))reasons.Add(DocumentaryMediaProjectionRejectionReason.ProjectionPolicyRejected);
        if(!request.Policy.SupportedTopicFamilies.Contains(request.TopicProfile.TopicFamily))reasons.Add(DocumentaryMediaProjectionRejectionReason.TopicProfileRejected);
        if(reasons.Count>0)return new(DocumentaryMediaProjectionStatus.Rejected,reasons.Distinct().OrderBy(x=>(int)x).ToArray(),null);
        var id=$"{r.MaterializationId}.media-project";var variants=DocumentaryMediaProjectionInventory.Variants.Select(x=>CreateVariant(id,x,request)).ToArray();
        var project=new DocumentaryMediaProject(id,r,r.ExportSpecification,r.CertificationRecord,r.ProvenanceRecord,r.ProductionPackage,request.Policy,request.Metadata,request.TopicProfile,variants,r.MaterializationId,r.ExportSpecificationId,r.CertificationId,r.ProvenanceId,r.PackageId,r.ReleaseCandidateId,r.ConvergenceId,request.TopicProfile.TopicId,4,variants.Sum(x=>x.SceneCount),variants.Sum(x=>x.PlannedDurationMilliseconds),true);
        if(!DocumentaryMediaProjectionValidator.ProjectValid(project))return new(DocumentaryMediaProjectionStatus.Rejected,[DocumentaryMediaProjectionRejectionReason.SceneInventoryMismatch],null);
        return new(DocumentaryMediaProjectionStatus.Complete,[],project);
    }
    private static DocumentaryMediaVariant CreateVariant(string projectId,DocumentaryMediaVariantType type,DocumentaryMediaProjectionRequest request)
    {var (format,language)=DocumentaryMediaProjectionInventory.Mapping(type);var policy=request.Policy;var count=format==DocumentaryVideoFormat.Long?policy.LongMinimumSceneCount:policy.ShortMinimumSceneCount;var duration=(format==DocumentaryVideoFormat.Long?policy.LongMinimumDurationSeconds:policy.ShortMinimumDurationSeconds)*1000L;var id=$"{projectId}.{type}";var scenes=new List<DocumentaryMediaScene>();long start=0;for(var i=0;i<count;i++){var length=duration/count+(i<duration%count?1:0);scenes.Add(CreateScene(id,type,language,format,i,start,length,request));start+=length;}var name=language==DocumentaryMediaLanguage.English?request.TopicProfile.DisplayNameEnglish:request.TopicProfile.DisplayNameHindi;return new(id,type,format,language,name,$"{name} — certified documentary projection",format==DocumentaryVideoFormat.Long?$"Discover {name} through certified knowledge.":$"One memorable view of {name}.",scenes,count,duration,format==DocumentaryVideoFormat.Long?"16:9":"9:16",request.Metadata.CorrelationId);}
    private static DocumentaryMediaScene CreateScene(string variantId,DocumentaryMediaVariantType type,DocumentaryMediaLanguage language,DocumentaryVideoFormat format,int sequence,long start,long duration,DocumentaryMediaProjectionRequest request)
    {var payload=request.MaterializationRecord.Payloads[sequence%request.MaterializationRecord.Payloads.Count];var sceneId=$"{variantId}.scene.{sequence}";var reference=new DocumentaryMediaKnowledgeReference($"{sceneId}.reference.0",payload.PayloadId,payload.PayloadType,payload.SourceItemId,payload.ArtifactIdentity,payload.ArtifactVersion,"/",0,request.Metadata.CorrelationId);var refs=new[]{reference};var role=format==DocumentaryVideoFormat.Short?new[]{DocumentaryMediaSceneRole.Hook,DocumentaryMediaSceneRole.MajorFeature,DocumentaryMediaSceneRole.Observation,DocumentaryMediaSceneRole.Summary,DocumentaryMediaSceneRole.CallToAction}[sequence%5]:(DocumentaryMediaSceneRole)Math.Min(sequence,(int)DocumentaryMediaSceneRole.CallToAction);var text=language==DocumentaryMediaLanguage.English?$"Certified knowledge presents {request.TopicProfile.DisplayNameEnglish} in this {role} scene.":$"प्रमाणित ज्ञान इस दृश्य में {request.TopicProfile.DisplayNameHindi} का {role} परिचय देता है।";if(text.Length>request.Policy.MaximumNarrationCharactersPerScene)text=text[..request.Policy.MaximumNarrationCharactersPerScene];var narrationDuration=Math.Max(1,duration-500);var narrationId=$"{sceneId}.narration.0";var narration=new DocumentaryNarrationBlock(narrationId,language,text,0,narrationDuration,refs,request.Metadata.CorrelationId);var line=language==DocumentaryMediaLanguage.English?"Certified astronomy knowledge":"प्रमाणित खगोलीय ज्ञान";if(line.Length>request.Policy.MaximumSubtitleCharactersPerLine)line=line[..request.Policy.MaximumSubtitleCharactersPerLine];var subtitle=new DocumentarySubtitleCue($"{sceneId}.subtitle.0",language,line,line,null,DocumentarySubtitlePresentation.Standard,0,narrationDuration,0,narrationId,refs,request.Metadata.CorrelationId);var subjects=request.TopicProfile.PrimaryObjectIds.Concat(request.TopicProfile.SecondaryObjectIds).Distinct(StringComparer.Ordinal).ToArray();var visual=new DocumentaryVisualPrompt($"{sceneId}.visual.0",DocumentaryMediaVisualType.ScientificDiagram,$"Accurate astronomical composition of {request.TopicProfile.DisplayNameEnglish}, {role}",$"{request.TopicProfile.DisplayNameHindi} का सटीक खगोलीय दृश्य",string.Empty,format==DocumentaryVideoFormat.Long?"16:9":"9:16",DocumentaryCameraMotion.SlowZoomIn,subjects,refs,0,request.Metadata.CorrelationId);var timing=new DocumentarySceneTiming($"{sceneId}.timing",start,start+duration,duration,narrationDuration,500,0,request.Metadata.CorrelationId);return new(sceneId,type,role,role.ToString(),sequence,[narration],[subtitle],[visual],timing,sequence==0?DocumentarySceneTransition.FadeFromBlack:DocumentarySceneTransition.CrossFade,refs,request.Metadata.CorrelationId);}
}
