namespace Astronomy.MediaFactory.Core.DocumentaryBlueprint;

public enum DocumentaryNarrativeRevisionEditorType { Human, Automated, Hybrid }

public sealed record DocumentaryNarrativeRevisionExecutionMetadata
{
    public DocumentaryNarrativeRevisionExecutionMetadata(DateTimeOffset createdUtc, string createdBy, string executionSchemaVersion, string correlationId)
    { CreatedUtc=createdUtc!=default?createdUtc:throw new ArgumentException("A non-default creation timestamp is required.",nameof(createdUtc)); CreatedBy=Guard.Required(createdBy,nameof(createdBy)); ExecutionSchemaVersion=executionSchemaVersion=="1.0"?executionSchemaVersion:throw new ArgumentException("Execution schema version must be 1.0.",nameof(executionSchemaVersion)); CorrelationId=Guard.Required(correlationId,nameof(correlationId)); }
    public DateTimeOffset CreatedUtc{get;} public string CreatedBy{get;} public string ExecutionSchemaVersion{get;} public string CorrelationId{get;}
}

public sealed record DocumentaryNarrativePassageContext
{
    public DocumentaryNarrativePassageContext(string passageId,int passageNumber,string title,string text)
    { PassageId=Guard.Required(passageId,nameof(passageId)); PassageNumber=passageNumber; Title=Guard.Required(title,nameof(title)); Text=Guard.Required(text,nameof(text)); }
    public string PassageId{get;} public int PassageNumber{get;} public string Title{get;} public string Text{get;}
}

public sealed class DocumentaryNarrativePassageRevisionWorkItem
{
    public DocumentaryNarrativePassageRevisionWorkItem(string workItemId,int sequenceNumber,string revisionRequestId,string draftId,string draftVersion,string sectionId,int sectionNumber,string sectionTitle,string passageId,int passageNumber,string passageTitle,DocumentaryNarrativePassageType passageType,DocumentaryNarrativeStage narrativeStage,DocumentarySceneRole sceneRole,string originalText,IReadOnlyList<string> revisionItemIds,IReadOnlyList<string> ruleCodes,IReadOnlyList<DocumentaryNarrativeDraftValidationSeverity> severities,IReadOnlyList<DocumentaryNarrativeRevisionAction> actions,IReadOnlyList<string> messages,DocumentaryNarrativePassageContext? previousPassageContext,DocumentaryNarrativePassageContext? nextPassageContext)
    {
        WorkItemId=Guard.Required(workItemId,nameof(workItemId)); if(sequenceNumber<=0)throw new ArgumentOutOfRangeException(nameof(sequenceNumber)); SequenceNumber=sequenceNumber; RevisionRequestId=Guard.Required(revisionRequestId,nameof(revisionRequestId)); DraftId=Guard.Required(draftId,nameof(draftId)); DraftVersion=Guard.Required(draftVersion,nameof(draftVersion)); SectionId=Guard.Required(sectionId,nameof(sectionId)); SectionNumber=sectionNumber; SectionTitle=Guard.Required(sectionTitle,nameof(sectionTitle)); PassageId=Guard.Required(passageId,nameof(passageId)); PassageNumber=passageNumber; PassageTitle=Guard.Required(passageTitle,nameof(passageTitle)); Guard.Enum(passageType,nameof(passageType)); PassageType=passageType; Guard.Enum(narrativeStage,nameof(narrativeStage)); NarrativeStage=narrativeStage; Guard.Enum(sceneRole,nameof(sceneRole)); SceneRole=sceneRole; OriginalText=Guard.Required(originalText,nameof(originalText));
        RevisionItemIds=Guard.Copy(revisionItemIds,nameof(revisionItemIds)); RuleCodes=Guard.Copy(ruleCodes,nameof(ruleCodes)); ArgumentNullException.ThrowIfNull(severities); Severities=Array.AsReadOnly(severities.ToArray()); ArgumentNullException.ThrowIfNull(actions); Actions=Array.AsReadOnly(actions.ToArray()); Messages=Guard.Copy(messages,nameof(messages));
        if(RevisionItemIds.Count==0||new[]{RuleCodes.Count,Severities.Count,Actions.Count,Messages.Count}.Any(x=>x!=RevisionItemIds.Count)||RevisionItemIds.Any(string.IsNullOrWhiteSpace)||RevisionItemIds.Distinct(StringComparer.Ordinal).Count()!=RevisionItemIds.Count||RuleCodes.Any(string.IsNullOrWhiteSpace)||Messages.Any(string.IsNullOrWhiteSpace))throw new ArgumentException("Revision collections must be nonempty, unique, and aligned.");
        foreach(var value in Severities)Guard.Enum(value,nameof(severities)); foreach(var value in Actions)Guard.Enum(value,nameof(actions)); PreviousPassageContext=previousPassageContext; NextPassageContext=nextPassageContext;
    }
    public string WorkItemId{get;} public int SequenceNumber{get;} public string RevisionRequestId{get;} public string DraftId{get;} public string DraftVersion{get;} public string SectionId{get;} public int SectionNumber{get;} public string SectionTitle{get;} public string PassageId{get;} public int PassageNumber{get;} public string PassageTitle{get;} public DocumentaryNarrativePassageType PassageType{get;} public DocumentaryNarrativeStage NarrativeStage{get;} public DocumentarySceneRole SceneRole{get;} public string OriginalText{get;} public IReadOnlyList<string> RevisionItemIds{get;} public IReadOnlyList<string> RuleCodes{get;} public IReadOnlyList<DocumentaryNarrativeDraftValidationSeverity> Severities{get;} public IReadOnlyList<DocumentaryNarrativeRevisionAction> Actions{get;} public IReadOnlyList<string> Messages{get;} public DocumentaryNarrativePassageContext? PreviousPassageContext{get;} public DocumentaryNarrativePassageContext? NextPassageContext{get;}
}

public sealed record DocumentaryNarrativeManualReviewWorkItem
{
    public DocumentaryNarrativeManualReviewWorkItem(string workItemId,int sequenceNumber,string revisionRequestId,string revisionItemId,string ruleCode,DocumentaryNarrativeDraftValidationSeverity severity,DocumentaryNarrativeRevisionAction action,string message,string draftId,string? sectionId,int? sectionNumber,string? passageId,int? passageNumber,string? fieldName)
    { WorkItemId=Guard.Required(workItemId,nameof(workItemId)); if(sequenceNumber<=0)throw new ArgumentOutOfRangeException(nameof(sequenceNumber)); SequenceNumber=sequenceNumber; RevisionRequestId=Guard.Required(revisionRequestId,nameof(revisionRequestId)); RevisionItemId=Guard.Required(revisionItemId,nameof(revisionItemId)); RuleCode=Guard.Required(ruleCode,nameof(ruleCode)); Guard.Enum(severity,nameof(severity)); Severity=severity; Guard.Enum(action,nameof(action)); Action=action; Message=Guard.Required(message,nameof(message)); DraftId=Guard.Required(draftId,nameof(draftId)); SectionId=Guard.OptionalIdentifier(sectionId,nameof(sectionId)); SectionNumber=sectionNumber; PassageId=Guard.OptionalIdentifier(passageId,nameof(passageId)); PassageNumber=passageNumber; FieldName=Guard.OptionalIdentifier(fieldName,nameof(fieldName)); }
    public string WorkItemId{get;} public int SequenceNumber{get;} public string RevisionRequestId{get;} public string RevisionItemId{get;} public string RuleCode{get;} public DocumentaryNarrativeDraftValidationSeverity Severity{get;} public DocumentaryNarrativeRevisionAction Action{get;} public string Message{get;} public string DraftId{get;} public string? SectionId{get;} public int? SectionNumber{get;} public string? PassageId{get;} public int? PassageNumber{get;} public string? FieldName{get;}
}

public sealed class DocumentaryNarrativeRevisionWorkPackage
{
    public DocumentaryNarrativeRevisionWorkPackage(string workPackageId,string revisionRequestId,string draftId,string draftVersion,string subjectId,string subjectName,BlueprintPublicationFormat publicationFormat,string primaryLanguage,DocumentaryNarrativeRevisionExecutionMetadata metadata,IReadOnlyList<DocumentaryNarrativePassageRevisionWorkItem> passageWorkItems,IReadOnlyList<DocumentaryNarrativeManualReviewWorkItem> manualReviewWorkItems)
    { WorkPackageId=Guard.Required(workPackageId,nameof(workPackageId)); RevisionRequestId=Guard.Required(revisionRequestId,nameof(revisionRequestId)); DraftId=Guard.Required(draftId,nameof(draftId)); DraftVersion=Guard.Required(draftVersion,nameof(draftVersion)); SubjectId=Guard.Required(subjectId,nameof(subjectId)); SubjectName=Guard.Required(subjectName,nameof(subjectName)); Guard.Enum(publicationFormat,nameof(publicationFormat)); PublicationFormat=publicationFormat; PrimaryLanguage=Guard.Required(primaryLanguage,nameof(primaryLanguage)); Metadata=metadata??throw new ArgumentNullException(nameof(metadata)); PassageWorkItems=Guard.Copy(passageWorkItems,nameof(passageWorkItems)); ManualReviewWorkItems=Guard.Copy(manualReviewWorkItems,nameof(manualReviewWorkItems)); if(PassageWorkItems.Select(x=>x.WorkItemId).Concat(ManualReviewWorkItems.Select(x=>x.WorkItemId)).Distinct(StringComparer.Ordinal).Count()!=PassageWorkItems.Count+ManualReviewWorkItems.Count)throw new ArgumentException("Work item IDs must be unique."); }
    public string WorkPackageId{get;} public string RevisionRequestId{get;} public string DraftId{get;} public string DraftVersion{get;} public string SubjectId{get;} public string SubjectName{get;} public BlueprintPublicationFormat PublicationFormat{get;} public string PrimaryLanguage{get;} public DocumentaryNarrativeRevisionExecutionMetadata Metadata{get;} public IReadOnlyList<DocumentaryNarrativePassageRevisionWorkItem> PassageWorkItems{get;} public IReadOnlyList<DocumentaryNarrativeManualReviewWorkItem> ManualReviewWorkItems{get;} public bool RequiresExternalEditing=>PassageWorkItems.Count>0; public int PassageWorkItemCount=>PassageWorkItems.Count; public int ManualReviewWorkItemCount=>ManualReviewWorkItems.Count; public int RevisionItemCount=>PassageWorkItems.Sum(x=>x.RevisionItemIds.Count)+ManualReviewWorkItems.Count;
}

public sealed record DocumentaryNarrativeRevisionSubmissionMetadata
{
    public DocumentaryNarrativeRevisionSubmissionMetadata(DateTimeOffset createdUtc,string createdBy,string submissionSchemaVersion,DocumentaryNarrativeRevisionEditorType editorType,string editorName,string correlationId)
    { CreatedUtc=createdUtc!=default?createdUtc:throw new ArgumentException("A non-default creation timestamp is required.",nameof(createdUtc)); CreatedBy=Guard.Required(createdBy,nameof(createdBy)); SubmissionSchemaVersion=submissionSchemaVersion=="1.0"?submissionSchemaVersion:throw new ArgumentException("Submission schema version must be 1.0.",nameof(submissionSchemaVersion)); Guard.Enum(editorType,nameof(editorType)); EditorType=editorType; EditorName=Guard.Required(editorName,nameof(editorName)); CorrelationId=Guard.Required(correlationId,nameof(correlationId)); }
    public DateTimeOffset CreatedUtc{get;} public string CreatedBy{get;} public string SubmissionSchemaVersion{get;} public DocumentaryNarrativeRevisionEditorType EditorType{get;} public string EditorName{get;} public string CorrelationId{get;}
}

public sealed class DocumentaryNarrativePassageRevisionSubmission
{
    public DocumentaryNarrativePassageRevisionSubmission(string workItemId,string passageId,string originalText,string revisedText,IReadOnlyList<string> resolvedRevisionItemIds)
    { WorkItemId=Guard.Required(workItemId,nameof(workItemId)); PassageId=Guard.Required(passageId,nameof(passageId)); OriginalText=Guard.Required(originalText,nameof(originalText)); RevisedText=Guard.Required(revisedText,nameof(revisedText)); ResolvedRevisionItemIds=Guard.Copy(resolvedRevisionItemIds,nameof(resolvedRevisionItemIds)); if(ResolvedRevisionItemIds.Count==0||ResolvedRevisionItemIds.Any(string.IsNullOrWhiteSpace)||ResolvedRevisionItemIds.Distinct(StringComparer.Ordinal).Count()!=ResolvedRevisionItemIds.Count)throw new ArgumentException("Resolved revision item IDs must be nonempty and unique.",nameof(resolvedRevisionItemIds)); }
    public string WorkItemId{get;} public string PassageId{get;} public string OriginalText{get;} public string RevisedText{get;} public IReadOnlyList<string> ResolvedRevisionItemIds{get;}
}

public sealed class DocumentaryNarrativeRevisionSubmission
{
    public DocumentaryNarrativeRevisionSubmission(string submissionId,string workPackageId,string revisionRequestId,string draftId,string draftVersion,DocumentaryNarrativeRevisionSubmissionMetadata metadata,IReadOnlyList<DocumentaryNarrativePassageRevisionSubmission> passageSubmissions)
    { SubmissionId=Guard.Required(submissionId,nameof(submissionId)); WorkPackageId=Guard.Required(workPackageId,nameof(workPackageId)); RevisionRequestId=Guard.Required(revisionRequestId,nameof(revisionRequestId)); DraftId=Guard.Required(draftId,nameof(draftId)); DraftVersion=Guard.Required(draftVersion,nameof(draftVersion)); Metadata=metadata??throw new ArgumentNullException(nameof(metadata)); PassageSubmissions=Guard.Copy(passageSubmissions,nameof(passageSubmissions)); if(PassageSubmissions.Select(x=>x.WorkItemId).Distinct(StringComparer.Ordinal).Count()!=PassageSubmissions.Count||PassageSubmissions.Select(x=>x.PassageId).Distinct(StringComparer.Ordinal).Count()!=PassageSubmissions.Count||PassageSubmissions.SelectMany(x=>x.ResolvedRevisionItemIds).Distinct(StringComparer.Ordinal).Count()!=ResolvedRevisionItemCount)throw new ArgumentException("Submission work, passage, and resolved item identities must be unique.",nameof(passageSubmissions)); }
    public string SubmissionId{get;} public string WorkPackageId{get;} public string RevisionRequestId{get;} public string DraftId{get;} public string DraftVersion{get;} public DocumentaryNarrativeRevisionSubmissionMetadata Metadata{get;} public IReadOnlyList<DocumentaryNarrativePassageRevisionSubmission> PassageSubmissions{get;} public int PassageSubmissionCount=>PassageSubmissions.Count; public int ResolvedRevisionItemCount=>PassageSubmissions.Sum(x=>x.ResolvedRevisionItemIds.Count);
}
