using System.Reflection;
using System.Text.Json;

namespace Astronomy.MediaFactory.Core.DocumentaryBlueprint;

internal static class DocumentaryCertificationValidator
{
    internal static void ValidatePolicy(DocumentaryCertificationPolicy p){ArgumentNullException.ThrowIfNull(p);if(!p.RequiredDomains.SequenceEqual(DocumentaryCertificationInventory.Domains)||!p.RequiredRules.SequenceEqual(DocumentaryCertificationInventory.Rules)||p.PolicySchemaVersion!="1.0")throw new ArgumentException("Certification policy is invalid.");}
    internal static void ValidateEvidence(DocumentaryCertificationMetadata m,IReadOnlyList<DocumentaryUpstreamCertificationEvidence> upstream,IReadOnlyList<DocumentaryCertificationDocumentationEvidence> docs)
    {ArgumentNullException.ThrowIfNull(m);if(upstream.Count!=13||upstream.Select(x=>x.ObjectiveId).Distinct(StringComparer.Ordinal).Count()!=13||upstream.Select((x,i)=>x.Sequence==i&&x.ObjectiveId==DocumentaryCertificationInventory.Objectives[i]&&x.ObjectiveVersion=="1.0"&&x.IsCertified&&DocumentaryCertificationInventory.Eq(x.CorrelationId,m.CorrelationId)).Any(x=>!x))throw new ArgumentException("Upstream evidence is incomplete.");if(docs.Count!=4||docs.Select(x=>x.DocumentId).Distinct(StringComparer.Ordinal).Count()!=4||docs.Select((x,i)=>x.Sequence==i&&x.DocumentId==DocumentaryCertificationInventory.DocumentIds[i]&&x.DocumentVersion=="1.0"&&x.RequiredStatements.SequenceEqual(DocumentaryCertificationInventory.Statements[i])&&DocumentaryCertificationInventory.Eq(x.CorrelationId,m.CorrelationId)).Any(x=>!x))throw new ArgumentException("Documentation evidence is incomplete.");}
    internal static bool JsonRoundTrips<T>(T value){try{var o=new JsonSerializerOptions(JsonSerializerDefaults.Web);var json=JsonSerializer.Serialize(value,o);var copy=JsonSerializer.Deserialize<T>(json,o);return copy is not null&&json==JsonSerializer.Serialize(copy,o);}catch{return false;}}
    internal static bool OperationsValid()=>new[]{typeof(DocumentaryProductionPackageAssembler),typeof(DocumentaryProductionPackageSummarizer),typeof(DocumentaryProvenanceBuilder),typeof(DocumentaryProvenanceSummarizer),typeof(DocumentaryCertificationEvaluator),typeof(DocumentaryCertificationSummarizer)}.All(t=>t.IsSealed&&t.GetConstructor(Type.EmptyTypes)is not null&&!t.GetFields(BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).Any()&&t.GetMethods(BindingFlags.Instance|BindingFlags.Public|BindingFlags.DeclaredOnly).Length==1&&!typeof(System.Threading.Tasks.Task).IsAssignableFrom(t.GetMethods(BindingFlags.Instance|BindingFlags.Public|BindingFlags.DeclaredOnly)[0].ReturnType));
    internal static bool Immutable()=>new[]{typeof(DocumentaryProductionPackage),typeof(DocumentaryProductionPackageManifest),typeof(DocumentaryProvenanceRecord),typeof(DocumentaryProvenanceArtifactNode),typeof(DocumentaryProvenanceRelationshipEdge)}.All(t=>t.GetProperties(BindingFlags.Instance|BindingFlags.Public).All(p=>p.SetMethod is null));
}
