using System.Globalization;

namespace Astronomy.MediaFactory.Core.DocumentaryBlueprint;

public sealed class DocumentaryExportSpecificationBuilder
{
    public DocumentaryExportSpecificationBuildResult Build(DocumentaryExportSpecificationRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);var c=request.CertificationRecord;var p=c.ProductionPackage;var provenance=c.ProvenanceRecord;var reasons=new List<DocumentaryExportSpecificationRejectionReason>();
        if(!c.IsCertified||!c.Decision.IsCertified||c.FailedRuleCount!=0||c.PassedRuleCount!=22||c.TotalRuleCount!=22)reasons.Add(DocumentaryExportSpecificationRejectionReason.CertificationRecordNotCertified);
        if(c.CertificationId!=$"{c.ProvenanceId}.certification"||c.ProvenanceId!=provenance.ProvenanceId)reasons.Add(DocumentaryExportSpecificationRejectionReason.CertificationIdentityMismatch);
        if(c.PackageId!=p.PackageId||provenance.PackageId!=p.PackageId)reasons.Add(DocumentaryExportSpecificationRejectionReason.PackageIdentityMismatch);
        if(provenance.ProvenanceId!=$"{p.PackageId}.provenance"||c.ProvenanceId!=provenance.ProvenanceId)reasons.Add(DocumentaryExportSpecificationRejectionReason.ProvenanceIdentityMismatch);
        if(!CorrelationsValid(c,request.Metadata.CorrelationId))reasons.Add(DocumentaryExportSpecificationRejectionReason.CorrelationMismatch);
        if(!DocumentaryExportSpecificationValidator.PolicyValid(request.Policy))reasons.Add(DocumentaryExportSpecificationRejectionReason.ExportPolicyRejected);
        if(request.Profile!=DocumentaryExportProfile.CertifiedKnowledgePackage)reasons.Add(DocumentaryExportSpecificationRejectionReason.ExportProfileRejected);
        if(reasons.Count!=0)return new(DocumentaryExportSpecificationStatus.Rejected,reasons,null);
        var id=$"{c.CertificationId}.export-specification";var items=BuildItems(c,id,request.Metadata);var manifest=new DocumentaryExportSpecificationManifest($"{id}.manifest",id,request.Profile,items,10,10,DocumentaryExportEncoding.StructuredJson,"1.0",request.Metadata.CorrelationId);
        var specification=new DocumentaryExportSpecification(id,c,provenance,p,request.Profile,request.Policy,request.Metadata,items,manifest,c.CertificationId,provenance.ProvenanceId,p.PackageId,p.ReleaseCandidateId,p.ConvergenceId,10,10,true);
        return new(DocumentaryExportSpecificationStatus.Complete,Array.Empty<DocumentaryExportSpecificationRejectionReason>(),specification);
    }
    private static IReadOnlyList<DocumentaryExportSpecificationItem> BuildItems(DocumentaryCertificationRecord c,string id,DocumentaryExportSpecificationMetadata m)
    { var p=c.ProductionPackage;var pr=c.ProvenanceRecord;var identities=new[]{p.CurrentDraftId,p.FinalValidationResult.DraftId,$"{p.ConvergenceId}.cycles",p.ConvergenceId,$"{p.ConvergenceId}.acceptance",p.Manifest.ManifestId,pr.ProvenanceId,$"{c.CertificationId}.decision",c.CertificationId,$"{id}.manifest"};var versions=new[]{p.CurrentDraftVersion,p.CurrentDraftVersion,p.CompletedCycleCount.ToString(CultureInfo.InvariantCulture),p.ConvergenceState.Metadata.ConvergenceSchemaVersion,p.AcceptanceDecision.Metadata.AcceptanceSchemaVersion,p.Manifest.ManifestSchemaVersion,pr.Metadata.ProvenanceSchemaVersion,c.Metadata.CertificationSchemaVersion,c.Metadata.CertificationSchemaVersion,m.ExportSchemaVersion};int[][] targets=[[],[0],[0],[1,2],[3],[0,1,2,3,4],[5],[6],[6,7],[0,1,2,3,4,5,6,7,8]];var result=new List<DocumentaryExportSpecificationItem>();for(var i=0;i<10;i++){var type=(DocumentaryExportItemType)i;var deps=targets[i].Select((target,sequence)=>new DocumentaryExportItemDependency($"{type}.depends-on.{(DocumentaryExportItemType)target}",type,(DocumentaryExportItemType)target,sequence,m.CorrelationId)).ToArray();result.Add(new($"{type}.{identities[i]}.{versions[i]}",type,DocumentaryExportItemRequirement.Required,(DocumentaryExportContentType)i,DocumentaryExportEncoding.StructuredJson,identities[i],versions[i],i,deps,m.CorrelationId));}return result; }
    private static bool CorrelationsValid(DocumentaryCertificationRecord c,string correlation){var p=c.ProductionPackage;var pr=c.ProvenanceRecord;return new[]{c.Metadata.CorrelationId,p.Metadata.CorrelationId,p.Manifest.CorrelationId,p.ReleaseCandidate.Metadata.CorrelationId,p.AcceptanceDecision.Metadata.CorrelationId,p.ConvergenceState.Metadata.CorrelationId,pr.Metadata.CorrelationId}.All(x=>DocumentaryExportSpecificationInventory.Eq(x,correlation))&&p.RevisionCycles.All(x=>DocumentaryExportSpecificationInventory.Eq(x.Metadata.CorrelationId,correlation))&&pr.ArtifactNodes.All(x=>DocumentaryExportSpecificationInventory.Eq(x.CorrelationId,correlation))&&pr.RelationshipEdges.All(x=>DocumentaryExportSpecificationInventory.Eq(x.CorrelationId,correlation))&&c.Decision.RuleResults.All(x=>DocumentaryExportSpecificationInventory.Eq(x.CorrelationId,correlation))&&c.Decision.Findings.All(x=>DocumentaryExportSpecificationInventory.Eq(x.CorrelationId,correlation))&&c.UpstreamCertificationEvidence.All(x=>DocumentaryExportSpecificationInventory.Eq(x.CorrelationId,correlation))&&c.DocumentationEvidence.All(x=>DocumentaryExportSpecificationInventory.Eq(x.CorrelationId,correlation));}
}
