namespace Astronomy.MediaFactory.Core.DocumentaryBlueprint;

internal static class DocumentaryExportSpecificationValidator
{
    internal static bool PolicyValid(DocumentaryExportSpecificationPolicy p)=>p is not null&&new[]{p.RequireCertifiedRecord,p.RequireCompleteProductionPackage,p.RequireCompleteProvenance,p.RequireCanonicalItems,p.RequireCanonicalOrdering,p.RequireExactCorrelation,p.RequireDeterministicIdentity,p.RequireDeterministicDependencies}.All(x=>x)&&p.RequiredItemTypes.SequenceEqual(DocumentaryExportSpecificationInventory.Items)&&p.RequiredContentTypes.SequenceEqual(DocumentaryExportSpecificationInventory.Contents)&&p.ExportEncoding==DocumentaryExportEncoding.StructuredJson&&p.PolicySchemaVersion=="1.0";
    internal static bool ItemsValid(IReadOnlyList<DocumentaryExportSpecificationItem> items,string correlation)=>items is not null&&items.Count==10&&items.Select(x=>x.ItemType).SequenceEqual(DocumentaryExportSpecificationInventory.Items)&&items.Select(x=>x.ContentType).SequenceEqual(DocumentaryExportSpecificationInventory.Contents)&&items.Select(x=>x.Sequence).SequenceEqual(Enumerable.Range(0,10))&&items.All(x=>x.Requirement==DocumentaryExportItemRequirement.Required&&x.Encoding==DocumentaryExportEncoding.StructuredJson&&DocumentaryExportSpecificationInventory.Eq(x.CorrelationId,correlation)&&x.Dependencies.All(d=>DocumentaryExportSpecificationInventory.Eq(d.CorrelationId,correlation)))&&items.Sum(x=>x.Dependencies.Count)==23;
    internal static bool SpecificationValid(DocumentaryExportSpecification s)
    {
        var c=s.CertificationRecord;var p=s.ProductionPackage;var provenance=s.ProvenanceRecord;var correlation=s.Metadata.CorrelationId;
        return s.IsComplete==false /* construction-time value */&&c.IsCertified&&c.Decision.IsCertified&&c.FailedRuleCount==0&&c.PassedRuleCount==22&&c.TotalRuleCount==22&&s.Profile==DocumentaryExportProfile.CertifiedKnowledgePackage&&PolicyValid(s.Policy)&&s.ExportSpecificationId==$"{s.CertificationId}.export-specification"&&s.CertificationId==c.CertificationId&&s.ProvenanceId==provenance.ProvenanceId&&s.PackageId==p.PackageId&&s.ReleaseCandidateId==p.ReleaseCandidateId&&s.ConvergenceId==p.ConvergenceId&&provenance.ProvenanceId==$"{p.PackageId}.provenance"&&c.CertificationId==$"{provenance.ProvenanceId}.certification"&&p.IsComplete&&provenance.IsComplete&&DocumentaryExportSpecificationInventory.Eq(c.Metadata.CorrelationId,correlation)&&DocumentaryExportSpecificationInventory.Eq(provenance.Metadata.CorrelationId,correlation)&&DocumentaryExportSpecificationInventory.Eq(p.Metadata.CorrelationId,correlation)&&ItemsValid(s.Items,correlation)&&s.ItemCount==10&&s.RequiredItemCount==10&&s.Manifest.ExportSpecificationId==s.ExportSpecificationId&&s.Manifest.Items.Select(x=>x.ItemId).SequenceEqual(s.Items.Select(x=>x.ItemId))&&s.Manifest.Items.SelectMany(x=>x.Dependencies).Select(x=>x.DependencyId).SequenceEqual(s.Items.SelectMany(x=>x.Dependencies).Select(x=>x.DependencyId))&&DocumentaryExportSpecificationInventory.Eq(s.Manifest.CorrelationId,correlation);
    }
}
