namespace Astronomy.MediaFactory.Core.DocumentaryBlueprint;

public sealed class DocumentaryMediaPipelinePlanner
{
    public DocumentaryMediaPipelineExecutionPlan Plan(DocumentaryMediaPipelineRequest request)
    {
        ArgumentNullException.ThrowIfNull(request); DocumentaryMediaPipelineValidator.ValidateRequest(request);
        var all=new List<DocumentaryMediaAssetPlan>(); var deps=new List<DocumentaryMediaAssetDependency>(); var variants=new List<DocumentaryMediaVariantExecutionPlan>();
        foreach(var variant in request.MediaProject.Variants)
        {
            var visuals=new List<DocumentaryMediaAssetPlan>();var narrations=new List<DocumentaryMediaAssetPlan>();var subtitles=new List<DocumentaryMediaAssetPlan>();var scenes=new List<DocumentaryMediaAssetPlan>();
            var (w,h,f)=variant.Format==DocumentaryVideoFormat.Long?(request.Policy.LongWidth,request.Policy.LongHeight,request.Policy.LongFrameRate):(request.Policy.ShortWidth,request.Policy.ShortHeight,request.Policy.ShortFrameRate);
            foreach(var scene in variant.Scenes)
            {
                foreach(var prompt in scene.VisualPrompts) visuals.Add(New(prompt.VisualPromptId+".asset.visual",MapType(prompt.VisualType),request.Policy.VisualImageFormat,variant,scene,prompt.VisualPromptId,MapCapability(prompt.VisualType),prompt.Sequence,w,h,scene.Timing.PlannedDurationMilliseconds,f,0,0,prompt.KnowledgeReferences,request.Metadata.CorrelationId));
                foreach(var narration in scene.Narration) narrations.Add(New(narration.NarrationId+".asset.audio",DocumentaryMediaAssetType.NarrationAudio,request.Policy.NarrationMasterFormat,variant,scene,narration.NarrationId,DocumentaryMediaProviderCapability.TextToSpeech,narration.Sequence,0,0,narration.EstimatedDurationMilliseconds,0,request.Policy.AudioSampleRate,request.Policy.AudioChannelCount,narration.KnowledgeReferences,request.Metadata.CorrelationId));
                var subtitle=New(scene.SceneId+".asset.subtitle",DocumentaryMediaAssetType.SubtitleDocument,request.Policy.SubtitleFormat,variant,scene,scene.SceneId+".subtitle-cues",DocumentaryMediaProviderCapability.SubtitleGeneration,scene.Sequence,0,0,scene.Timing.NarrationDurationMilliseconds,0,0,0,scene.KnowledgeReferences,request.Metadata.CorrelationId); subtitles.Add(subtitle);
                var sceneVideo=New(scene.SceneId+".asset.video",DocumentaryMediaAssetType.SceneVideo,request.Policy.VideoFormat,variant,scene,scene.SceneId,DocumentaryMediaProviderCapability.SceneComposition,scene.Sequence,w,h,scene.Timing.PlannedDurationMilliseconds,f,request.Policy.AudioSampleRate,request.Policy.AudioChannelCount,scene.KnowledgeReferences,request.Metadata.CorrelationId); scenes.Add(sceneVideo);
                foreach(var target in visuals.Where(x=>x.SceneId==scene.SceneId).Concat(narrations.Where(x=>x.SceneId==scene.SceneId)).Append(subtitle)) deps.Add(Dep(sceneVideo.AssetId,target.AssetId,deps.Count,request.Metadata.CorrelationId));
            }
            var output=New(variant.VariantId+".asset.video",DocumentaryMediaAssetType.VariantVideo,request.Policy.VideoFormat,variant,null,variant.VariantId,DocumentaryMediaProviderCapability.VideoComposition,variant.VariantType.GetHashCode(),w,h,variant.PlannedDurationMilliseconds,f,request.Policy.AudioSampleRate,request.Policy.AudioChannelCount,variant.Scenes.SelectMany(x=>x.KnowledgeReferences).ToArray(),request.Metadata.CorrelationId);
            foreach(var scene in scenes)deps.Add(Dep(output.AssetId,scene.AssetId,deps.Count,request.Metadata.CorrelationId));
            var va=visuals.Concat(narrations).Concat(subtitles).Concat(scenes).Append(output).ToArray();all.AddRange(va);variants.Add(new(variant.VariantId+".execution-plan",variant.VariantId,variant.VariantType,visuals,narrations,subtitles,scenes,output,va.Length,deps.Count(x=>va.Any(a=>a.AssetId==x.SourceAssetId)),request.Metadata.CorrelationId));
        }
        return new(request.Metadata.ExecutionId+".plan",request.MediaProject.MediaProjectId,request.Metadata.ExecutionId,variants,all,deps,variants.Count,all.Count,deps.Count,request.Metadata.CorrelationId,true);
    }
    static DocumentaryMediaAssetPlan New(string id,DocumentaryMediaAssetType t,DocumentaryMediaAssetFormat fmt,DocumentaryMediaVariant v,DocumentaryMediaScene? s,string source,DocumentaryMediaProviderCapability cap,int seq,int w,int h,long d,int fps,int sample,int channels,IReadOnlyList<DocumentaryMediaKnowledgeReference> refs,string correlation)=>new(id,t,fmt,v.VariantType,s?.SceneId,source,cap,seq,Array.Empty<DocumentaryMediaAssetDependency>(),w,h,d,fps,sample,channels,refs,correlation);
    static DocumentaryMediaAssetDependency Dep(string source,string target,int seq,string c)=>new(source+".depends-on."+target,source,target,seq,c);
    static DocumentaryMediaProviderCapability MapCapability(DocumentaryMediaVisualType t)=>t switch { DocumentaryMediaVisualType.SkySimulation=>DocumentaryMediaProviderCapability.SkySimulation,DocumentaryMediaVisualType.StarChart=>DocumentaryMediaProviderCapability.StarChart,DocumentaryMediaVisualType.TelescopeView=>DocumentaryMediaProviderCapability.TelescopeView,DocumentaryMediaVisualType.OrbitalDiagram or DocumentaryMediaVisualType.ScientificDiagram or DocumentaryMediaVisualType.Map or DocumentaryMediaVisualType.Timeline=>DocumentaryMediaProviderCapability.ScientificDiagram,DocumentaryMediaVisualType.HistoricalIllustration=>DocumentaryMediaProviderCapability.HistoricalIllustration,_=>DocumentaryMediaProviderCapability.GeneratedIllustration};
    static DocumentaryMediaAssetType MapType(DocumentaryMediaVisualType t)=>t switch {DocumentaryMediaVisualType.SkySimulation=>DocumentaryMediaAssetType.SkySimulationImage,DocumentaryMediaVisualType.StarChart=>DocumentaryMediaAssetType.StarChartImage,DocumentaryMediaVisualType.TelescopeView=>DocumentaryMediaAssetType.TelescopeViewImage,DocumentaryMediaVisualType.OrbitalDiagram or DocumentaryMediaVisualType.ScientificDiagram or DocumentaryMediaVisualType.Map or DocumentaryMediaVisualType.Timeline=>DocumentaryMediaAssetType.ScientificDiagramImage,DocumentaryMediaVisualType.HistoricalIllustration=>DocumentaryMediaAssetType.HistoricalIllustrationImage,_=>DocumentaryMediaAssetType.VisualImage};
}
