namespace Astronomy.MediaFactory.Core.DocumentaryBlueprint;

public static class DocumentaryMediaProjectionValidator
{
    public static bool PolicyValid(DocumentaryMediaProjectionPolicy? p)=>p is not null&&p.RequireCompleteMaterialization&&p.RequireFourCanonicalVariants&&p.RequireCanonicalVariantOrdering&&p.RequireCanonicalSceneOrdering&&p.RequireExactCorrelation&&p.RequireDeterministicIdentity&&p.RequireNarrativeTraceability&&p.RequireSubtitleTraceability&&p.RequireVisualTraceability&&p.RequireTimingConsistency&&p.RequiredVariantTypes.SequenceEqual(DocumentaryMediaProjectionInventory.Variants)&&p.SupportedLanguages.SequenceEqual(DocumentaryMediaProjectionInventory.Languages)&&p.SupportedFormats.SequenceEqual(DocumentaryMediaProjectionInventory.Formats)&&p.SupportedTopicFamilies.SequenceEqual(DocumentaryMediaProjectionInventory.TopicFamilies)&&p.LongMinimumSceneCount>=1&&p.LongMaximumSceneCount>=p.LongMinimumSceneCount&&p.ShortMinimumSceneCount>=1&&p.ShortMaximumSceneCount>=p.ShortMinimumSceneCount&&p.LongMinimumDurationSeconds>=1&&p.LongMaximumDurationSeconds>=p.LongMinimumDurationSeconds&&p.ShortMinimumDurationSeconds>=1&&p.ShortMaximumDurationSeconds>=p.ShortMinimumDurationSeconds&&p.MaximumNarrationCharactersPerScene>=1&&p.MaximumSubtitleCharactersPerLine>=1&&p.MaximumSubtitleLines is 1 or 2&&p.PolicySchemaVersion=="1.0";

    internal static IReadOnlyList<DocumentaryMediaProjectionRejectionReason> ValidateRequest(DocumentaryMediaProjectionRequest request)
    {
        var r=request.MaterializationRecord;var reasons=new List<DocumentaryMediaProjectionRejectionReason>();
        if(!r.IsComplete)reasons.Add(DocumentaryMediaProjectionRejectionReason.MaterializationRecordNotComplete);
        if(r.MaterializationId!=$"{r.ExportSpecificationId}.materialization")reasons.Add(DocumentaryMediaProjectionRejectionReason.MaterializationIdentityMismatch);
        if(r.ExportSpecificationId!=r.ExportSpecification.ExportSpecificationId)reasons.Add(DocumentaryMediaProjectionRejectionReason.ExportSpecificationIdentityMismatch);
        if(r.CertificationId!=r.CertificationRecord.CertificationId)reasons.Add(DocumentaryMediaProjectionRejectionReason.CertificationIdentityMismatch);
        if(r.ProvenanceId!=r.ProvenanceRecord.ProvenanceId)reasons.Add(DocumentaryMediaProjectionRejectionReason.ProvenanceIdentityMismatch);
        if(r.PackageId!=r.ProductionPackage.PackageId)reasons.Add(DocumentaryMediaProjectionRejectionReason.PackageIdentityMismatch);
        var c=request.Metadata.CorrelationId;var correlations=new[]{request.TopicProfile.CorrelationId,r.Metadata.CorrelationId,r.Manifest.CorrelationId}.Concat(r.Payloads.Select(x=>x.CorrelationId)).Concat(r.Payloads.SelectMany(x=>x.Dependencies).Select(x=>x.CorrelationId));
        if(correlations.Any(x=>!DocumentaryMediaProjectionInventory.Eq(x,c)))reasons.Add(DocumentaryMediaProjectionRejectionReason.CorrelationMismatch);
        if(!PolicyValid(request.Policy))reasons.Add(DocumentaryMediaProjectionRejectionReason.ProjectionPolicyRejected);
        if(!Enum.IsDefined(request.TopicProfile.TopicFamily)||!request.Policy.SupportedTopicFamilies.Contains(request.TopicProfile.TopicFamily))reasons.Add(DocumentaryMediaProjectionRejectionReason.TopicProfileRejected);
        return reasons.Distinct().OrderBy(x=>(int)x).ToArray();
    }

    internal static IReadOnlyList<DocumentaryMediaProjectionRejectionReason> ValidateVariants(DocumentaryMediaProjectionRequest request,IReadOnlyList<DocumentaryMediaVariant> variants)
    {
        var reasons=new List<DocumentaryMediaProjectionRejectionReason>();var expected=DocumentaryMediaProjectionInventory.Variants;
        if(expected.Any(x=>variants.All(v=>v.VariantType!=x)))reasons.Add(DocumentaryMediaProjectionRejectionReason.RequiredVariantMissing);
        if(variants.Count!=expected.Length)reasons.Add(DocumentaryMediaProjectionRejectionReason.VariantInventoryMismatch);
        if(variants.Any(v=>!Enum.IsDefined(v.VariantType)))reasons.Add(DocumentaryMediaProjectionRejectionReason.UnsupportedVariantPresent);
        if(!variants.Select(v=>v.VariantType).SequenceEqual(expected))reasons.Add(DocumentaryMediaProjectionRejectionReason.VariantOrderMismatch);
        var projectId=$"{request.MaterializationRecord.MaterializationId}.media-project";
        foreach(var v in variants.Where(v=>Enum.IsDefined(v.VariantType))){var mapping=DocumentaryMediaProjectionInventory.Mapping(v.VariantType);if(v.VariantId!=$"{projectId}.{v.VariantType}"||v.Format!=mapping.Format||v.Language!=mapping.Language||!DocumentaryMediaProjectionInventory.Eq(v.CorrelationId,request.Metadata.CorrelationId))reasons.Add(DocumentaryMediaProjectionRejectionReason.VariantIdentityMismatch);var aspect=mapping.Format==DocumentaryVideoFormat.Long?"16:9":"9:16";if(v.AspectRatio!=aspect||string.IsNullOrWhiteSpace(v.Title)||string.IsNullOrWhiteSpace(v.Description)||string.IsNullOrWhiteSpace(v.Hook))reasons.Add(DocumentaryMediaProjectionRejectionReason.VariantInventoryMismatch);reasons.AddRange(ValidateScenes(request,v,v.Scenes,request.Policy));}
        return reasons.Distinct().OrderBy(x=>(int)x).ToArray();
    }

    internal static IReadOnlyList<DocumentaryMediaProjectionRejectionReason> ValidateScenes(DocumentaryMediaProjectionRequest request,DocumentaryMediaVariant variant,IReadOnlyList<DocumentaryMediaScene> scenes,DocumentaryMediaProjectionPolicy policy)
    {
        var r=new List<DocumentaryMediaProjectionRejectionReason>();var map=DocumentaryMediaProjectionInventory.Mapping(variant.VariantType);var min=map.Format==DocumentaryVideoFormat.Long?policy.LongMinimumSceneCount:policy.ShortMinimumSceneCount;var max=map.Format==DocumentaryVideoFormat.Long?policy.LongMaximumSceneCount:policy.ShortMaximumSceneCount;
        if(scenes.Count<min||scenes.Count>max||variant.SceneCount!=scenes.Count)r.Add(DocumentaryMediaProjectionRejectionReason.SceneInventoryMismatch);
        if(!scenes.Select(s=>s.Sequence).SequenceEqual(Enumerable.Range(0,scenes.Count)))r.Add(DocumentaryMediaProjectionRejectionReason.SceneOrderMismatch);
        long start=0;for(var i=0;i<scenes.Count;i++){var s=scenes[i];if(s.SceneId!=$"{variant.VariantId}.scene.{i}"||s.VariantType!=variant.VariantType||!DocumentaryMediaProjectionInventory.Eq(s.CorrelationId,request.Metadata.CorrelationId))r.Add(DocumentaryMediaProjectionRejectionReason.SceneIdentityMismatch);
            if(s.Narration.Count==0||!s.Narration.Select(x=>x.Sequence).SequenceEqual(Enumerable.Range(0,s.Narration.Count))||s.Narration.Any(n=>n.NarrationId!=$"{s.SceneId}.narration.{n.Sequence}"||n.Language!=variant.Language||n.Text.Length>policy.MaximumNarrationCharactersPerScene||!ReferencesValid(request,n.KnowledgeReferences)))r.Add(DocumentaryMediaProjectionRejectionReason.NarrativeMappingMismatch);
            var narration=s.Narration.SingleOrDefault();var reconstructed=string.Join(" ",s.SubtitleCues.OrderBy(x=>x.Sequence).Select(x=>x.Text));if(s.SubtitleCues.Count==0||narration is null||!Normalize(reconstructed).Equals(Normalize(narration?.Text??""),StringComparison.Ordinal)||!s.SubtitleCues.Select(x=>x.Sequence).SequenceEqual(Enumerable.Range(0,s.SubtitleCues.Count))||s.SubtitleCues.Any((c)=>c.SubtitleCueId!=$"{s.SceneId}.subtitle.{c.Sequence}"||c.Language!=variant.Language||c.NarrationId!=narration?.NarrationId||c.Line1.Length>policy.MaximumSubtitleCharactersPerLine||(c.Line2?.Length??0)>policy.MaximumSubtitleCharactersPerLine||Normalize(c.Text)!=Normalize(string.Join(" ",new[]{c.Line1,c.Line2}.Where(x=>x is not null)))||!ReferencesValid(request,c.KnowledgeReferences))||s.SubtitleCues.Zip(s.SubtitleCues.Skip(1),(a,b)=>a.EndOffsetMilliseconds>b.StartOffsetMilliseconds).Any(x=>x)||s.SubtitleCues[0].StartOffsetMilliseconds!=0||s.SubtitleCues[^1].EndOffsetMilliseconds!=narration?.EstimatedDurationMilliseconds)r.Add(DocumentaryMediaProjectionRejectionReason.SubtitleMappingMismatch);
            if(s.VisualPrompts.Count==0||!s.VisualPrompts.Select(x=>x.Sequence).SequenceEqual(Enumerable.Range(0,s.VisualPrompts.Count))||s.VisualPrompts.Any(v=>v.VisualPromptId!=$"{s.SceneId}.visual.{v.Sequence}"||v.AspectRatio!=variant.AspectRatio||!ReferencesValid(request,v.KnowledgeReferences)))r.Add(DocumentaryMediaProjectionRejectionReason.VisualPromptMappingMismatch);
            if(s.Timing.TimingId!=$"{s.SceneId}.timing"||s.Timing.PlannedStartMilliseconds!=start||s.Timing.PlannedEndMilliseconds-s.Timing.PlannedStartMilliseconds!=s.Timing.PlannedDurationMilliseconds||!DocumentaryMediaProjectionInventory.Eq(s.Timing.CorrelationId,request.Metadata.CorrelationId))r.Add(DocumentaryMediaProjectionRejectionReason.TimingPlanMismatch);start=s.Timing.PlannedEndMilliseconds;}
        var minMs=(map.Format==DocumentaryVideoFormat.Long?policy.LongMinimumDurationSeconds:policy.ShortMinimumDurationSeconds)*1000L;var maxMs=(map.Format==DocumentaryVideoFormat.Long?policy.LongMaximumDurationSeconds:policy.ShortMaximumDurationSeconds)*1000L;if(start<minMs||start>maxMs||variant.PlannedDurationMilliseconds!=start)r.Add(DocumentaryMediaProjectionRejectionReason.TimingPlanMismatch);
        return r.Distinct().OrderBy(x=>(int)x).ToArray();
    }
    private static string Normalize(string value)=>string.Join(" ",value.Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries));
    private static bool ReferencesValid(DocumentaryMediaProjectionRequest request,IReadOnlyList<DocumentaryMediaKnowledgeReference> references)
    {if(references.Count==0||!references.Select(x=>x.Sequence).SequenceEqual(Enumerable.Range(0,references.Count)))return false;foreach(var reference in references){var payload=request.MaterializationRecord.Payloads.SingleOrDefault(x=>x.PayloadId==reference.PayloadId);if(payload is null||payload.PayloadType!=reference.PayloadType||payload.SourceItemId!=reference.SourceItemId||payload.ArtifactIdentity!=reference.ArtifactIdentity||payload.ArtifactVersion!=reference.ArtifactVersion||payload.CorrelationId!=reference.CorrelationId||string.IsNullOrWhiteSpace(reference.JsonPointer)||!reference.JsonPointer.StartsWith("/",StringComparison.Ordinal)||!PointerResolves(payload.Content,reference.JsonPointer))return false;}return true;}
    private static bool PointerResolves(string content,string pointer){try{using var document=System.Text.Json.JsonDocument.Parse(content);var current=document.RootElement;if(pointer=="/")return true;foreach(var token in pointer.Split('/').Skip(1).Select(x=>x.Replace("~1","/",StringComparison.Ordinal).Replace("~0","~",StringComparison.Ordinal))){if(current.ValueKind==System.Text.Json.JsonValueKind.Object){if(!current.TryGetProperty(token,out current))return false;}else if(current.ValueKind==System.Text.Json.JsonValueKind.Array&&int.TryParse(token,out var index)&&index>=0&&index<current.GetArrayLength())current=current[index];else return false;}return true;}catch(System.Text.Json.JsonException){return false;}}
    public static bool ProjectValid(DocumentaryMediaProject? p)
    {if(p is null||!p.IsComplete||p.MediaProjectId!=$"{p.MaterializationId}.media-project"||p.MaterializationId!=p.MaterializationRecord.MaterializationId||p.ExportSpecificationId!=p.ExportSpecification.ExportSpecificationId||p.CertificationId!=p.CertificationRecord.CertificationId||p.ProvenanceId!=p.ProvenanceRecord.ProvenanceId||p.PackageId!=p.ProductionPackage.PackageId||p.ReleaseCandidateId!=p.MaterializationRecord.ReleaseCandidateId||p.ConvergenceId!=p.MaterializationRecord.ConvergenceId||p.TopicId!=p.TopicProfile.TopicId||!ValueEqual(p.ExportSpecification,p.MaterializationRecord.ExportSpecification)||!ValueEqual(p.CertificationRecord,p.MaterializationRecord.CertificationRecord)||!ValueEqual(p.ProvenanceRecord,p.MaterializationRecord.ProvenanceRecord)||!ValueEqual(p.ProductionPackage,p.MaterializationRecord.ProductionPackage)||p.VariantCount!=p.Variants.Count||p.TotalSceneCount!=p.Variants.Sum(x=>x.SceneCount)||p.TotalPlannedDurationMilliseconds!=p.Variants.Sum(x=>x.PlannedDurationMilliseconds))return false;var request=new DocumentaryMediaProjectionRequest(p.MaterializationRecord,p.Policy,p.Metadata,p.TopicProfile);return ValidateRequest(request).Count==0&&ValidateVariants(request,p.Variants).Count==0;}
    private static bool ValueEqual<T>(T left,T right)=>ReferenceEquals(left,right)||System.Text.Json.JsonSerializer.Serialize(left)==System.Text.Json.JsonSerializer.Serialize(right);
}
