namespace Astronomy.MediaFactory.Core.DocumentaryBlueprint;

public sealed class DocumentaryCertificationPolicy
{
    public DocumentaryCertificationPolicy(bool requireCompleteProductionPackage,bool requireCompleteProvenanceRecord,bool requireDeterministicIdentity,bool requireCanonicalManifest,bool requireCanonicalArtifactInventory,bool requireCanonicalRelationshipInventory,bool requireCompleteLineage,bool requireExactCorrelation,bool requireDeterministicReconstruction,bool requireImmutability,bool requireOperationBoundaryCompliance,bool requireForbiddenCapabilityCompliance,bool requireDocumentationCompliance,bool requireUpstreamCertification,IReadOnlyList<DocumentaryCertificationDomain> requiredDomains,IReadOnlyList<DocumentaryCertificationRule> requiredRules,string policySchemaVersion)
    {
        if(new[]{requireCompleteProductionPackage,requireCompleteProvenanceRecord,requireDeterministicIdentity,requireCanonicalManifest,requireCanonicalArtifactInventory,requireCanonicalRelationshipInventory,requireCompleteLineage,requireExactCorrelation,requireDeterministicReconstruction,requireImmutability,requireOperationBoundaryCompliance,requireForbiddenCapabilityCompliance,requireDocumentationCompliance,requireUpstreamCertification}.Any(x=>!x))throw new ArgumentException("Policy 1.0 requires every certification control.");
        if(requiredDomains is null||!requiredDomains.SequenceEqual(DocumentaryCertificationInventory.Domains))throw new ArgumentException("Domains must be the canonical inventory.",nameof(requiredDomains));
        if(requiredRules is null||!requiredRules.SequenceEqual(DocumentaryCertificationInventory.Rules))throw new ArgumentException("Rules must be the canonical inventory.",nameof(requiredRules));
        PolicySchemaVersion=policySchemaVersion=="1.0"?policySchemaVersion:throw new ArgumentException("Policy schema must be 1.0.",nameof(policySchemaVersion));
        RequireCompleteProductionPackage=requireCompleteProductionPackage;RequireCompleteProvenanceRecord=requireCompleteProvenanceRecord;RequireDeterministicIdentity=requireDeterministicIdentity;RequireCanonicalManifest=requireCanonicalManifest;RequireCanonicalArtifactInventory=requireCanonicalArtifactInventory;RequireCanonicalRelationshipInventory=requireCanonicalRelationshipInventory;RequireCompleteLineage=requireCompleteLineage;RequireExactCorrelation=requireExactCorrelation;RequireDeterministicReconstruction=requireDeterministicReconstruction;RequireImmutability=requireImmutability;RequireOperationBoundaryCompliance=requireOperationBoundaryCompliance;RequireForbiddenCapabilityCompliance=requireForbiddenCapabilityCompliance;RequireDocumentationCompliance=requireDocumentationCompliance;RequireUpstreamCertification=requireUpstreamCertification;RequiredDomains=DocumentaryCertificationInventory.Copy(requiredDomains,nameof(requiredDomains));RequiredRules=DocumentaryCertificationInventory.Copy(requiredRules,nameof(requiredRules));
    }
    public bool RequireCompleteProductionPackage{get;} public bool RequireCompleteProvenanceRecord{get;} public bool RequireDeterministicIdentity{get;} public bool RequireCanonicalManifest{get;} public bool RequireCanonicalArtifactInventory{get;} public bool RequireCanonicalRelationshipInventory{get;} public bool RequireCompleteLineage{get;} public bool RequireExactCorrelation{get;} public bool RequireDeterministicReconstruction{get;} public bool RequireImmutability{get;} public bool RequireOperationBoundaryCompliance{get;} public bool RequireForbiddenCapabilityCompliance{get;} public bool RequireDocumentationCompliance{get;} public bool RequireUpstreamCertification{get;} public IReadOnlyList<DocumentaryCertificationDomain> RequiredDomains{get;} public IReadOnlyList<DocumentaryCertificationRule> RequiredRules{get;} public string PolicySchemaVersion{get;}
}
public sealed class DocumentaryCertificationMetadata
{
    public DocumentaryCertificationMetadata(DateTimeOffset evaluatedUtc,string evaluatedBy,string certificationSchemaVersion,string correlationId){EvaluatedUtc=evaluatedUtc!=default?evaluatedUtc:throw new ArgumentException("Timestamp is required.",nameof(evaluatedUtc));EvaluatedBy=Guard.Required(evaluatedBy,nameof(evaluatedBy));CertificationSchemaVersion=certificationSchemaVersion=="1.0"?certificationSchemaVersion:throw new ArgumentException("Schema must be 1.0.",nameof(certificationSchemaVersion));CorrelationId=Guard.Required(correlationId,nameof(correlationId));}
    public DateTimeOffset EvaluatedUtc{get;} public string EvaluatedBy{get;} public string CertificationSchemaVersion{get;} public string CorrelationId{get;}
}
public sealed class DocumentaryUpstreamCertificationEvidence
{
    public DocumentaryUpstreamCertificationEvidence(string objectiveId,string objectiveVersion,bool isCertified,int sequence,string correlationId){ObjectiveId=Guard.Required(objectiveId,nameof(objectiveId));ObjectiveVersion=Guard.Required(objectiveVersion,nameof(objectiveVersion));if(!isCertified)throw new ArgumentException("Upstream objective must be certified.",nameof(isCertified));if(sequence<0)throw new ArgumentOutOfRangeException(nameof(sequence));if(sequence>=13||DocumentaryCertificationInventory.Objectives[sequence]!=objectiveId||objectiveVersion!="1.0")throw new ArgumentException("Objective identity, version, and sequence must be canonical.");CorrelationId=Guard.Required(correlationId,nameof(correlationId));IsCertified=true;Sequence=sequence;}
    public string ObjectiveId{get;} public string ObjectiveVersion{get;} public bool IsCertified{get;} public int Sequence{get;} public string CorrelationId{get;}
}
public sealed class DocumentaryCertificationDocumentationEvidence
{
    public DocumentaryCertificationDocumentationEvidence(string documentId,string documentVersion,IReadOnlyList<string> requiredStatements,int sequence,string correlationId){DocumentId=Guard.Required(documentId,nameof(documentId));DocumentVersion=Guard.Required(documentVersion,nameof(documentVersion));if(sequence<0)throw new ArgumentOutOfRangeException(nameof(sequence));ArgumentNullException.ThrowIfNull(requiredStatements);if(requiredStatements.Count==0||requiredStatements.Any(string.IsNullOrWhiteSpace)||requiredStatements.Distinct(StringComparer.Ordinal).Count()!=requiredStatements.Count)throw new ArgumentException("Statements must be nonblank and unique.",nameof(requiredStatements));if(sequence>=4||DocumentaryCertificationInventory.DocumentIds[sequence]!=documentId||documentVersion!="1.0"||!requiredStatements.SequenceEqual(DocumentaryCertificationInventory.Statements[sequence]))throw new ArgumentException("Documentation evidence must be canonical.");CorrelationId=Guard.Required(correlationId,nameof(correlationId));RequiredStatements=DocumentaryCertificationInventory.Copy(requiredStatements,nameof(requiredStatements));Sequence=sequence;}
    public string DocumentId{get;} public string DocumentVersion{get;} public IReadOnlyList<string> RequiredStatements{get;} public int Sequence{get;} public string CorrelationId{get;}
}
public sealed class DocumentaryCertificationRequest
{
    public DocumentaryCertificationRequest(DocumentaryProvenanceRecord provenanceRecord,DocumentaryCertificationPolicy policy,DocumentaryCertificationMetadata metadata,IReadOnlyList<DocumentaryUpstreamCertificationEvidence> upstreamCertificationEvidence,IReadOnlyList<DocumentaryCertificationDocumentationEvidence> documentationEvidence){ProvenanceRecord=provenanceRecord??throw new ArgumentNullException(nameof(provenanceRecord));Policy=policy??throw new ArgumentNullException(nameof(policy));Metadata=metadata??throw new ArgumentNullException(nameof(metadata));UpstreamCertificationEvidence=DocumentaryCertificationInventory.Copy(upstreamCertificationEvidence,nameof(upstreamCertificationEvidence));DocumentationEvidence=DocumentaryCertificationInventory.Copy(documentationEvidence,nameof(documentationEvidence));}
    public DocumentaryProvenanceRecord ProvenanceRecord{get;} public DocumentaryCertificationPolicy Policy{get;} public DocumentaryCertificationMetadata Metadata{get;} public IReadOnlyList<DocumentaryUpstreamCertificationEvidence> UpstreamCertificationEvidence{get;} public IReadOnlyList<DocumentaryCertificationDocumentationEvidence> DocumentationEvidence{get;}
}
public sealed class DocumentaryCertificationFinding
{
    public DocumentaryCertificationFinding(string findingId,DocumentaryCertificationDomain domain,DocumentaryCertificationRule rule,DocumentaryCertificationSeverity severity,string messageCode,string evidenceIdentity,int sequence,string correlationId){FindingId=Guard.Required(findingId,nameof(findingId));Guard.Enum(domain,nameof(domain));Guard.Enum(rule,nameof(rule));if(domain!=DocumentaryCertificationInventory.DomainFor(rule))throw new ArgumentException("Domain is not canonical for the rule.",nameof(domain));if(severity!=DocumentaryCertificationSeverity.Error)throw new ArgumentException("Severity must be Error.",nameof(severity));MessageCode=Guard.Required(messageCode,nameof(messageCode));if(messageCode!=DocumentaryCertificationInventory.MessageCodeFor(rule))throw new ArgumentException("Message code is not canonical for the rule.",nameof(messageCode));EvidenceIdentity=Guard.Required(evidenceIdentity,nameof(evidenceIdentity));if(findingId!=$"{rule}.{evidenceIdentity}")throw new ArgumentException("Finding identity is inconsistent.",nameof(findingId));if(sequence<0)throw new ArgumentOutOfRangeException(nameof(sequence));CorrelationId=Guard.Required(correlationId,nameof(correlationId));Domain=domain;Rule=rule;Severity=severity;Sequence=sequence;}
    public string FindingId{get;} public DocumentaryCertificationDomain Domain{get;} public DocumentaryCertificationRule Rule{get;} public DocumentaryCertificationSeverity Severity{get;} public string MessageCode{get;} public string EvidenceIdentity{get;} public int Sequence{get;} public string CorrelationId{get;}
}
public sealed class DocumentaryCertificationRuleResult
{
    public DocumentaryCertificationRuleResult(DocumentaryCertificationRule rule,DocumentaryCertificationDomain domain,bool passed,IReadOnlyList<DocumentaryCertificationFinding> findings,int sequence,string correlationId){Guard.Enum(rule,nameof(rule));Guard.Enum(domain,nameof(domain));if(domain!=DocumentaryCertificationInventory.DomainFor(rule))throw new ArgumentException("Domain is not canonical for the rule.",nameof(domain));if(sequence<0)throw new ArgumentOutOfRangeException(nameof(sequence));CorrelationId=Guard.Required(correlationId,nameof(correlationId));var copy=DocumentaryCertificationInventory.Copy(findings,nameof(findings));if(passed?copy.Count!=0:copy.Count==0)throw new ArgumentException("Pass state and findings disagree.");if(copy.Any(x=>x.Rule!=rule||x.Domain!=domain||!DocumentaryCertificationInventory.Eq(x.CorrelationId,correlationId))||copy.Select(x=>x.FindingId).Distinct(StringComparer.Ordinal).Count()!=copy.Count||!copy.Select(x=>x.Sequence).SequenceEqual(Enumerable.Range(0,copy.Count)))throw new ArgumentException("Findings must be matching, unique, and ordered.");Rule=rule;Domain=domain;Passed=passed;Findings=copy;Sequence=sequence;}
    public DocumentaryCertificationRule Rule{get;} public DocumentaryCertificationDomain Domain{get;} public bool Passed{get;} public IReadOnlyList<DocumentaryCertificationFinding> Findings{get;} public int Sequence{get;} public string CorrelationId{get;}
}
public sealed class DocumentaryCertificationDecision
{
    public DocumentaryCertificationDecision(DocumentaryCertificationStatus status,IReadOnlyList<DocumentaryCertificationRuleResult> ruleResults,IReadOnlyList<DocumentaryCertificationFinding> findings,int passedRuleCount,int failedRuleCount,int totalRuleCount){Guard.Enum(status,nameof(status));var rr=DocumentaryCertificationInventory.Copy(ruleResults,nameof(ruleResults));var ff=DocumentaryCertificationInventory.Copy(findings,nameof(findings));if(rr.Count!=22||!rr.Select(x=>x.Rule).SequenceEqual(DocumentaryCertificationInventory.Rules)||!rr.Select(x=>x.Sequence).SequenceEqual(Enumerable.Range(0,22))||rr.Select(x=>x.CorrelationId).Distinct(StringComparer.Ordinal).Count()!=1)throw new ArgumentException("Rule results must be complete and canonical.");var flat=rr.SelectMany(x=>x.Findings).ToArray();if(!flat.SequenceEqual(ff,FindingComparer.Instance))throw new ArgumentException("Findings must be the canonical flattening.");if(passedRuleCount!=rr.Count(x=>x.Passed)||failedRuleCount!=rr.Count(x=>!x.Passed)||totalRuleCount!=22||passedRuleCount+failedRuleCount!=totalRuleCount)throw new ArgumentException("Counts are inconsistent.");if(status==DocumentaryCertificationStatus.Certified?(failedRuleCount!=0||ff.Count!=0):(failedRuleCount==0||ff.Count==0))throw new ArgumentException("Status is inconsistent.");Status=status;RuleResults=rr;Findings=ff;PassedRuleCount=passedRuleCount;FailedRuleCount=failedRuleCount;TotalRuleCount=totalRuleCount;}
    private sealed class FindingComparer:IEqualityComparer<DocumentaryCertificationFinding>{internal static readonly FindingComparer Instance=new();public bool Equals(DocumentaryCertificationFinding? x,DocumentaryCertificationFinding? y)=>x is not null&&y is not null&&x.FindingId==y.FindingId&&x.Domain==y.Domain&&x.Rule==y.Rule&&x.Severity==y.Severity&&x.MessageCode==y.MessageCode&&x.EvidenceIdentity==y.EvidenceIdentity&&x.Sequence==y.Sequence&&x.CorrelationId==y.CorrelationId;public int GetHashCode(DocumentaryCertificationFinding value)=>HashCode.Combine(value.FindingId,value.Domain,value.Rule,value.Severity,value.MessageCode,value.EvidenceIdentity,value.Sequence,value.CorrelationId);}
    public DocumentaryCertificationStatus Status{get;} public IReadOnlyList<DocumentaryCertificationRuleResult> RuleResults{get;} public IReadOnlyList<DocumentaryCertificationFinding> Findings{get;} public int PassedRuleCount{get;} public int FailedRuleCount{get;} public int TotalRuleCount{get;} public bool IsCertified=>Status==DocumentaryCertificationStatus.Certified; public bool IsNonCompliant=>!IsCertified;
}
public sealed class DocumentaryCertificationRecord
{
    public DocumentaryCertificationRecord(string certificationId,DocumentaryProvenanceRecord provenanceRecord,DocumentaryProductionPackage productionPackage,DocumentaryCertificationPolicy policy,DocumentaryCertificationMetadata metadata,IReadOnlyList<DocumentaryUpstreamCertificationEvidence> upstreamCertificationEvidence,IReadOnlyList<DocumentaryCertificationDocumentationEvidence> documentationEvidence,DocumentaryCertificationDecision decision,string packageId,string provenanceId,string releaseCandidateId,string convergenceId,int passedRuleCount,int failedRuleCount,int totalRuleCount,bool isCertified)
    { CertificationId=Guard.Required(certificationId,nameof(certificationId));ProvenanceRecord=provenanceRecord??throw new ArgumentNullException(nameof(provenanceRecord));ProductionPackage=productionPackage??throw new ArgumentNullException(nameof(productionPackage));Policy=policy??throw new ArgumentNullException(nameof(policy));Metadata=metadata??throw new ArgumentNullException(nameof(metadata));Decision=decision??throw new ArgumentNullException(nameof(decision));UpstreamCertificationEvidence=DocumentaryCertificationInventory.Copy(upstreamCertificationEvidence,nameof(upstreamCertificationEvidence));DocumentationEvidence=DocumentaryCertificationInventory.Copy(documentationEvidence,nameof(documentationEvidence));PackageId=Guard.Required(packageId,nameof(packageId));ProvenanceId=Guard.Required(provenanceId,nameof(provenanceId));ReleaseCandidateId=Guard.Required(releaseCandidateId,nameof(releaseCandidateId));ConvergenceId=Guard.Required(convergenceId,nameof(convergenceId));var correlation=metadata.CorrelationId;var correlationOk=DocumentaryCertificationInventory.Eq(productionPackage.Metadata.CorrelationId,correlation)&&DocumentaryCertificationInventory.Eq(provenanceRecord.Metadata.CorrelationId,correlation)&&provenanceRecord.ArtifactNodes.All(x=>DocumentaryCertificationInventory.Eq(x.CorrelationId,correlation))&&provenanceRecord.RelationshipEdges.All(x=>DocumentaryCertificationInventory.Eq(x.CorrelationId,correlation))&&UpstreamCertificationEvidence.All(x=>DocumentaryCertificationInventory.Eq(x.CorrelationId,correlation))&&DocumentationEvidence.All(x=>DocumentaryCertificationInventory.Eq(x.CorrelationId,correlation))&&decision.RuleResults.All(x=>DocumentaryCertificationInventory.Eq(x.CorrelationId,correlation));if(!isCertified||!decision.IsCertified||failedRuleCount!=0||passedRuleCount!=22||totalRuleCount!=22||certificationId!=$"{provenanceId}.certification"||provenanceId!=provenanceRecord.ProvenanceId||packageId!=productionPackage.PackageId||packageId!=provenanceRecord.PackageId||releaseCandidateId!=productionPackage.ReleaseCandidateId||convergenceId!=productionPackage.ConvergenceId||!correlationOk||!ReferenceEquals(productionPackage,provenanceRecord.ProductionPackage)&&!DocumentaryProductionPackageValidator.PackagesAreEquivalent(productionPackage,provenanceRecord.ProductionPackage))throw new ArgumentException("Certification record is inconsistent.");DocumentaryCertificationValidator.ValidateEvidence(metadata,UpstreamCertificationEvidence,DocumentationEvidence);DocumentaryProvenanceValidator.ValidateRecord(provenanceRecord);PassedRuleCount=passedRuleCount;FailedRuleCount=failedRuleCount;TotalRuleCount=totalRuleCount;IsCertified=true;}
    public string CertificationId{get;} public DocumentaryProvenanceRecord ProvenanceRecord{get;} public DocumentaryProductionPackage ProductionPackage{get;} public DocumentaryCertificationPolicy Policy{get;} public DocumentaryCertificationMetadata Metadata{get;} public IReadOnlyList<DocumentaryUpstreamCertificationEvidence> UpstreamCertificationEvidence{get;} public IReadOnlyList<DocumentaryCertificationDocumentationEvidence> DocumentationEvidence{get;} public DocumentaryCertificationDecision Decision{get;} public string PackageId{get;} public string ProvenanceId{get;} public string ReleaseCandidateId{get;} public string ConvergenceId{get;} public int PassedRuleCount{get;} public int FailedRuleCount{get;} public int TotalRuleCount{get;} public bool IsCertified{get;}
}
public sealed class DocumentaryCertificationEvaluationResult
{
    public DocumentaryCertificationEvaluationResult(DocumentaryCertificationStatus status,DocumentaryCertificationDecision decision,DocumentaryCertificationRecord? certificationRecord):this(status,decision,certificationRecord,null,null){}
    [System.Text.Json.Serialization.JsonConstructor]
    public DocumentaryCertificationEvaluationResult(DocumentaryCertificationStatus status,DocumentaryCertificationDecision decision,DocumentaryCertificationRecord? certificationRecord,DocumentaryProvenanceRecord? contextProvenance,DocumentaryCertificationMetadata? contextMetadata){Guard.Enum(status,nameof(status));Decision=decision??throw new ArgumentNullException(nameof(decision));if(status!=decision.Status||(status==DocumentaryCertificationStatus.Certified)!=(certificationRecord is not null))throw new ArgumentException("Evaluation result is inconsistent.");if(certificationRecord is not null&&!certificationRecord.IsCertified)throw new ArgumentException("Record must be certified.");Status=status;CertificationRecord=certificationRecord;ContextProvenance=certificationRecord?.ProvenanceRecord??contextProvenance;ContextMetadata=certificationRecord?.Metadata??contextMetadata;if(status==DocumentaryCertificationStatus.NonCompliant&&(ContextProvenance is null||ContextMetadata is null))throw new ArgumentException("Noncompliant results require reconstructable context.");}
    public DocumentaryProvenanceRecord? ContextProvenance{get;} public DocumentaryCertificationMetadata? ContextMetadata{get;}
    public DocumentaryCertificationStatus Status{get;} public DocumentaryCertificationDecision Decision{get;} public DocumentaryCertificationRecord? CertificationRecord{get;} public bool HasCertificationRecord=>CertificationRecord is not null; public bool IsCertified=>Status==DocumentaryCertificationStatus.Certified; public bool IsNonCompliant=>!IsCertified;
}
public sealed class DocumentaryCertificationSummary
{
    public DocumentaryCertificationSummary(string certificationId,string packageId,string provenanceId,string releaseCandidateId,string convergenceId,DocumentaryCertificationStatus status,int totalRuleCount,int passedRuleCount,int failedRuleCount,int findingCount,IReadOnlyList<DocumentaryCertificationDomain> evaluatedDomains,IReadOnlyList<DocumentaryCertificationRule> evaluatedRules,DateTimeOffset evaluatedUtc,string evaluatedBy,bool isCertified){CertificationId=Guard.Required(certificationId,nameof(certificationId));PackageId=Guard.Required(packageId,nameof(packageId));ProvenanceId=Guard.Required(provenanceId,nameof(provenanceId));ReleaseCandidateId=Guard.Required(releaseCandidateId,nameof(releaseCandidateId));ConvergenceId=Guard.Required(convergenceId,nameof(convergenceId));Guard.Enum(status,nameof(status));if(new[]{totalRuleCount,passedRuleCount,failedRuleCount,findingCount}.Any(x=>x<0)||totalRuleCount!=22||passedRuleCount+failedRuleCount!=22)throw new ArgumentException("Counts are inconsistent.");var domains=DocumentaryCertificationInventory.Copy(evaluatedDomains,nameof(evaluatedDomains));var rules=DocumentaryCertificationInventory.Copy(evaluatedRules,nameof(evaluatedRules));if(domains.Any(x=>!Enum.IsDefined(x))||!domains.SequenceEqual(DocumentaryCertificationInventory.EvaluatedDomains)||rules.Any(x=>!Enum.IsDefined(x))||!rules.SequenceEqual(DocumentaryCertificationInventory.Rules))throw new ArgumentException("Inventories are inconsistent.");if(evaluatedUtc==default)throw new ArgumentException("Timestamp is required.",nameof(evaluatedUtc));EvaluatedBy=Guard.Required(evaluatedBy,nameof(evaluatedBy));if(isCertified!=(status==DocumentaryCertificationStatus.Certified)||(isCertified?(failedRuleCount!=0||findingCount!=0):(failedRuleCount==0||findingCount==0)))throw new ArgumentException("Status is inconsistent.");Status=status;TotalRuleCount=totalRuleCount;PassedRuleCount=passedRuleCount;FailedRuleCount=failedRuleCount;FindingCount=findingCount;EvaluatedDomains=domains;EvaluatedRules=rules;EvaluatedUtc=evaluatedUtc;IsCertified=isCertified;}
    public string CertificationId{get;} public string PackageId{get;} public string ProvenanceId{get;} public string ReleaseCandidateId{get;} public string ConvergenceId{get;} public DocumentaryCertificationStatus Status{get;} public int TotalRuleCount{get;} public int PassedRuleCount{get;} public int FailedRuleCount{get;} public int FindingCount{get;} public IReadOnlyList<DocumentaryCertificationDomain> EvaluatedDomains{get;} public IReadOnlyList<DocumentaryCertificationRule> EvaluatedRules{get;} public DateTimeOffset EvaluatedUtc{get;} public string EvaluatedBy{get;} public bool IsCertified{get;}
}
