using System.Collections.ObjectModel;
using System.Text.Json.Serialization;

namespace Astronomy.MediaFactory.Core.DocumentaryBlueprint;

public sealed class DocumentaryMediaPipelinePolicy
{
    public DocumentaryMediaPipelinePolicy(DocumentaryMediaPipelineMode mode = DocumentaryMediaPipelineMode.PlanOnly, bool allowPartialCompletion = true, int maximumVisualAttempts = 1, int maximumNarrationAttempts = 1, int maximumCompositionAttempts = 1)
    {
        if (!Enum.IsDefined(mode) || maximumVisualAttempts < 1 || maximumNarrationAttempts < 1 || maximumCompositionAttempts < 1) throw new ArgumentOutOfRangeException();
        Mode=mode; AllowPartialCompletion=allowPartialCompletion; MaximumVisualAttempts=maximumVisualAttempts; MaximumNarrationAttempts=maximumNarrationAttempts; MaximumCompositionAttempts=maximumCompositionAttempts;
    }
    public DocumentaryMediaPipelineMode Mode{get;} public bool RequireCompleteMediaProject=>true; public bool RequireFourCanonicalVariants=>true; public bool RequireCanonicalVariantOrdering=>true; public bool RequireCanonicalSceneOrdering=>true; public bool RequireExactCorrelation=>true; public bool RequireDeterministicAssetIdentity=>true; public bool RequireKnowledgeTraceability=>true; public bool RequireNarrationAudio=>true; public bool RequireSubtitleAsset=>true; public bool RequireVisualAssetPerScene=>true; public bool RequireSceneVideoPerScene=>true; public bool RequireVariantVideo=>true; public bool RequireRenderVerification=>true; public bool AllowPartialCompletion{get;}
    public IReadOnlyList<DocumentaryMediaVariantType> RequiredVariantTypes {get;}=Array.AsReadOnly(Enum.GetValues<DocumentaryMediaVariantType>()); public IReadOnlyList<DocumentaryMediaAssetType> SupportedAssetTypes{get;}=Array.AsReadOnly(Enum.GetValues<DocumentaryMediaAssetType>()); public IReadOnlyList<DocumentaryMediaAssetFormat> SupportedAssetFormats{get;}=Array.AsReadOnly(Enum.GetValues<DocumentaryMediaAssetFormat>()); public IReadOnlyList<DocumentaryMediaProviderCapability> RequiredProviderCapabilities{get;}=Array.AsReadOnly(Enum.GetValues<DocumentaryMediaProviderCapability>());
    public DocumentaryMediaAssetFormat VisualImageFormat=>DocumentaryMediaAssetFormat.Png; public DocumentaryMediaAssetFormat NarrationMasterFormat=>DocumentaryMediaAssetFormat.Wav; public DocumentaryMediaAssetFormat NarrationDeliveryFormat=>DocumentaryMediaAssetFormat.Aac; public DocumentaryMediaAssetFormat SubtitleFormat=>DocumentaryMediaAssetFormat.Srt; public DocumentaryMediaAssetFormat VideoFormat=>DocumentaryMediaAssetFormat.Mp4;
    public int LongWidth=>1920; public int LongHeight=>1080; public int ShortWidth=>1080; public int ShortHeight=>1920; public int LongFrameRate=>30; public int ShortFrameRate=>30; public int AudioSampleRate=>48000; public int AudioChannelCount=>2; public int MaximumVisualAttempts{get;} public int MaximumNarrationAttempts{get;} public int MaximumCompositionAttempts{get;} public string PipelineSchemaVersion=>"1.0";
}
[method: JsonConstructor]
public sealed record DocumentaryMediaPipelineMetadata(DateTimeOffset CreatedUtc,string CreatedBy,string PipelineSchemaVersion,string CorrelationId,string ExecutionId)
{ public DocumentaryMediaPipelineMetadata(DateTimeOffset createdUtc,string createdBy,string correlationId,string executionId):this(createdUtc,Required(createdBy),"1.0",Required(correlationId),Required(executionId)){} private static string Required(string x)=>string.IsNullOrWhiteSpace(x)?throw new ArgumentException("Value required."):x; }
public sealed record DocumentaryMediaPipelineRequest(DocumentaryMediaProject MediaProject,DocumentaryMediaPipelinePolicy Policy,DocumentaryMediaPipelineMetadata Metadata);
public sealed record DocumentaryMediaProviderDescriptor(string ProviderId,string DisplayName,IReadOnlyList<DocumentaryMediaProviderCapability> Capabilities,IReadOnlyList<DocumentaryMediaAssetFormat> SupportedAssetFormats,bool IsAvailable,string ProviderSchemaVersion);
public sealed record DocumentaryMediaAssetDependency(string DependencyId,string SourceAssetId,string TargetAssetId,int Sequence,string CorrelationId);
public sealed record DocumentaryMediaAssetPlan(string AssetId,DocumentaryMediaAssetType AssetType,DocumentaryMediaAssetFormat AssetFormat,DocumentaryMediaVariantType VariantType,string? SceneId,string SourceInstructionId,DocumentaryMediaProviderCapability ProviderCapability,int Sequence,IReadOnlyList<DocumentaryMediaAssetDependency> Dependencies,int ExpectedWidth,int ExpectedHeight,long ExpectedDurationMilliseconds,int ExpectedFrameRate,int ExpectedSampleRate,int ExpectedChannelCount,IReadOnlyList<DocumentaryMediaKnowledgeReference> KnowledgeReferences,string CorrelationId);
public sealed record DocumentaryMediaAssetResult(string AssetId,DocumentaryMediaAssetType AssetType,DocumentaryMediaAssetFormat AssetFormat,DocumentaryMediaAssetStatus Status,string? ProviderId,string? ContentIdentity,long ContentLength,long DurationMilliseconds,int Width,int Height,int FrameRate,int SampleRate,int ChannelCount,string? Checksum,string? FailureCode,string? FailureMessage,int AttemptCount,string CorrelationId);
public sealed record DocumentaryVisualGenerationRequest(DocumentaryMediaAssetPlan AssetPlan,DocumentaryVisualPrompt VisualPrompt,int Width,int Height,DocumentaryMediaAssetFormat AssetFormat,int Attempt,string CorrelationId);
public sealed record DocumentaryVisualGenerationResult(DocumentaryMediaAssetStatus Status,DocumentaryMediaAssetResult AssetResult,string? FailureCode,string? FailureMessage);
public sealed record DocumentaryNarrationSynthesisRequest(DocumentaryMediaAssetPlan AssetPlan,DocumentaryNarrationBlock NarrationBlock,string VoiceProfileId,DocumentaryMediaLanguage Language,DocumentaryMediaAssetFormat AssetFormat,int SampleRate,int ChannelCount,int Attempt,string CorrelationId);
public sealed record DocumentaryNarrationSynthesisResult(DocumentaryMediaAssetStatus Status,DocumentaryMediaAssetResult AssetResult,long MeasuredDurationMilliseconds,string? FailureCode,string? FailureMessage);
public sealed record DocumentarySubtitleGenerationRequest(DocumentaryMediaAssetPlan AssetPlan,DocumentaryMediaVariantType VariantType,string SceneId,DocumentaryMediaLanguage Language,IReadOnlyList<DocumentarySubtitleCue> SubtitleCues,long MeasuredNarrationDurationMilliseconds,DocumentaryMediaAssetFormat AssetFormat,string CorrelationId);
public sealed record DocumentarySubtitleGenerationResult(DocumentaryMediaAssetStatus Status,DocumentaryMediaAssetResult AssetResult,int CueCount,string? FailureCode,string? FailureMessage);
public sealed record DocumentarySceneCompositionRequest(DocumentaryMediaAssetPlan AssetPlan,DocumentaryMediaScene MediaScene,IReadOnlyList<DocumentaryMediaAssetResult> VisualAssets,DocumentaryMediaAssetResult NarrationAsset,DocumentaryMediaAssetResult SubtitleAsset,long MeasuredNarrationDurationMilliseconds,long PlannedSceneDurationMilliseconds,long EffectiveSceneDurationMilliseconds,DocumentarySceneTransition Transition,int Width,int Height,int FrameRate,string CorrelationId,int Attempt = 1);
public sealed record DocumentarySceneCompositionResult(DocumentaryMediaAssetStatus Status,DocumentaryMediaAssetResult AssetResult,long EffectiveDurationMilliseconds,string? FailureCode,string? FailureMessage);
public sealed record DocumentaryVariantCompositionRequest(DocumentaryMediaAssetPlan AssetPlan,DocumentaryMediaVariant MediaVariant,IReadOnlyList<DocumentaryMediaAssetResult> SceneAssets,int Width,int Height,int FrameRate,int AudioSampleRate,int AudioChannelCount,DocumentaryMediaAssetFormat VideoFormat,string CorrelationId,int Attempt = 1);
public sealed record DocumentaryVariantCompositionResult(DocumentaryMediaAssetStatus Status,DocumentaryMediaAssetResult AssetResult,int SceneCount,long EffectiveDurationMilliseconds,string? FailureCode,string? FailureMessage);
public sealed record DocumentaryRenderVerificationRequest(DocumentaryMediaVariant Variant,DocumentaryMediaAssetResult VariantAsset,int ExpectedSceneCount,int ExpectedWidth,int ExpectedHeight,int ExpectedFrameRate,int ExpectedAudioSampleRate,int ExpectedAudioChannelCount,long ExpectedMinimumDurationMilliseconds,long ExpectedMaximumDurationMilliseconds,string CorrelationId);
public sealed record DocumentaryRenderVerificationResult(bool IsValid,int ActualSceneCount,int ActualWidth,int ActualHeight,int ActualFrameRate,int ActualAudioSampleRate,int ActualAudioChannelCount,long ActualDurationMilliseconds,bool HasVideo,bool HasAudio,bool HasSubtitleTrack,bool ChecksumValid,IReadOnlyList<string> Failures);
public sealed record DocumentaryMediaVariantExecutionPlan(string VariantExecutionPlanId,string VariantId,DocumentaryMediaVariantType VariantType,IReadOnlyList<DocumentaryMediaAssetPlan> SceneAssetPlans,IReadOnlyList<DocumentaryMediaAssetPlan> NarrationAssetPlans,IReadOnlyList<DocumentaryMediaAssetPlan> SubtitleAssetPlans,IReadOnlyList<DocumentaryMediaAssetPlan> SceneVideoAssetPlans,DocumentaryMediaAssetPlan VariantVideoAssetPlan,int AssetCount,int DependencyCount,string CorrelationId);
public sealed record DocumentaryMediaPipelineExecutionPlan(string ExecutionPlanId,string MediaProjectId,string ExecutionId,IReadOnlyList<DocumentaryMediaVariantExecutionPlan> VariantPlans,IReadOnlyList<DocumentaryMediaAssetPlan> AssetPlans,IReadOnlyList<DocumentaryMediaAssetDependency> AssetDependencies,int VariantCount,int AssetCount,int DependencyCount,string CorrelationId,bool IsComplete);
public sealed record DocumentaryMediaVariantExecutionRecord(string VariantExecutionId,string VariantId,DocumentaryMediaVariantType VariantType,DocumentaryMediaPipelineStatus Status,IReadOnlyList<DocumentaryMediaAssetResult> AssetResults,int CompletedSceneCount,int FailedSceneCount,long PlannedDurationMilliseconds,long EffectiveDurationMilliseconds,string? OutputAssetId,IReadOnlyList<DocumentaryMediaPipelineRejectionReason> RejectionReasons,string CorrelationId);
public sealed record DocumentaryMediaOutputManifest(string ManifestId,string ExecutionId,string MediaProjectId,string TopicId,IReadOnlyList<DocumentaryMediaVariantExecutionRecord> VariantRecords,IReadOnlyList<DocumentaryMediaAssetResult> Assets,IReadOnlyList<string> Checksums,int VariantCount,int AssetCount,int CompletedVariantCount,int FailedVariantCount,string ManifestSchemaVersion,string CorrelationId);
public sealed record DocumentaryMediaPipelineExecutionRecord(string ExecutionId,DocumentaryMediaProject MediaProject,DocumentaryMediaPipelinePolicy Policy,DocumentaryMediaPipelineMetadata Metadata,DocumentaryMediaPipelineExecutionPlan ExecutionPlan,IReadOnlyList<DocumentaryMediaVariantExecutionRecord> VariantRecords,DocumentaryMediaOutputManifest OutputManifest,DocumentaryMediaPipelineStatus Status,string MediaProjectId,string MaterializationId,string TopicId,int VariantCount,int CompletedVariantCount,int FailedVariantCount,int AssetCount,int GeneratedAssetCount,int VerifiedAssetCount,int FailedAssetCount,long PlannedDurationMilliseconds,long EffectiveDurationMilliseconds)
{ public bool IsPlanned=>Status==DocumentaryMediaPipelineStatus.Planned; public bool IsComplete=>Status==DocumentaryMediaPipelineStatus.Complete; public bool IsPartiallyComplete=>Status==DocumentaryMediaPipelineStatus.PartiallyComplete; public bool IsRejected=>Status==DocumentaryMediaPipelineStatus.Rejected; }
public sealed record DocumentaryMediaPipelineResult(DocumentaryMediaPipelineStatus Status,IReadOnlyList<DocumentaryMediaPipelineRejectionReason> RejectionReasons,DocumentaryMediaPipelineExecutionRecord? ExecutionRecord)
{ public bool HasExecutionRecord=>ExecutionRecord is not null; public bool IsPlanned=>Status==DocumentaryMediaPipelineStatus.Planned; public bool IsComplete=>Status==DocumentaryMediaPipelineStatus.Complete; public bool IsPartiallyComplete=>Status==DocumentaryMediaPipelineStatus.PartiallyComplete; public bool IsRejected=>Status==DocumentaryMediaPipelineStatus.Rejected; }
public sealed record DocumentaryMediaPipelineSummary(string ExecutionId,string MediaProjectId,string TopicId,DocumentaryAstronomyTopicFamily TopicFamily,DocumentaryMediaPipelineStatus Status,int VariantCount,int CompletedVariantCount,int FailedVariantCount,int LongCompletedCount,int ShortCompletedCount,int EnglishCompletedCount,int HindiCompletedCount,int AssetCount,int VisualAssetCount,int NarrationAssetCount,int SubtitleAssetCount,int SceneVideoAssetCount,int VariantVideoAssetCount,long PlannedDurationMilliseconds,long EffectiveDurationMilliseconds,DateTimeOffset CreatedUtc,string CreatedBy,bool IsComplete);
