using System.Text;
using System.Text.Json;

namespace Astronomy.MediaFactory.Core.DocumentaryBlueprint;

internal static class DocumentaryExportMaterializationValidator
{
    internal static readonly JsonSerializerOptions WebJsonOptions=new(JsonSerializerDefaults.Web);
    internal static bool PolicyValid(DocumentaryExportMaterializationPolicy p)=>p is not null&&new[]{p.RequireCompleteExportSpecification,p.RequireCanonicalPayloads,p.RequireCanonicalOrdering,p.RequireExactCorrelation,p.RequireDeterministicSerialization,p.RequireDeterministicIdentity,p.RequireDependencyPreservation,p.RequireUtf8Encoding}.All(x=>x)&&p.RequiredPayloadTypes.SequenceEqual(DocumentaryExportMaterializationInventory.PayloadTypes)&&p.RequiredPayloadContentTypes.SequenceEqual(DocumentaryExportMaterializationInventory.ContentTypes)&&p.SerializerProfile==DocumentaryExportSerializerProfile.CanonicalWebJson&&p.CharacterEncoding==DocumentaryExportCharacterEncoding.Utf8&&p.PolicySchemaVersion=="1.0";
    internal static bool PayloadsStructurallyValid(IReadOnlyList<DocumentaryExportPayload> payloads,string correlation)=>payloads is not null&&payloads.Count==10&&payloads.Select((p,i)=>(p,i)).All(x=>x.p.PayloadType==(DocumentaryExportPayloadType)x.i&&x.p.ContentType==(DocumentaryExportPayloadContentType)x.i&&x.p.Sequence==x.i&&x.p.SerializerProfile==DocumentaryExportSerializerProfile.CanonicalWebJson&&x.p.CharacterEncoding==DocumentaryExportCharacterEncoding.Utf8&&DocumentaryExportMaterializationInventory.Eq(x.p.CorrelationId,correlation)&&x.p.PayloadId==$"{x.p.PayloadType}.{x.p.ArtifactIdentity}.{x.p.ArtifactVersion}.payload"&&x.p.Utf8Bytes.SequenceEqual(Encoding.UTF8.GetBytes(x.p.Content))&&x.p.CharacterCount==x.p.Content.Length&&x.p.ByteCount==x.p.Utf8Bytes.Count)&&payloads.Sum(x=>x.Dependencies.Count)==23&&payloads.Select(x=>x.PayloadId).Distinct(StringComparer.Ordinal).Count()==10;
    internal static bool RecordValid(DocumentaryExportMaterializationRecord r)
    {try{DocumentaryExportSpecificationValidator.ValidateSpecification(r.ExportSpecification);}catch(ArgumentException){return false;}var s=r.ExportSpecification;var expected=DocumentaryExportMaterializer.CreatePayloads(s,r.Metadata,r.SerializerProfile);return r.MaterializationId==$"{s.ExportSpecificationId}.materialization"&&r.ExportSpecificationId==s.ExportSpecificationId&&r.CertificationId==s.CertificationId&&r.ProvenanceId==s.ProvenanceId&&r.PackageId==s.PackageId&&r.ReleaseCandidateId==s.ReleaseCandidateId&&r.ConvergenceId==s.ConvergenceId&&r.CertificationRecord.CertificationId==s.CertificationId&&r.ProvenanceRecord.ProvenanceId==s.ProvenanceId&&r.ProductionPackage.PackageId==s.PackageId&&PolicyValid(r.Policy)&&r.SerializerProfile==DocumentaryExportSerializerProfile.CanonicalWebJson&&r.CharacterEncoding==DocumentaryExportCharacterEncoding.Utf8&&PayloadsEqual(r.Payloads,expected)&&r.PayloadCount==10&&r.DependencyCount==23&&r.TotalCharacterCount==r.Payloads.Sum(x=>x.CharacterCount)&&r.TotalByteCount==r.Payloads.Sum(x=>x.ByteCount)&&r.Manifest.ManifestId==$"{r.MaterializationId}.manifest"&&r.Manifest.MaterializationId==r.MaterializationId&&r.Manifest.ExportSpecificationId==s.ExportSpecificationId&&r.Manifest.Payloads.Count==r.Payloads.Count&&PayloadsEqual(r.Manifest.Payloads,r.Payloads)&&r.Manifest.TotalCharacterCount==r.TotalCharacterCount&&r.Manifest.TotalByteCount==r.TotalByteCount&&r.Manifest.CorrelationId==r.Metadata.CorrelationId;}
    private static bool PayloadsEqual(IReadOnlyList<DocumentaryExportPayload> a,IReadOnlyList<DocumentaryExportPayload> b)=>JsonSerializer.Serialize(a,WebJsonOptions)==JsonSerializer.Serialize(b,WebJsonOptions);
}
