using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Events;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
namespace Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Events;
public static class AstronomyEventValidationRegistrationExtensions
{
 public static IServiceCollection AddAstronomyEventValidation(this IServiceCollection services){ArgumentNullException.ThrowIfNull(services); services.AddAstronomyKnowledgeValidation();
  services.AddAstronomyKnowledgeValidationRule<AstronomyEventAggregateValidationRule,AstronomyEventPayload>(AstronomyEventAggregateValidationRule.Id,AstronomyKnowledgeDomain.Event,AstronomyKnowledgePayloadFamily.AstronomicalEvent,100);
  services.AddAstronomyKnowledgeValidationRule<AstronomyEventTemporalExtentValidationRule,AstronomyEventPayload>(AstronomyEventTemporalExtentValidationRule.Id,AstronomyKnowledgeDomain.Event,AstronomyKnowledgePayloadFamily.AstronomicalEvent,200);
  services.AddAstronomyKnowledgeValidationRule<AstronomyEventReferenceContextValidationRule,AstronomyEventPayload>(AstronomyEventReferenceContextValidationRule.Id,AstronomyKnowledgeDomain.Event,AstronomyKnowledgePayloadFamily.AstronomicalEvent,300);
  services.AddAstronomyKnowledgeValidationRule<AstronomyEventParticipantValidationRule,AstronomyEventPayload>(AstronomyEventParticipantValidationRule.Id,AstronomyKnowledgeDomain.Event,AstronomyKnowledgePayloadFamily.AstronomicalEvent,400);
  services.AddAstronomyKnowledgeValidationRule<AstronomyEventPhaseMarkerValidationRule,AstronomyEventPayload>(AstronomyEventPhaseMarkerValidationRule.Id,AstronomyKnowledgeDomain.Event,AstronomyKnowledgePayloadFamily.AstronomicalEvent,500);
  services.AddAstronomyKnowledgeValidationRule<AstronomyEventGeometryValidationRule,AstronomyEventPayload>(AstronomyEventGeometryValidationRule.Id,AstronomyKnowledgeDomain.Event,AstronomyKnowledgePayloadFamily.AstronomicalEvent,600);
  services.AddAstronomyKnowledgeValidationRule<AstronomyEventCircumstanceValidationRule,AstronomyEventPayload>(AstronomyEventCircumstanceValidationRule.Id,AstronomyKnowledgeDomain.Event,AstronomyKnowledgePayloadFamily.AstronomicalEvent,700); return services;}
}
