using System.Collections.Immutable;
using System.Text.Json.Serialization;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Contracts;

namespace Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Catalog;

[JsonConverter(typeof(JsonStringEnumConverter<LegacySemanticCapabilityResolutionStatus>))]
public enum LegacySemanticCapabilityResolutionStatus { CanonicalMatch, DeprecatedAliasMatch, StructuredFieldMigration, UnsupportedLegacyTerm, AmbiguousMapping }
[JsonConverter(typeof(JsonStringEnumConverter<LegacySemanticCapabilityMigrationDisposition>))]
public enum LegacySemanticCapabilityMigrationDisposition { CanonicalCapability, StructuredField, Future, NeedsDomainDecision, RemoveDeadReference, Unsupported, UnsupportedLegacyTerm }

public sealed record LegacySemanticCapabilityResolution(string InputTerm, LegacySemanticCapabilityResolutionStatus Status, SemanticCapabilityId? CanonicalCapabilityId, string? StructuredFieldPath, LegacySemanticCapabilityMigrationDisposition MigrationDisposition, bool IsDeprecatedAlias, string? Diagnostic);
public sealed record LegacySemanticCapabilityMapEntry(string LegacyTerm, SemanticCapabilityId? CanonicalCapabilityId, string? StructuredFieldPath, LegacySemanticCapabilityMigrationDisposition MigrationDisposition);

public static class LegacySemanticCapabilityMapV1
{
    public static ImmutableArray<LegacySemanticCapabilityMapEntry> Entries { get; } =
    [
        Entry("EventIdentity", V.EventIdentity), Entry("EventType", V.EventIdentity), Entry("Title", V.EventIdentity), Entry("SubjectIdentity", V.EventIdentity),
        Path("EventDate", V.EventWindow, "EventWindow.date"), Path("EventDateOrWindow", V.EventWindow, "EventWindow.window"), Path("Date", V.EventWindow, "EventWindow.date"), Path("EventTiming", V.EventWindow, "EventWindow.timing"), Path("ObservationTiming", V.EventWindow, "EventWindow.observationTiming"), Path("StartTime", V.EventWindow, "EventWindow.startTime"), Path("PeakTime", V.EventWindow, "EventWindow.peakTime"), Path("EndTime", V.EventWindow, "EventWindow.endTime"), Path("PeakWindow", V.EventWindow, "EventWindow.peakWindow"), Path("LocalPeakTime", V.EventWindow, "EventWindow.localPeakTime"), Path("PeakUTC", V.EventWindow, "EventWindow.peakUtc"), Path("ViewingWindow", V.EventWindow, "EventWindow.viewingWindow"), Path("BestViewingWindowLocal", V.EventWindow, "EventWindow.bestViewingWindowLocal"), Path("MoonriseTime", V.EventWindow, "EventWindow.moonriseTime"), Path("TimeOfDay", V.EventWindow, "EventWindow.timeOfDay"),
        Path("Name", V.ObjectKnowledge, "ObjectKnowledge.name"), Path("ObjectName", V.ObjectKnowledge, "ObjectKnowledge.name"), Path("SkyRegion", V.ObjectKnowledge, "ObjectKnowledge.skyLocation"), Path("SkyLocation", V.ObjectKnowledge, "ObjectKnowledge.skyLocation"), Path("PrimaryObjects", V.AstronomicalObjects, "AstronomicalObjects.primary"), Path("Objects", V.AstronomicalObjects, "AstronomicalObjects.items"), Path("ObjectType", V.ObjectKnowledge, "ObjectKnowledge.objectType"), Path("PlanetType", V.ObjectKnowledge, "ObjectKnowledge.planetType"), Path("ScientificIdentity", V.ObjectKnowledge, "ObjectKnowledge.scientificIdentity"), Path("OccultingObject", V.AstronomicalObjects, "AstronomicalObjects.occultingObject"), Path("HiddenObject", V.SecondaryAstronomicalObjects, "SecondaryAstronomicalObjects.hiddenObject"),
        Entry("AngularRelationship", V.AngularSeparation), Entry("AngularSeparation", V.AngularSeparation), Entry("Separation", V.AngularSeparation),
        Path("ObservationMode", V.ObservationEquipment, "ObservationEquipment.mode"), Path("VisibilityMethod", V.ObservationEquipment, "ObservationEquipment.visibilityMethod"), Path("NakedEye", V.ObservationEquipment, "ObservationEquipment.nakedEye"), Path("BinocularGuidance", V.ObservationEquipment, "ObservationEquipment.binocularGuidance"), Path("TelescopeGuidance", V.ObservationEquipment, "ObservationEquipment.telescopeGuidance"),
        Entry("VisibilityConditions", V.ObservationConditions), Path("DarkSkyGuidance", V.ObservationConditions, "ObservationConditions.darkSkyGuidance"), Path("MoonPhase", V.FullMoonObservation, "FullMoonObservation.moonPhase"), Entry("Visibility", V.ObservationConditions),
        Path("ZHR", V.MeteorActivity, "MeteorActivity.zhr"), Path("ZenithalHourlyRate", V.MeteorActivity, "MeteorActivity.zhr"),
        Path("ApparentAlignmentExplanation", V.DomainScientificKnowledge, "DomainScientificKnowledge.apparentAlignment"), Path("ApparentPairingScience", V.DomainScientificKnowledge, "DomainScientificKnowledge.apparentPairingScience"), Path("PerspectiveExplanation", V.DomainScientificKnowledge, "DomainScientificKnowledge.perspective"), Path("WhyPlanetsAppearClose", V.DomainScientificKnowledge, "DomainScientificKnowledge.apparentAlignment"), Path("PhysicalProximityClarification", V.DomainScientificKnowledge, "DomainScientificKnowledge.physicalProximityClarification"), Path("ScientificMechanism", V.DomainScientificKnowledge, "DomainScientificKnowledge.mechanism"), Path("Mechanism", V.DomainScientificKnowledge, "DomainScientificKnowledge.mechanism"),
        Path("EclipseType", V.EclipseCircumstances, "EclipseCircumstances.eclipseType"), Path("Magnitude", V.EclipseCircumstances, "EclipseCircumstances.magnitude"), Path("Duration", V.OccultationContacts, "OccultationContacts.duration"), Path("ReappearanceTime", V.OccultationContacts, "OccultationContacts.reappearanceTime"),
        Entry("CulturalNameContext", V.CulturalContext), Entry("Mythology", V.CulturalContext), Entry("WolfMoon", V.CulturalContext), Entry("SnowMoon", V.CulturalContext),
        Path("Distance", V.ObjectKnowledge, "ObjectKnowledge.distance"), Path("DiscoveryHistory", V.ObjectKnowledge, "ObjectKnowledge.discoveryHistory"), Path("Moons", V.ObjectKnowledge, "ObjectKnowledge.moons"), Path("Atmosphere", V.ObjectKnowledge, "ObjectKnowledge.atmosphere"), Path("Perihelion", V.ObjectKnowledge, "ObjectKnowledge.perihelion"), Future("ImagingNotes"), Path("ObservationMethod", V.DomainScientificKnowledge, "DomainScientificKnowledge.observationMethod"), Path("IdentificationPattern", V.ObjectKnowledge, "ObjectKnowledge.identificationPattern"), Path("MajorStars", V.ObjectKnowledge, "ObjectKnowledge.majorStars"), Future("BestSeason"), Future("DeepSkyObjects"), Path("ScientificImportance", V.DomainScientificKnowledge, "DomainScientificKnowledge.scientificImportance"), Path("Evidence", V.DomainScientificKnowledge, "DomainScientificKnowledge.evidence"), Path("Concept", V.DomainScientificKnowledge, "DomainScientificKnowledge.concept"), Domain("Orbit")
    ];
    private static class V { public const string EventIdentity=SemanticCapabilityVocabularyV1.EventIdentity, EventWindow=SemanticCapabilityVocabularyV1.EventWindow, AstronomicalObjects=SemanticCapabilityVocabularyV1.AstronomicalObjects, SecondaryAstronomicalObjects=SemanticCapabilityVocabularyV1.SecondaryAstronomicalObjects, AngularSeparation=SemanticCapabilityVocabularyV1.AngularSeparation, ObservationEquipment=SemanticCapabilityVocabularyV1.ObservationEquipment, ObservationConditions=SemanticCapabilityVocabularyV1.ObservationConditions, FullMoonObservation=SemanticCapabilityVocabularyV1.FullMoonObservation, MeteorActivity=SemanticCapabilityVocabularyV1.MeteorActivity, DomainScientificKnowledge=SemanticCapabilityVocabularyV1.DomainScientificKnowledge, EclipseCircumstances=SemanticCapabilityVocabularyV1.EclipseCircumstances, OccultationContacts=SemanticCapabilityVocabularyV1.OccultationContacts, CulturalContext=SemanticCapabilityVocabularyV1.CulturalContext, ObjectKnowledge=SemanticCapabilityVocabularyV1.ObjectKnowledge; }
    public static LegacySemanticCapabilityMapEntry Entry(string t,string c)=>new(t,new(c),null,LegacySemanticCapabilityMigrationDisposition.CanonicalCapability);
    public static LegacySemanticCapabilityMapEntry Path(string t,string c,string p)=>new(t,new(c),p,LegacySemanticCapabilityMigrationDisposition.StructuredField);
    public static LegacySemanticCapabilityMapEntry Future(string t)=>new(t,null,null,LegacySemanticCapabilityMigrationDisposition.Future);
    public static LegacySemanticCapabilityMapEntry Domain(string t)=>new(t,null,null,LegacySemanticCapabilityMigrationDisposition.NeedsDomainDecision);
}
