using System.Collections.ObjectModel;
using System.Text.Json;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Microsoft.Extensions.Options;

namespace Astronomy.MediaFactory.ProductionAdapters;

public enum DocumentaryProductionExecutionStatus { NotStarted, Preparing, Executing, PartiallySucceeded, Succeeded, VerificationFailed, CertificationRejected, Cancelled, Failed }
public enum DocumentaryProductionItemStatus { NotStarted, Executing, Succeeded, VerificationFailed, Failed }
public enum DocumentaryProductionSubtitleStrategy { BurnedIn, Embedded, Sidecar, None }
public sealed record DocumentaryProductionSceneExecutionResult(string SceneId,int Sequence,DocumentaryProductionItemStatus Status,DocumentaryPhysicalArtifactDescriptor? VisualArtifact,DocumentaryPhysicalArtifactDescriptor? NarrationArtifact,DocumentaryPhysicalArtifactDescriptor? SubtitleArtifact,DocumentaryPhysicalArtifactDescriptor? SceneVideoArtifact,DocumentaryProductionMediaVerificationAdapterResult? VerificationResult,IReadOnlyList<DocumentaryProductionFailure> Failures,int AttemptCount,string? DiagnosticsReference);
public sealed record DocumentaryProductionVariantExecutionResult(string VariantId,DocumentaryMediaVariantType VariantType,DocumentaryMediaLanguage Language,DocumentaryProductionItemStatus Status,IReadOnlyList<DocumentaryProductionSceneExecutionResult> SceneResults,DocumentaryPhysicalArtifactDescriptor? FinalVariantArtifact,DocumentaryProductionMediaVerificationAdapterResult? VerificationResult,IReadOnlyList<DocumentaryProductionFailure> Failures,int AttemptCount,DateTimeOffset StartedAtUtc,DateTimeOffset CompletedAtUtc,string? DiagnosticsReference);
public sealed record DocumentaryProductionCertificationResult(bool Certified,bool Rejected,string? EvidenceReference,IReadOnlyList<DocumentaryProductionFailure> Failures);
public sealed record DocumentaryProductionExecutionResult(bool Succeeded,DocumentaryProductionExecutionStatus Status,string ExecutionId,string CorrelationId,DocumentaryMediaPipelineExecutionRecord? ExecutionRecord,IReadOnlyList<DocumentaryProductionVariantExecutionResult> Variants,IReadOnlyList<DocumentaryProductionFailure> Failures,string? ExecutionDiagnosticsReference,string? ArtifactManifestReference,DocumentaryProductionCertificationResult? CertificationResult,bool EligibleForPublishing);

public sealed class DocumentaryProductionExecutionHostOptions {
 public const string SectionName="DocumentaryProductionAdapters:ExecutionHost";
 public bool Enabled{get;set;} public int MaximumAttemptsPerOperation{get;set;}=1; public bool VerifySceneVideos{get;set;}=true; public bool VerifyFinalVariants{get;set;}=true; public bool RunProductionCertification{get;set;} public bool ContinueOtherVariantsAfterVariantFailure{get;set;} public bool RetainFailedAttempts{get;set;}=true; public bool PersistArtifactManifest{get;set;}=true; public bool PersistExecutionRecord{get;set;}=true;
 public int? VisualGenerationTimeoutSeconds{get;set;} public int? NarrationSynthesisTimeoutSeconds{get;set;} public int? SubtitleGenerationTimeoutSeconds{get;set;} public int? SceneCompositionTimeoutSeconds{get;set;} public int? VariantCompositionTimeoutSeconds{get;set;} public int? MediaVerificationTimeoutSeconds{get;set;}
}
public sealed class DocumentaryProductionAttemptContextFactory(IDocumentaryProductionClock clock):IDocumentaryProductionAttemptContextFactory { public DocumentaryProductionAttemptContext Create(DocumentaryProductionExecutionContext e,DocumentaryProductionOperationKind kind,string asset,string provider,int attempt,TimeSpan timeout,string? variantId=null,string? sceneId=null){ArgumentNullException.ThrowIfNull(e);ArgumentException.ThrowIfNullOrWhiteSpace(asset);ArgumentException.ThrowIfNullOrWhiteSpace(provider);if(attempt<1||timeout<=TimeSpan.Zero)throw new ArgumentOutOfRangeException();return new(e.ExecutionId,e.CorrelationId,kind,asset,variantId,sceneId,attempt,provider,clock.UtcNow,timeout);} }
public sealed class DocumentaryProductionExecutionDependencyResolver(IDocumentaryPhysicalArtifactRegistry registry):IDocumentaryProductionExecutionDependencyResolver {
 public async Task<DocumentaryPhysicalArtifactDescriptor> ResolveAsync(string id,DocumentaryPhysicalArtifactKind kind,string correlation,CancellationToken token){var x=await registry.GetRegisteredAsync(id,token);if(x is null)throw new InvalidOperationException("A required registered dependency is missing.");if(x.Kind!=kind||x.Descriptor.CorrelationId!=correlation)throw new InvalidOperationException("A registered dependency has incompatible identity or kind.");return x.Descriptor;}
 public async Task<IReadOnlyList<DocumentaryPhysicalArtifactDescriptor>> ResolveOrderedAsync(IEnumerable<DocumentaryMediaAssetPlan> plans,DocumentaryPhysicalArtifactKind kind,string correlation,CancellationToken token){var result=new List<DocumentaryPhysicalArtifactDescriptor>();foreach(var p in plans.OrderBy(x=>x.Sequence).ThenBy(x=>x.AssetId,StringComparer.Ordinal))result.Add(await ResolveAsync(p.AssetId,kind,correlation,token));return new ReadOnlyCollection<DocumentaryPhysicalArtifactDescriptor>(result);}
}

public interface IDocumentaryProductionExecutionRequestBuilder {
 DocumentaryVisualGenerationRequest Visual(DocumentaryMediaAssetPlan plan,DocumentaryVisualPrompt prompt,int attempt);
 DocumentaryNarrationSynthesisRequest Narration(DocumentaryMediaAssetPlan plan,DocumentaryNarrationBlock narration,DocumentaryMediaLanguage language,int attempt);
 DocumentarySubtitleGenerationRequest Subtitle(DocumentaryMediaAssetPlan plan,DocumentaryMediaVariant variant,DocumentaryMediaScene scene,long duration);
 DocumentarySceneCompositionRequest Scene(DocumentaryMediaAssetPlan plan,DocumentaryMediaScene scene,IReadOnlyList<DocumentaryMediaAssetResult> visuals,DocumentaryMediaAssetResult narration,DocumentaryMediaAssetResult subtitle,long duration,int attempt);
 DocumentaryVariantCompositionRequest Variant(DocumentaryMediaAssetPlan plan,DocumentaryMediaVariant variant,IReadOnlyList<DocumentaryMediaAssetResult> scenes,int attempt);
 DocumentaryMediaVerificationRequest Verification(DocumentaryMediaAssetPlan plan,DocumentaryPhysicalArtifactKind kind,string variantId,string? sceneId,int attempt,DocumentaryProductionSubtitleStrategy strategy);
}
public sealed class DocumentaryProductionExecutionRequestBuilder:IDocumentaryProductionExecutionRequestBuilder {
 public DocumentaryVisualGenerationRequest Visual(DocumentaryMediaAssetPlan p,DocumentaryVisualPrompt x,int a)=>new(p,x,p.ExpectedWidth,p.ExpectedHeight,p.AssetFormat,a,p.CorrelationId);
 public DocumentaryNarrationSynthesisRequest Narration(DocumentaryMediaAssetPlan p,DocumentaryNarrationBlock x,DocumentaryMediaLanguage l,int a)=>new(p,x,l==DocumentaryMediaLanguage.Hindi?"hi-IN-default":"en-US-default",l,p.AssetFormat,p.ExpectedSampleRate,p.ExpectedChannelCount,a,p.CorrelationId);
 public DocumentarySubtitleGenerationRequest Subtitle(DocumentaryMediaAssetPlan p,DocumentaryMediaVariant v,DocumentaryMediaScene s,long d)=>new(p,v.VariantType,s.SceneId,v.Language,new ReadOnlyCollection<DocumentarySubtitleCue>(s.SubtitleCues.OrderBy(x=>x.Sequence).ToArray()),d,p.AssetFormat,p.CorrelationId);
 public DocumentarySceneCompositionRequest Scene(DocumentaryMediaAssetPlan p,DocumentaryMediaScene s,IReadOnlyList<DocumentaryMediaAssetResult> v,DocumentaryMediaAssetResult n,DocumentaryMediaAssetResult sub,long d,int a)=>new(p,s,v,n,sub,d,s.Timing.PlannedDurationMilliseconds,Math.Max(d,s.Timing.PlannedDurationMilliseconds),s.Transition,p.ExpectedWidth,p.ExpectedHeight,p.ExpectedFrameRate,p.CorrelationId,a);
 public DocumentaryVariantCompositionRequest Variant(DocumentaryMediaAssetPlan p,DocumentaryMediaVariant v,IReadOnlyList<DocumentaryMediaAssetResult> scenes,int a)=>new(p,v,scenes,p.ExpectedWidth,p.ExpectedHeight,p.ExpectedFrameRate,p.ExpectedSampleRate,p.ExpectedChannelCount,p.AssetFormat,p.CorrelationId,a);
 public DocumentaryMediaVerificationRequest Verification(DocumentaryMediaAssetPlan p,DocumentaryPhysicalArtifactKind k,string variant,string? scene,int a,DocumentaryProductionSubtitleStrategy strategy)=>new(p.AssetId,p.AssetType,p.AssetFormat,k,p.CorrelationId,a,variant,scene,"video/mp4",p.ExpectedDurationMilliseconds,p.ExpectedWidth,p.ExpectedHeight,p.ExpectedFrameRate,p.ExpectedSampleRate,p.ExpectedChannelCount,true,true,true,strategy==DocumentaryProductionSubtitleStrategy.Embedded,true,VerificationProfileId:k==DocumentaryPhysicalArtifactKind.SceneVideo?DocumentaryMediaVerificationPolicyIds.SceneVideoVerificationV1:DocumentaryMediaVerificationPolicyIds.VariantVideoVerificationV1);
}

public sealed class DocumentaryProductionExecutionCoordinator(IOptions<DocumentaryProductionExecutionHostOptions> hostOptions,IOptions<DocumentaryProductionAdaptersOptions> bridgeOptions,IDocumentaryProductionExecutionContextFactory contexts,IDocumentaryProductionWorkspaceManager workspaces,IDocumentaryProductionDiagnosticsWriter diagnostics,IDocumentaryPhysicalArtifactRegistry artifacts,IDocumentaryProductionAdapterRegistry adapters,IDocumentaryProductionAttemptContextFactory attempts,IDocumentaryProductionExecutionRequestBuilder requests,IDocumentaryProductionClock clock):IDocumentaryProductionExecutionCoordinator {
 static readonly DocumentaryProductionOperationKind[] Required=[DocumentaryProductionOperationKind.VisualGeneration,DocumentaryProductionOperationKind.NarrationSynthesis,DocumentaryProductionOperationKind.SubtitleGeneration,DocumentaryProductionOperationKind.SceneComposition,DocumentaryProductionOperationKind.VariantComposition,DocumentaryProductionOperationKind.MediaVerification];
 public async Task<DocumentaryProductionExecutionResult> ExecuteAsync(DocumentaryMediaPipelineRequest request,CancellationToken token){
  token.ThrowIfCancellationRequested();ArgumentNullException.ThrowIfNull(request);var context=contexts.Create(request);if(!hostOptions.Value.Enabled)return Empty(context,DocumentaryProductionExecutionStatus.NotStarted);
  DocumentaryMediaPipelineValidator.ValidateRequest(request);var workspace=await workspaces.CreateAsync(context,token);await diagnostics.WriteAsync(workspace.DiagnosticsDirectory,"execution-started.json",new{context.ExecutionId,context.CorrelationId,context.StartedAtUtc,Status="Preparing"},token);
  var missing=Required.Where(x=>!adapters.IsAvailable(x)).ToArray();if(missing.Length>0){var f=new DocumentaryProductionFailure(DocumentaryProductionFailureCode.AdapterUnavailable,$"Required production adapters are unavailable: {string.Join(", ",missing)}.");return await Finish(context,workspace,[],[f],DocumentaryProductionExecutionStatus.Failed,token);}
  var plan=new DocumentaryMediaPipelinePlanner().Plan(request);var variants=new List<DocumentaryProductionVariantExecutionResult>();var failures=new List<DocumentaryProductionFailure>();
  foreach(var variant in request.MediaProject.Variants){token.ThrowIfCancellationRequested();var vp=plan.VariantPlans.Single(x=>x.VariantId==variant.VariantId);var vr=await ExecuteVariant(variant,vp,context,workspace,token);variants.Add(vr);failures.AddRange(vr.Failures);if(vr.Status!=DocumentaryProductionItemStatus.Succeeded&&!hostOptions.Value.ContinueOtherVariantsAfterVariantFailure)break;}
  var status=Status(variants,failures);return await Finish(context,workspace,variants,failures,status,token);
 }
 async Task<DocumentaryProductionVariantExecutionResult> ExecuteVariant(DocumentaryMediaVariant variant,DocumentaryMediaVariantExecutionPlan plan,DocumentaryProductionExecutionContext context,DocumentaryProductionWorkspace workspace,CancellationToken token){
  var started=clock.UtcNow;var scenes=new List<DocumentaryProductionSceneExecutionResult>();var failures=new List<DocumentaryProductionFailure>();
  foreach(var scene in variant.Scenes.OrderBy(x=>x.Sequence)){var result=await ExecuteScene(variant,scene,plan,context,workspace,token);scenes.Add(result);failures.AddRange(result.Failures);if(result.Status!=DocumentaryProductionItemStatus.Succeeded)return new(variant.VariantId,variant.VariantType,variant.Language,result.Status,scenes,null,null,failures,result.AttemptCount,started,clock.UtcNow,result.DiagnosticsReference);}
  var sceneAssets=scenes.Select(x=>Map(plan.SceneVideoAssetPlans.Single(p=>p.SceneId==x.SceneId),x.SceneVideoArtifact!)).ToArray();var request=requests.Variant(plan.VariantVideoAssetPlan,variant,sceneAssets,1);var composed=await adapters.VariantComposition!.ComposeAsync(request,context,Attempt(context,DocumentaryProductionOperationKind.VariantComposition,request.AssetPlan,1,DocumentaryVariantCompositionProviderIds.ExistingFFmpegVariantComposer,variant.VariantId,null),workspace,token);
  if(!composed.Succeeded){failures.Add(composed.Failure!);return new(variant.VariantId,variant.VariantType,variant.Language,DocumentaryProductionItemStatus.Failed,scenes,null,null,failures,1,started,clock.UtcNow,composed.ProviderDiagnosticsReference);}
  DocumentaryProductionMediaVerificationAdapterResult? verification=null;if(hostOptions.Value.VerifyFinalVariants){var verify=requests.Verification(plan.VariantVideoAssetPlan,DocumentaryPhysicalArtifactKind.VariantVideo,variant.VariantId,null,1,DocumentaryProductionSubtitleStrategy.Sidecar);verification=await adapters.MediaVerification!.VerifyAsync(verify,context,Attempt(context,DocumentaryProductionOperationKind.MediaVerification,plan.VariantVideoAssetPlan,1,DocumentaryMediaVerificationProviderIds.ExistingFFprobeMediaVerifier,variant.VariantId,null),workspace,token);if(!verification.Succeeded||!verification.Verified){failures.Add(verification.Failure??new(DocumentaryProductionFailureCode.OutputFormatInvalid,"Final variant verification failed."));return new(variant.VariantId,variant.VariantType,variant.Language,DocumentaryProductionItemStatus.VerificationFailed,scenes,composed.Artifact,verification,failures,1,started,clock.UtcNow,verification.ProviderDiagnosticsReference);}}
  return new(variant.VariantId,variant.VariantType,variant.Language,DocumentaryProductionItemStatus.Succeeded,scenes,composed.Artifact,verification,failures,1,started,clock.UtcNow,composed.ProviderDiagnosticsReference);
 }
 async Task<DocumentaryProductionSceneExecutionResult> ExecuteScene(DocumentaryMediaVariant variant,DocumentaryMediaScene scene,DocumentaryMediaVariantExecutionPlan plan,DocumentaryProductionExecutionContext context,DocumentaryProductionWorkspace workspace,CancellationToken token){
  var failures=new List<DocumentaryProductionFailure>();DocumentaryPhysicalArtifactDescriptor? visual=null,narration=null,subtitle=null,video=null;var visualResults=new List<DocumentaryMediaAssetResult>();var maxAttempt=1;
  foreach(var prompt in scene.VisualPrompts.OrderBy(x=>x.Sequence)){var p=plan.SceneAssetPlans.Single(x=>x.SceneId==scene.SceneId&&x.SourceInstructionId==prompt.VisualPromptId);var r=requests.Visual(p,prompt,1);var x=await adapters.VisualGeneration!.GenerateAsync(r,context,Attempt(context,DocumentaryProductionOperationKind.VisualGeneration,p,1,"VisualProvider",variant.VariantId,scene.SceneId),workspace,token);if(!x.Succeeded)return Failed(x.Failure!);visual=x.Artifact;visualResults.Add(Map(p,x.Artifact!));}
  var narrationPlan=plan.NarrationAssetPlans.Single(x=>x.SceneId==scene.SceneId);var narrationBlock=scene.Narration.Single();DocumentaryProductionNarrationAdapterResult? nr=null;
  for(var n=1;n<=Math.Max(1,hostOptions.Value.MaximumAttemptsPerOperation);n++){maxAttempt=Math.Max(maxAttempt,n);var req=requests.Narration(narrationPlan,narrationBlock,variant.Language,n);nr=await adapters.NarrationSynthesis!.SynthesizeAsync(req,context,Attempt(context,DocumentaryProductionOperationKind.NarrationSynthesis,narrationPlan,n,DocumentaryNarrationProviderIds.AzureSpeech,variant.VariantId,scene.SceneId),workspace,token);if(nr.Succeeded||nr.Failure?.Retryable!=true||NeverRetry(nr.Failure.Code))break;}
  if(nr?.Succeeded!=true)return Failed(nr?.Failure??new(DocumentaryProductionFailureCode.ProviderInvalidResponse,"Narration returned no result."));narration=nr.Artifact;var subtitlePlan=plan.SubtitleAssetPlans.Single(x=>x.SceneId==scene.SceneId);var sr=await adapters.SubtitleGeneration!.GenerateAsync(requests.Subtitle(subtitlePlan,variant,scene,narration.DurationMilliseconds!.Value),context,Attempt(context,DocumentaryProductionOperationKind.SubtitleGeneration,subtitlePlan,1,DocumentarySubtitleProviderIds.ExistingSubtitlePipeline,variant.VariantId,scene.SceneId),workspace,token);if(!sr.Succeeded)return Failed(sr.Failure!);subtitle=sr.Artifact;
  var scenePlan=plan.SceneVideoAssetPlans.Single(x=>x.SceneId==scene.SceneId);var cr=requests.Scene(scenePlan,scene,visualResults,Map(narrationPlan,narration),Map(subtitlePlan,subtitle),narration.DurationMilliseconds.Value,1);var composed=await adapters.SceneComposition!.ComposeAsync(cr,context,Attempt(context,DocumentaryProductionOperationKind.SceneComposition,scenePlan,1,DocumentarySceneCompositionProviderIds.ExistingFFmpegSceneComposer,variant.VariantId,scene.SceneId),workspace,token);if(!composed.Succeeded)return Failed(composed.Failure!);video=composed.Artifact;DocumentaryProductionMediaVerificationAdapterResult? verification=null;
  if(hostOptions.Value.VerifySceneVideos){var vr=requests.Verification(scenePlan,DocumentaryPhysicalArtifactKind.SceneVideo,variant.VariantId,scene.SceneId,1,DocumentaryProductionSubtitleStrategy.Sidecar);verification=await adapters.MediaVerification!.VerifyAsync(vr,context,Attempt(context,DocumentaryProductionOperationKind.MediaVerification,scenePlan,1,DocumentaryMediaVerificationProviderIds.ExistingFFprobeMediaVerifier,variant.VariantId,scene.SceneId),workspace,token);if(!verification.Succeeded||!verification.Verified){failures.Add(verification.Failure??new(DocumentaryProductionFailureCode.OutputFormatInvalid,"Scene verification failed."));return new(scene.SceneId,scene.Sequence,DocumentaryProductionItemStatus.VerificationFailed,visual,narration,subtitle,video,verification,failures,maxAttempt,verification.ProviderDiagnosticsReference);}}
  return new(scene.SceneId,scene.Sequence,DocumentaryProductionItemStatus.Succeeded,visual,narration,subtitle,video,verification,failures,maxAttempt,composed.ProviderDiagnosticsReference);
  DocumentaryProductionSceneExecutionResult Failed(DocumentaryProductionFailure f){failures.Add(f);return new(scene.SceneId,scene.Sequence,DocumentaryProductionItemStatus.Failed,visual,narration,subtitle,video,null,failures,maxAttempt,f.DiagnosticReference);}
 }
 DocumentaryProductionAttemptContext Attempt(DocumentaryProductionExecutionContext c,DocumentaryProductionOperationKind k,DocumentaryMediaAssetPlan p,int n,string provider,string? variant,string? scene)=>attempts.Create(c,k,p.AssetId,provider,n,Timeout(k),variant,scene);
 TimeSpan Timeout(DocumentaryProductionOperationKind k){int? specific=k switch{DocumentaryProductionOperationKind.VisualGeneration=>hostOptions.Value.VisualGenerationTimeoutSeconds,DocumentaryProductionOperationKind.NarrationSynthesis=>hostOptions.Value.NarrationSynthesisTimeoutSeconds,DocumentaryProductionOperationKind.SubtitleGeneration=>hostOptions.Value.SubtitleGenerationTimeoutSeconds,DocumentaryProductionOperationKind.SceneComposition=>hostOptions.Value.SceneCompositionTimeoutSeconds,DocumentaryProductionOperationKind.VariantComposition=>hostOptions.Value.VariantCompositionTimeoutSeconds,DocumentaryProductionOperationKind.MediaVerification=>hostOptions.Value.MediaVerificationTimeoutSeconds,_=>null};return TimeSpan.FromSeconds(specific??bridgeOptions.Value.DefaultOperationTimeoutSeconds);}
 static bool NeverRetry(DocumentaryProductionFailureCode c)=>c is DocumentaryProductionFailureCode.ProviderRejectedRequest or DocumentaryProductionFailureCode.SourceArtifactInvalid or DocumentaryProductionFailureCode.OutputFormatInvalid or DocumentaryProductionFailureCode.DimensionMismatch or DocumentaryProductionFailureCode.AudioStreamMissing or DocumentaryProductionFailureCode.VideoStreamMissing or DocumentaryProductionFailureCode.SubtitleMissing or DocumentaryProductionFailureCode.Cancelled;
 static DocumentaryMediaAssetResult Map(DocumentaryMediaAssetPlan p,DocumentaryPhysicalArtifactDescriptor d)=>new(p.AssetId,p.AssetType,p.AssetFormat,DocumentaryMediaAssetStatus.Generated,d.ProviderId,d.ContentIdentity,d.Length,d.DurationMilliseconds??0,d.Width??0,d.Height??0,(int)(d.FrameRate??0),d.AudioSampleRate??0,d.AudioChannelCount??0,d.Checksum,null,null,d.AttemptCount,d.CorrelationId);
 static DocumentaryProductionExecutionStatus Status(IReadOnlyList<DocumentaryProductionVariantExecutionResult> variants,IReadOnlyList<DocumentaryProductionFailure> failures){if(variants.Any(x=>x.Status==DocumentaryProductionItemStatus.VerificationFailed))return DocumentaryProductionExecutionStatus.VerificationFailed;var ok=variants.Count(x=>x.Status==DocumentaryProductionItemStatus.Succeeded);return ok==variants.Count&&ok>0?DocumentaryProductionExecutionStatus.Succeeded:ok>0?DocumentaryProductionExecutionStatus.PartiallySucceeded:DocumentaryProductionExecutionStatus.Failed;}
 async Task<DocumentaryProductionExecutionResult> Finish(DocumentaryProductionExecutionContext c,DocumentaryProductionWorkspace w,IReadOnlyList<DocumentaryProductionVariantExecutionResult> variants,IReadOnlyList<DocumentaryProductionFailure> failures,DocumentaryProductionExecutionStatus status,CancellationToken token){string? manifest=null;if(hostOptions.Value.PersistArtifactManifest){await artifacts.PersistAsync(w.DiagnosticsDirectory,token);manifest=Path.Combine(w.DiagnosticsDirectory,"documentary-artifacts.json");}var result=new DocumentaryProductionExecutionResult(status==DocumentaryProductionExecutionStatus.Succeeded,status,c.ExecutionId,c.CorrelationId,null,variants,failures,Path.Combine(w.DiagnosticsDirectory,"execution-completed.json"),manifest,null,status==DocumentaryProductionExecutionStatus.Succeeded);if(hostOptions.Value.PersistExecutionRecord)await diagnostics.WriteAsync(w.DiagnosticsDirectory,"documentary-production-execution.json",result,token);await diagnostics.WriteAsync(w.DiagnosticsDirectory,"execution-completed.json",new{c.ExecutionId,c.CorrelationId,Status=status.ToString(),CompletedAtUtc=clock.UtcNow,VariantCount=variants.Count,FailureCount=failures.Count},token);return result;}
 static DocumentaryProductionExecutionResult Empty(DocumentaryProductionExecutionContext c,DocumentaryProductionExecutionStatus s)=>new(false,s,c.ExecutionId,c.CorrelationId,null,[],[],null,null,null,false);
}

// Compatibility facade retained for certified CG-A2 callers; new callers use the coordinator.
public sealed class DocumentaryProductionExecutionHost(IDocumentaryProductionExecutionCoordinator coordinator):IDocumentaryProductionExecutionHost { public async Task<DocumentaryMediaPipelineExecutionRecord?> ExecuteAsync(DocumentaryMediaPipelineRequest request,CancellationToken cancellationToken)=>(await coordinator.ExecuteAsync(request,cancellationToken)).ExecutionRecord; }
