using System.Collections.ObjectModel;
using System.Text.Json;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Microsoft.Extensions.Options;

namespace Astronomy.MediaFactory.ProductionAdapters;

public enum DocumentaryProductionExecutionStatus { NotStarted, Preparing, Executing, PartiallySucceeded, Succeeded, VerificationFailed, CertificationRejected, Cancelled, Failed }
public enum DocumentaryProductionItemStatus { NotStarted, Executing, Succeeded, VerificationFailed, Failed }
public enum DocumentaryProductionSubtitleStrategy { BurnedIn, Embedded, Sidecar, None }
public sealed record DocumentaryProductionSceneExecutionResult(string SceneId,int Sequence,DocumentaryProductionItemStatus Status,IReadOnlyList<DocumentaryPhysicalArtifactDescriptor> VisualArtifacts,DocumentaryPhysicalArtifactDescriptor? NarrationArtifact,DocumentaryPhysicalArtifactDescriptor? SubtitleArtifact,DocumentaryPhysicalArtifactDescriptor? SceneVideoArtifact,DocumentaryProductionMediaVerificationAdapterResult? VerificationResult,IReadOnlyList<DocumentaryProductionFailure> Failures,int AttemptCount,string? DiagnosticsReference)
{ public DocumentaryPhysicalArtifactDescriptor? VisualArtifact => VisualArtifacts.LastOrDefault(); }
public sealed record DocumentaryProductionVariantExecutionResult(string VariantId,DocumentaryMediaVariantType VariantType,DocumentaryMediaLanguage Language,DocumentaryProductionItemStatus Status,IReadOnlyList<DocumentaryProductionSceneExecutionResult> SceneResults,DocumentaryPhysicalArtifactDescriptor? FinalVariantArtifact,DocumentaryProductionMediaVerificationAdapterResult? VerificationResult,IReadOnlyList<DocumentaryProductionFailure> Failures,int AttemptCount,DateTimeOffset StartedAtUtc,DateTimeOffset CompletedAtUtc,string? DiagnosticsReference);
public sealed record DocumentaryProductionCertificationResult(bool Certified,bool Rejected,string? EvidenceReference,IReadOnlyList<DocumentaryProductionFailure> Failures);
public sealed record DocumentaryProductionExecutionResult(bool Succeeded,DocumentaryProductionExecutionStatus Status,string ExecutionId,string CorrelationId,DocumentaryMediaPipelineExecutionRecord? ExecutionRecord,IReadOnlyList<DocumentaryProductionVariantExecutionResult> Variants,IReadOnlyList<DocumentaryProductionFailure> Failures,string? ExecutionDiagnosticsReference,string? ArtifactManifestReference,DocumentaryProductionCertificationResult? CertificationResult,bool EligibleForPublishing);

public sealed class DocumentaryProductionExecutionHostOptions {
 public const string SectionName="DocumentaryProductionAdapters:ExecutionHost";
 public bool Enabled{get;set;} public int MaximumAttemptsPerOperation{get;set;}=1; public bool VerifySceneVideos{get;set;}=true; public bool VerifyFinalVariants{get;set;}=true; public bool RunProductionCertification{get;set;} public bool ContinueOtherVariantsAfterVariantFailure{get;set;} public bool RetainFailedAttempts{get;set;}=true; public bool PersistArtifactManifest{get;set;}=true; public bool PersistExecutionRecord{get;set;}=true;
 public int? VisualGenerationTimeoutSeconds{get;set;} public int? NarrationSynthesisTimeoutSeconds{get;set;} public int? SubtitleGenerationTimeoutSeconds{get;set;} public int? SceneCompositionTimeoutSeconds{get;set;} public int? VariantCompositionTimeoutSeconds{get;set;} public int? MediaVerificationTimeoutSeconds{get;set;}
 public int? OperationTimeoutMilliseconds{get;set;}
}
public sealed class DocumentaryProductionAttemptContextFactory(IDocumentaryProductionClock clock):IDocumentaryProductionAttemptContextFactory { public DocumentaryProductionAttemptContext Create(DocumentaryProductionExecutionContext e,DocumentaryProductionOperationKind kind,string asset,string provider,int attempt,TimeSpan timeout,string? variantId=null,string? sceneId=null){ArgumentNullException.ThrowIfNull(e);ArgumentException.ThrowIfNullOrWhiteSpace(asset);ArgumentException.ThrowIfNullOrWhiteSpace(provider);if(attempt<1||timeout<=TimeSpan.Zero)throw new ArgumentOutOfRangeException();return new(e.ExecutionId,e.CorrelationId,kind,asset,variantId,sceneId,attempt,provider,clock.UtcNow,timeout);} }
public sealed class DocumentaryProductionExecutionDependencyResolver(IDocumentaryPhysicalArtifactRegistry registry):IDocumentaryProductionExecutionDependencyResolver {
 public async Task<DocumentaryPhysicalArtifactDescriptor> ResolveAsync(string id,DocumentaryPhysicalArtifactKind kind,string correlation,CancellationToken token){var x=await registry.GetRegisteredAsync(id,token);if(x is null)throw new InvalidOperationException("A required registered dependency is missing.");if(x.Kind!=kind||x.Descriptor.CorrelationId!=correlation)throw new InvalidOperationException("A registered dependency has incompatible identity or kind.");return x.Descriptor;}
 public async Task<IReadOnlyList<DocumentaryPhysicalArtifactDescriptor>> ResolveOrderedAsync(IEnumerable<DocumentaryMediaAssetPlan> plans,DocumentaryPhysicalArtifactKind kind,string correlation,CancellationToken token){var result=new List<DocumentaryPhysicalArtifactDescriptor>();foreach(var p in plans.OrderBy(x=>x.Sequence).ThenBy(x=>x.AssetId,StringComparer.Ordinal))result.Add(await ResolveAsync(p.AssetId,kind,correlation,token));return new ReadOnlyCollection<DocumentaryPhysicalArtifactDescriptor>(result);}
}

public interface IDocumentaryProductionExecutionRequestBuilder {
 DocumentaryVisualGenerationRequest Visual(DocumentaryMediaAssetPlan plan,DocumentaryVisualPrompt prompt,int attempt);
 DocumentaryNarrationSynthesisRequest Narration(DocumentaryMediaAssetPlan plan,DocumentaryNarrationBlock narration,DocumentaryMediaLanguage language,int attempt);
 DocumentarySubtitleGenerationRequest Subtitle(DocumentaryMediaAssetPlan plan,DocumentaryMediaVariant variant,DocumentaryMediaScene scene,long duration);
 DocumentarySceneCompositionRequest Scene(DocumentaryMediaAssetPlan plan,DocumentaryMediaScene scene,IReadOnlyList<DocumentaryMediaAssetResult> visuals,DocumentaryMediaAssetResult narration,DocumentaryMediaAssetResult subtitle,long duration,int attempt);
 DocumentaryVariantCompositionRequest Variant(DocumentaryMediaAssetPlan plan,DocumentaryMediaVariant variant,IReadOnlyList<DocumentaryMediaAssetResult> scenes,int attempt);
 DocumentaryMediaVerificationRequest Verification(DocumentaryMediaAssetPlan plan,DocumentaryPhysicalArtifactKind kind,string variantId,string? sceneId,int attempt,DocumentaryProductionSubtitleStrategy strategy,bool requireAudio=true,bool allowAudio=true);
}
public sealed class DocumentaryProductionExecutionRequestBuilder(IDocumentaryNarrationVoiceResolver voices):IDocumentaryProductionExecutionRequestBuilder {
 public DocumentaryVisualGenerationRequest Visual(DocumentaryMediaAssetPlan p,DocumentaryVisualPrompt x,int a)=>new(p,x,p.ExpectedWidth,p.ExpectedHeight,p.AssetFormat,a,p.CorrelationId);
 public DocumentaryNarrationSynthesisRequest Narration(DocumentaryMediaAssetPlan p,DocumentaryNarrationBlock x,DocumentaryMediaLanguage l,int a){var request=new DocumentaryNarrationSynthesisRequest(p,x,"default",l,p.AssetFormat,p.ExpectedSampleRate,p.ExpectedChannelCount,a,p.CorrelationId);var resolved=voices.Resolve(request);if(!resolved.Succeeded)throw new InvalidOperationException(resolved.Failure?.Message);return request with { VoiceProfileId=resolved.VoiceId! };}
 public DocumentarySubtitleGenerationRequest Subtitle(DocumentaryMediaAssetPlan p,DocumentaryMediaVariant v,DocumentaryMediaScene s,long d)=>new(p,v.VariantType,s.SceneId,v.Language,new ReadOnlyCollection<DocumentarySubtitleCue>(s.SubtitleCues.OrderBy(x=>x.Sequence).ToArray()),d,p.AssetFormat,p.CorrelationId);
 public DocumentarySceneCompositionRequest Scene(DocumentaryMediaAssetPlan p,DocumentaryMediaScene s,IReadOnlyList<DocumentaryMediaAssetResult> v,DocumentaryMediaAssetResult n,DocumentaryMediaAssetResult sub,long d,int a)=>new(p,s,v,n,sub,d,s.Timing.PlannedDurationMilliseconds,Math.Max(d,s.Timing.PlannedDurationMilliseconds),s.Transition,p.ExpectedWidth,p.ExpectedHeight,p.ExpectedFrameRate,p.CorrelationId,a);
 public DocumentaryVariantCompositionRequest Variant(DocumentaryMediaAssetPlan p,DocumentaryMediaVariant v,IReadOnlyList<DocumentaryMediaAssetResult> scenes,int a)=>new(p,v,scenes,p.ExpectedWidth,p.ExpectedHeight,p.ExpectedFrameRate,p.ExpectedSampleRate,p.ExpectedChannelCount,p.AssetFormat,p.CorrelationId,a);
 public DocumentaryMediaVerificationRequest Verification(DocumentaryMediaAssetPlan p,DocumentaryPhysicalArtifactKind k,string variant,string? scene,int a,DocumentaryProductionSubtitleStrategy strategy,bool requireAudio=true,bool allowAudio=true)=>new(p.AssetId,p.AssetType,p.AssetFormat,k,p.CorrelationId,a,variant,scene,"video/mp4",p.ExpectedDurationMilliseconds,p.ExpectedWidth,p.ExpectedHeight,p.ExpectedFrameRate,p.ExpectedSampleRate,p.ExpectedChannelCount,true,requireAudio,allowAudio,strategy==DocumentaryProductionSubtitleStrategy.Embedded,true,VerificationProfileId:k==DocumentaryPhysicalArtifactKind.SceneVideo?DocumentaryMediaVerificationPolicyIds.SceneVideoVerificationV1:DocumentaryMediaVerificationPolicyIds.VariantVideoVerificationV1);
}

public sealed class DocumentaryProductionExecutionCoordinator(IOptions<DocumentaryProductionExecutionHostOptions> hostOptions,IOptions<DocumentaryProductionAdaptersOptions> bridgeOptions,IDocumentaryProductionExecutionContextFactory contexts,IDocumentaryProductionWorkspaceManager workspaces,IDocumentaryProductionDiagnosticsWriter diagnostics,IDocumentaryPhysicalArtifactRegistry artifacts,IDocumentaryProductionAdapterRegistry adapters,IDocumentaryProductionAttemptContextFactory attempts,IDocumentaryProductionExecutionRequestBuilder requests,IDocumentaryProductionExecutionDependencyResolver dependencies,IDocumentaryProductionExecutionRecordMapper recordMapper,IDocumentaryProductionOperationRunner runner,IDocumentaryProductionClock clock):IDocumentaryProductionExecutionCoordinator {
 static readonly DocumentaryProductionOperationKind[] Required=[DocumentaryProductionOperationKind.VisualGeneration,DocumentaryProductionOperationKind.NarrationSynthesis,DocumentaryProductionOperationKind.SubtitleGeneration,DocumentaryProductionOperationKind.SceneComposition,DocumentaryProductionOperationKind.VariantComposition,DocumentaryProductionOperationKind.MediaVerification];
 public async Task<DocumentaryProductionExecutionResult> ExecuteAsync(DocumentaryMediaPipelineRequest request,CancellationToken token){
  token.ThrowIfCancellationRequested();ArgumentNullException.ThrowIfNull(request);var context=contexts.Create(request);if(!hostOptions.Value.Enabled)return Empty(context,DocumentaryProductionExecutionStatus.NotStarted);
  DocumentaryMediaPipelineValidator.ValidateRequest(request);var workspace=await workspaces.CreateAsync(context,token);await diagnostics.WriteAsync(workspace.DiagnosticsDirectory,"execution-started.json",new{context.ExecutionId,context.CorrelationId,context.StartedAtUtc,Status="Preparing"},token);
  var missing=Required.Where(x=>!adapters.IsAvailable(x)).ToArray();if(missing.Length>0){var f=new DocumentaryProductionFailure(DocumentaryProductionFailureCode.AdapterUnavailable,$"Required production adapters are unavailable: {string.Join(", ",missing)}.");return await Finish(context,workspace,[],[f],DocumentaryProductionExecutionStatus.Failed,token);}
  var plan=new DocumentaryMediaPipelinePlanner().Plan(request);var variants=new List<DocumentaryProductionVariantExecutionResult>();var failures=new List<DocumentaryProductionFailure>();
  foreach(var variant in request.MediaProject.Variants){token.ThrowIfCancellationRequested();var vp=plan.VariantPlans.Single(x=>x.VariantId==variant.VariantId);var vr=await ExecuteVariant(variant,vp,context,workspace,token);variants.Add(vr);failures.AddRange(vr.Failures);if(vr.Status!=DocumentaryProductionItemStatus.Succeeded&&!hostOptions.Value.ContinueOtherVariantsAfterVariantFailure)break;}
  var status=Status(variants,failures);return await Finish(context,workspace,variants,failures,status,token,request,plan);
 }
 async Task<DocumentaryProductionVariantExecutionResult> ExecuteVariant(DocumentaryMediaVariant variant,DocumentaryMediaVariantExecutionPlan plan,DocumentaryProductionExecutionContext context,DocumentaryProductionWorkspace workspace,CancellationToken token){
  var started=clock.UtcNow;var scenes=new List<DocumentaryProductionSceneExecutionResult>();var failures=new List<DocumentaryProductionFailure>();
  foreach(var scene in variant.Scenes.OrderBy(x=>x.Sequence)){var result=await ExecuteScene(variant,scene,plan,context,workspace,token);scenes.Add(result);failures.AddRange(result.Failures);if(result.Status!=DocumentaryProductionItemStatus.Succeeded)return new(variant.VariantId,variant.VariantType,variant.Language,result.Status,scenes,null,null,failures,result.AttemptCount,started,clock.UtcNow,result.DiagnosticsReference);}
  IReadOnlyList<DocumentaryPhysicalArtifactDescriptor> registeredScenes;try{registeredScenes=await dependencies.ResolveOrderedAsync(plan.SceneVideoAssetPlans,DocumentaryPhysicalArtifactKind.SceneVideo,plan.VariantVideoAssetPlan.CorrelationId,token);}catch(InvalidOperationException){failures.Add(new(DocumentaryProductionFailureCode.SourceArtifactMissing,"A registered scene video dependency is missing."));return new(variant.VariantId,variant.VariantType,variant.Language,DocumentaryProductionItemStatus.Failed,scenes,null,null,failures,1,started,clock.UtcNow,null);}
  var sceneAssets=registeredScenes.Select(d=>Map(plan.SceneVideoAssetPlans.Single(p=>p.AssetId==d.AssetId),d)).ToArray();
  var composition=await runner.ExecuteAsync(Operation(context,DocumentaryProductionOperationKind.VariantComposition,plan.VariantVideoAssetPlan,DocumentaryVariantCompositionProviderIds.ExistingFFmpegVariantComposer,variant.VariantId,null),async(a,t)=>await adapters.VariantComposition!.ComposeAsync(requests.Variant(plan.VariantVideoAssetPlan,variant,sceneAssets,a.AttemptNumber),context,a,workspace,t),x=>x.Succeeded,x=>x.Failure,token);
  var composed=composition.Value;if(!composition.Succeeded||composed is null){failures.Add(composition.Failure!);return new(variant.VariantId,variant.VariantType,variant.Language,DocumentaryProductionItemStatus.Failed,scenes,null,null,failures,composition.AttemptCount,started,clock.UtcNow,composed?.ProviderDiagnosticsReference);}
  DocumentaryPhysicalArtifactDescriptor finalArtifact;try{finalArtifact=await dependencies.ResolveAsync(plan.VariantVideoAssetPlan.AssetId,DocumentaryPhysicalArtifactKind.VariantVideo,plan.VariantVideoAssetPlan.CorrelationId,token);}catch(InvalidOperationException){failures.Add(new(DocumentaryProductionFailureCode.SourceArtifactMissing,"The variant adapter did not register its finalized artifact."));return new(variant.VariantId,variant.VariantType,variant.Language,DocumentaryProductionItemStatus.Failed,scenes,null,null,failures,composition.AttemptCount,started,clock.UtcNow,null);}
  DocumentaryProductionMediaVerificationAdapterResult? verification=null;var attempts=composition.AttemptCount;
  if(hostOptions.Value.VerifyFinalVariants){var verified=await runner.ExecuteAsync(Operation(context,DocumentaryProductionOperationKind.MediaVerification,plan.VariantVideoAssetPlan,DocumentaryMediaVerificationProviderIds.ExistingFFprobeMediaVerifier,variant.VariantId,null),async(a,t)=>await adapters.MediaVerification!.VerifyAsync(requests.Verification(plan.VariantVideoAssetPlan,DocumentaryPhysicalArtifactKind.VariantVideo,variant.VariantId,null,a.AttemptNumber,DocumentaryProductionSubtitleStrategy.Sidecar,true),context,a,workspace,t),x=>x.Succeeded&&x.Verified,x=>x.Failure??new(DocumentaryProductionFailureCode.OutputFormatInvalid,"Final variant verification failed."),token);verification=verified.Value;attempts=Math.Max(attempts,verified.AttemptCount);if(!verified.Succeeded){failures.Add(verified.Failure!);return new(variant.VariantId,variant.VariantType,variant.Language,DocumentaryProductionItemStatus.VerificationFailed,scenes,finalArtifact,verification,failures,attempts,started,clock.UtcNow,verification?.ProviderDiagnosticsReference);}}
  return new(variant.VariantId,variant.VariantType,variant.Language,DocumentaryProductionItemStatus.Succeeded,scenes,finalArtifact,verification,failures,attempts,started,clock.UtcNow,composed.ProviderDiagnosticsReference);
 }
 async Task<DocumentaryProductionSceneExecutionResult> ExecuteScene(DocumentaryMediaVariant variant,DocumentaryMediaScene scene,DocumentaryMediaVariantExecutionPlan plan,DocumentaryProductionExecutionContext context,DocumentaryProductionWorkspace workspace,CancellationToken token){
  var failures=new List<DocumentaryProductionFailure>();var visualArtifacts=new List<DocumentaryPhysicalArtifactDescriptor>();DocumentaryPhysicalArtifactDescriptor? narration=null,subtitle=null,video=null;var visualResults=new List<DocumentaryMediaAssetResult>();var maxAttempt=1;
  foreach(var prompt in scene.VisualPrompts.OrderBy(x=>x.Sequence)){var p=plan.SceneAssetPlans.Single(x=>x.SceneId==scene.SceneId&&x.SourceInstructionId==prompt.VisualPromptId);var run=await runner.ExecuteAsync(Operation(context,DocumentaryProductionOperationKind.VisualGeneration,p,"VisualProvider",variant.VariantId,scene.SceneId),async(a,t)=>await adapters.VisualGeneration!.GenerateAsync(requests.Visual(p,prompt,a.AttemptNumber),context,a,workspace,t),x=>x.Succeeded,x=>x.Failure,token);maxAttempt=Math.Max(maxAttempt,run.AttemptCount);if(!run.Succeeded)return Failed(run.Failure!);try{var registered=await dependencies.ResolveAsync(p.AssetId,DocumentaryPhysicalArtifactKind.VisualImage,p.CorrelationId,token);visualArtifacts.Add(registered);visualResults.Add(Map(p,registered));}catch(InvalidOperationException){return Failed(new(DocumentaryProductionFailureCode.SourceArtifactMissing,"The visual adapter did not register its finalized artifact."));}}
  var narrationPlan=plan.NarrationAssetPlans.Single(x=>x.SceneId==scene.SceneId);var narrationBlock=CombineNarration(scene);var narrationRun=await runner.ExecuteAsync(Operation(context,DocumentaryProductionOperationKind.NarrationSynthesis,narrationPlan,DocumentaryNarrationProviderIds.AzureSpeech,variant.VariantId,scene.SceneId),async(a,t)=>await adapters.NarrationSynthesis!.SynthesizeAsync(requests.Narration(narrationPlan,narrationBlock,variant.Language,a.AttemptNumber),context,a,workspace,t),x=>x.Succeeded,x=>x.Failure,token);maxAttempt=Math.Max(maxAttempt,narrationRun.AttemptCount);if(!narrationRun.Succeeded)return Failed(narrationRun.Failure!);try{narration=await dependencies.ResolveAsync(narrationPlan.AssetId,DocumentaryPhysicalArtifactKind.NarrationAudio,narrationPlan.CorrelationId,token);}catch(InvalidOperationException){return Failed(new(DocumentaryProductionFailureCode.SourceArtifactMissing,"The narration adapter did not register its finalized artifact."));}
  var subtitlePlan=plan.SubtitleAssetPlans.Single(x=>x.SceneId==scene.SceneId);var subtitleRequest=requests.Subtitle(subtitlePlan,variant,scene,narration.DurationMilliseconds!.Value);var subtitleRun=await runner.ExecuteAsync(Operation(context,DocumentaryProductionOperationKind.SubtitleGeneration,subtitlePlan,DocumentarySubtitleProviderIds.ExistingSubtitlePipeline,variant.VariantId,scene.SceneId),async(a,t)=>await adapters.SubtitleGeneration!.GenerateAsync(subtitleRequest,context,a,workspace,t),x=>x.Succeeded,x=>x.Failure,token);maxAttempt=Math.Max(maxAttempt,subtitleRun.AttemptCount);if(!subtitleRun.Succeeded)return Failed(subtitleRun.Failure!);try{subtitle=await dependencies.ResolveAsync(subtitlePlan.AssetId,DocumentaryPhysicalArtifactKind.SubtitleDocument,subtitlePlan.CorrelationId,token);}catch(InvalidOperationException){return Failed(new(DocumentaryProductionFailureCode.SourceArtifactMissing,"The subtitle adapter did not register its finalized artifact."));}
  var scenePlan=plan.SceneVideoAssetPlans.Single(x=>x.SceneId==scene.SceneId);var sceneRun=await runner.ExecuteAsync(Operation(context,DocumentaryProductionOperationKind.SceneComposition,scenePlan,DocumentarySceneCompositionProviderIds.ExistingFFmpegSceneComposer,variant.VariantId,scene.SceneId),async(a,t)=>await adapters.SceneComposition!.ComposeAsync(requests.Scene(scenePlan,scene,visualResults,Map(narrationPlan,narration),Map(subtitlePlan,subtitle),narration.DurationMilliseconds.Value,a.AttemptNumber),context,a,workspace,t),x=>x.Succeeded,x=>x.Failure,token);maxAttempt=Math.Max(maxAttempt,sceneRun.AttemptCount);var composed=sceneRun.Value;if(!sceneRun.Succeeded)return Failed(sceneRun.Failure!);try{video=await dependencies.ResolveAsync(scenePlan.AssetId,DocumentaryPhysicalArtifactKind.SceneVideo,scenePlan.CorrelationId,token);}catch(InvalidOperationException){return Failed(new(DocumentaryProductionFailureCode.SourceArtifactMissing,"The scene adapter did not register its finalized artifact."));}
  DocumentaryProductionMediaVerificationAdapterResult? verification=null;if(hostOptions.Value.VerifySceneVideos){var requireAudio=scene.Timing.NarrationDurationMilliseconds>0;var verifyRun=await runner.ExecuteAsync(Operation(context,DocumentaryProductionOperationKind.MediaVerification,scenePlan,DocumentaryMediaVerificationProviderIds.ExistingFFprobeMediaVerifier,variant.VariantId,scene.SceneId),async(a,t)=>await adapters.MediaVerification!.VerifyAsync(requests.Verification(scenePlan,DocumentaryPhysicalArtifactKind.SceneVideo,variant.VariantId,scene.SceneId,a.AttemptNumber,DocumentaryProductionSubtitleStrategy.Sidecar,requireAudio),context,a,workspace,t),x=>x.Succeeded&&x.Verified,x=>x.Failure??new(DocumentaryProductionFailureCode.OutputFormatInvalid,"Scene verification failed."),token);maxAttempt=Math.Max(maxAttempt,verifyRun.AttemptCount);verification=verifyRun.Value;if(!verifyRun.Succeeded){failures.Add(verifyRun.Failure!);return new(scene.SceneId,scene.Sequence,DocumentaryProductionItemStatus.VerificationFailed,new ReadOnlyCollection<DocumentaryPhysicalArtifactDescriptor>(visualArtifacts),narration,subtitle,video,verification,failures,maxAttempt,verification?.ProviderDiagnosticsReference);}}
  return new(scene.SceneId,scene.Sequence,DocumentaryProductionItemStatus.Succeeded,new ReadOnlyCollection<DocumentaryPhysicalArtifactDescriptor>(visualArtifacts),narration,subtitle,video,verification,failures,maxAttempt,composed?.ProviderDiagnosticsReference);
  DocumentaryProductionSceneExecutionResult Failed(DocumentaryProductionFailure f){failures.Add(f);return new(scene.SceneId,scene.Sequence,DocumentaryProductionItemStatus.Failed,new ReadOnlyCollection<DocumentaryPhysicalArtifactDescriptor>(visualArtifacts),narration,subtitle,video,null,failures,maxAttempt,f.DiagnosticReference);}
 }
 DocumentaryNarrationBlock CombineNarration(DocumentaryMediaScene scene){var blocks=scene.Narration.OrderBy(x=>x.Sequence).ToArray();if(blocks.Length==1)return blocks[0];return new DocumentaryNarrationBlock(blocks[0].NarrationId,blocks[0].Language,string.Join("\n",blocks.Select(x=>x.Text)),blocks[0].Sequence,blocks.Sum(x=>x.EstimatedDurationMilliseconds),blocks.SelectMany(x=>x.KnowledgeReferences).Distinct().ToArray(),blocks[0].CorrelationId);}
 DocumentaryProductionOperationExecutionRequest Operation(DocumentaryProductionExecutionContext context,DocumentaryProductionOperationKind kind,DocumentaryMediaAssetPlan plan,string provider,string? variant,string? scene)=>new(context,kind,plan.AssetId,provider,Timeout(kind),hostOptions.Value.MaximumAttemptsPerOperation,variant,scene);
 DocumentaryProductionAttemptContext Attempt(DocumentaryProductionExecutionContext c,DocumentaryProductionOperationKind k,DocumentaryMediaAssetPlan p,int n,string provider,string? variant,string? scene)=>attempts.Create(c,k,p.AssetId,provider,n,Timeout(k),variant,scene);
 TimeSpan Timeout(DocumentaryProductionOperationKind k){int? specific=k switch{DocumentaryProductionOperationKind.VisualGeneration=>hostOptions.Value.VisualGenerationTimeoutSeconds,DocumentaryProductionOperationKind.NarrationSynthesis=>hostOptions.Value.NarrationSynthesisTimeoutSeconds,DocumentaryProductionOperationKind.SubtitleGeneration=>hostOptions.Value.SubtitleGenerationTimeoutSeconds,DocumentaryProductionOperationKind.SceneComposition=>hostOptions.Value.SceneCompositionTimeoutSeconds,DocumentaryProductionOperationKind.VariantComposition=>hostOptions.Value.VariantCompositionTimeoutSeconds,DocumentaryProductionOperationKind.MediaVerification=>hostOptions.Value.MediaVerificationTimeoutSeconds,_=>null};return specific is not null?TimeSpan.FromSeconds(specific.Value):hostOptions.Value.OperationTimeoutMilliseconds is int milliseconds?TimeSpan.FromMilliseconds(milliseconds):TimeSpan.FromSeconds(bridgeOptions.Value.DefaultOperationTimeoutSeconds);}
 static bool NeverRetry(DocumentaryProductionFailureCode c)=>c is DocumentaryProductionFailureCode.ProviderRejectedRequest or DocumentaryProductionFailureCode.SourceArtifactInvalid or DocumentaryProductionFailureCode.OutputFormatInvalid or DocumentaryProductionFailureCode.DimensionMismatch or DocumentaryProductionFailureCode.AudioStreamMissing or DocumentaryProductionFailureCode.VideoStreamMissing or DocumentaryProductionFailureCode.SubtitleMissing or DocumentaryProductionFailureCode.Cancelled;
 DocumentaryMediaAssetResult Map(DocumentaryMediaAssetPlan p,DocumentaryPhysicalArtifactDescriptor d)=>recordMapper.MapAsset(new(p,d));
 static DocumentaryProductionExecutionStatus Status(IReadOnlyList<DocumentaryProductionVariantExecutionResult> variants,IReadOnlyList<DocumentaryProductionFailure> failures){if(variants.Any(x=>x.Status==DocumentaryProductionItemStatus.VerificationFailed))return DocumentaryProductionExecutionStatus.VerificationFailed;var ok=variants.Count(x=>x.Status==DocumentaryProductionItemStatus.Succeeded);return ok==variants.Count&&ok>0?DocumentaryProductionExecutionStatus.Succeeded:ok>0?DocumentaryProductionExecutionStatus.PartiallySucceeded:DocumentaryProductionExecutionStatus.Failed;}
 async Task<DocumentaryProductionExecutionResult> Finish(DocumentaryProductionExecutionContext c,DocumentaryProductionWorkspace w,IReadOnlyList<DocumentaryProductionVariantExecutionResult> variants,IReadOnlyList<DocumentaryProductionFailure> sourceFailures,DocumentaryProductionExecutionStatus status,CancellationToken token,DocumentaryMediaPipelineRequest? request=null,DocumentaryMediaPipelineExecutionPlan? plan=null){
  var failures=sourceFailures.ToList();string? manifestReference=null,diagnosticsReference=null;var executionRecord=request is not null&&plan is not null?BuildExecutionRecord(request,plan,variants,status):null;
  if(hostOptions.Value.PersistArtifactManifest)try{await artifacts.PersistAsync(w.DiagnosticsDirectory,token);manifestReference=Path.Combine(w.DiagnosticsDirectory,"documentary-artifacts.json");}catch(OperationCanceledException)when(token.IsCancellationRequested){throw;}catch(Exception){failures.Add(new(DocumentaryProductionFailureCode.FileSystemFailure,"Artifact manifest persistence failed."));}
  if(failures.Count>sourceFailures.Count&&status==DocumentaryProductionExecutionStatus.Succeeded)status=DocumentaryProductionExecutionStatus.Failed;
  DocumentaryProductionExecutionResult Result()=>new(status==DocumentaryProductionExecutionStatus.Succeeded,status,c.ExecutionId,c.CorrelationId,executionRecord,new ReadOnlyCollection<DocumentaryProductionVariantExecutionResult>(variants.ToArray()),new ReadOnlyCollection<DocumentaryProductionFailure>(failures.ToArray()),diagnosticsReference,manifestReference,null,false);
  if(hostOptions.Value.PersistExecutionRecord)try{await diagnostics.WriteAsync(w.DiagnosticsDirectory,"documentary-production-execution.json",new{hostResult=Result(),executionRecord,variants,artifacts=executionRecord?.OutputManifest.Assets,failures},token);}catch(OperationCanceledException)when(token.IsCancellationRequested){throw;}catch(Exception){failures.Add(new(DocumentaryProductionFailureCode.FileSystemFailure,"Execution record persistence failed."));if(status==DocumentaryProductionExecutionStatus.Succeeded)status=DocumentaryProductionExecutionStatus.Failed;}
  try{await diagnostics.WriteAsync(w.DiagnosticsDirectory,"execution-completed.json",new{c.ExecutionId,c.CorrelationId,Status=status.ToString(),CompletedAtUtc=clock.UtcNow,VariantCount=variants.Count,FailureCount=failures.Count},token);diagnosticsReference=Path.Combine(w.DiagnosticsDirectory,"execution-completed.json");}catch(OperationCanceledException)when(token.IsCancellationRequested){throw;}catch(Exception){failures.Add(new(DocumentaryProductionFailureCode.FileSystemFailure,"Completion diagnostic persistence failed."));if(status==DocumentaryProductionExecutionStatus.Succeeded)status=DocumentaryProductionExecutionStatus.Failed;}
  // O2.19 is not connected to A3.10. Pipeline success alone is never publishing certification.
  var result=Result();return result with { EligibleForPublishing=result.CertificationResult?.Certified==true };
 }
 DocumentaryMediaPipelineExecutionRecord BuildExecutionRecord(DocumentaryMediaPipelineRequest request,DocumentaryMediaPipelineExecutionPlan plan,IReadOnlyList<DocumentaryProductionVariantExecutionResult> variants,DocumentaryProductionExecutionStatus status){
  var records=new List<DocumentaryMediaVariantExecutionRecord>();
  foreach(var variant in variants){var vp=plan.VariantPlans.Single(x=>x.VariantId==variant.VariantId);var assets=new List<DocumentaryMediaAssetResult>();foreach(var scene in variant.SceneResults.OrderBy(x=>x.Sequence)){var visuals=vp.SceneAssetPlans.Where(x=>x.SceneId==scene.SceneId).OrderBy(x=>x.Sequence).ToArray();for(var i=0;i<Math.Min(visuals.Length,scene.VisualArtifacts.Count);i++)assets.Add(Map(visuals[i],scene.VisualArtifacts[i]));if(scene.NarrationArtifact is not null)assets.Add(Map(vp.NarrationAssetPlans.Single(x=>x.SceneId==scene.SceneId),scene.NarrationArtifact));if(scene.SubtitleArtifact is not null)assets.Add(Map(vp.SubtitleAssetPlans.Single(x=>x.SceneId==scene.SceneId),scene.SubtitleArtifact));if(scene.SceneVideoArtifact is not null)assets.Add(Map(vp.SceneVideoAssetPlans.Single(x=>x.SceneId==scene.SceneId),scene.SceneVideoArtifact) with { Status=scene.VerificationResult?.Verified==true?DocumentaryMediaAssetStatus.Verified:DocumentaryMediaAssetStatus.Generated });}if(variant.FinalVariantArtifact is not null)assets.Add(Map(vp.VariantVideoAssetPlan,variant.FinalVariantArtifact) with { Status=variant.VerificationResult?.Verified==true?DocumentaryMediaAssetStatus.Verified:DocumentaryMediaAssetStatus.Generated });var complete=variant.Status==DocumentaryProductionItemStatus.Succeeded;records.Add(new($"{request.Metadata.ExecutionId}.{variant.VariantId}",variant.VariantId,variant.VariantType,complete?DocumentaryMediaPipelineStatus.Complete:DocumentaryMediaPipelineStatus.Rejected,new ReadOnlyCollection<DocumentaryMediaAssetResult>(assets),variant.SceneResults.Count(x=>x.Status==DocumentaryProductionItemStatus.Succeeded),variant.SceneResults.Count(x=>x.Status!=DocumentaryProductionItemStatus.Succeeded),request.MediaProject.Variants.Single(x=>x.VariantId==variant.VariantId).PlannedDurationMilliseconds,assets.Where(x=>x.AssetType==DocumentaryMediaAssetType.SceneVideo).Sum(x=>x.DurationMilliseconds),complete?vp.VariantVideoAssetPlan.AssetId:null,[],request.Metadata.CorrelationId));}
  var all=records.SelectMany(x=>x.AssetResults).ToArray();var completed=records.Count(x=>x.Status==DocumentaryMediaPipelineStatus.Complete);var pipelineStatus=status==DocumentaryProductionExecutionStatus.Succeeded?DocumentaryMediaPipelineStatus.Complete:completed>0?DocumentaryMediaPipelineStatus.PartiallyComplete:DocumentaryMediaPipelineStatus.Rejected;var manifest=new DocumentaryMediaOutputManifest($"{request.Metadata.ExecutionId}.manifest",request.Metadata.ExecutionId,request.MediaProject.MediaProjectId,request.MediaProject.TopicId,records,all,all.Where(x=>x.Checksum is not null).Select(x=>x.Checksum!).ToArray(),records.Count,all.Length,completed,records.Count-completed,"1.0",request.Metadata.CorrelationId);return new(request.Metadata.ExecutionId,request.MediaProject,request.Policy,request.Metadata,plan,records,manifest,pipelineStatus,request.MediaProject.MediaProjectId,request.MediaProject.MaterializationId,request.MediaProject.TopicId,records.Count,completed,records.Count-completed,all.Length,all.Count(x=>x.Status==DocumentaryMediaAssetStatus.Generated),all.Count(x=>x.Status==DocumentaryMediaAssetStatus.Verified),all.Count(x=>x.Status==DocumentaryMediaAssetStatus.Failed),request.MediaProject.TotalPlannedDurationMilliseconds,records.Sum(x=>x.EffectiveDurationMilliseconds));
 }
 static DocumentaryProductionExecutionResult Empty(DocumentaryProductionExecutionContext c,DocumentaryProductionExecutionStatus s)=>new(false,s,c.ExecutionId,c.CorrelationId,null,[],[],null,null,null,false);
}

// Compatibility facade retained for certified CG-A2 callers; new callers use the coordinator.
public sealed class DocumentaryProductionExecutionHost(IDocumentaryProductionExecutionCoordinator coordinator):IDocumentaryProductionExecutionHost { public async Task<DocumentaryMediaPipelineExecutionRecord?> ExecuteAsync(DocumentaryMediaPipelineRequest request,CancellationToken cancellationToken)=>(await coordinator.ExecuteAsync(request,cancellationToken)).ExecutionRecord; }
