using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Astronomy.MediaFactory.ProductionAdapters;

public sealed class DocumentaryProductionAdaptersOptionsValidator : IValidateOptions<DocumentaryProductionAdaptersOptions> { public ValidateOptionsResult Validate(string? name,DocumentaryProductionAdaptersOptions o){var errors=new List<string>();if(o.CleanupTimeoutSeconds is <1 or >3600)errors.Add("CleanupTimeoutSeconds must be between 1 and 3600.");if(o.DefaultOperationTimeoutSeconds is <1 or >86400)errors.Add("DefaultOperationTimeoutSeconds must be between 1 and 86400.");if(o.ExecutionMode==DocumentaryProductionExecutionMode.Certified&&!o.Enabled)errors.Add("Certified mode requires Enabled.");if(o.Enabled&&string.IsNullOrWhiteSpace(o.WorkspaceRoot))errors.Add("WorkspaceRoot is required when enabled.");if(!string.IsNullOrWhiteSpace(o.WorkspaceRoot)){try{_ = Path.GetFullPath(o.WorkspaceRoot);}catch(Exception e) when(e is ArgumentException or NotSupportedException or PathTooLongException){errors.Add("WorkspaceRoot is not a legal path.");}}return errors.Count==0?ValidateOptionsResult.Success:ValidateOptionsResult.Fail(errors);} }
public sealed class DocumentaryProductionFailureNormalizer : IDocumentaryProductionFailureNormalizer { public DocumentaryProductionFailure Normalize(Exception e,DocumentaryProductionOperationKind operation,bool callerCancelled){if(e is OperationCanceledException&&callerCancelled)throw e;var code=e switch{OperationCanceledException when operation is DocumentaryProductionOperationKind.SceneComposition or DocumentaryProductionOperationKind.VariantComposition=>DocumentaryProductionFailureCode.ProcessTimedOut,OperationCanceledException or TimeoutException=>DocumentaryProductionFailureCode.ProviderTimeout,FileNotFoundException=>DocumentaryProductionFailureCode.SourceArtifactMissing,DirectoryNotFoundException=>DocumentaryProductionFailureCode.SourceArtifactMissing,UnauthorizedAccessException or IOException=>DocumentaryProductionFailureCode.FileSystemFailure,ArgumentException or InvalidOperationException=>DocumentaryProductionFailureCode.ProviderRejectedRequest,_=>DocumentaryProductionFailureCode.ProviderUnavailable};return new(code,code switch{DocumentaryProductionFailureCode.SourceArtifactMissing=>"A required source artifact is missing.",DocumentaryProductionFailureCode.FileSystemFailure=>"A filesystem operation failed.",DocumentaryProductionFailureCode.ProviderTimeout=>"The provider operation timed out.",DocumentaryProductionFailureCode.ProcessTimedOut=>"The process timed out.",_=>"The production operation failed."},code is DocumentaryProductionFailureCode.ProviderTimeout or DocumentaryProductionFailureCode.ProcessTimedOut);}}
public sealed class EmptyDocumentaryProductionAdapterRegistry : IDocumentaryProductionAdapterRegistry { public bool IsAvailable(DocumentaryProductionOperationKind operation)=>false; }
public sealed class DocumentaryProductionExecutionRecordMapper : IDocumentaryProductionExecutionRecordMapper { public DocumentaryMediaAssetResult MapAsset(DocumentaryArtifactMappingContext c){var p=c.Plan;var d=c.Descriptor;if(p.AssetId!=d.AssetId||p.CorrelationId!=d.CorrelationId)throw new ArgumentException("Mapping identity mismatch.");return new(d.AssetId,p.AssetType,p.AssetFormat,DocumentaryMediaAssetStatus.Generated,d.ProviderId,d.ContentIdentity,d.Length,d.DurationMilliseconds??0,d.Width??0,d.Height??0,(int)(d.FrameRate??0),d.AudioSampleRate??0,d.AudioChannelCount??0,d.Checksum,null,null,d.AttemptCount,d.CorrelationId);} }
public sealed class DocumentaryProductionExecutionHost(IOptions<DocumentaryProductionAdaptersOptions> options,IDocumentaryProductionExecutionContextFactory contexts,IDocumentaryProductionWorkspaceManager workspaces,IDocumentaryProductionDiagnosticsWriter diagnostics,IDocumentaryProductionAdapterRegistry adapters) : IDocumentaryProductionExecutionHost {
 public async Task<DocumentaryMediaPipelineExecutionRecord?> ExecuteAsync(DocumentaryMediaPipelineRequest request,CancellationToken token){token.ThrowIfCancellationRequested();if(!options.Value.Enabled)return null;DocumentaryMediaPipelineValidator.ValidateRequest(request);var context=contexts.Create(request);var workspace=await workspaces.CreateAsync(context,token);await diagnostics.WriteAsync(workspace.DiagnosticsDirectory,"execution-started.json",new{context.ExecutionId,context.CorrelationId,context.StartedAtUtc,context.ExecutionMode},token);var failure=new DocumentaryProductionFailure(DocumentaryProductionFailureCode.AdapterUnavailable,"No production adapter is configured.");if(!adapters.IsAvailable(DocumentaryProductionOperationKind.VisualGeneration)){await diagnostics.WriteAsync(workspace.DiagnosticsDirectory,"execution-completed.json",new{context.ExecutionId,context.CorrelationId,Status="Failed",Failure=failure},token);return null;}throw new InvalidOperationException("A3.3 does not execute adapters.");}
}
public static class DocumentaryProductionBridgeServiceCollectionExtensions { public static IServiceCollection AddDocumentaryProductionBridge(this IServiceCollection services,IConfiguration configuration){services.AddOptions<DocumentaryProductionAdaptersOptions>().Bind(configuration.GetSection(DocumentaryProductionAdaptersOptions.SectionName));services.AddSingleton<IValidateOptions<DocumentaryProductionAdaptersOptions>,DocumentaryProductionAdaptersOptionsValidator>();services.AddSingleton<IDocumentaryProductionClock,SystemDocumentaryProductionClock>();services.AddSingleton<IDocumentaryExecutionIdGenerator,DocumentaryExecutionIdGenerator>();services.AddSingleton<IDocumentarySafeFileNameGenerator,DocumentarySafeFileNameGenerator>();services.AddSingleton<IDocumentaryChecksumService,DocumentaryChecksumService>();services.AddSingleton<IDocumentaryContentIdentityFactory,DocumentaryContentIdentityFactory>();services.AddSingleton<IDocumentaryPhysicalArtifactDescriptorValidator,DocumentaryPhysicalArtifactDescriptorValidator>();services.AddSingleton<IDocumentaryMediaProbe,NullDocumentaryMediaProbe>();services.AddSingleton<IDocumentaryProductionFailureNormalizer,DocumentaryProductionFailureNormalizer>();services.AddSingleton<IDocumentaryProductionDiagnosticsWriter,DocumentaryProductionDiagnosticsWriter>();services.AddSingleton<IDocumentaryProductionAdapterRegistry,EmptyDocumentaryProductionAdapterRegistry>();services.AddSingleton<IDocumentaryProductionExecutionRecordMapper,DocumentaryProductionExecutionRecordMapper>();services.AddScoped<IDocumentaryProductionExecutionContextFactory,DocumentaryProductionExecutionContextFactory>();services.AddScoped<IDocumentaryProductionWorkspaceManager,DocumentaryProductionWorkspaceManager>();services.AddScoped<IDocumentaryPhysicalArtifactRegistry,DocumentaryPhysicalArtifactRegistry>();services.AddScoped<IDocumentaryPhysicalArtifactInspector,DocumentaryPhysicalArtifactInspector>();services.AddScoped<IDocumentaryProductionExecutionHost,DocumentaryProductionExecutionHost>();return services;}}
