using System.Collections.ObjectModel;
using System.Text.Json;

namespace Astronomy.MediaFactory.ProductionAdapters;

public sealed class DocumentaryProductionWorkspaceManager(IDocumentarySafeFileNameGenerator names, IDocumentaryChecksumService checksums) : IDocumentaryProductionWorkspaceManager {
 public async Task<DocumentaryProductionWorkspace> CreateAsync(DocumentaryProductionExecutionContext c,CancellationToken token){token.ThrowIfCancellationRequested();var root=Path.GetFullPath(c.WorkspaceRoot);var execution=Below(root,root,names.Create(c.CorrelationId),names.Create(c.ExecutionId));var w=new DocumentaryProductionWorkspace(root,execution,Below(root,execution,"variants"),Below(root,execution,"attempts"),Below(root,execution,"diagnostics"));foreach(var p in new[]{w.VariantsDirectory,w.AttemptsDirectory,w.DiagnosticsDirectory})await CreateDirectoryAsync(p,token);return w;}
 public string GetVariantDirectory(DocumentaryProductionWorkspace w,string variantId)=>Below(w.Root,w.VariantsDirectory,names.Create(variantId));
 public string GetSceneDirectory(DocumentaryProductionWorkspace w,string variantId,int sequence){if(sequence<1)throw new ArgumentOutOfRangeException(nameof(sequence));return Below(w.Root,GetVariantDirectory(w,variantId),"scenes",sequence.ToString("D4"));}
 public string GetAttemptDirectory(DocumentaryProductionWorkspace w,DocumentaryProductionOperationKind operation,string assetId,int attempt){if(attempt<1)throw new ArgumentOutOfRangeException(nameof(attempt));return Below(w.Root,w.AttemptsDirectory,operation.ToString(),names.Create(assetId),attempt.ToString("D2"),"tmp");}
 public string GetFinalArtifactPath(DocumentaryProductionWorkspace w,string variantId,int? scene,DocumentaryPhysicalArtifactKind kind,string assetId,string extension){if(extension.Contains('/')||extension.Contains('\\'))throw new ArgumentException("Invalid extension.");var dir=scene.HasValue?GetSceneDirectory(w,variantId,scene.Value):Below(w.Root,GetVariantDirectory(w,variantId),"output");var leaf=kind switch{DocumentaryPhysicalArtifactKind.VisualImage=>"visuals",DocumentaryPhysicalArtifactKind.NarrationAudio=>"narration",DocumentaryPhysicalArtifactKind.SubtitleDocument=>"subtitles",DocumentaryPhysicalArtifactKind.SceneVideo=>"scene-video",_=>""};return Below(w.Root,dir,leaf,$"{names.Create(assetId)}{(extension.StartsWith('.')?extension:"."+extension)}");}
 public async Task FinalizeArtifactAsync(DocumentaryProductionWorkspace w,string temporaryPath,string finalPath,bool allowReplace,CancellationToken token){token.ThrowIfCancellationRequested();temporaryPath=Below(w.Root,temporaryPath);finalPath=Below(w.Root,finalPath);if(!temporaryPath.Split(Path.DirectorySeparatorChar).Contains("tmp",StringComparer.OrdinalIgnoreCase))throw new InvalidOperationException("Temporary artifact must be in an owned tmp directory.");var info=new FileInfo(temporaryPath);if(!info.Exists)throw new FileNotFoundException("Temporary artifact missing.",temporaryPath);if(info.Length==0)throw new InvalidDataException("Temporary artifact is empty.");var incoming=await checksums.ComputeSha256Async(temporaryPath,token);Directory.CreateDirectory(Path.GetDirectoryName(finalPath)!);if(File.Exists(finalPath)){var existing=await checksums.ComputeSha256Async(finalPath,token);if(existing==incoming){File.Delete(temporaryPath);return;}if(!allowReplace)throw new IOException("Final artifact conflict.");}var staging=finalPath+".finalizing";File.Delete(staging);await CopyFlushedAsync(temporaryPath,staging,token);if(await checksums.ComputeSha256Async(staging,token)!=incoming){File.Delete(staging);throw new IOException("Finalization checksum mismatch.");}File.Move(staging,finalPath,true);File.Delete(temporaryPath);}
 public async Task<string> QuarantineAttemptAsync(DocumentaryProductionWorkspace w,string attemptDirectory,CancellationToken token){token.ThrowIfCancellationRequested();var source=Below(w.Root,attemptDirectory);var target=source.TrimEnd(Path.DirectorySeparatorChar)+"-quarantine";if(Directory.Exists(source))Directory.Move(source,target);await Task.CompletedTask;return target;}
 public async Task CleanupSuccessfulAttemptAsync(DocumentaryProductionWorkspace w,string attemptDirectory,CancellationToken token){token.ThrowIfCancellationRequested();var p=Below(w.Root,attemptDirectory);if(Directory.Exists(p))Directory.Delete(p,true);await Task.CompletedTask;}
 static async Task CreateDirectoryAsync(string path,CancellationToken token){token.ThrowIfCancellationRequested();Directory.CreateDirectory(path);await Task.CompletedTask;}
 static async Task CopyFlushedAsync(string from,string to,CancellationToken token){await using var input=new FileStream(from,FileMode.Open,FileAccess.Read,FileShare.Read,81920,true);await using var output=new FileStream(to,FileMode.CreateNew,FileAccess.Write,FileShare.None,81920,true);await input.CopyToAsync(output,token);await output.FlushAsync(token);output.Flush(true);}
 static string Below(string root,params string[] parts){var full=Path.GetFullPath(Path.Combine(parts));if(!DocumentaryPathComparison.IsBelow(root,full))throw new UnauthorizedAccessException("Path escapes the production workspace.");return full;}
}

public sealed record DocumentaryArtifactManifestEntry(DocumentaryPhysicalArtifactKind Kind,DocumentaryPhysicalArtifactDescriptor Descriptor);
public sealed class DocumentaryPhysicalArtifactRegistry : IDocumentaryPhysicalArtifactRegistry {
 readonly SemaphoreSlim gate=new(1,1);readonly SortedDictionary<string,DocumentaryArtifactManifestEntry> entries=new(StringComparer.Ordinal);string? correlation;
 public async Task RegisterAsync(DocumentaryPhysicalArtifactDescriptor d,DocumentaryPhysicalArtifactKind k,CancellationToken token){await gate.WaitAsync(token);try{correlation??=d.CorrelationId;if(correlation!=d.CorrelationId)throw new InvalidOperationException("Registry correlation mismatch.");if(entries.TryGetValue(d.AssetId,out var old)){if(old.Descriptor.Checksum==d.Checksum)return;throw new InvalidOperationException("Asset checksum conflict.");}entries.Add(d.AssetId,new(k,d));}finally{gate.Release();}}
 public async Task<DocumentaryPhysicalArtifactDescriptor?> GetAsync(string id,CancellationToken token){await gate.WaitAsync(token);try{return entries.TryGetValue(id,out var e)?e.Descriptor:null;}finally{gate.Release();}}
 public async Task<IReadOnlyCollection<DocumentaryPhysicalArtifactDescriptor>> GetAllAsync(string c,CancellationToken token){await gate.WaitAsync(token);try{if(correlation is not null&&correlation!=c)throw new InvalidOperationException("Registry correlation mismatch.");return Array.AsReadOnly(entries.Values.Select(x=>x.Descriptor).ToArray());}finally{gate.Release();}}
 public async Task PersistAsync(string directory,CancellationToken token){await gate.WaitAsync(token);try{Directory.CreateDirectory(directory);var path=Path.Combine(directory,"documentary-artifacts.json");var temp=path+".tmp";var bytes=JsonSerializer.SerializeToUtf8Bytes(entries.Values.ToArray(),JsonOptions.Value);await File.WriteAllBytesAsync(temp,bytes,token);File.Move(temp,path,true);}finally{gate.Release();}}
 internal static readonly Lazy<JsonSerializerOptions> JsonOptions=new(()=>new(){WriteIndented=true,PropertyNamingPolicy=JsonNamingPolicy.CamelCase});
}
public sealed class DocumentaryProductionDiagnosticsWriter : IDocumentaryProductionDiagnosticsWriter { public async Task WriteAsync(string directory,string fileName,object value,CancellationToken token){if(Path.GetFileName(fileName)!=fileName)throw new ArgumentException("Diagnostic file name required.");Directory.CreateDirectory(directory);var path=Path.Combine(directory,fileName);var temp=path+".tmp";var sanitized=Sanitize(JsonSerializer.Serialize(value,DocumentaryPhysicalArtifactRegistry.JsonOptions.Value));await File.WriteAllTextAsync(temp,sanitized,token);File.Move(temp,path,true);}static string Sanitize(string json)=>System.Text.RegularExpressions.Regex.Replace(json,"(?i)(bearer|token|password|secret|api[-_]?key)[^,}\"]*","[REDACTED]"); }
