using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Astronomy.MediaFactory.Contracts;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Astronomy.MediaFactory.Rendering;
using Microsoft.Extensions.Options;

namespace Astronomy.MediaFactory.ProductionAdapters;

public static class DocumentaryMediaVerificationProviderIds { public const string ExistingFFprobeMediaVerifier = "ExistingFFprobeMediaVerifier"; }
public static class DocumentaryMediaVerificationPolicyIds { public const string NarrationAudioVerificationV1="NarrationAudioVerificationV1"; public const string SceneVideoVerificationV1="SceneVideoVerificationV1"; public const string VariantVideoVerificationV1="VariantVideoVerificationV1"; }
public sealed class DocumentaryMediaVerificationAdapterOptions { public const string SectionName="DocumentaryProductionAdapters:MediaVerification"; public bool Enabled {get;set;} public int DurationToleranceMilliseconds {get;set;}=500; public decimal FrameRateTolerance {get;set;}=.01m; public int ProbeTimeoutSeconds {get;set;}=60; public bool PersistVerificationDiagnostics {get;set;}=true; }

public sealed record DocumentaryMediaVerificationRequest(string AssetId, DocumentaryMediaAssetType AssetType, DocumentaryMediaAssetFormat AssetFormat, DocumentaryPhysicalArtifactKind ArtifactKind, string CorrelationId, int Attempt, string? VariantId=null, string? SceneId=null, string? ExpectedContentType=null, long? ExpectedDurationMilliseconds=null, int? ExpectedWidth=null, int? ExpectedHeight=null, decimal? ExpectedFrameRate=null, int? ExpectedAudioSampleRate=null, int? ExpectedAudioChannelCount=null, bool RequireVideo=false, bool RequireAudio=false, bool AllowAudio=true, bool RequireSubtitle=false, bool AllowSubtitle=true, int? DurationToleranceMilliseconds=null, decimal? FrameRateTolerance=null, string? VerificationProfileId=null);
public sealed record DocumentaryMediaVerificationViolation(DocumentaryProductionFailureCode Code,string Message,string? ExpectedValue,string? MeasuredValue,string RuleId);
public sealed record DocumentaryMediaVerificationEvidence(string AssetId,DocumentaryPhysicalArtifactKind ArtifactKind,string VerificationPolicyId,string ProviderId,string? ContainerFormat,long? DurationMilliseconds,int? Width,int? Height,decimal? FrameRate,bool HasVideo,bool HasAudio,bool HasSubtitle,int? AudioSampleRate,int? AudioChannelCount,IReadOnlyList<string> PassedChecks,IReadOnlyList<DocumentaryMediaVerificationViolation> Violations,string CorrelationId);
public sealed record DocumentaryMediaVerificationPolicy(string PolicyId,DocumentaryPhysicalArtifactKind ArtifactKind,IReadOnlySet<DocumentaryMediaAssetFormat> Formats);
public sealed record DocumentaryMediaVerificationEvaluation(bool Verified,DocumentaryMediaVerificationEvidence Evidence,DocumentaryProductionFailure? Failure);
public sealed record DocumentaryMediaVerificationProviderRequest(string AssetId,DocumentaryPhysicalArtifactKind ArtifactKind,DocumentaryMediaAssetType AssetType,DocumentaryMediaAssetFormat AssetFormat,string CorrelationId,int Attempt,string PhysicalPath,string? ExpectedContentType,string VerificationPolicyId,TimeSpan Timeout);
public sealed record DocumentaryMediaVerificationProviderResponse(bool Succeeded,DocumentaryMediaProbeResult? ProbeResult,DocumentaryProductionFailure? Failure,int? ExitCode=null,long? ElapsedMilliseconds=null,string? SanitizedStandardErrorHash=null,string? ProbeVersion=null);
public sealed record DocumentaryProductionMediaVerificationAdapterResult(bool Succeeded,bool Verified,DocumentaryPhysicalArtifactDescriptor? Artifact,DocumentaryMediaVerificationEvidence? VerificationEvidence,DocumentaryProductionFailure? Failure,string RequestedProviderId,string? ActualProviderId,string AssetId,DocumentaryPhysicalArtifactKind ArtifactKind,DocumentaryMediaAssetType AssetType,DocumentaryMediaAssetFormat AssetFormat,string? ContainerFormat=null,long? MeasuredDurationMilliseconds=null,int? MeasuredWidth=null,int? MeasuredHeight=null,decimal? MeasuredFrameRate=null,bool HasVideo=false,bool HasAudio=false,bool HasSubtitle=false,int? AudioSampleRate=null,int? AudioChannelCount=null,string? VerificationPolicyId=null,string? ProviderDiagnosticsReference=null);

public interface IDocumentaryProductionMediaVerificationAdapter { Task<DocumentaryProductionMediaVerificationAdapterResult> VerifyAsync(DocumentaryMediaVerificationRequest request,DocumentaryProductionExecutionContext executionContext,DocumentaryProductionAttemptContext attemptContext,DocumentaryProductionWorkspace workspace,CancellationToken cancellationToken); }
public interface IDocumentaryMediaVerificationPolicyResolver { DocumentaryMediaVerificationPolicy Resolve(DocumentaryMediaVerificationRequest request); }
public interface IDocumentaryMediaVerificationEvaluator { DocumentaryMediaVerificationEvaluation Evaluate(DocumentaryMediaVerificationRequest request,DocumentaryPhysicalArtifactDescriptor artifact,DocumentaryMediaProbeResult probeResult,DocumentaryMediaVerificationPolicy policy); }
public interface IDocumentaryMediaVerificationProviderBinding { string ProviderId {get;} Task<DocumentaryMediaVerificationProviderResponse> ProbeAsync(DocumentaryMediaVerificationProviderRequest request,CancellationToken cancellationToken); }
public interface IDocumentaryMediaVerificationResultMapper { DocumentaryMediaAssetResult Map(DocumentaryMediaVerificationRequest request,DocumentaryProductionMediaVerificationAdapterResult result); }
public interface IDocumentaryFfprobeResultParser { DocumentaryMediaProbeResult Parse(string json); }
public interface IDocumentaryFfprobeProbe { Task<DocumentaryMediaProbeResult> ProbeAsync(string path, TimeSpan timeout, CancellationToken cancellationToken); }

public sealed class DocumentaryMediaVerificationPolicyResolver : IDocumentaryMediaVerificationPolicyResolver {
 public DocumentaryMediaVerificationPolicy Resolve(DocumentaryMediaVerificationRequest r)=>r.ArtifactKind switch {
  DocumentaryPhysicalArtifactKind.NarrationAudio when r.AssetType==DocumentaryMediaAssetType.NarrationAudio=>new(DocumentaryMediaVerificationPolicyIds.NarrationAudioVerificationV1,r.ArtifactKind,new HashSet<DocumentaryMediaAssetFormat>{DocumentaryMediaAssetFormat.Wav,DocumentaryMediaAssetFormat.Mp3,DocumentaryMediaAssetFormat.Aac,DocumentaryMediaAssetFormat.Mp4}),
  DocumentaryPhysicalArtifactKind.SceneVideo when r.AssetType==DocumentaryMediaAssetType.SceneVideo&&r.AssetFormat==DocumentaryMediaAssetFormat.Mp4=>new(DocumentaryMediaVerificationPolicyIds.SceneVideoVerificationV1,r.ArtifactKind,new HashSet<DocumentaryMediaAssetFormat>{DocumentaryMediaAssetFormat.Mp4}),
  DocumentaryPhysicalArtifactKind.VariantVideo when r.AssetType==DocumentaryMediaAssetType.VariantVideo&&r.AssetFormat==DocumentaryMediaAssetFormat.Mp4=>new(DocumentaryMediaVerificationPolicyIds.VariantVideoVerificationV1,r.ArtifactKind,new HashSet<DocumentaryMediaAssetFormat>{DocumentaryMediaAssetFormat.Mp4}),
  _=>throw new NotSupportedException("The artifact kind, type, and format combination is not supported for media verification.")};
}

public sealed class DocumentaryMediaVerificationEvaluator(IOptions<DocumentaryMediaVerificationAdapterOptions> options) : IDocumentaryMediaVerificationEvaluator {
 public DocumentaryMediaVerificationEvaluation Evaluate(DocumentaryMediaVerificationRequest r,DocumentaryPhysicalArtifactDescriptor a,DocumentaryMediaProbeResult p,DocumentaryMediaVerificationPolicy policy){
  var passed=new List<string>();var violations=new List<DocumentaryMediaVerificationViolation>();
  void Check(bool ok,string id,DocumentaryProductionFailureCode code,string message,object? expected=null,object? actual=null){if(ok)passed.Add(id);else violations.Add(new(code,message,Safe(expected),Safe(actual),id));}
  Check(ContainerMatches(r.AssetFormat,p.ContainerFormat),"container",DocumentaryProductionFailureCode.OutputFormatInvalid,"Container does not match the requested format.",r.AssetFormat,p.ContainerFormat);
  var video=p.HasVideoStream==true;var audio=p.HasAudioStream==true;var subtitle=p.HasSubtitleStream==true;
  Check(!r.RequireVideo||video,"video-stream",DocumentaryProductionFailureCode.VideoStreamMissing,"A required video stream is missing.",true,video);
  Check(!r.RequireAudio||audio,"audio-stream-required",DocumentaryProductionFailureCode.AudioStreamMissing,"A required audio stream is missing.",true,audio);
  Check(r.AllowAudio||!audio,"audio-stream-allowed",DocumentaryProductionFailureCode.OutputFormatInvalid,"An audio stream is not allowed.",false,audio);
  Check(!r.RequireSubtitle||subtitle,"subtitle-stream-required",DocumentaryProductionFailureCode.SubtitleMissing,"A required subtitle stream is missing.",true,subtitle);
  Check(r.AllowSubtitle||!subtitle,"subtitle-stream-allowed",DocumentaryProductionFailureCode.OutputFormatInvalid,"A subtitle stream is not allowed.",false,subtitle);
  if(r.ArtifactKind==DocumentaryPhysicalArtifactKind.NarrationAudio)Check(!video,"narration-video-absent",DocumentaryProductionFailureCode.OutputFormatInvalid,"Narration audio contains a video stream.",false,video);
  var durationTolerance=r.DurationToleranceMilliseconds??options.Value.DurationToleranceMilliseconds;
  Check(p.DurationMilliseconds is >0&&(!r.ExpectedDurationMilliseconds.HasValue||Math.Abs(p.DurationMilliseconds.Value-r.ExpectedDurationMilliseconds.Value)<=durationTolerance),"duration",DocumentaryProductionFailureCode.DurationMeasurementFailed,"Duration is missing or outside tolerance.",r.ExpectedDurationMilliseconds,p.DurationMilliseconds);
  if(video||r.RequireVideo){Check(p.Width is >0&&(!r.ExpectedWidth.HasValue||p.Width==r.ExpectedWidth),"width",DocumentaryProductionFailureCode.DimensionMismatch,"Video width does not match.",r.ExpectedWidth,p.Width);Check(p.Height is >0&&(!r.ExpectedHeight.HasValue||p.Height==r.ExpectedHeight),"height",DocumentaryProductionFailureCode.DimensionMismatch,"Video height does not match.",r.ExpectedHeight,p.Height);var t=r.FrameRateTolerance??options.Value.FrameRateTolerance;Check(p.FrameRate is >0&&(!r.ExpectedFrameRate.HasValue||Math.Abs(p.FrameRate.Value-r.ExpectedFrameRate.Value)<=t),"frame-rate",DocumentaryProductionFailureCode.OutputFormatInvalid,"Frame rate is missing or outside tolerance.",r.ExpectedFrameRate,p.FrameRate);}
  if(audio){Check(p.AudioSampleRate is >0&&(!r.ExpectedAudioSampleRate.HasValue||p.AudioSampleRate==r.ExpectedAudioSampleRate),"audio-sample-rate",DocumentaryProductionFailureCode.OutputFormatInvalid,"Audio sample rate does not match.",r.ExpectedAudioSampleRate,p.AudioSampleRate);Check(p.AudioChannelCount is >0&&(!r.ExpectedAudioChannelCount.HasValue||p.AudioChannelCount==r.ExpectedAudioChannelCount),"audio-channels",DocumentaryProductionFailureCode.OutputFormatInvalid,"Audio channel count does not match.",r.ExpectedAudioChannelCount,p.AudioChannelCount);}
  var evidence=new DocumentaryMediaVerificationEvidence(r.AssetId,r.ArtifactKind,policy.PolicyId,DocumentaryMediaVerificationProviderIds.ExistingFFprobeMediaVerifier,p.ContainerFormat,p.DurationMilliseconds,p.Width,p.Height,p.FrameRate,video,audio,subtitle,p.AudioSampleRate,p.AudioChannelCount,new EquatableReadOnlyCollection<string>(passed),new EquatableReadOnlyCollection<DocumentaryMediaVerificationViolation>(violations),r.CorrelationId);
  var failure=violations.Count==0?null:new DocumentaryProductionFailure(violations[0].Code,violations[0].Message,ProviderId:DocumentaryMediaVerificationProviderIds.ExistingFFprobeMediaVerifier);return new(violations.Count==0,evidence,failure);
 }
 static string? Safe(object? value)=>value is null?null:Convert.ToString(value,CultureInfo.InvariantCulture);
 internal static bool ContainerMatches(DocumentaryMediaAssetFormat f,string? container){var names=(container??"").Split(',',StringSplitOptions.TrimEntries|StringSplitOptions.RemoveEmptyEntries).Select(x=>x.ToLowerInvariant()).ToArray();return f switch{DocumentaryMediaAssetFormat.Mp4=>names.Any(x=>x is "mp4" or "mov" or "m4a" or "3gp" or "3g2" or "mj2"),DocumentaryMediaAssetFormat.Wav=>names.Contains("wav"),DocumentaryMediaAssetFormat.Mp3=>names.Contains("mp3"),DocumentaryMediaAssetFormat.Aac=>names.Contains("aac"),_=>false};}
}

internal sealed class EquatableReadOnlyCollection<T>(IList<T> values) : ReadOnlyCollection<T>(values) {
 public override bool Equals(object? obj)=>ReferenceEquals(this,obj)||obj is IReadOnlyList<T> other&&this.SequenceEqual(other);
 public override int GetHashCode(){var hash=new HashCode();foreach(var value in this)hash.Add(value);return hash.ToHashCode();}
}

public sealed class DocumentaryFfprobeResultParser : IDocumentaryFfprobeResultParser {
 public DocumentaryMediaProbeResult Parse(string json){
  if(string.IsNullOrWhiteSpace(json))return Invalid();try{using var doc=JsonDocument.Parse(json);var root=doc.RootElement;string? container=null;long? duration=null;if(root.TryGetProperty("format",out var format)){container=Text(format,"format_name");if(Decimal(format,"duration") is { } seconds)duration=checked((long)Math.Round(seconds*1000m,MidpointRounding.AwayFromZero));}
   bool video=false,audio=false,subtitle=false;int? width=null,height=null,sample=null,channels=null;decimal? fps=null;
   if(root.TryGetProperty("streams",out var streams)&&streams.ValueKind==JsonValueKind.Array)foreach(var s in streams.EnumerateArray()){var type=Text(s,"codec_type");if(type=="video"){video=true;width??=Int(s,"width");height??=Int(s,"height");fps??=Rate(Text(s,"avg_frame_rate"))??Rate(Text(s,"r_frame_rate"));}else if(type=="audio"){audio=true;sample??=Int(s,"sample_rate");channels??=Int(s,"channels");}else if(type=="subtitle")subtitle=true;}
   return new(true,duration,video,audio,subtitle,width,height,fps,sample,channels,container);
  }catch(Exception e) when(e is JsonException or OverflowException or InvalidOperationException){return Invalid();}}
 static string? Text(JsonElement e,string name)=>e.TryGetProperty(name,out var p)&&p.ValueKind==JsonValueKind.String?p.GetString():null;
 static int? Int(JsonElement e,string name){if(!e.TryGetProperty(name,out var p))return null;var text=p.ValueKind==JsonValueKind.String?p.GetString():p.GetRawText();return int.TryParse(text,NumberStyles.Integer,CultureInfo.InvariantCulture,out var n)&&n>0?n:null;}
 static decimal? Decimal(JsonElement e,string name){if(!e.TryGetProperty(name,out var p))return null;var text=p.ValueKind==JsonValueKind.String?p.GetString():p.ValueKind==JsonValueKind.Number?p.GetRawText():null;return decimal.TryParse(text,NumberStyles.Number,CultureInfo.InvariantCulture,out var n)&&n>0?n:null;}
 static decimal? Rate(string? text){if(string.IsNullOrWhiteSpace(text))return null;var parts=text.Split('/');if(parts.Length==2&&decimal.TryParse(parts[0],NumberStyles.Number,CultureInfo.InvariantCulture,out var n)&&decimal.TryParse(parts[1],NumberStyles.Number,CultureInfo.InvariantCulture,out var d)&&n>0&&d>0)return n/d;return decimal.TryParse(text,NumberStyles.Number,CultureInfo.InvariantCulture,out var v)&&v>0?v:null;}
 static DocumentaryMediaProbeResult Invalid()=>new(false,Failure:new(DocumentaryProductionFailureCode.ProviderInvalidResponse,"FFprobe returned invalid structured metadata.",ProviderId:DocumentaryMediaVerificationProviderIds.ExistingFFprobeMediaVerifier));
}

public sealed class ExistingFfprobeDocumentaryMediaProbe(IProcessRunner runner,IDocumentaryFfprobeResultParser parser,IOptions<RenderingOptions> rendering,IOptions<DocumentaryMediaVerificationAdapterOptions> options):IDocumentaryMediaProbe,IDocumentaryFfprobeProbe {
 public Task<DocumentaryMediaProbeResult> ProbeAsync(string path,CancellationToken token)=>ProbeAsync(path,TimeSpan.FromSeconds(options.Value.ProbeTimeoutSeconds),token);
 public async Task<DocumentaryMediaProbeResult> ProbeAsync(string path,TimeSpan timeout,CancellationToken token){token.ThrowIfCancellationRequested();var executable=string.IsNullOrWhiteSpace(rendering.Value.FfprobePath)?"ffprobe":rendering.Value.FfprobePath!;var args=$"-v error -show_format -show_streams -of json -- {Quote(path)}";ProcessExecutionResult result;try{result=await runner.ExecuteAsync(executable,args,token,timeout);}catch(OperationCanceledException) when(token.IsCancellationRequested){throw;}catch(Win32Exception){return Fail(DocumentaryProductionFailureCode.DependencyMissing,"The FFprobe executable is unavailable.");}catch(Exception){return Fail(DocumentaryProductionFailureCode.ProcessStartFailed,"FFprobe could not be started.");}token.ThrowIfCancellationRequested();if(result.TimedOut)return Fail(DocumentaryProductionFailureCode.ProcessTimedOut,"FFprobe timed out.");if(!string.IsNullOrWhiteSpace(result.ExceptionText))return Fail(DocumentaryProductionFailureCode.ProcessStartFailed,"FFprobe execution failed.");if(result.ExitCode!=0)return Fail(DocumentaryProductionFailureCode.ProcessExitedWithError,"FFprobe exited with an error.");if(string.IsNullOrWhiteSpace(result.StandardOutput))return Fail(DocumentaryProductionFailureCode.ProviderInvalidResponse,"FFprobe returned invalid structured metadata.");return parser.Parse(result.StandardOutput);}
 static string Quote(string value)=>$"\"{value.Replace("\\","\\\\",StringComparison.Ordinal).Replace("\"","\\\"",StringComparison.Ordinal)}\"";
 static DocumentaryMediaProbeResult Fail(DocumentaryProductionFailureCode code,string message)=>new(false,Failure:new(code,message,ProviderId:DocumentaryMediaVerificationProviderIds.ExistingFFprobeMediaVerifier));
}

public sealed class ExistingFFprobeDocumentaryMediaVerificationProviderBinding(IDocumentaryFfprobeProbe probe):IDocumentaryMediaVerificationProviderBinding {
 public string ProviderId=>DocumentaryMediaVerificationProviderIds.ExistingFFprobeMediaVerifier;
 public async Task<DocumentaryMediaVerificationProviderResponse> ProbeAsync(DocumentaryMediaVerificationProviderRequest r,CancellationToken token){var started=DateTimeOffset.UtcNow;var p=await probe.ProbeAsync(r.PhysicalPath,r.Timeout,token);if(p is null)return new(false,null,new(DocumentaryProductionFailureCode.ProviderInvalidResponse,"The FFprobe provider returned an invalid response."));if(!p.Succeeded&&p.Failure is null)return new(false,p,new(DocumentaryProductionFailureCode.ProviderInvalidResponse,"The FFprobe provider returned an invalid response."));return new(p.Succeeded,p,p.Failure,ElapsedMilliseconds:Math.Max(0,(long)(DateTimeOffset.UtcNow-started).TotalMilliseconds));}
}

public sealed class DocumentaryProductionMediaVerificationAdapter(IOptions<DocumentaryMediaVerificationAdapterOptions> options,IDocumentaryPhysicalArtifactRegistry registry,IDocumentaryPhysicalArtifactDescriptorValidator validator,IDocumentaryChecksumService checksums,IDocumentaryMediaVerificationPolicyResolver policies,IEnumerable<IDocumentaryMediaVerificationProviderBinding> providers,IDocumentaryMediaVerificationEvaluator evaluator,IDocumentaryProductionDiagnosticsWriter diagnostics,IDocumentarySafeFileNameGenerator names,IDocumentaryProductionFailureNormalizer failures):IDocumentaryProductionMediaVerificationAdapter {
 public async Task<DocumentaryProductionMediaVerificationAdapterResult> VerifyAsync(DocumentaryMediaVerificationRequest r,DocumentaryProductionExecutionContext execution,DocumentaryProductionAttemptContext attempt,DocumentaryProductionWorkspace workspace,CancellationToken token){
  token.ThrowIfCancellationRequested();const string requested=DocumentaryMediaVerificationProviderIds.ExistingFFprobeMediaVerifier;DocumentaryProductionMediaVerificationAdapterResult Fail(DocumentaryProductionFailure f,DocumentaryPhysicalArtifactDescriptor? artifact=null)=>new(false,false,artifact,null,f,requested,null,r.AssetId,r.ArtifactKind,r.AssetType,r.AssetFormat);
  if(!options.Value.Enabled)return Fail(new(DocumentaryProductionFailureCode.AdapterUnavailable,"Media verification is disabled."));
  if(r.CorrelationId!=execution.CorrelationId||r.CorrelationId!=attempt.CorrelationId||r.AssetId!=attempt.AssetId||r.Attempt!=attempt.AttemptNumber||attempt.OperationKind!=DocumentaryProductionOperationKind.MediaVerification)return Fail(new(DocumentaryProductionFailureCode.ProviderRejectedRequest,"Verification execution identity does not match."));
  DocumentaryMediaVerificationPolicy policy;try{policy=policies.Resolve(r);}catch(NotSupportedException){return Fail(new(DocumentaryProductionFailureCode.ProviderRejectedRequest,"The requested media verification policy is unsupported."));}
  var registered=await registry.GetRegisteredAsync(r.AssetId,token);var artifact=registered?.Descriptor;if(artifact is null)return Fail(new(DocumentaryProductionFailureCode.SourceArtifactMissing,"The registered source artifact is missing."));if(registered!.Kind!=r.ArtifactKind)return Fail(new(DocumentaryProductionFailureCode.SourceArtifactInvalid,"The registered source artifact kind does not match."),artifact);
  if(artifact.AssetId!=r.AssetId||artifact.CorrelationId!=r.CorrelationId||validator.Validate(artifact).Count>0)return Fail(new(DocumentaryProductionFailureCode.SourceArtifactInvalid,"The registered source artifact descriptor is invalid."),artifact);
  var path=Path.GetFullPath(artifact.PhysicalPath);if(DocumentaryPathComparison.IsBelow(workspace.AttemptsDirectory,path))return Fail(new(DocumentaryProductionFailureCode.SourceArtifactInvalid,"The source artifact is not finalized."),artifact);if(!File.Exists(path))return Fail(new(DocumentaryProductionFailureCode.SourceArtifactMissing,"The physical source artifact is missing."),artifact);if(new FileInfo(path).Length<=0)return Fail(new(DocumentaryProductionFailureCode.SourceArtifactInvalid,"The physical source artifact is empty."),artifact);
  if(artifact.Checksum.Length!=64||artifact.Checksum.Any(c=>c is not (>= '0' and <= '9') and not (>= 'a' and <= 'f')))return Fail(new(DocumentaryProductionFailureCode.SourceArtifactInvalid,"The physical source artifact identity is invalid."),artifact);var checksum=await checksums.ComputeSha256Async(path,token);if(checksum!=artifact.Checksum||artifact.ContentIdentity!=$"sha256:{checksum}"||new FileInfo(path).Length!=artifact.Length)return Fail(new(DocumentaryProductionFailureCode.SourceArtifactInvalid,"The physical source artifact identity is invalid."),artifact);
  if(!string.IsNullOrWhiteSpace(r.ExpectedContentType)&&!string.Equals(r.ExpectedContentType,artifact.ContentType,StringComparison.OrdinalIgnoreCase))return Fail(new(DocumentaryProductionFailureCode.SourceArtifactInvalid,"The source artifact content type does not match."),artifact);
  var matches=providers.Where(x=>x.ProviderId==requested).ToArray();if(matches.Length!=1)return Fail(new(DocumentaryProductionFailureCode.AdapterUnavailable,"The FFprobe verification provider is unavailable or ambiguous."),artifact);
  DocumentaryMediaVerificationProviderResponse response;try{response=await matches[0].ProbeAsync(new(r.AssetId,r.ArtifactKind,r.AssetType,r.AssetFormat,r.CorrelationId,r.Attempt,path,r.ExpectedContentType,policy.PolicyId,TimeSpan.FromSeconds(Math.Min(options.Value.ProbeTimeoutSeconds,Math.Max(1,attempt.Timeout.TotalSeconds)))),token);}catch(OperationCanceledException) when(token.IsCancellationRequested){throw;}catch(Exception e){return Fail(failures.Normalize(e,DocumentaryProductionOperationKind.MediaVerification,false),artifact);}if(response is null||!response.Succeeded||response.ProbeResult is not {Succeeded:true} probe)return Fail(response.Failure??response.ProbeResult?.Failure??new(DocumentaryProductionFailureCode.ProviderInvalidResponse,"The FFprobe provider returned an invalid response."),artifact);
  var evaluation=evaluator.Evaluate(r,artifact,probe,policy);var diagnosticName=$"verification-{names.Create(r.AssetId)}-{r.Attempt:D2}.json";string? reference=null;
  if(options.Value.PersistVerificationDiagnostics){try{await diagnostics.WriteAsync(workspace.DiagnosticsDirectory,diagnosticName,new{execution.ExecutionId,r.CorrelationId,r.AssetId,ArtifactKind=r.ArtifactKind.ToString(),AssetType=r.AssetType.ToString(),AssetFormat=r.AssetFormat.ToString(),VerificationPolicyId=policy.PolicyId,ProviderId=matches[0].ProviderId,Attempt=r.Attempt,PhysicalContentIdentity=artifact.ContentIdentity,artifact.Checksum,artifact.Length,r.ExpectedContentType,ActualContainer=probe.ContainerFormat,r.ExpectedDurationMilliseconds,ActualDurationMilliseconds=probe.DurationMilliseconds,DurationToleranceMilliseconds=r.DurationToleranceMilliseconds??options.Value.DurationToleranceMilliseconds,r.ExpectedWidth,ActualWidth=probe.Width,r.ExpectedHeight,ActualHeight=probe.Height,r.ExpectedFrameRate,ActualFrameRate=probe.FrameRate,FrameRateTolerance=r.FrameRateTolerance??options.Value.FrameRateTolerance,r.RequireVideo,HasVideo=probe.HasVideoStream==true,r.RequireAudio,HasAudio=probe.HasAudioStream==true,r.AllowAudio,r.RequireSubtitle,HasSubtitle=probe.HasSubtitleStream==true,r.ExpectedAudioSampleRate,ActualAudioSampleRate=probe.AudioSampleRate,r.ExpectedAudioChannelCount,ActualAudioChannelCount=probe.AudioChannelCount,evaluation.Evidence.PassedChecks,evaluation.Evidence.Violations,response.ExitCode,response.ElapsedMilliseconds,response.SanitizedStandardErrorHash,Outcome=evaluation.Verified?"Verified":"Failed"},token);reference=diagnosticName;}catch(OperationCanceledException) when(token.IsCancellationRequested){throw;}catch(Exception e){return Fail(failures.Normalize(e,DocumentaryProductionOperationKind.MediaVerification,false),artifact);}}
  return new(true,evaluation.Verified,artifact,evaluation.Evidence,evaluation.Failure,requested,matches[0].ProviderId,r.AssetId,r.ArtifactKind,r.AssetType,r.AssetFormat,probe.ContainerFormat,probe.DurationMilliseconds,probe.Width,probe.Height,probe.FrameRate,probe.HasVideoStream==true,probe.HasAudioStream==true,probe.HasSubtitleStream==true,probe.AudioSampleRate,probe.AudioChannelCount,policy.PolicyId,reference);
 }
}

public sealed class DocumentaryMediaVerificationResultMapper:IDocumentaryMediaVerificationResultMapper { public DocumentaryMediaAssetResult Map(DocumentaryMediaVerificationRequest r,DocumentaryProductionMediaVerificationAdapterResult x){var a=x.Artifact;return new(r.AssetId,r.AssetType,r.AssetFormat,x.Verified?DocumentaryMediaAssetStatus.Verified:DocumentaryMediaAssetStatus.Failed,x.ActualProviderId,a?.ContentIdentity,a?.Length??0,x.MeasuredDurationMilliseconds??0,x.MeasuredWidth??0,x.MeasuredHeight??0,(int)(x.MeasuredFrameRate??0),x.AudioSampleRate??0,x.AudioChannelCount??0,a?.Checksum,x.Failure?.Code.ToString(),x.Failure?.Message,r.Attempt,r.CorrelationId);}}
