using System.Diagnostics;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Microsoft.Extensions.Options;

namespace Astronomy.MediaFactory.ProductionAdapters;

public static class DocumentarySubtitleProviderIds { public const string ExistingSubtitlePipeline = "ExistingSubtitlePipeline"; }
public sealed class DocumentarySubtitleAdapterOptions { public const string SectionName="DocumentaryProductionAdapters:Subtitles"; public bool Enabled{get;set;} public bool RequireExactTextReconstruction{get;set;}=true; public int AlignmentToleranceMilliseconds{get;set;}=250; public bool RetainProviderNativeSubtitle{get;set;} }
public sealed record DocumentarySubtitleCuePolicy(int MaximumCharactersPerLine=42,int MaximumLinesPerCue=2,bool AllowOverlap=false);
public sealed record DocumentarySubtitleProviderRequest(string AssetId,string SourceInstructionId,string? SceneId,string VariantId,string CorrelationId,DocumentaryMediaLanguage Language,string NarrationBlockId,string NarrationText,string NarrationAudioPath,long NarrationDurationMilliseconds,DocumentaryMediaAssetFormat RequestedSubtitleFormat,int Attempt,string OutputDirectory,DocumentarySubtitleCuePolicy CuePolicy,IReadOnlyList<DocumentarySubtitleCue> Cues);
public sealed record DocumentarySubtitleProviderResponse(string? OutputPath,DocumentaryMediaAssetFormat? Format,int CueCount,string? ProviderRequestId=null,DocumentaryProductionFailure? Failure=null);
public interface IDocumentarySubtitleProviderBinding { string ProviderId{get;} Task<DocumentarySubtitleProviderResponse> GenerateAsync(DocumentarySubtitleProviderRequest request,CancellationToken cancellationToken); }

// This binding deliberately serializes the certified, already-segmented O2.18 cues. It never owns timing,
// tokenization, alignment, narration synthesis, finalization, checksums, or registration.
public sealed class ExistingDocumentarySubtitleProviderBinding : IDocumentarySubtitleProviderBinding
{
 public string ProviderId=>DocumentarySubtitleProviderIds.ExistingSubtitlePipeline;
 public async Task<DocumentarySubtitleProviderResponse> GenerateAsync(DocumentarySubtitleProviderRequest r,CancellationToken token)
 {
  token.ThrowIfCancellationRequested();
  if(r.Language is not(DocumentaryMediaLanguage.English or DocumentaryMediaLanguage.Hindi)||r.RequestedSubtitleFormat is not(DocumentaryMediaAssetFormat.Srt or DocumentaryMediaAssetFormat.Vtt)||r.Cues.Count==0||!Path.IsPathFullyQualified(r.OutputDirectory))return Fail("The translated subtitle request is unsupported.");
  Directory.CreateDirectory(r.OutputDirectory);var ext=r.RequestedSubtitleFormat==DocumentaryMediaAssetFormat.Srt?"srt":"vtt";var path=Path.Combine(r.OutputDirectory,$"provider-subtitles.{ext}");
  var b=new StringBuilder();if(ext=="vtt")b.Append("WEBVTT\n\n");
  for(var i=0;i<r.Cues.Count;i++){var c=r.Cues[i];b.Append(i+1).Append('\n').Append(Time(c.StartOffsetMilliseconds,ext=="srt"?',':'.')).Append(" --> ").Append(Time(c.EndOffsetMilliseconds,ext=="srt"?',':'.')).Append('\n').Append(c.Line1);if(c.Line2 is not null)b.Append('\n').Append(c.Line2);b.Append("\n\n");}
  await File.WriteAllTextAsync(path,b.ToString(),new UTF8Encoding(false),token);return new(path,r.RequestedSubtitleFormat,r.Cues.Count);
 }
 static string Time(long ms,char separator){var t=TimeSpan.FromMilliseconds(ms);return $"{(int)t.TotalHours:00}:{t.Minutes:00}:{t.Seconds:00}{separator}{t.Milliseconds:000}";}
 static DocumentarySubtitleProviderResponse Fail(string message)=>new(null,null,0,Failure:new(DocumentaryProductionFailureCode.ProviderRejectedRequest,message,ProviderId:DocumentarySubtitleProviderIds.ExistingSubtitlePipeline));
}

public sealed record DocumentarySubtitleInspectionRequest(string Path,DocumentaryMediaAssetFormat ExpectedFormat,long NarrationDurationMilliseconds,string ExpectedText,DocumentarySubtitleCuePolicy CuePolicy,int AlignmentToleranceMilliseconds,bool RequireExactText);
public sealed record DocumentarySubtitleInspectionResult(bool Succeeded,DocumentaryMediaAssetFormat? Format,int CueCount,long FirstStartMilliseconds,long LastEndMilliseconds,string ReconstructedText,DocumentaryProductionFailure? Failure);
public interface IDocumentarySubtitleInspector { Task<DocumentarySubtitleInspectionResult> InspectAsync(DocumentarySubtitleInspectionRequest request,CancellationToken cancellationToken); }
public sealed partial class DocumentarySubtitleInspector : IDocumentarySubtitleInspector
{
 public async Task<DocumentarySubtitleInspectionResult> InspectAsync(DocumentarySubtitleInspectionRequest r,CancellationToken token)
 {
  token.ThrowIfCancellationRequested();if(!File.Exists(r.Path))return Fail(DocumentaryProductionFailureCode.OutputArtifactMissing,"Subtitle output is missing.");byte[] bytes=await File.ReadAllBytesAsync(r.Path,token);if(bytes.Length==0)return Fail(DocumentaryProductionFailureCode.OutputArtifactEmpty,"Subtitle output is empty.");string text;try{text=new UTF8Encoding(false,true).GetString(bytes);}catch(DecoderFallbackException){return Fail(DocumentaryProductionFailureCode.OutputFormatInvalid,"Subtitle output is not valid UTF-8.");}
  var vtt=text.StartsWith("WEBVTT",StringComparison.Ordinal);var format=vtt?DocumentaryMediaAssetFormat.Vtt:DocumentaryMediaAssetFormat.Srt;if(format!=r.ExpectedFormat)return Fail(DocumentaryProductionFailureCode.OutputFormatInvalid,"Subtitle format does not match the request.");var body=vtt?text[(text.IndexOf('\n')+1)..]:text;var blocks=BlockSplit().Split(body.Trim()).Where(x=>!string.IsNullOrWhiteSpace(x)).ToArray();var reconstructed=new List<string>();long first=0,last=0,previous=0;
  for(var i=0;i<blocks.Length;i++){var lines=blocks[i].Replace("\r","").Split('\n');if(lines.Length<3||!int.TryParse(lines[0],out var index)||index!=i+1)return Fail(DocumentaryProductionFailureCode.OutputFormatInvalid,"Cue numbering is invalid.");var match=Timestamp().Match(lines[1]);if(!match.Success||!TryMs(match.Groups[1].Value,out var start)||!TryMs(match.Groups[2].Value,out var end))return Fail(DocumentaryProductionFailureCode.OutputFormatInvalid,"Cue timestamp syntax is invalid.");if(start<0||end<=start||(!r.CuePolicy.AllowOverlap&&i>0&&start<previous)||end>r.NarrationDurationMilliseconds+r.AlignmentToleranceMilliseconds)return Fail(DocumentaryProductionFailureCode.SourceArtifactInvalid,"Cue timing is invalid.");var cueLines=lines.Skip(2).ToArray();if(cueLines.Length>r.CuePolicy.MaximumLinesPerCue||cueLines.Any(x=>string.IsNullOrWhiteSpace(x)||x.Length>r.CuePolicy.MaximumCharactersPerLine))return Fail(DocumentaryProductionFailureCode.SourceArtifactInvalid,"Cue text violates the approved line policy.");if(i==0)first=start;last=end;previous=end;reconstructed.Add(string.Join(' ',cueLines));}
  var joined=Normalize(string.Join(' ',reconstructed));if(blocks.Length==0)return Fail(DocumentaryProductionFailureCode.OutputFormatInvalid,"Subtitle output contains no cues.");if(r.RequireExactText&&joined!=Normalize(r.ExpectedText))return Fail(DocumentaryProductionFailureCode.SourceArtifactInvalid,"Reconstructed subtitle text differs from narration text.");if(Math.Abs(r.NarrationDurationMilliseconds-last)>r.AlignmentToleranceMilliseconds)return Fail(DocumentaryProductionFailureCode.SourceArtifactInvalid,"Final cue is not aligned with narration duration.");return new(true,format,blocks.Length,first,last,joined,null);
 }
 static bool TryMs(string value,out long ms){ms=0;var m=SingleTimestamp().Match(value);if(!m.Success)return false;return long.TryParse(m.Groups[1].Value,out var h)&&int.TryParse(m.Groups[2].Value,out var n)&&int.TryParse(m.Groups[3].Value,out var s)&&int.TryParse(m.Groups[4].Value,out var z)&&(ms=((h*60+n)*60+s)*1000+z)>=0;}
 public static string Normalize(string text)=>Whitespace().Replace(text.Normalize(NormalizationForm.FormC).Trim()," ");
 static DocumentarySubtitleInspectionResult Fail(DocumentaryProductionFailureCode c,string m)=>new(false,null,0,0,0,"",new(c,m));
 [GeneratedRegex("(?:\\r?\\n){2,}")]private static partial Regex BlockSplit();[GeneratedRegex("^(.+?) --> (.+?)$")]private static partial Regex Timestamp();[GeneratedRegex("^(\\d{2,}):(\\d{2}):(\\d{2})[,.](\\d{3})$")]private static partial Regex SingleTimestamp();[GeneratedRegex("\\s+")]private static partial Regex Whitespace();
}

public sealed record DocumentaryProductionSubtitleAdapterResult
{
 private DocumentaryProductionSubtitleAdapterResult(bool ok,DocumentaryPhysicalArtifactDescriptor? artifact,DocumentaryProductionFailure? failure,DocumentaryMediaLanguage language,DocumentaryMediaAssetFormat format,int cues,long start,long end,string? diagnostics){Succeeded=ok;Artifact=artifact;Failure=failure;RequestedProviderId=ActualProviderId=DocumentarySubtitleProviderIds.ExistingSubtitlePipeline;Language=language;SubtitleFormat=format;CueCount=cues;MeasuredStartMilliseconds=start;MeasuredEndMilliseconds=end;ProviderDiagnosticsReference=diagnostics;}
 public bool Succeeded{get;}public DocumentaryPhysicalArtifactDescriptor? Artifact{get;}public DocumentaryProductionFailure? Failure{get;}public string RequestedProviderId{get;}public string ActualProviderId{get;}public DocumentaryMediaLanguage Language{get;}public DocumentaryMediaAssetFormat SubtitleFormat{get;}public int CueCount{get;}public long MeasuredStartMilliseconds{get;}public long MeasuredEndMilliseconds{get;}public string? ProviderDiagnosticsReference{get;}
 public static DocumentaryProductionSubtitleAdapterResult Success(DocumentaryPhysicalArtifactDescriptor d,DocumentaryMediaLanguage l,DocumentaryMediaAssetFormat f,int c,long s,long e,string? diag)=>new(true,d,null,l,f,c,s,e,diag);public static DocumentaryProductionSubtitleAdapterResult Failed(DocumentaryProductionFailure x,DocumentaryMediaLanguage l,DocumentaryMediaAssetFormat f)=>new(false,null,x,l,f,0,0,0,null);
}
public interface IDocumentaryProductionSubtitleAdapter { Task<DocumentaryProductionSubtitleAdapterResult> GenerateAsync(DocumentarySubtitleGenerationRequest request,DocumentaryProductionExecutionContext executionContext,DocumentaryProductionAttemptContext attemptContext,DocumentaryProductionWorkspace workspace,CancellationToken cancellationToken); }
public sealed class ExistingDocumentarySubtitleAdapter(IOptions<DocumentarySubtitleAdapterOptions> options,IEnumerable<IDocumentarySubtitleProviderBinding> bindings,IDocumentarySubtitleInspector inspector,IDocumentaryProductionWorkspaceManager workspaces,IDocumentaryPhysicalArtifactInspector artifacts,IDocumentaryPhysicalArtifactDescriptorValidator validator,IDocumentaryPhysicalArtifactRegistry registry,IDocumentaryProductionDiagnosticsWriter diagnostics,IDocumentaryProductionFailureNormalizer failures):IDocumentaryProductionSubtitleAdapter
{
 public async Task<DocumentaryProductionSubtitleAdapterResult> GenerateAsync(DocumentarySubtitleGenerationRequest r,DocumentaryProductionExecutionContext execution,DocumentaryProductionAttemptContext attempt,DocumentaryProductionWorkspace workspace,CancellationToken token)
 {
  token.ThrowIfCancellationRequested();if(r.CorrelationId!=r.AssetPlan.CorrelationId||r.CorrelationId!=execution.CorrelationId||r.CorrelationId!=attempt.CorrelationId||r.AssetPlan.AssetId!=attempt.AssetId)throw new ArgumentException("Subtitle execution identity mismatch.");if(!options.Value.Enabled)return Failed(DocumentaryProductionFailureCode.AdapterUnavailable,"The subtitle adapter is disabled.");var selected=bindings.Where(x=>x.ProviderId==DocumentarySubtitleProviderIds.ExistingSubtitlePipeline).ToArray();if(selected.Length!=1)return Failed(DocumentaryProductionFailureCode.AdapterUnavailable,"The subtitle provider binding is unavailable or duplicated.");if(r.AssetFormat is not(DocumentaryMediaAssetFormat.Srt or DocumentaryMediaAssetFormat.Vtt)||r.Language is not(DocumentaryMediaLanguage.English or DocumentaryMediaLanguage.Hindi))return Failed(DocumentaryProductionFailureCode.ProviderRejectedRequest,"The subtitle language or format is unsupported.");var dependency=r.AssetPlan.Dependencies.OrderBy(x=>x.Sequence).FirstOrDefault();if(dependency is null)return Failed(DocumentaryProductionFailureCode.SourceArtifactMissing,"The finalized narration dependency is missing.");var narration=await registry.GetAsync(dependency.SourceAssetId,token);if(narration is null)return Failed(DocumentaryProductionFailureCode.SourceArtifactMissing,"The finalized narration artifact is missing.");if(narration.CorrelationId!=r.CorrelationId||narration.Length<=0||narration.DurationMilliseconds is null or <=0||DocumentaryPathComparison.IsBelow(workspace.AttemptsDirectory,narration.PhysicalPath)||!narration.ContentType.StartsWith("audio/",StringComparison.Ordinal))return Failed(DocumentaryProductionFailureCode.SourceArtifactInvalid,"The narration dependency is not a valid finalized audio artifact.");if(r.MeasuredNarrationDurationMilliseconds<=0)return Failed(DocumentaryProductionFailureCode.DurationMeasurementFailed,"Narration duration is unavailable.");
  var cues=r.SubtitleCues.ToArray();var text=DocumentarySubtitleInspector.Normalize(string.Join(' ',cues.OrderBy(x=>x.Sequence).Select(x=>x.Text)));var narrationIds=cues.Select(x=>x.NarrationId).Distinct(StringComparer.Ordinal).ToArray();var narrationId=narrationIds.Length==1?narrationIds[0]:null;if(string.IsNullOrWhiteSpace(narrationId))return Failed(DocumentaryProductionFailureCode.ProviderRejectedRequest,"Subtitle cues do not identify one narration block.");var policy=new DocumentarySubtitleCuePolicy();var dir=workspaces.GetAttemptDirectory(workspace,DocumentaryProductionOperationKind.SubtitleGeneration,r.AssetPlan.AssetId,attempt.AttemptNumber);Directory.CreateDirectory(dir);var translated=new DocumentarySubtitleProviderRequest(r.AssetPlan.AssetId,r.AssetPlan.SourceInstructionId,r.SceneId,r.VariantType.ToString(),r.CorrelationId,r.Language,narrationId,text,narration.PhysicalPath,r.MeasuredNarrationDurationMilliseconds,r.AssetFormat,attempt.AttemptNumber,dir,policy,cues);var watch=Stopwatch.StartNew();DocumentarySubtitleProviderResponse response;try{response=await selected[0].GenerateAsync(translated,token);}catch(OperationCanceledException)when(token.IsCancellationRequested){throw;}catch(Exception ex){return DocumentaryProductionSubtitleAdapterResult.Failed(failures.Normalize(ex,DocumentaryProductionOperationKind.SubtitleGeneration,false),r.Language,r.AssetFormat);}if(response.Failure is not null)return DocumentaryProductionSubtitleAdapterResult.Failed(response.Failure,r.Language,r.AssetFormat);if(string.IsNullOrWhiteSpace(response.OutputPath)||!DocumentaryPathComparison.IsBelow(dir,response.OutputPath))return Failed(DocumentaryProductionFailureCode.ProviderInvalidResponse,"Provider output is not owned by the attempt workspace.");var inspection=await inspector.InspectAsync(new(response.OutputPath,r.AssetFormat,r.MeasuredNarrationDurationMilliseconds,text,policy,options.Value.AlignmentToleranceMilliseconds,options.Value.RequireExactTextReconstruction),token);if(!inspection.Succeeded)return DocumentaryProductionSubtitleAdapterResult.Failed(inspection.Failure!,r.Language,r.AssetFormat);
  var ext=r.AssetFormat==DocumentaryMediaAssetFormat.Srt?"srt":"vtt";var final=workspaces.GetFinalArtifactPath(workspace,r.VariantType.ToString(),int.TryParse(r.SceneId,out var scene)?scene:null,DocumentaryPhysicalArtifactKind.SubtitleDocument,r.AssetPlan.AssetId,ext);await workspaces.FinalizeArtifactAsync(workspace,response.OutputPath,final,true,token);var descriptor=await artifacts.InspectAsync(new(r.AssetPlan.AssetId,final,ext=="srt"?"application/x-subrip":"text/vtt",selected[0].ProviderId,attempt.AttemptNumber,r.CorrelationId),token);descriptor=descriptor with{DurationMilliseconds=inspection.LastEndMilliseconds};if(validator.Validate(descriptor).Count>0)return Failed(DocumentaryProductionFailureCode.OutputFormatInvalid,"The finalized subtitle descriptor is invalid.");await registry.RegisterAsync(descriptor,DocumentaryPhysicalArtifactKind.SubtitleDocument,token);watch.Stop();var diag=$"subtitle-{Safe(r.AssetPlan.AssetId)}-{attempt.AttemptNumber}.json";await diagnostics.WriteAsync(workspace.DiagnosticsDirectory,diag,new{execution.ExecutionId,r.CorrelationId,r.AssetPlan.AssetId,r.AssetPlan.SourceInstructionId,r.SceneId,VariantId=r.VariantType.ToString(),Language=r.Language.ToString(),ProviderId=selected[0].ProviderId,Attempt=attempt.AttemptNumber,NarrationAssetId=narration.AssetId,NarrationContentIdentity=narration.ContentIdentity,NarrationDurationMilliseconds=r.MeasuredNarrationDurationMilliseconds,RequestedFormat=r.AssetFormat.ToString(),ActualFormat=inspection.Format.ToString(),inspection.CueCount,inspection.FirstStartMilliseconds,inspection.LastEndMilliseconds,policy.MaximumCharactersPerLine,policy.MaximumLinesPerCue,TextHash=Hash(text),ReconstructedTextHash=Hash(inspection.ReconstructedText),descriptor.Length,descriptor.Checksum,descriptor.ContentIdentity,watch.ElapsedMilliseconds,Outcome="Succeeded",response.ProviderRequestId},token);return DocumentaryProductionSubtitleAdapterResult.Success(descriptor,r.Language,r.AssetFormat,inspection.CueCount,inspection.FirstStartMilliseconds,inspection.LastEndMilliseconds,diag);
  DocumentaryProductionSubtitleAdapterResult Failed(DocumentaryProductionFailureCode c,string m)=>DocumentaryProductionSubtitleAdapterResult.Failed(new(c,m,ProviderId:DocumentarySubtitleProviderIds.ExistingSubtitlePipeline),r.Language,r.AssetFormat);
 }
 static string Safe(string v)=>new(v.Select(c=>char.IsAsciiLetterOrDigit(c)||c is '-' or '_'?c:'_').ToArray());static string Hash(string v)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(v))).ToLowerInvariant();
}
public interface IDocumentarySubtitleGenerationResultMapper { DocumentarySubtitleGenerationResult Map(DocumentarySubtitleGenerationRequest request,DocumentaryProductionSubtitleAdapterResult result); }
public sealed class DocumentarySubtitleGenerationResultMapper:IDocumentarySubtitleGenerationResultMapper { public DocumentarySubtitleGenerationResult Map(DocumentarySubtitleGenerationRequest r,DocumentaryProductionSubtitleAdapterResult x){var d=x.Artifact;var status=x.Succeeded?DocumentaryMediaAssetStatus.Generated:DocumentaryMediaAssetStatus.Failed;var asset=new DocumentaryMediaAssetResult(r.AssetPlan.AssetId,r.AssetPlan.AssetType,r.AssetFormat,status,x.ActualProviderId,d?.ContentIdentity,d?.Length??0,d?.DurationMilliseconds??0,0,0,0,0,0,d?.Checksum,x.Failure?.Code.ToString(),x.Failure?.Message,d?.AttemptCount??0,r.CorrelationId);return new(status,asset,x.CueCount,x.Failure?.Code.ToString(),x.Failure?.Message);} }
