using System.Security.Cryptography;
using System.Text.Json;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;

namespace Astronomy.MediaFactory.Infrastructure.DocumentaryBlueprint;

public sealed class Phase4DocumentaryBlueprintPublicationService(IPhase4ArtifactSerializer serializer,IPhase4FileSystem fileSystem,
    IPhase4ExecutionLock executionLock,IPhase4RecoveryService recovery,IPhase4PublishedAuthorityValidator validator,
    IPhase4ManifestUpdater manifestUpdater,IPhase4CommittedStateValidator committedValidator,IPhase4PublicationFaultInjector faultInjector):IPhase4DocumentaryBlueprintPublicationService,IPhase4PublicationTransactionCoordinator
{
    private static readonly string[] Inventory=["documentary-blueprint.json","documentary-blueprint.long.json","documentary-blueprint.short.json","knowledge-selection.json","long-scene-index.json","short-scene-index.json","blueprint-build-report.json"];

    public async Task<Phase4DocumentaryBlueprintPublicationResult> PublishAsync(Phase4DocumentaryBlueprintPublicationRequest request,CancellationToken token=default)
    {
        ArgumentNullException.ThrowIfNull(request);var tx=Guid.NewGuid().ToString("N");var paths=Paths(request,tx);var errors=Preflight(request);
        if(errors.Count>0)return Result(false,false,false,false,false,false,errors,[],request,tx,paths,[]);
        try
        {
            bool recovered;
            try
            {
                recovered=request.PublicationPolicy.RemoveStaleTransactions&&
                    await recovery.RecoverAsync(request.ExecutionRoot,request.ExecutionId,
                        request.PublicationPolicy.StaleTransactionAge??TimeSpan.FromHours(1),token);
            }
            catch(Exception ex)
            {
                return Result(false,false,false,false,false,false,
                    [new(Phase4PublicationReasonCodes.RecoveryFailed,ex.Message)],[],request,tx,paths,[]);
            }

            await using var held=await executionLock.AcquireAsync(request.ExecutionRoot,request.ExecutionId,token);
            if(!VerifyUpstream(request,out var changed))return Result(false,false,false,false,false,recovered,[new(Phase4PublicationReasonCodes.UpstreamChanged,"Frozen upstream checksum changed.",changed)],[],request,tx,paths,[]);
            var aggregate=request.ProjectionResult.Aggregate!;
            if(await IsAlreadyPublished(paths,aggregate,token))return Result(true,true,false,true,false,recovered,[],[new("P4PUB_ALREADY_PUBLISHED","The identical Phase 4 authority is already valid.")],request,tx,paths,ReadEntries(paths.Manifest),aggregate);
            if(Directory.Exists(paths.Phase)&&!request.PublicationPolicy.ReplaceExisting)return Result(false,false,false,false,false,recovered,[new(Phase4PublicationReasonCodes.AuthorityCommitFailed,"Phase 4 already exists and replacement is disabled.")],[],request,tx,paths,[]);
            try{Directory.CreateDirectory(paths.TempPhase);WriteTransaction(paths.TempRoot,request.ExecutionId,tx,aggregate.DeterministicChecksum,"Staging");faultInjector.Checkpoint(Phase4PublicationCheckpoint.TempDirectoryCreated);}catch(Exception ex){return Result(false,false,false,false,false,recovered,[new(Phase4PublicationReasonCodes.TemporaryDirectoryFailed,ex.Message)],[],request,tx,paths,[]);}
            Dictionary<string,object> artifacts;try{artifacts=BuildArtifacts(request);var first=true;foreach(var item in artifacts){await fileSystem.WriteAsync(Path.Combine(paths.TempPhase,item.Key),serializer.Serialize(item.Value),token);if(first){faultInjector.Checkpoint(Phase4PublicationCheckpoint.FirstArtifactWritten);first=false;}}faultInjector.Checkpoint(Phase4PublicationCheckpoint.AllArtifactsWritten);}catch(Exception ex){SafeDelete(paths.TempRoot);return Result(false,false,false,false,false,recovered,[new(Phase4PublicationReasonCodes.SerializationFailed,ex.Message)],[],request,tx,paths,[]);}
            var stagedErrors=await validator.ValidateAsync(paths.TempPhase,aggregate,token);
            if(stagedErrors.Count>0){Directory.Delete(paths.TempRoot,true);return Result(false,false,false,false,false,recovered,stagedErrors,[],request,tx,paths,[]);}
            try{faultInjector.Checkpoint(Phase4PublicationCheckpoint.TemporaryValidationPassed);}catch(Exception ex){SafeDelete(paths.TempRoot);return Result(false,false,false,false,false,recovered,[new(Phase4PublicationReasonCodes.TemporaryValidationFailed,ex.Message)],[],request,tx,paths,[]);}
            var entries=CreateEntries(paths.TempPhase,aggregate,artifacts);
            var existingManifest=File.Exists(paths.Manifest)?File.ReadAllBytes(paths.Manifest):request.ExistingManifest is null?null:serializer.Serialize(request.ExistingManifest);
            try{await fileSystem.WriteAsync(paths.TempManifest,manifestUpdater.Merge(existingManifest,entries),token);}catch(Exception ex){SafeDelete(paths.TempRoot);return Result(false,false,false,false,false,recovered,[new(Phase4PublicationReasonCodes.ManifestPrepareFailed,ex.Message)],[],request,tx,paths,entries);}
            var started=DateTimeOffset.UtcNow;
            if(!VerifyUpstream(request,out changed)){Directory.Delete(paths.TempRoot,true);return Result(false,false,false,false,false,recovered,[new(Phase4PublicationReasonCodes.UpstreamChanged,"Frozen upstream changed immediately before commit.",changed)],[],request,tx,paths,[]);}
            var mutated=false;var backupState=new Phase4BackupMutationState(false,false,false,false);
            try
            {
                mutated=true;try{Backup(paths,request.ExecutionId,tx,aggregate.DeterministicChecksum,ref backupState);}catch(Exception ex){throw new Phase4CommitException(Phase4PublicationReasonCodes.BackupFailed,ex.Message);}
                try{Directory.Move(paths.TempPhase,paths.Phase);faultInjector.Checkpoint(Phase4PublicationCheckpoint.PhaseDirectoryCommitted);}catch(Exception ex){throw new Phase4CommitException(Phase4PublicationReasonCodes.AuthorityCommitFailed,ex.Message);}
                try{Directory.CreateDirectory(Path.GetDirectoryName(paths.Manifest)!);File.Move(paths.TempManifest,paths.Manifest,true);faultInjector.Checkpoint(Phase4PublicationCheckpoint.ManifestCommitted);}catch(Exception ex){throw new Phase4CommitException(Phase4PublicationReasonCodes.ManifestCommitFailed,ex.Message);}
                var physicalErrors=await committedValidator.ValidateAuthorityAndManifestAsync(request.ExecutionRoot,aggregate,CancellationToken.None);
                if(physicalErrors.Count>0)throw new Phase4CommitException(Phase4PublicationReasonCodes.PostCommitValidationFailed,string.Join("; ",physicalErrors.Select(x=>x.Message)));
                try{faultInjector.Checkpoint(Phase4PublicationCheckpoint.PostCommitValidated);}catch(Exception ex){throw new Phase4CommitException(Phase4PublicationReasonCodes.PostCommitValidationFailed,ex.Message);}
                var evidence=CreateEvidence(request,physicalErrors.Count==0);
                if(!evidence.IsComplete)throw new Phase4CommitException(Phase4PublicationReasonCodes.PostCommitValidationFailed,"Publication validation evidence is incomplete.");
                try{await fileSystem.WriteAsync(paths.TempValidation,serializer.Serialize(CreateValidation(request,tx,entries,started,evidence)),CancellationToken.None);}catch(Exception ex){throw new Phase4CommitException(Phase4PublicationReasonCodes.SerializationFailed,ex.Message);}
                try{Directory.CreateDirectory(Path.GetDirectoryName(paths.Validation)!);File.Move(paths.TempValidation,paths.Validation,true);faultInjector.Checkpoint(Phase4PublicationCheckpoint.SuccessValidationCommitted);}catch(Exception ex){throw new Phase4CommitException(Phase4PublicationReasonCodes.ValidationCommitFailed,ex.Message);}
                var markerErrors=await committedValidator.ValidateCommitMarkerAsync(request.ExecutionRoot,aggregate,CancellationToken.None);
                if(markerErrors.Count>0)throw new Phase4CommitException(Phase4PublicationReasonCodes.ValidationCommitFailed,string.Join("; ",markerErrors.Select(x=>x.Message)));
                Cleanup(paths);return Result(true,true,true,true,false,recovered,[],[],request,tx,paths,entries,aggregate);
            }
            catch(Exception ex)
            {
                var rollback=mutated&&Rollback(paths,backupState);var code=ex is Phase4CommitException p?p.Code:ex is IOException?Phase4PublicationReasonCodes.BackupFailed:Phase4PublicationReasonCodes.CommitFailed;if(mutated&&!rollback)code=Phase4PublicationReasonCodes.RollbackFailed;
                return Result(false,false,false,false,rollback,recovered,[new(code,ex.Message)],[],request,tx,paths,entries);
            }
        }
        catch(OperationCanceledException){throw;}
        catch(Exception ex){return Result(false,false,false,false,false,false,[new(Phase4PublicationReasonCodes.LockFailed,ex.Message)],[],request,tx,paths,[]);}
    }

    private Dictionary<string,object> BuildArtifacts(Phase4DocumentaryBlueprintPublicationRequest request)
    {
        var a=request.ProjectionResult.Aggregate!;var knowledge=Knowledge(a);var longIndex=Index(a,a.LongVariant);var shortIndex=Index(a,a.ShortVariant);
        var p=request.ProjectionResult;var report=new Phase4BlueprintBuildReport("1.0","documentary-blueprint-build-report.v1","1.0",a.ExecutionId,a.PlanId,a.EventId,a.Language,a.ProfileId,a.ProfileVersion,a.SourceIntentId,a.SourceIntentChecksum,a.AggregateId,a.DeterministicChecksum,a.LongVariant.VariantArtifactId,a.LongVariant.DeterministicChecksum,a.ShortVariant.VariantArtifactId,a.ShortVariant.DeterministicChecksum,p.LongSceneCount,p.ShortSceneCount,p.LongDurationSeconds,p.ShortDurationSeconds,p.QuestionReconciliationPassed,p.ObjectiveReconciliationPassed,p.KnowledgeReconciliationPassed,p.SafetyReconciliationPassed,p.DurationReconciliationPassed,p.TransitionReconciliationPassed,p.VariantIndependencePassed,p.ChecksumValidationPassed,Inventory,false,"Prepared","");report=report with{DeterministicChecksum=serializer.SemanticChecksum(report,x=>x with{DeterministicChecksum=""})};
        return new(){{Inventory[0],a},{Inventory[1],a.LongVariant},{Inventory[2],a.ShortVariant},{Inventory[3],knowledge},{Inventory[4],longIndex},{Inventory[5],shortIndex},{Inventory[6],report}};
    }
    private DocumentaryBlueprintKnowledgeSelectionArtifact Knowledge(DocumentaryBlueprintAggregate a)
    {
        static IEnumerable<Phase4KnowledgeSelectionEntry> Entries(DocumentaryBlueprintVariantArtifact v)=>v.SceneTraceability.SelectMany(t=>t.KnowledgeSelections.Select(k=>new Phase4KnowledgeSelectionEntry(k.KnowledgeSelectionId,k.Variant,k.SceneOpportunityId,t.SceneId,k.PrimaryViewerQuestionId,k.KnowledgeReferenceId,k.SourceArtifact,k.SourcePointer,k.SemanticChecksum,k.PurposeCode,k.SelectionReasonCode,k.IsPrimary,k.EvidenceStatus))).OrderBy(x=>x.KnowledgeSelectionId,StringComparer.Ordinal);
        var l=Entries(a.LongVariant).ToArray();var s=Entries(a.ShortVariant).ToArray();var reuse=l.Concat(s).GroupBy(x=>x.KnowledgeReferenceId,StringComparer.Ordinal).OrderBy(x=>x.Key,StringComparer.Ordinal).Select(g=>new Phase4KnowledgeReuse(g.Key,g.Count(x=>x.Variant.Equals("Long",StringComparison.OrdinalIgnoreCase)),g.Count(x=>x.Variant.Equals("Short",StringComparison.OrdinalIgnoreCase)),g.Count())).ToArray();var all=a.LongVariant.SceneTraceability.Concat(a.ShortVariant.SceneTraceability).ToArray();
        var value=new DocumentaryBlueprintKnowledgeSelectionArtifact("1.0","documentary-blueprint-knowledge-selection.v1",a.ExecutionId,a.PlanId,a.EventId,a.Language,a.ProfileId,a.ProfileVersion,a.AggregateId,a.DeterministicChecksum,l,s,reuse.Select(x=>x.KnowledgeReferenceId).ToArray(),reuse,all.Count(x=>x.QuestionEvidenceStatus==QuestionEvidenceStatus.EditorialOnly),all.Count(x=>x.QuestionEvidenceStatus==QuestionEvidenceStatus.Mixed),"");return value with{DeterministicChecksum=serializer.SemanticChecksum(value,x=>x with{DeterministicChecksum=""})};
    }
    private Phase4SceneIndex Index(DocumentaryBlueprintAggregate a,DocumentaryBlueprintVariantArtifact v)
    {var traces=v.SceneTraceability.ToDictionary(x=>x.SceneId,StringComparer.Ordinal);var rows=v.Blueprint.Scenes.OrderBy(x=>x.SceneNumber).Select(scene=>{var t=traces[scene.SceneId];return new Phase4SceneIndexEntry(scene.SceneId,scene.SceneNumber,t.SourceOpportunityId,t.ProfileSlotId,scene.NarrativeStage.ToString(),scene.SceneRole.ToString(),t.PrimaryViewerQuestionId,t.SupportingViewerQuestionIds,t.LearningObjectiveId,t.QuestionEvidenceStatus,scene.EstimatedDurationSeconds,t.MinimumDurationSeconds,t.MaximumDurationSeconds,scene.Transition.TransitionIntent,t.KnowledgeSelections.Select(x=>x.KnowledgeReferenceId).Distinct().OrderBy(x=>x,StringComparer.Ordinal).ToArray(),t.EditorialConstraints.Select(x=>x.Code).OrderBy(x=>x,StringComparer.Ordinal).ToArray(),t.MustNotClaim,Hash(serializer.Serialize(scene)),t.SourceOpportunityChecksum);}).ToArray();var value=new Phase4SceneIndex("1.0","documentary-blueprint-scene-index.v1",v.Variant,a.AggregateId,a.DeterministicChecksum,rows,"");return value with{DeterministicChecksum=serializer.SemanticChecksum(value,x=>x with{DeterministicChecksum=""})};}

    private List<Phase4ArtifactEntry> CreateEntries(string phase,DocumentaryBlueprintAggregate a,Dictionary<string,object> artifacts)=>Inventory.Select((name,i)=>{var bytes=File.ReadAllBytes(Path.Combine(phase,name));var variant=i==1?"Long":i==2?"Short":null;return new Phase4ArtifactEntry("04-blueprint/"+name,4,"Documentary Blueprint",artifacts[name].GetType().Name,i==0?"CanonicalAuthority":i<3?"AuthoritativeProjection":"Derived",i switch{0=>a.SchemaVersion,1=>a.LongVariant.SchemaVersion,2=>a.ShortVariant.SchemaVersion,_=>"1.0"},i switch{0=>a.DeterministicChecksum,1=>a.LongVariant.DeterministicChecksum,2=>a.ShortVariant.DeterministicChecksum,_=>ReadDeterministicChecksum(bytes)},fileSystem.Sha256(bytes),bytes.LongLength,a.DeterministicChecksum,variant,true,false);}).ToList();
    private static List<Phase4PublicationDiagnostic> Preflight(Phase4DocumentaryBlueprintPublicationRequest r){var e=new List<Phase4PublicationDiagnostic>();if(r.ExpectedPhase1ChecksumSnapshot.Files.Count==0||r.ExpectedPhase2ChecksumSnapshot.Files.Count==0||r.ExpectedPhase3ChecksumSnapshot.Files.Count==0)e.Add(new(Phase4PublicationReasonCodes.UpstreamChanged,"Phase 1-3 frozen snapshots must each be non-empty and complete."));var p=r.ProjectionResult;var a=p.Aggregate;if(!p.Success||a is null||p.LongArtifact is null||p.ShortArtifact is null)e.Add(new(Phase4PublicationReasonCodes.ProjectionInvalid,"A successful complete projection is required."));else{if(!DocumentaryBlueprintProjectionChecksum.HasValidAggregateChecksum(a)||!DocumentaryBlueprintProjectionChecksum.HasValidVariantChecksum(a.LongVariant)||!DocumentaryBlueprintProjectionChecksum.HasValidVariantChecksum(a.ShortVariant)||p.LongArtifact.DeterministicChecksum!=a.LongVariant.DeterministicChecksum||p.ShortArtifact.DeterministicChecksum!=a.ShortVariant.DeterministicChecksum)e.Add(new(Phase4PublicationReasonCodes.ChecksumFailed,"Aggregate or variant checksum is invalid."));if(a.ExecutionId!=r.ExecutionId||a.PlanId!=r.PlanId||a.EventId!=r.EventId)e.Add(new(Phase4PublicationReasonCodes.IdentityMismatch,"Publication identity differs from the aggregate."));if(a.Language!=r.Language)e.Add(new(Phase4PublicationReasonCodes.LanguageMismatch,"Publication language differs from the aggregate."));if(a.LongVariant.ProfileId!=a.ProfileId||a.ShortVariant.ProfileId!=a.ProfileId||a.LongVariant.ProfileVersion!=a.ProfileVersion||a.ShortVariant.ProfileVersion!=a.ProfileVersion)e.Add(new(Phase4PublicationReasonCodes.ProfileMismatch,"Variant profile differs from the aggregate."));if(r.CompatibilityProjectionRequired)e.Add(new(Phase4PublicationReasonCodes.CompatibilityFailed,"No current downstream consumer requires the legacy story graph; compatibility publication is not supported."));}return e;}
    private static bool VerifyUpstream(Phase4DocumentaryBlueprintPublicationRequest r,out string? changed){foreach(var snapshot in new[]{r.ExpectedPhase1ChecksumSnapshot,r.ExpectedPhase2ChecksumSnapshot,r.ExpectedPhase3ChecksumSnapshot})foreach(var pair in snapshot.Files){var path=Path.IsPathRooted(pair.Key)?pair.Key:Path.Combine(r.ExecutionRoot,pair.Key.Replace('/',Path.DirectorySeparatorChar));if(!File.Exists(path)||Hash(File.ReadAllBytes(path))!=pair.Value){changed=pair.Key;return false;}}changed=null;return true;}
    private async Task<bool> IsAlreadyPublished(PublicationPaths p,DocumentaryBlueprintAggregate a,CancellationToken token){if(!File.Exists(p.Canonical)||!File.Exists(p.Validation)||!File.Exists(p.Manifest))return false;try{return serializer.Deserialize<DocumentaryBlueprintAggregate>(File.ReadAllBytes(p.Canonical)).DeterministicChecksum==a.DeterministicChecksum&&(await committedValidator.ValidateAsync(Path.GetDirectoryName(p.Manifest)!,a,token)).Count==0;}catch{return false;}}
    private static string ReadDeterministicChecksum(byte[] bytes){using var doc=JsonDocument.Parse(bytes);return doc.RootElement.TryGetProperty("deterministicChecksum",out var x)?x.GetString()??"":"";}
    private IReadOnlyList<Phase4ArtifactEntry> ReadEntries(string path){try{using var d=JsonDocument.Parse(File.ReadAllBytes(path));return d.RootElement.GetProperty("phase4Artifacts").Deserialize<Phase4ArtifactEntry[]>(new JsonSerializerOptions(JsonSerializerDefaults.Web))??[];}catch{return [];}}
    private static Phase4PublicationValidationEvidence CreateEvidence(Phase4DocumentaryBlueprintPublicationRequest r,bool authorityAndManifestPassed){var p=r.ProjectionResult;var checksums=p.ChecksumValidationPassed&&p.Aggregate is not null&&DocumentaryBlueprintProjectionChecksum.HasValidAggregateChecksum(p.Aggregate);return new(p.Success,checksums,authorityAndManifestPassed,p.LongArtifact is not null&&p.ShortArtifact is not null,p.KnowledgeReconciliationPassed,p.QuestionReconciliationPassed&&p.ObjectiveReconciliationPassed,p.SafetyReconciliationPassed&&p.DurationReconciliationPassed&&p.TransitionReconciliationPassed&&p.VariantIndependencePassed,VerifyUpstream(r,out _));}
    private Phase4ValidationRecord CreateValidation(Phase4DocumentaryBlueprintPublicationRequest r,string tx,IReadOnlyList<Phase4ArtifactEntry> entries,DateTimeOffset started,Phase4PublicationValidationEvidence e){var a=r.ProjectionResult.Aggregate!;var p=r.ProjectionResult;var value=new Phase4ValidationRecord("1.0","phase-04-validation.v1",4,"Documentary Blueprint",r.ExecutionId,r.PlanId,r.EventId,r.Language,a.ProfileId,a.ProfileVersion,tx,started,DateTimeOffset.UtcNow,"Valid","Valid",e.IsComplete,a.AggregateId,a.DeterministicChecksum,a.LongVariant.DeterministicChecksum,a.ShortVariant.DeterministicChecksum,e.SemanticValidationPassed,e.ChecksumValidationPassed,e.ManifestValidationPassed,e.ProjectionValidationPassed,e.KnowledgeSelectionValidationPassed,e.SceneIndexValidationPassed,e.BuildReportValidationPassed,e.FrozenUpstreamValidationPassed,p.LongSceneCount,p.ShortSceneCount,p.LongDurationSeconds,p.ShortDurationSeconds,entries.Count,3,4,[],[],"");return value with{DeterministicChecksum=serializer.SemanticChecksum(value,x=>x with{DeterministicChecksum=""})};}
    private void WriteTransaction(string root,string execution,string tx,string aggregate,string state){Directory.CreateDirectory(root);var value=new Phase4TransactionRecord("1.0",execution,tx,aggregate,DateTimeOffset.UtcNow,state,"");value=value with{DeterministicChecksum=serializer.SemanticChecksum(value,x=>x with{DeterministicChecksum=""})};File.WriteAllBytes(Path.Combine(root,"transaction.json"),serializer.Serialize(value));}
    private static void SafeDelete(string path){try{if(Directory.Exists(path))Directory.Delete(path,true);}catch{}}

    private void Backup(PublicationPaths p,string execution,string tx,string aggregate,ref Phase4BackupMutationState state){if(Directory.Exists(p.BackupRoot))Directory.Delete(p.BackupRoot,true);Directory.CreateDirectory(p.BackupRoot);WriteTransaction(p.BackupRoot,execution,tx,aggregate,"BackingUp");state=new Phase4BackupMutationState(false,false,false,false);if(Directory.Exists(p.Phase)){Directory.Move(p.Phase,p.BackupPhase);state=state with{PhaseMoved=true};faultInjector.Checkpoint(Phase4PublicationCheckpoint.BackupPhaseMoved);}if(File.Exists(p.Manifest)){File.Copy(p.Manifest,p.BackupManifest,true);state=state with{ManifestCopied=true};faultInjector.Checkpoint(Phase4PublicationCheckpoint.BackupManifestCreated);}if(File.Exists(p.Validation)){File.Copy(p.Validation,p.BackupValidation,true);state=state with{ValidationCopied=true};faultInjector.Checkpoint(Phase4PublicationCheckpoint.BackupValidationCreated);}}

    private static bool Rollback(PublicationPaths p,Phase4BackupMutationState state){try{if(Directory.Exists(p.Phase))Directory.Delete(p.Phase,true);if(state.PhaseMoved&&Directory.Exists(p.BackupPhase))Directory.Move(p.BackupPhase,p.Phase);Restore(state.ManifestCopied,p.BackupManifest,p.Manifest);Restore(state.ValidationCopied,p.BackupValidation,p.Validation);if(Directory.Exists(p.TempRoot))Directory.Delete(p.TempRoot,true);if(Directory.Exists(p.BackupRoot))Directory.Delete(p.BackupRoot,true);return true;}catch{return false;}static void Restore(bool mutated,string backup,string target){if(mutated&&File.Exists(backup)){Directory.CreateDirectory(Path.GetDirectoryName(target)!);File.Copy(backup,target,true);}else if(!mutated&&File.Exists(target))File.Delete(target);}}
    private static void Cleanup(PublicationPaths p){if(Directory.Exists(p.TempRoot))Directory.Delete(p.TempRoot,true);if(Directory.Exists(p.BackupRoot))Directory.Delete(p.BackupRoot,true);}
    private static string Hash(byte[] bytes)=>Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
    private static Phase4DocumentaryBlueprintPublicationResult Result(bool success,bool committed,bool manifest,bool validation,bool rollback,bool recovery,IReadOnlyList<Phase4PublicationDiagnostic> errors,IReadOnlyList<Phase4PublicationDiagnostic> warnings,Phase4DocumentaryBlueprintPublicationRequest r,string tx,PublicationPaths p,IReadOnlyList<Phase4ArtifactEntry> entries,DocumentaryBlueprintAggregate? a=null)=>new(success,committed,tx,r.ExecutionId,r.PlanId,r.EventId,p.Phase,p.Canonical,p.Long,p.Short,p.Knowledge,p.LongIndex,p.ShortIndex,p.Report,p.Validation,p.Manifest,null,a?.AggregateId??r.ProjectionResult.Aggregate?.AggregateId,a?.DeterministicChecksum??r.ProjectionResult.Aggregate?.DeterministicChecksum,entries,errors,warnings,manifest,validation,false,rollback,recovery,errors.All(x=>x.Code!=Phase4PublicationReasonCodes.UpstreamChanged));
    private static PublicationPaths Paths(Phase4DocumentaryBlueprintPublicationRequest r,string tx)=>new(r.ExecutionRoot,tx);
    private sealed record PublicationPaths
    {public PublicationPaths(string root,string tx){Phase=Path.Combine(root,"04-blueprint");Canonical=Path.Combine(Phase,Inventory[0]);Long=Path.Combine(Phase,Inventory[1]);Short=Path.Combine(Phase,Inventory[2]);Knowledge=Path.Combine(Phase,Inventory[3]);LongIndex=Path.Combine(Phase,Inventory[4]);ShortIndex=Path.Combine(Phase,Inventory[5]);Report=Path.Combine(Phase,Inventory[6]);Manifest=Path.Combine(root,"phase-manifest.json");Validation=Path.Combine(root,"validation","phase-04-validation.json");TempRoot=Path.Combine(root,$".{tx}.phase-04.tmp");TempPhase=Path.Combine(TempRoot,"04-blueprint");TempManifest=Path.Combine(TempRoot,"phase-manifest.json");TempValidation=Path.Combine(TempRoot,"phase-04-validation.json");BackupRoot=Path.Combine(root,$".{tx}.phase-04.backup");BackupPhase=Path.Combine(BackupRoot,"04-blueprint");BackupManifest=Path.Combine(BackupRoot,"phase-manifest.json");BackupValidation=Path.Combine(BackupRoot,"phase-04-validation.json");}public string Phase{get;}public string Canonical{get;}public string Long{get;}public string Short{get;}public string Knowledge{get;}public string LongIndex{get;}public string ShortIndex{get;}public string Report{get;}public string Manifest{get;}public string Validation{get;}public string TempRoot{get;}public string TempPhase{get;}public string TempManifest{get;}public string TempValidation{get;}public string BackupRoot{get;}public string BackupPhase{get;}public string BackupManifest{get;}public string BackupValidation{get;}}
    private sealed class Phase4CommitException(string code,string message):IOException(message){public string Code{get;}=code;}
}
