using System.Security.Cryptography;
using System.Text.Json;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;

namespace Astronomy.MediaFactory.Infrastructure.DocumentaryBlueprint;

public sealed class Phase4DocumentaryBlueprintPublicationService(IPhase4ArtifactSerializer serializer,IPhase4FileSystem fileSystem,
    IPhase4ExecutionLock executionLock,IPhase4RecoveryService recovery,IPhase4PublishedAuthorityValidator validator,
    IPhase4ManifestUpdater manifestUpdater):IPhase4DocumentaryBlueprintPublicationService,IPhase4PublicationTransactionCoordinator
{
    private static readonly string[] Inventory=["documentary-blueprint.json","documentary-blueprint.long.json","documentary-blueprint.short.json","knowledge-selection.json","long-scene-index.json","short-scene-index.json","blueprint-build-report.json"];

    public async Task<Phase4DocumentaryBlueprintPublicationResult> PublishAsync(Phase4DocumentaryBlueprintPublicationRequest request,CancellationToken token=default)
    {
        ArgumentNullException.ThrowIfNull(request);var tx=Guid.NewGuid().ToString("N");var paths=Paths(request,tx);var errors=Preflight(request);
        if(errors.Count>0)return Result(false,false,false,false,false,false,errors,[],request,tx,paths,[]);
        try
        {
            await using var held=await executionLock.AcquireAsync(request.ExecutionRoot,request.ExecutionId,token);
            var recovered=await recovery.RecoverAsync(request.ExecutionRoot,token);
            if(!VerifyUpstream(request,out var changed))return Result(false,false,false,false,false,recovered,[new(Phase4PublicationReasonCodes.UpstreamChanged,"Frozen upstream checksum changed.",changed)],[],request,tx,paths,[]);
            var aggregate=request.ProjectionResult.Aggregate!;
            if(IsAlreadyPublished(paths,aggregate))return Result(true,true,false,true,false,recovered,[],[new("P4PUB_ALREADY_PUBLISHED","The identical Phase 4 authority is already valid.")],request,tx,paths,ReadEntries(paths.Manifest),aggregate);
            Directory.CreateDirectory(paths.TempPhase);
            var artifacts=BuildArtifacts(request);
            foreach(var item in artifacts)await fileSystem.WriteAsync(Path.Combine(paths.TempPhase,item.Key),serializer.Serialize(item.Value),token);
            var stagedErrors=await validator.ValidateAsync(paths.TempPhase,aggregate,token);
            if(stagedErrors.Count>0){Directory.Delete(paths.TempRoot,true);return Result(false,false,false,false,false,recovered,stagedErrors,[],request,tx,paths,[]);}
            var entries=CreateEntries(paths.TempPhase,aggregate,artifacts);
            var existingManifest=File.Exists(paths.Manifest)?File.ReadAllBytes(paths.Manifest):request.ExistingManifest is null?null:serializer.Serialize(request.ExistingManifest);
            await fileSystem.WriteAsync(paths.TempManifest,manifestUpdater.Merge(existingManifest,entries),token);
            var started=DateTimeOffset.UtcNow;
            await fileSystem.WriteAsync(paths.TempValidation,serializer.Serialize(CreateValidation(request,tx,entries,started)),token);
            if(!VerifyUpstream(request,out changed)){Directory.Delete(paths.TempRoot,true);return Result(false,false,false,false,false,recovered,[new(Phase4PublicationReasonCodes.UpstreamChanged,"Frozen upstream changed immediately before commit.",changed)],[],request,tx,paths,[]);}
            var mutated=false;
            try
            {
                Backup(paths);mutated=true;
                Directory.Move(paths.TempPhase,paths.Phase);
                Directory.CreateDirectory(Path.GetDirectoryName(paths.Manifest)!);File.Move(paths.TempManifest,paths.Manifest,true);
                var physicalErrors=await validator.ValidateAsync(paths.Phase,aggregate,CancellationToken.None);
                if(physicalErrors.Count>0)throw new Phase4CommitException(Phase4PublicationReasonCodes.PostCommitValidationFailed,string.Join("; ",physicalErrors.Select(x=>x.Message)));
                Directory.CreateDirectory(Path.GetDirectoryName(paths.Validation)!);File.Move(paths.TempValidation,paths.Validation,true); // final commit marker
                Cleanup(paths);return Result(true,true,true,true,false,recovered,[],[],request,tx,paths,entries,aggregate);
            }
            catch(Exception ex)
            {
                var rollback=mutated&&Rollback(paths);var code=ex is Phase4CommitException p?p.Code:Phase4PublicationReasonCodes.CommitFailed;
                return Result(false,false,false,false,rollback,recovered,[new(code,ex.Message)],[],request,tx,paths,entries);
            }
        }
        catch(OperationCanceledException){throw;}
        catch(Exception ex){return Result(false,false,false,false,false,false,[new(Phase4PublicationReasonCodes.LockFailed,ex.Message)],[],request,tx,paths,[]);}
    }

    private Dictionary<string,object> BuildArtifacts(Phase4DocumentaryBlueprintPublicationRequest request)
    {
        var a=request.ProjectionResult.Aggregate!;var knowledge=Knowledge(a);var longIndex=Index(a,a.LongVariant);var shortIndex=Index(a,a.ShortVariant);
        var p=request.ProjectionResult;var report=new Phase4BlueprintBuildReport("1.0","documentary-blueprint-build-report.v1","1.0",a.ExecutionId,a.PlanId,a.EventId,a.Language,a.ProfileId,a.ProfileVersion,a.SourceIntentId,a.SourceIntentChecksum,a.AggregateId,a.DeterministicChecksum,a.LongVariant.VariantArtifactId,a.LongVariant.DeterministicChecksum,a.ShortVariant.VariantArtifactId,a.ShortVariant.DeterministicChecksum,p.LongSceneCount,p.ShortSceneCount,p.LongDurationSeconds,p.ShortDurationSeconds,p.QuestionReconciliationPassed,p.ObjectiveReconciliationPassed,p.KnowledgeReconciliationPassed,p.SafetyReconciliationPassed,p.DurationReconciliationPassed,p.TransitionReconciliationPassed,p.VariantIndependencePassed,p.ChecksumValidationPassed,Inventory,false,"Prepared","");report=report with{DeterministicChecksum=Hash(serializer.Serialize(report))};
        return new(){{Inventory[0],a},{Inventory[1],a.LongVariant},{Inventory[2],a.ShortVariant},{Inventory[3],knowledge},{Inventory[4],longIndex},{Inventory[5],shortIndex},{Inventory[6],report}};
    }
    private DocumentaryBlueprintKnowledgeSelectionArtifact Knowledge(DocumentaryBlueprintAggregate a)
    {
        static IEnumerable<Phase4KnowledgeSelectionEntry> Entries(DocumentaryBlueprintVariantArtifact v)=>v.SceneTraceability.SelectMany(t=>t.KnowledgeSelections.Select(k=>new Phase4KnowledgeSelectionEntry(k.KnowledgeSelectionId,k.Variant,k.SceneOpportunityId,t.SceneId,k.PrimaryViewerQuestionId,k.KnowledgeReferenceId,k.SourceArtifact,k.SourcePointer,k.SemanticChecksum,k.PurposeCode,k.SelectionReasonCode,k.IsPrimary,k.EvidenceStatus))).OrderBy(x=>x.KnowledgeSelectionId,StringComparer.Ordinal);
        var l=Entries(a.LongVariant).ToArray();var s=Entries(a.ShortVariant).ToArray();var reuse=l.Concat(s).GroupBy(x=>x.KnowledgeReferenceId,StringComparer.Ordinal).OrderBy(x=>x.Key,StringComparer.Ordinal).Select(g=>new Phase4KnowledgeReuse(g.Key,g.Count(x=>x.Variant.Equals("Long",StringComparison.OrdinalIgnoreCase)),g.Count(x=>x.Variant.Equals("Short",StringComparison.OrdinalIgnoreCase)),g.Count())).ToArray();var all=a.LongVariant.SceneTraceability.Concat(a.ShortVariant.SceneTraceability).ToArray();
        var value=new DocumentaryBlueprintKnowledgeSelectionArtifact("1.0","documentary-blueprint-knowledge-selection.v1",a.ExecutionId,a.PlanId,a.EventId,a.Language,a.ProfileId,a.ProfileVersion,a.AggregateId,a.DeterministicChecksum,l,s,reuse.Select(x=>x.KnowledgeReferenceId).ToArray(),reuse,all.Count(x=>x.QuestionEvidenceStatus==QuestionEvidenceStatus.EditorialOnly),all.Count(x=>x.QuestionEvidenceStatus==QuestionEvidenceStatus.Mixed),"");return value with{DeterministicChecksum=Hash(serializer.Serialize(value))};
    }
    private Phase4SceneIndex Index(DocumentaryBlueprintAggregate a,DocumentaryBlueprintVariantArtifact v)
    {var traces=v.SceneTraceability.ToDictionary(x=>x.SceneId,StringComparer.Ordinal);var rows=v.Blueprint.Scenes.OrderBy(x=>x.SceneNumber).Select(scene=>{var t=traces[scene.SceneId];return new Phase4SceneIndexEntry(scene.SceneId,scene.SceneNumber,t.SourceOpportunityId,t.ProfileSlotId,scene.NarrativeStage.ToString(),scene.SceneRole.ToString(),t.PrimaryViewerQuestionId,t.SupportingViewerQuestionIds,t.LearningObjectiveId,t.QuestionEvidenceStatus,scene.EstimatedDurationSeconds,t.MinimumDurationSeconds,t.MaximumDurationSeconds,scene.Transition.TransitionIntent,t.KnowledgeSelections.Select(x=>x.KnowledgeReferenceId).Distinct().OrderBy(x=>x,StringComparer.Ordinal).ToArray(),t.EditorialConstraints.Select(x=>x.Code).OrderBy(x=>x,StringComparer.Ordinal).ToArray(),t.MustNotClaim,Hash(serializer.Serialize(scene)),t.SourceOpportunityChecksum);}).ToArray();var value=new Phase4SceneIndex("1.0","documentary-blueprint-scene-index.v1",v.Variant,a.AggregateId,a.DeterministicChecksum,rows,"");return value with{DeterministicChecksum=Hash(serializer.Serialize(value))};}

    private List<Phase4ArtifactEntry> CreateEntries(string phase,DocumentaryBlueprintAggregate a,Dictionary<string,object> artifacts)=>Inventory.Select((name,i)=>{var bytes=File.ReadAllBytes(Path.Combine(phase,name));var variant=i==1?"Long":i==2?"Short":null;return new Phase4ArtifactEntry("04-blueprint/"+name,4,"Documentary Blueprint",artifacts[name].GetType().Name,i==0?"CanonicalAuthority":i<3?"AuthoritativeProjection":"Derived",i switch{0=>a.SchemaVersion,1=>a.LongVariant.SchemaVersion,2=>a.ShortVariant.SchemaVersion,_=>"1.0"},i switch{0=>a.DeterministicChecksum,1=>a.LongVariant.DeterministicChecksum,2=>a.ShortVariant.DeterministicChecksum,_=>ReadDeterministicChecksum(bytes)},fileSystem.Sha256(bytes),bytes.LongLength,a.DeterministicChecksum,variant,true,false);}).ToList();
    private static List<Phase4PublicationDiagnostic> Preflight(Phase4DocumentaryBlueprintPublicationRequest r){var e=new List<Phase4PublicationDiagnostic>();var p=r.ProjectionResult;var a=p.Aggregate;if(!p.Success||a is null||p.LongArtifact is null||p.ShortArtifact is null)e.Add(new(Phase4PublicationReasonCodes.ProjectionInvalid,"A successful complete projection is required."));else{if(!DocumentaryBlueprintProjectionChecksum.HasValidAggregateChecksum(a)||!DocumentaryBlueprintProjectionChecksum.HasValidVariantChecksum(a.LongVariant)||!DocumentaryBlueprintProjectionChecksum.HasValidVariantChecksum(a.ShortVariant)||p.LongArtifact.DeterministicChecksum!=a.LongVariant.DeterministicChecksum||p.ShortArtifact.DeterministicChecksum!=a.ShortVariant.DeterministicChecksum)e.Add(new(Phase4PublicationReasonCodes.ChecksumFailed,"Aggregate or variant checksum is invalid."));if(a.ExecutionId!=r.ExecutionId||a.PlanId!=r.PlanId||a.EventId!=r.EventId)e.Add(new(Phase4PublicationReasonCodes.IdentityMismatch,"Publication identity differs from the aggregate."));if(a.Language!=r.Language)e.Add(new(Phase4PublicationReasonCodes.LanguageMismatch,"Publication language differs from the aggregate."));if(a.LongVariant.ProfileId!=a.ProfileId||a.ShortVariant.ProfileId!=a.ProfileId||a.LongVariant.ProfileVersion!=a.ProfileVersion||a.ShortVariant.ProfileVersion!=a.ProfileVersion)e.Add(new(Phase4PublicationReasonCodes.ProfileMismatch,"Variant profile differs from the aggregate."));if(r.CompatibilityProjectionRequired)e.Add(new(Phase4PublicationReasonCodes.CompatibilityFailed,"No current downstream consumer requires the legacy story graph; compatibility publication is not supported."));}return e;}
    private static bool VerifyUpstream(Phase4DocumentaryBlueprintPublicationRequest r,out string? changed){foreach(var snapshot in new[]{r.ExpectedPhase1ChecksumSnapshot,r.ExpectedPhase2ChecksumSnapshot,r.ExpectedPhase3ChecksumSnapshot})foreach(var pair in snapshot.Files){var path=Path.IsPathRooted(pair.Key)?pair.Key:Path.Combine(r.ExecutionRoot,pair.Key.Replace('/',Path.DirectorySeparatorChar));if(!File.Exists(path)||Hash(File.ReadAllBytes(path))!=pair.Value){changed=pair.Key;return false;}}changed=null;return true;}
    private bool IsAlreadyPublished(PublicationPaths p,DocumentaryBlueprintAggregate a){if(!File.Exists(p.Canonical)||!File.Exists(p.Validation)||!File.Exists(p.Manifest))return false;try{return serializer.Deserialize<DocumentaryBlueprintAggregate>(File.ReadAllBytes(p.Canonical)).DeterministicChecksum==a.DeterministicChecksum&&validator.ValidateAsync(p.Phase,a,CancellationToken.None).GetAwaiter().GetResult().Count==0;}catch{return false;}}
    private static string ReadDeterministicChecksum(byte[] bytes){using var doc=JsonDocument.Parse(bytes);return doc.RootElement.TryGetProperty("deterministicChecksum",out var x)?x.GetString()??"":"";}
    private IReadOnlyList<Phase4ArtifactEntry> ReadEntries(string path){try{using var d=JsonDocument.Parse(File.ReadAllBytes(path));return d.RootElement.GetProperty("phase4Artifacts").Deserialize<Phase4ArtifactEntry[]>(new JsonSerializerOptions(JsonSerializerDefaults.Web))??[];}catch{return [];}}
    private object CreateValidation(Phase4DocumentaryBlueprintPublicationRequest r,string tx,IReadOnlyList<Phase4ArtifactEntry> entries,DateTimeOffset started){var a=r.ProjectionResult.Aggregate!;var p=r.ProjectionResult;return new{schemaVersion="1.0",contractVersion="phase-04-validation.v1",phaseNo=4,phaseName="Documentary Blueprint",executionId=r.ExecutionId,planId=r.PlanId,eventId=r.EventId,language=r.Language,profileId=a.ProfileId,profileVersion=a.ProfileVersion,transactionId=tx,startedUtc=started,completedUtc=DateTimeOffset.UtcNow,status="Valid",validationStatus="Valid",publicationCommitted=true,aggregateId=a.AggregateId,aggregateChecksum=a.DeterministicChecksum,longVariantChecksum=a.LongVariant.DeterministicChecksum,shortVariantChecksum=a.ShortVariant.DeterministicChecksum,manifestValidationStatus="Valid",compatibilityValidationStatus="NotRequired",semanticValidationPassed=true,checksumValidationPassed=true,manifestValidationPassed=true,compatibilityEquivalencePassed=true,projectionValidationPassed=true,p.QuestionReconciliationPassed,p.ObjectiveReconciliationPassed,p.KnowledgeReconciliationPassed,p.SafetyReconciliationPassed,p.DurationReconciliationPassed,p.TransitionReconciliationPassed,p.VariantIndependencePassed,frozenUpstreamValidationPassed=true,longSceneCount=p.LongSceneCount,shortSceneCount=p.ShortSceneCount,longDurationSeconds=p.LongDurationSeconds,shortDurationSeconds=p.ShortDurationSeconds,artifactCount=entries.Count,authoritativeArtifactCount=3,derivedArtifactCount=4,compatibilityArtifactCount=0,errors=Array.Empty<object>(),warnings=Array.Empty<object>()};}
    private static void Backup(PublicationPaths p){if(Directory.Exists(p.BackupRoot))Directory.Delete(p.BackupRoot,true);Directory.CreateDirectory(p.BackupRoot);if(Directory.Exists(p.Phase))Directory.Move(p.Phase,p.BackupPhase);if(File.Exists(p.Manifest))File.Copy(p.Manifest,p.BackupManifest,true);if(File.Exists(p.Validation))File.Copy(p.Validation,p.BackupValidation,true);}
    private static bool Rollback(PublicationPaths p){try{if(Directory.Exists(p.Phase))Directory.Delete(p.Phase,true);if(Directory.Exists(p.BackupPhase))Directory.Move(p.BackupPhase,p.Phase);Restore(p.BackupManifest,p.Manifest);Restore(p.BackupValidation,p.Validation);if(Directory.Exists(p.TempRoot))Directory.Delete(p.TempRoot,true);if(Directory.Exists(p.BackupRoot))Directory.Delete(p.BackupRoot,true);return true;}catch{return false;}static void Restore(string backup,string target){if(File.Exists(backup)){Directory.CreateDirectory(Path.GetDirectoryName(target)!);File.Copy(backup,target,true);}else if(File.Exists(target))File.Delete(target);}}
    private static void Cleanup(PublicationPaths p){if(Directory.Exists(p.TempRoot))Directory.Delete(p.TempRoot,true);if(Directory.Exists(p.BackupRoot))Directory.Delete(p.BackupRoot,true);}
    private static string Hash(byte[] bytes)=>Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
    private static Phase4DocumentaryBlueprintPublicationResult Result(bool success,bool committed,bool manifest,bool validation,bool rollback,bool recovery,IReadOnlyList<Phase4PublicationDiagnostic> errors,IReadOnlyList<Phase4PublicationDiagnostic> warnings,Phase4DocumentaryBlueprintPublicationRequest r,string tx,PublicationPaths p,IReadOnlyList<Phase4ArtifactEntry> entries,DocumentaryBlueprintAggregate? a=null)=>new(success,committed,tx,r.ExecutionId,r.PlanId,r.EventId,p.Phase,p.Canonical,p.Long,p.Short,p.Knowledge,p.LongIndex,p.ShortIndex,p.Report,p.Validation,p.Manifest,null,a?.AggregateId??r.ProjectionResult.Aggregate?.AggregateId,a?.DeterministicChecksum??r.ProjectionResult.Aggregate?.DeterministicChecksum,entries,errors,warnings,manifest,validation,false,rollback,recovery,errors.All(x=>x.Code!=Phase4PublicationReasonCodes.UpstreamChanged));
    private static PublicationPaths Paths(Phase4DocumentaryBlueprintPublicationRequest r,string tx)=>new(r.ExecutionRoot,tx);
    private sealed record PublicationPaths
    {public PublicationPaths(string root,string tx){Phase=Path.Combine(root,"04-blueprint");Canonical=Path.Combine(Phase,Inventory[0]);Long=Path.Combine(Phase,Inventory[1]);Short=Path.Combine(Phase,Inventory[2]);Knowledge=Path.Combine(Phase,Inventory[3]);LongIndex=Path.Combine(Phase,Inventory[4]);ShortIndex=Path.Combine(Phase,Inventory[5]);Report=Path.Combine(Phase,Inventory[6]);Manifest=Path.Combine(root,"phase-manifest.json");Validation=Path.Combine(root,"validation","phase-04-validation.json");TempRoot=Path.Combine(root,$".{tx}.phase-04.tmp");TempPhase=Path.Combine(TempRoot,"04-blueprint");TempManifest=Path.Combine(TempRoot,"phase-manifest.json");TempValidation=Path.Combine(TempRoot,"phase-04-validation.json");BackupRoot=Path.Combine(root,$".{tx}.phase-04.backup");BackupPhase=Path.Combine(BackupRoot,"04-blueprint");BackupManifest=Path.Combine(BackupRoot,"phase-manifest.json");BackupValidation=Path.Combine(BackupRoot,"phase-04-validation.json");}public string Phase{get;}public string Canonical{get;}public string Long{get;}public string Short{get;}public string Knowledge{get;}public string LongIndex{get;}public string ShortIndex{get;}public string Report{get;}public string Manifest{get;}public string Validation{get;}public string TempRoot{get;}public string TempPhase{get;}public string TempManifest{get;}public string TempValidation{get;}public string BackupRoot{get;}public string BackupPhase{get;}public string BackupManifest{get;}public string BackupValidation{get;}}
    private sealed class Phase4CommitException(string code,string message):IOException(message){public string Code{get;}=code;}
}
