using System.Collections.Immutable;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Catalog;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Contracts;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Families;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Certification;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Contracts;

namespace Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Catalog;

public sealed class SemanticSourcePolicyCatalogV1 : ISemanticSourcePolicyCatalogV1
{
    private readonly ImmutableArray<SemanticSourcePolicyV1> _policies;
    public SemanticSourcePolicyCatalogV1() : this(CreatePolicies()) { }
    public SemanticSourcePolicyCatalogV1(IEnumerable<SemanticSourcePolicyV1> policies) { _policies=policies.ToImmutableArray(); Policies=_policies; }
    public IReadOnlyCollection<SemanticSourcePolicyV1> Policies { get; }
    public bool TryGet(SemanticCapabilityId capabilityId, out SemanticSourcePolicyV1 policy) { policy=_policies.FirstOrDefault(p=>p.SemanticCapabilityId.Equals(capabilityId))!; return policy is not null; }
    public SemanticSourcePolicyV1 GetRequired(SemanticCapabilityId capabilityId)=>TryGet(capabilityId,out var p)?p:throw new KeyNotFoundException($"Source policy '{capabilityId.Value}' was not registered.");
    public SemanticSourcePolicyValidationResult Validate()=>SemanticSourcePolicyValidatorV1.Validate(_policies);
    public bool IsSourceApproved(SemanticCapabilityId capabilityId,string sourceId)=>TryGet(capabilityId,out var p)&&p.ApprovedSources.Any(s=>s.ActiveInV1&&s.SourceId.Equals(sourceId,StringComparison.Ordinal));
    public SemanticSourceApprovalResultV1 EvaluateSource(SemanticCapabilityId capabilityId, SemanticSourceDescriptorV1 d)
    { if(!TryGet(capabilityId,out var p)) return new(capabilityId,d.SourceId,false,d.EvidenceCategory,d.EvidenceStrength,d.CompatibilityOnly,"MissingCapabilityPolicy","No policy exists."); var s=p.ApprovedSources.FirstOrDefault(x=>x.SourceId==d.SourceId); var ok=s is not null && p.AllowedEvidenceCategories.Contains(d.EvidenceCategory) && d.EvidenceStrength>=p.MinimumEvidenceStrength && !d.CompatibilityOnly; return new(capabilityId,d.SourceId,ok,d.EvidenceCategory,d.EvidenceStrength,d.CompatibilityOnly,ok?"Approved":"Rejected",ok?"Source is approved by policy.":"Source does not satisfy policy."); }
    public SemanticSourcePolicyCertificationReportV1 CertifyFamilyProfile(AstronomyFamilyProfileV1 profile)=>new SemanticSourcePolicyCertifierV1(this,new SemanticCapabilityCatalogV1()).Certify(profile);

    private static ApprovedSemanticSourceV1 S(string id, SemanticEvidenceCategoryV1 cat, int pri, bool ev=false, SemanticEvidenceStrengthV1 str=SemanticEvidenceStrengthV1.Strong, bool compat=false)=>new(id,cat,str,pri,ev,true,true,false,true,true,compat,true,$"{id} policy declaration only.");
    private static SemanticSourcePolicyV1 P(string id, SemanticEvidenceCategoryV1[] cats, ApprovedSemanticSourceV1[] src, SemanticEvidenceStrengthV1 min, bool ev, bool domain, bool cultural, bool editorial, SemanticSourceMultiplicityV1 multi, SemanticSourceConflictPolicyV1 conflict, SemanticSourceMissingPolicyV1 opt=SemanticSourceMissingPolicyV1.OmitCapability, bool derived=false, string[]? rules=null)=>new(new SemanticCapabilityId(id),"V1",cats,src,min,ev,domain,cultural,editorial,false,multi,conflict,SemanticSourceMissingPolicyV1.Block,opt,derived,rules??[],[],true,new("Sprint3A","PolicyOnly","V1 source policy is not wired to runtime extraction."));
    private static SemanticSourcePolicyV1[] CreatePolicies()=>
    [
        P(SemanticCapabilityVocabularyV1.EventIdentity,[SemanticEvidenceCategoryV1.VerifiedEventData,SemanticEvidenceCategoryV1.EventIdentityContext],[S(SemanticSourcePolicyVocabularyV1.EventIdentityContext,SemanticEvidenceCategoryV1.EventIdentityContext,1,true),S(SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence,SemanticEvidenceCategoryV1.VerifiedEventData,2,true),S(SemanticSourcePolicyVocabularyV1.ContentPlan,SemanticEvidenceCategoryV1.VerifiedEventData,3,true)],SemanticEvidenceStrengthV1.Strong,true,false,false,false,SemanticSourceMultiplicityV1.RequireAgreement,SemanticSourceConflictPolicyV1.BlockRequired),
        P(SemanticCapabilityVocabularyV1.EventWindow,[SemanticEvidenceCategoryV1.VerifiedEventData],[S(SemanticSourcePolicyVocabularyV1.ObservationMetadata,SemanticEvidenceCategoryV1.VerifiedEventData,1,true),S(SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence,SemanticEvidenceCategoryV1.VerifiedEventData,2,true),S(SemanticSourcePolicyVocabularyV1.DocumentaryContract,SemanticEvidenceCategoryV1.VerifiedEventData,3,true),S(SemanticSourcePolicyVocabularyV1.EditorialContract,SemanticEvidenceCategoryV1.VerifiedEventData,4,true,SemanticEvidenceStrengthV1.Moderate)],SemanticEvidenceStrengthV1.Strong,true,false,false,false,SemanticSourceMultiplicityV1.FirstApprovedByPriority,SemanticSourceConflictPolicyV1.PreferVerifiedEventData,derived:true,rules:["OptionalDescriptiveWindowOnly"]),
        P(SemanticCapabilityVocabularyV1.AstronomicalObjects,[SemanticEvidenceCategoryV1.VerifiedEventData,SemanticEvidenceCategoryV1.VerifiedObjectData],[S(SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence,SemanticEvidenceCategoryV1.VerifiedEventData,1,true),S(SemanticSourcePolicyVocabularyV1.DocumentaryContract,SemanticEvidenceCategoryV1.VerifiedEventData,2,true),S(SemanticSourcePolicyVocabularyV1.EditorialContract,SemanticEvidenceCategoryV1.VerifiedEventData,3,true),S(SemanticSourcePolicyVocabularyV1.VerifiedObjectCatalog,SemanticEvidenceCategoryV1.VerifiedObjectData,4)],SemanticEvidenceStrengthV1.Strong,true,false,false,false,SemanticSourceMultiplicityV1.RequireAgreement,SemanticSourceConflictPolicyV1.BlockRequired,rules:["NoTitleInference"]),
        P(SemanticCapabilityVocabularyV1.SecondaryAstronomicalObjects,[SemanticEvidenceCategoryV1.VerifiedEventData,SemanticEvidenceCategoryV1.VerifiedObjectData],[S(SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence,SemanticEvidenceCategoryV1.VerifiedEventData,1,true),S(SemanticSourcePolicyVocabularyV1.VerifiedObjectCatalog,SemanticEvidenceCategoryV1.VerifiedObjectData,2)],SemanticEvidenceStrengthV1.Strong,true,false,false,false,SemanticSourceMultiplicityV1.CombineStructuredFields,SemanticSourceConflictPolicyV1.OmitOptional,rules:["NoTitleInference"]),
        P(SemanticCapabilityVocabularyV1.AngularSeparation,[SemanticEvidenceCategoryV1.VerifiedEventData],[S(SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence,SemanticEvidenceCategoryV1.VerifiedEventData,1,true),S(SemanticSourcePolicyVocabularyV1.ObservationMetadata,SemanticEvidenceCategoryV1.VerifiedEventData,2,true)],SemanticEvidenceStrengthV1.Strong,true,false,false,false,SemanticSourceMultiplicityV1.RequireAgreement,SemanticSourceConflictPolicyV1.BlockRequired),
        P(SemanticCapabilityVocabularyV1.ObservationDirection,[SemanticEvidenceCategoryV1.VerifiedEventData],[S(SemanticSourcePolicyVocabularyV1.ObservationMetadata,SemanticEvidenceCategoryV1.VerifiedEventData,1,true),S(SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence,SemanticEvidenceCategoryV1.VerifiedEventData,2,true)],SemanticEvidenceStrengthV1.Strong,true,false,false,false,SemanticSourceMultiplicityV1.FirstApprovedByPriority,SemanticSourceConflictPolicyV1.PreferVerifiedEventData),
        P(SemanticCapabilityVocabularyV1.ObservationLocation,[SemanticEvidenceCategoryV1.VerifiedEventData],[S(SemanticSourcePolicyVocabularyV1.ObservationMetadata,SemanticEvidenceCategoryV1.VerifiedEventData,1,true),S(SemanticSourcePolicyVocabularyV1.ContentPlan,SemanticEvidenceCategoryV1.VerifiedEventData,2,true)],SemanticEvidenceStrengthV1.Strong,true,false,false,false,SemanticSourceMultiplicityV1.FirstApprovedByPriority,SemanticSourceConflictPolicyV1.PreferVerifiedEventData),
        P(SemanticCapabilityVocabularyV1.ObservationConditions,[SemanticEvidenceCategoryV1.VerifiedEventData,SemanticEvidenceCategoryV1.DomainScientificKnowledge],[S(SemanticSourcePolicyVocabularyV1.ObservationMetadata,SemanticEvidenceCategoryV1.VerifiedEventData,1,true),S(SemanticSourcePolicyVocabularyV1.AstronomyDomainKnowledgeProvider,SemanticEvidenceCategoryV1.DomainScientificKnowledge,2,false)],SemanticEvidenceStrengthV1.Strong,true,true,false,false,SemanticSourceMultiplicityV1.PreferEventDataThenDomainContext,SemanticSourceConflictPolicyV1.PreferVerifiedEventData,derived:true,rules:["NoCurrentWeatherFabrication"]),
        P(SemanticCapabilityVocabularyV1.ObservationEquipment,[SemanticEvidenceCategoryV1.DomainScientificKnowledge,SemanticEvidenceCategoryV1.VerifiedEventData],[S(SemanticSourcePolicyVocabularyV1.AstronomyDomainKnowledgeProvider,SemanticEvidenceCategoryV1.DomainScientificKnowledge,1),S(SemanticSourcePolicyVocabularyV1.ObservationMetadata,SemanticEvidenceCategoryV1.VerifiedEventData,2,true)],SemanticEvidenceStrengthV1.Strong,false,true,false,false,SemanticSourceMultiplicityV1.PreferEventDataThenDomainContext,SemanticSourceConflictPolicyV1.RecordAndUseHighestStrength),
        P(SemanticCapabilityVocabularyV1.MeteorActivity,[SemanticEvidenceCategoryV1.VerifiedEventData,SemanticEvidenceCategoryV1.DomainScientificKnowledge],[S(SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence,SemanticEvidenceCategoryV1.VerifiedEventData,1,true),S(SemanticSourcePolicyVocabularyV1.ObservationMetadata,SemanticEvidenceCategoryV1.VerifiedEventData,2,true),S(SemanticSourcePolicyVocabularyV1.AstronomyDomainKnowledgeProvider,SemanticEvidenceCategoryV1.DomainScientificKnowledge,3)],SemanticEvidenceStrengthV1.Strong,true,true,false,false,SemanticSourceMultiplicityV1.CombineStructuredFields,SemanticSourceConflictPolicyV1.BlockRequired,rules:["NoZhrFabrication"]),
        P(SemanticCapabilityVocabularyV1.FullMoonObservation,[SemanticEvidenceCategoryV1.VerifiedEventData,SemanticEvidenceCategoryV1.DomainScientificKnowledge],[S(SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence,SemanticEvidenceCategoryV1.VerifiedEventData,1,true),S(SemanticSourcePolicyVocabularyV1.ObservationMetadata,SemanticEvidenceCategoryV1.VerifiedEventData,2,true),S(SemanticSourcePolicyVocabularyV1.AstronomyDomainKnowledgeProvider,SemanticEvidenceCategoryV1.DomainScientificKnowledge,3)],SemanticEvidenceStrengthV1.Strong,true,true,false,false,SemanticSourceMultiplicityV1.CombineStructuredFields,SemanticSourceConflictPolicyV1.BlockRequired,rules:["NoCulturalMoonNaming"]),
        P(SemanticCapabilityVocabularyV1.EclipseCircumstances,[SemanticEvidenceCategoryV1.VerifiedEventData],[S(SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence,SemanticEvidenceCategoryV1.VerifiedEventData,1,true),S(SemanticSourcePolicyVocabularyV1.ObservationMetadata,SemanticEvidenceCategoryV1.VerifiedEventData,2,true)],SemanticEvidenceStrengthV1.Strong,true,false,false,false,SemanticSourceMultiplicityV1.RequireAgreement,SemanticSourceConflictPolicyV1.BlockRequired),
        P(SemanticCapabilityVocabularyV1.OccultationContacts,[SemanticEvidenceCategoryV1.VerifiedEventData],[S(SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence,SemanticEvidenceCategoryV1.VerifiedEventData,1,true),S(SemanticSourcePolicyVocabularyV1.ObservationMetadata,SemanticEvidenceCategoryV1.VerifiedEventData,2,true)],SemanticEvidenceStrengthV1.Strong,true,false,false,false,SemanticSourceMultiplicityV1.RequireAgreement,SemanticSourceConflictPolicyV1.BlockRequired),
        P(SemanticCapabilityVocabularyV1.ObjectKnowledge,[SemanticEvidenceCategoryV1.VerifiedObjectData,SemanticEvidenceCategoryV1.DomainScientificKnowledge],[S(SemanticSourcePolicyVocabularyV1.VerifiedObjectCatalog,SemanticEvidenceCategoryV1.VerifiedObjectData,1),S(SemanticSourcePolicyVocabularyV1.AstronomyObjectKnowledgeProvider,SemanticEvidenceCategoryV1.VerifiedObjectData,2),S(SemanticSourcePolicyVocabularyV1.AstronomyDomainKnowledgeProvider,SemanticEvidenceCategoryV1.DomainScientificKnowledge,3)],SemanticEvidenceStrengthV1.Strong,false,true,false,false,SemanticSourceMultiplicityV1.CombineStructuredFields,SemanticSourceConflictPolicyV1.PreferAuthoritative,rules:["NoTitleInference"]),
        P(SemanticCapabilityVocabularyV1.DomainScientificKnowledge,[SemanticEvidenceCategoryV1.DomainScientificKnowledge],[S(SemanticSourcePolicyVocabularyV1.AstronomyDomainKnowledgeProvider,SemanticEvidenceCategoryV1.DomainScientificKnowledge,1),S(SemanticSourcePolicyVocabularyV1.ScientificKnowledgeCatalog,SemanticEvidenceCategoryV1.DomainScientificKnowledge,2,false,SemanticEvidenceStrengthV1.Authoritative)],SemanticEvidenceStrengthV1.Strong,false,true,false,false,SemanticSourceMultiplicityV1.HighestEvidenceStrength,SemanticSourceConflictPolicyV1.PreferAuthoritative,rules:["NoEventMeasurements"]),
        P(SemanticCapabilityVocabularyV1.CulturalContext,[SemanticEvidenceCategoryV1.CulturalContext],[S(SemanticSourcePolicyVocabularyV1.VerifiedCulturalContext,SemanticEvidenceCategoryV1.CulturalContext,1,false,SemanticEvidenceStrengthV1.Strong),S(SemanticSourcePolicyVocabularyV1.CulturalAstronomyKnowledgeProvider,SemanticEvidenceCategoryV1.CulturalContext,2,false,SemanticEvidenceStrengthV1.Moderate)],SemanticEvidenceStrengthV1.Moderate,false,false,true,false,SemanticSourceMultiplicityV1.CombineStructuredFields,SemanticSourceConflictPolicyV1.OmitOptional),
        P(SemanticCapabilityVocabularyV1.EditorialContext,[SemanticEvidenceCategoryV1.EditorialContext],[S(SemanticSourcePolicyVocabularyV1.EditorialIntent,SemanticEvidenceCategoryV1.EditorialContext,1,false,SemanticEvidenceStrengthV1.Moderate),S(SemanticSourcePolicyVocabularyV1.DocumentaryStructure,SemanticEvidenceCategoryV1.EditorialContext,2,false,SemanticEvidenceStrengthV1.Moderate)],SemanticEvidenceStrengthV1.Moderate,false,false,false,true,SemanticSourceMultiplicityV1.CombineStructuredFields,SemanticSourceConflictPolicyV1.OmitOptional),
        P(SemanticCapabilityVocabularyV1.SafetyGuidance,[SemanticEvidenceCategoryV1.DomainScientificKnowledge,SemanticEvidenceCategoryV1.VerifiedEventData],[S(SemanticSourcePolicyVocabularyV1.AstronomyDomainKnowledgeProvider,SemanticEvidenceCategoryV1.DomainScientificKnowledge,1,false,SemanticEvidenceStrengthV1.Strong),S(SemanticSourcePolicyVocabularyV1.ScientificKnowledgeCatalog,SemanticEvidenceCategoryV1.DomainScientificKnowledge,2,false,SemanticEvidenceStrengthV1.Authoritative),S(SemanticSourcePolicyVocabularyV1.ProductionEventIntelligence,SemanticEvidenceCategoryV1.VerifiedEventData,3,true,SemanticEvidenceStrengthV1.Strong)],SemanticEvidenceStrengthV1.Strong,false,true,false,false,SemanticSourceMultiplicityV1.HighestEvidenceStrength,SemanticSourceConflictPolicyV1.PreferAuthoritative,rules:["SolarSafetyRequired"])
    ];
}
