using System.Text.Json.Nodes;
using Astronomy.MediaFactory.Core.DocumentaryBlueprint;
using Astronomy.MediaFactory.Infrastructure.DocumentaryBlueprint;

namespace Astronomy.MediaFactory.Tests;

public sealed class Phase5PublicationTransactionCoordinatorTests
{
    [Fact] public async Task PublishAsync_InvalidCandidate_DoesNotMutateWorkspace(){using var f=new Phase5PublicationTestFixture();var bad=f.Request with{Candidate=f.Candidate with{Certification=f.Candidate.Certification with{Passed=false}}};var r=await f.Coordinator().PublishAsync(bad);Failed(r,"P5PUB_CANDIDATE_INVALID",false);Assert.Empty(Directory.GetFileSystemEntries(f.Root));}
    [Fact] public async Task PublishAsync_InvokesRecoveryBeforePublication(){using var f=new Phase5PublicationTestFixture();var recovery=new StubPhase5Recovery(new(true,"ok",[],[]));var r=await f.Coordinator(recovery:recovery).PublishAsync(f.Request);Assert.Equal(1,recovery.Calls);Assert.True(r.Succeeded);}
    [Fact] public async Task PublishAsync_ValidCandidate_CommitsAllRequiredArtifacts(){using var f=new Phase5PublicationTestFixture();var r=await f.Coordinator().PublishAsync(f.Request);Committed(r);Assert.Equal(8,Directory.GetFiles(Path.Combine(f.Root,"05-editorial")).Length);}
    [Fact] public async Task PublishAsync_WritesCertificationDiagnostics(){using var f=await Published();Assert.True(File.Exists(f.Editorial("certification-diagnostics.json")));}
    [Fact] public async Task PublishAsync_PreservesExistingManifestProperties(){using var f=new Phase5PublicationTestFixture();await File.WriteAllTextAsync(f.Manifest,"{\"custom\":42}");await f.PublishValidAsync();Assert.Equal(42,JsonNode.Parse(File.ReadAllText(f.Manifest))!["custom"]!.GetValue<int>());}
    [Fact] public async Task PublishAsync_PreservesPhase1ToPhase4ManifestEntries(){using var f=new Phase5PublicationTestFixture();await File.WriteAllTextAsync(f.Manifest,"{\"phase4Artifacts\":[{\"path\":\"04-blueprint/a.json\"}]}");await f.PublishValidAsync();Assert.NotNull(JsonNode.Parse(File.ReadAllText(f.Manifest))!["phase4Artifacts"]);}
    [Fact] public async Task PublishAsync_MergesOnlyPhase5Artifacts(){using var f=await Published();var n=JsonNode.Parse(File.ReadAllText(f.Manifest))!;Assert.Equal(7,n["phase5Artifacts"]!.AsArray().Count);}
    [Fact] public async Task PublishAsync_WritesCommittedValidation(){using var f=await Published();var n=JsonNode.Parse(File.ReadAllText(f.Validation))!;Assert.True(n["publicationCommitted"]!.GetValue<bool>());Assert.Equal("Valid",n["validationStatus"]!.GetValue<string>());}
    [Fact] public async Task PublishAsync_RequiresCommittedReadback(){using var f=new Phase5PublicationTestFixture();var e=StubPhase5Evaluator.Invalid();var r=await f.Coordinator(e,new StubPhase5Recovery(new(true,"ok",[],[]))).PublishAsync(f.Request);Assert.Equal(1,e.Calls);Assert.False(r.CommittedStateValidationPassed);}
    [Fact] public async Task PublishAsync_CommittedReadbackFailure_RollsBackNewPublication()=>await ReadbackRestoresAbsence();
    [Fact] public async Task PublishAsync_ReadbackFailure_RestoresPreviousEditorialAuthority()=>await ReadbackRestoresPrevious("editorial");
    [Fact] public async Task PublishAsync_ReadbackFailure_RestoresPreviousManifest()=>await ReadbackRestoresPrevious("manifest");
    [Fact] public async Task PublishAsync_ReadbackFailure_RestoresPreviousValidation()=>await ReadbackRestoresPrevious("validation");
    [Fact] public async Task PublishAsync_ReadbackFailure_WithNoPreviousState_RestoresAbsence()=>await ReadbackRestoresAbsence();
    [Fact] public async Task PublishAsync_Success_CleansStagingBackupMarkerAndSnapshots(){using var f=await Published();Assert.DoesNotContain(Directory.GetFileSystemEntries(f.Root),x=>Path.GetFileName(x).StartsWith(".phase-05-")||Path.GetFileName(x).StartsWith(".05-editorial-"));}
    [Fact] public async Task PublishAsync_StagedArtifactValidationFailure_DoesNotSwapAuthority(){using var f=new Phase5PublicationTestFixture();Directory.CreateDirectory(Path.Combine(f.Root,"05-editorial"));File.WriteAllText(f.Editorial("old"),"old");var fs=new FaultInjectingPhase5PublicationFileSystem{Fail=x=>x.Contains("ReadAllBytes")&&x.Contains("staging")};var r=await f.Coordinator(fs:fs).PublishAsync(f.Request);Assert.False(r.Succeeded);Assert.True(File.Exists(f.Editorial("old")));}
    [Fact] public async Task PublishAsync_FailureBeforeSwap_CleansUncommittedState()=>await FailureAt("WriteAllText",false);
    [Fact] public async Task PublishAsync_FailureAfterEditorialSwap_PerformsRollback()=>await FailureAt("phase-manifest.json",true);
    [Fact] public async Task PublishAsync_FailureDuringManifestPublication_PerformsRollback()=>await FailureAt("phase-manifest.json",true);
    [Fact] public async Task PublishAsync_FailureDuringValidationPublication_PerformsRollback()=>await FailureAt("phase-05-validation.json",true);
    [Fact] public async Task PublishAsync_RollbackMoveFailure_ReturnsRollbackFailed()=>await RollbackFailure("MoveDirectory");
    [Fact] public async Task PublishAsync_RollbackManifestRestoreFailure_ReturnsRollbackFailed()=>await RollbackFailure("manifest-backup");
    [Fact] public async Task PublishAsync_RollbackValidationRestoreFailure_ReturnsRollbackFailed()=>await RollbackFailure("validation-backup");
    [Fact] public async Task PublishAsync_RollbackFailure_WritesPayloadFreeFailureDiagnostics(){var (f,r)=await RollbackFailureCore("MoveDirectory");using(f){Assert.NotNull(r.FailureDiagnosticsPath);var text=File.ReadAllText(r.FailureDiagnosticsPath!);Assert.DoesNotContain("sceneLevelOutcomes",text);}}
    [Fact] public async Task PublishAsync_RollbackFailure_PreservesOriginalAndRollbackErrors(){var(f,r)=await RollbackFailureCore("MoveDirectory");using(f){Assert.Contains(r.Errors,x=>x.Contains("readback failed"));Assert.Contains(r.Errors,x=>x.Contains("Injected"));}}
    [Fact] public async Task PublishAsync_UsesExactTypedTransactionPaths(){using var f=await Published();Assert.True(Directory.Exists(Path.Combine(f.Root,"05-editorial")));Assert.False(Directory.Exists(Path.Combine(f.Root,"phase5")));}
    [Fact] public async Task PublishAsync_DoesNotTouchUnrelatedTransactionLikeDirectories(){using var f=new Phase5PublicationTestFixture();var unrelated=Path.Combine(f.Root,".05-editorial-staging-unrelated");Directory.CreateDirectory(unrelated);File.WriteAllText(Path.Combine(unrelated,"keep"),"x");await f.PublishValidAsync();Assert.True(File.Exists(Path.Combine(unrelated,"keep")));}
    [Fact] public async Task PublishAsync_CancellationBeforeMutation_LeavesWorkspaceUnchanged(){using var f=new Phase5PublicationTestFixture();using var c=new CancellationTokenSource();c.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>f.Coordinator().PublishAsync(f.Request,c.Token));Assert.Empty(Directory.GetFileSystemEntries(f.Root));}
    [Fact] public async Task PublishAsync_CancellationAfterMutation_UsesNonInterruptibleRollback(){using var f=new Phase5PublicationTestFixture();var fs=new FaultInjectingPhase5PublicationFileSystem{Fail=x=>x.Contains("phase-manifest.json")};var r=await f.Coordinator(fs:fs).PublishAsync(f.Request);Assert.True(r.RollbackPerformed);}

    private static async Task<Phase5PublicationTestFixture> Published(){var f=new Phase5PublicationTestFixture();await f.PublishValidAsync();return f;}
    private static void Committed(Phase5PublicationTransactionResult r){Assert.True(r.Succeeded);Assert.True(r.PublicationCommitted);Assert.True(r.CommittedStateValidationPassed);Assert.Equal("P5PUB_COMMITTED",r.ReasonCode);Assert.False(r.RollbackPerformed);Assert.True(r.RollbackSucceeded);Assert.Null(r.FailureDiagnosticsPath);}
    private static void Failed(Phase5PublicationTransactionResult r,string code,bool rollback){Assert.False(r.Succeeded);Assert.False(r.PublicationCommitted);Assert.False(r.CommittedStateValidationPassed);Assert.Equal(code,r.ReasonCode);Assert.Equal(rollback,r.RollbackPerformed);}
    private static async Task ReadbackRestoresAbsence(){using var f=new Phase5PublicationTestFixture();var r=await f.Coordinator(StubPhase5Evaluator.Invalid(),new StubPhase5Recovery(new(true,"ok",[],[]))).PublishAsync(f.Request);Failed(r,"P5REUSE_CHECKSUM_INVALID",true);Assert.True(r.RollbackSucceeded);Assert.False(r.PreviousAuthorityRestored);Assert.False(Directory.Exists(Path.Combine(f.Root,"05-editorial")));Assert.False(File.Exists(f.Manifest));Assert.False(File.Exists(f.Validation));}
    private static async Task ReadbackRestoresPrevious(string item){using var f=new Phase5PublicationTestFixture();Directory.CreateDirectory(Path.Combine(f.Root,"05-editorial"));File.WriteAllText(f.Editorial("old"),"old");File.WriteAllText(f.Manifest,"old manifest");Directory.CreateDirectory(Path.GetDirectoryName(f.Validation)!);File.WriteAllText(f.Validation,"old validation");var r=await f.Coordinator(StubPhase5Evaluator.Invalid(),new StubPhase5Recovery(new(true,"ok",[],[]))).PublishAsync(f.Request);Assert.True(r.RollbackPerformed);Assert.True(r.RollbackSucceeded);Assert.True(r.PreviousAuthorityRestored);if(item=="editorial")Assert.Equal("old",File.ReadAllText(f.Editorial("old")));if(item=="manifest")Assert.Equal("old manifest",File.ReadAllText(f.Manifest));if(item=="validation")Assert.Equal("old validation",File.ReadAllText(f.Validation));}
    private static async Task FailureAt(string match,bool rollback){using var f=new Phase5PublicationTestFixture();var count=0;var fs=new FaultInjectingPhase5PublicationFileSystem{Fail=x=>x.Contains(match)&&++count==1};var r=await f.Coordinator(fs:fs).PublishAsync(f.Request);Assert.False(r.Succeeded);Assert.Equal(rollback,r.RollbackPerformed);}
    private static async Task RollbackFailure(string match){var(f,r)=await RollbackFailureCore(match);using(f){Assert.Equal("P5PUB_ROLLBACK_FAILED",r.ReasonCode);Assert.True(r.RollbackPerformed);Assert.False(r.RollbackSucceeded);Assert.NotNull(r.FailureDiagnosticsPath);}}
    private static async Task<(Phase5PublicationTestFixture,Phase5PublicationTransactionResult)> RollbackFailureCore(string match){var f=new Phase5PublicationTestFixture();Directory.CreateDirectory(Path.Combine(f.Root,"05-editorial"));File.WriteAllText(f.Editorial("old"),"old");File.WriteAllText(f.Manifest,"old");Directory.CreateDirectory(Path.GetDirectoryName(f.Validation)!);File.WriteAllText(f.Validation,"old");var fs=new FaultInjectingPhase5PublicationFileSystem{Fail=x=>x.Contains(match)&&(!x.Contains("staging"))};var r=await f.Coordinator(StubPhase5Evaluator.Invalid(),new StubPhase5Recovery(new(true,"ok",[],[])),fs).PublishAsync(f.Request);return(f,r);}
}
