using System.Text.Json;
using Astronomy.MediaFactory.Infrastructure.DocumentaryBlueprint;

namespace Astronomy.MediaFactory.Tests;

public sealed class Phase5PublicationRecoveryServiceTests
{
    [Fact] public async Task RecoverAsync_NoMarkers_ReturnsSuccessfulNoOp(){using var f=new Phase5PublicationTestFixture();var r=await Recover(f);Success(r,0);}
    [Fact] public async Task RecoverAsync_PreparingMarker_CleansUncommittedState()=>await Cleans(Phase5PublicationTransactionStatus.Preparing);
    [Fact] public async Task RecoverAsync_StagedValidatedMarker_CleansUncommittedState()=>await Cleans(Phase5PublicationTransactionStatus.StagedValidated);
    [Fact] public async Task RecoverAsync_PreviousStateBackedUp_RestoresPreviousState()=>await Restores(Phase5PublicationTransactionStatus.PreviousStateBackedUp);
    [Fact] public async Task RecoverAsync_EditorialSwapped_RestoresPreviousState()=>await Restores(Phase5PublicationTransactionStatus.EditorialSwapped);
    [Fact] public async Task RecoverAsync_MetadataPublished_ValidCommittedState_CleansTransactionEvidence()=>await CleansCommitted(Phase5PublicationTransactionStatus.MetadataPublished);
    [Fact] public async Task RecoverAsync_MetadataPublished_InvalidCommittedState_RestoresPreviousState()=>await Restores(Phase5PublicationTransactionStatus.MetadataPublished);
    [Fact] public async Task RecoverAsync_Committed_ValidCommittedState_CleansResidualEvidence()=>await CleansCommitted(Phase5PublicationTransactionStatus.Committed);
    [Fact] public async Task RecoverAsync_MarkerPathsMismatch_ReturnsAmbiguousState(){using var f=new Phase5PublicationTestFixture();var m=f.WriteMarker("a",Phase5PublicationTransactionStatus.Preparing);var bad=m with{Paths=m.Paths with{StagingRoot=m.Paths.StagingRoot+"-wrong"}};File.WriteAllText(m.Paths.TransactionMarkerPath,JsonSerializer.Serialize(bad,new JsonSerializerOptions(JsonSerializerDefaults.Web)));var r=await Recover(f);Assert.False(r.Succeeded);Assert.Equal("P5PUB_RECOVERY_AMBIGUOUS_STATE",r.ReasonCode);}
    [Fact] public async Task RecoverAsync_RollbackFailedMarker_ReturnsRollbackFailed(){using var f=new Phase5PublicationTestFixture();f.WriteMarker("a",Phase5PublicationTransactionStatus.RollbackFailed);var r=await Recover(f);Assert.False(r.Succeeded);Assert.Equal("P5PUB_ROLLBACK_FAILED",r.ReasonCode);}
    [Fact] public async Task RecoverAsync_MissingEditorialBackup_ReturnsRecoveryFailed(){using var f=new Phase5PublicationTestFixture();f.WriteMarker("a",Phase5PublicationTransactionStatus.EditorialSwapped,true);var r=await Recover(f);Failure(r);Assert.Contains(r.Errors,x=>x.Contains("editorial backup"));}
    [Fact] public async Task RecoverAsync_MissingManifestSnapshot_ReturnsRecoveryFailed(){using var f=new Phase5PublicationTestFixture();f.WriteMarker("a",Phase5PublicationTransactionStatus.EditorialSwapped,false,true);var r=await Recover(f);Failure(r);Assert.Contains(r.Errors,x=>x.Contains("Snapshot"));}
    [Fact] public async Task RecoverAsync_MissingValidationSnapshot_ReturnsRecoveryFailed(){using var f=new Phase5PublicationTestFixture();f.WriteMarker("a",Phase5PublicationTransactionStatus.EditorialSwapped,false,false,true);var r=await Recover(f);Failure(r);Assert.Contains(r.Errors,x=>x.Contains("Snapshot"));}
    [Fact] public async Task RecoverAsync_MultipleMarkers_ProcessesInOrdinalOrder(){using var f=new Phase5PublicationTestFixture();f.WriteMarker("b",Phase5PublicationTransactionStatus.Preparing);f.WriteMarker("a",Phase5PublicationTransactionStatus.Preparing);var r=await Recover(f);Assert.Equal(["a","b"],r.RecoveredTransactionIds);}
    [Fact] public async Task RecoverAsync_OneFailure_ReturnsRecoveredIdsAndErrorsAccurately(){using var f=new Phase5PublicationTestFixture();f.WriteMarker("a",Phase5PublicationTransactionStatus.Preparing);f.WriteMarker("b",Phase5PublicationTransactionStatus.EditorialSwapped,true);var r=await Recover(f);Failure(r);Assert.Equal(["a"],r.RecoveredTransactionIds);Assert.Single(r.Errors);}
    [Fact] public async Task RecoverAsync_DoesNotGuessUnmarkedWildcardDirectories(){using var f=new Phase5PublicationTestFixture();var p=Path.Combine(f.Root,".05-editorial-staging-orphan");Directory.CreateDirectory(p);await Recover(f);Assert.True(Directory.Exists(p));}
    [Fact] public async Task RecoverAsync_DoesNotDeleteUnrelatedFiles(){using var f=new Phase5PublicationTestFixture();var keep=Path.Combine(f.Root,"keep.txt");File.WriteAllText(keep,"keep");f.WriteMarker("a",Phase5PublicationTransactionStatus.Preparing);await Recover(f);Assert.Equal("keep",File.ReadAllText(keep));}
    [Fact] public async Task RecoverAsync_RestoresPriorAbsenceCorrectly(){using var f=new Phase5PublicationTestFixture();var m=f.WriteMarker("a",Phase5PublicationTransactionStatus.EditorialSwapped);Directory.CreateDirectory(m.Paths.EditorialRoot);File.WriteAllText(Path.Combine(m.Paths.EditorialRoot,"new"),"new");File.WriteAllText(m.Paths.ManifestPath,"new");Directory.CreateDirectory(Path.GetDirectoryName(m.Paths.ValidationPath)!);File.WriteAllText(m.Paths.ValidationPath,"new");var r=await Recover(f);Success(r,1);Assert.False(Directory.Exists(m.Paths.EditorialRoot));Assert.False(File.Exists(m.Paths.ManifestPath));Assert.False(File.Exists(m.Paths.ValidationPath));}
    [Fact] public async Task RecoverAsync_ValidatesExactMarkerTransactionPaths(){using var f=new Phase5PublicationTestFixture();var m=f.WriteMarker("a",Phase5PublicationTransactionStatus.Preparing);Assert.Equal(Phase5PublicationTransactionPaths.Create(f.Root,"a"),m.Paths);Success(await Recover(f),1);}
    [Fact] public async Task RecoverAsync_CancellationBeforeProcessing_ThrowsOrReturnsWithoutMutation(){using var f=new Phase5PublicationTestFixture();var m=f.WriteMarker("a",Phase5PublicationTransactionStatus.Preparing);Directory.CreateDirectory(m.Paths.StagingRoot);using var c=new CancellationTokenSource();c.Cancel();await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>Recover(f,token:c.Token));Assert.True(File.Exists(m.Paths.TransactionMarkerPath));Assert.True(Directory.Exists(m.Paths.StagingRoot));}

    private static async Task Cleans(Phase5PublicationTransactionStatus status){using var f=new Phase5PublicationTestFixture();var m=f.WriteMarker("a",status);Directory.CreateDirectory(m.Paths.StagingRoot);File.WriteAllText(m.Paths.ManifestBackupPath,"x");File.WriteAllText(m.Paths.ValidationBackupPath,"x");Success(await Recover(f),1);Assert.False(Directory.Exists(m.Paths.StagingRoot));Assert.False(File.Exists(m.Paths.TransactionMarkerPath));}
    private static async Task Restores(Phase5PublicationTransactionStatus status){using var f=new Phase5PublicationTestFixture();var m=f.WriteMarker("a",status,true,true,true);Directory.CreateDirectory(m.Paths.BackupRoot);File.WriteAllText(Path.Combine(m.Paths.BackupRoot,"old"),"old");File.WriteAllText(m.Paths.ManifestBackupPath,"old manifest");File.WriteAllText(m.Paths.ValidationBackupPath,"old validation");Directory.CreateDirectory(m.Paths.EditorialRoot);File.WriteAllText(Path.Combine(m.Paths.EditorialRoot,"new"),"new");Success(await Recover(f),1);Assert.Equal("old",File.ReadAllText(Path.Combine(m.Paths.EditorialRoot,"old")));Assert.Equal("old manifest",File.ReadAllText(m.Paths.ManifestPath));Assert.Equal("old validation",File.ReadAllText(m.Paths.ValidationPath));}
    private static async Task CleansCommitted(Phase5PublicationTransactionStatus status){using var f=new Phase5PublicationTestFixture();await f.PublishValidAsync();var m=f.WriteMarker("a",status);Directory.CreateDirectory(m.Paths.BackupRoot);File.WriteAllText(Path.Combine(m.Paths.BackupRoot,"old"),"old");Success(await Recover(f),1);Assert.False(Directory.Exists(m.Paths.BackupRoot));Assert.False(File.Exists(m.Paths.TransactionMarkerPath));Assert.True(Directory.Exists(m.Paths.EditorialRoot));}
    private static Task<Phase5PublicationRecoveryResult> Recover(Phase5PublicationTestFixture f,IPhase5PublicationFileSystem? fs=null,CancellationToken token=default)=>new Phase5PublicationRecoveryService(new Phase5CommittedAuthorityEvaluator(),fs??f.FileSystem).RecoverAsync(f.Root,f.CertificationRequest.ExecutionId,f.CertificationRequest.PlanId,f.CertificationRequest.EventId,f.CertificationRequest.Language,f.Expected,token);
    private static void Success(Phase5PublicationRecoveryResult r,int count){Assert.True(r.Succeeded,string.Join(";",r.Errors));Assert.Equal("P5PUB_RECOVERY_COMPLETED",r.ReasonCode);Assert.Equal(count,r.RecoveredTransactionIds.Count);Assert.Empty(r.Errors);}
    private static void Failure(Phase5PublicationRecoveryResult r){Assert.False(r.Succeeded);Assert.Equal("P5PUB_RECOVERY_FAILED",r.ReasonCode);Assert.NotEmpty(r.Errors);}
}
