using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Catalog;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Contracts;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Catalog;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Contracts;
namespace Astronomy.MediaFactory.Tests;
public sealed class SemanticSourcePolicyValidationV1Tests
{
    private static SemanticSourcePolicyV1 Clone(SemanticSourcePolicyV1 p)=>p with{};
    [Fact] public void Compatibility_Only_Source_Cannot_Satisfy_Required_Certification(){var p=new SemanticSourcePolicyCatalogV1().Policies.First(); var bad=p with{ApprovedSources=[p.ApprovedSources[0] with{CompatibilityOnly=true, SourceId="LegacyRawJsonScanner"}]}; var r=SemanticSourcePolicyValidatorV1.Validate([bad,..new SemanticSourcePolicyCatalogV1().Policies.Skip(1)]); Assert.False(r.IsValid); Assert.Contains(r.Errors,e=>e.Contains("Compatibility-only"));}
    [Fact] public void Synthetic_Duplicate_Policy_Fails_Validation(){var ps=new SemanticSourcePolicyCatalogV1().Policies.ToArray(); var r=SemanticSourcePolicyValidatorV1.Validate([..ps,ps[0]]); Assert.False(r.IsValid); Assert.Contains(r.Errors,e=>e.Contains("Duplicate capability"));}
    [Fact] public void Synthetic_Duplicate_Source_Priority_Fails_Validation(){var ps=new SemanticSourcePolicyCatalogV1().Policies.ToArray(); var p=ps[0]; ps[0]=p with{ApprovedSources=[p.ApprovedSources[0],p.ApprovedSources[1] with{Priority=p.ApprovedSources[0].Priority}]}; var r=SemanticSourcePolicyValidatorV1.Validate(ps); Assert.False(r.IsValid); Assert.Contains(r.Errors,e=>e.Contains("Duplicate source priority"));}
    [Fact] public void Synthetic_Event_Specific_Policy_With_Only_Domain_Source_Fails(){var ps=new SemanticSourcePolicyCatalogV1().Policies.ToArray(); var p=ps.First(x=>x.SemanticCapabilityId.Value==SemanticCapabilityVocabularyV1.AngularSeparation); var bad=p with{AllowedEvidenceCategories=[SemanticEvidenceCategoryV1.DomainScientificKnowledge],ApprovedSources=[new("AstronomyDomainKnowledgeProvider",SemanticEvidenceCategoryV1.DomainScientificKnowledge,SemanticEvidenceStrengthV1.Strong,1,false,true,true,false,true,true,false,true,"bad")]}; ps[Array.IndexOf(ps,p)]=bad; var r=SemanticSourcePolicyValidatorV1.Validate(ps); Assert.False(r.IsValid); Assert.Contains(r.Errors,e=>e.Contains("only non-event"));}
    [Fact] public void Synthetic_Raw_Json_Required_Source_Fails(){var ps=new SemanticSourcePolicyCatalogV1().Policies.ToArray(); ps[0]=ps[0] with{RawJsonCompatibilityAllowed=true}; var r=SemanticSourcePolicyValidatorV1.Validate(ps); Assert.False(r.IsValid); Assert.Contains(r.Errors,e=>e.Contains("Raw JSON"));}
    [Fact] public void Synthetic_Cultural_Source_For_EclipseCircumstances_Fails(){var ps=new SemanticSourcePolicyCatalogV1().Policies.ToArray(); var p=ps.First(x=>x.SemanticCapabilityId.Value==SemanticCapabilityVocabularyV1.EclipseCircumstances); var bad=p with{AllowedEvidenceCategories=[..p.AllowedEvidenceCategories,SemanticEvidenceCategoryV1.CulturalContext],ApprovedSources=[..p.ApprovedSources,new("VerifiedCulturalContext",SemanticEvidenceCategoryV1.CulturalContext,SemanticEvidenceStrengthV1.Strong,99,false,true,true,false,false,true,false,true,"bad")]}; ps[Array.IndexOf(ps,p)]=bad; var r=SemanticSourcePolicyValidatorV1.Validate(ps); Assert.False(r.IsValid); Assert.Contains(r.Errors,e=>e.Contains("Cultural source"));}
}
