using System.Collections.Immutable;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Adapters.Contracts;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Adapters.Event;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Adapters.Knowledge;
using Xunit;
namespace Astronomy.MediaFactory.Tests;
public class SemanticSourceAdaptersV1Tests
{
    [Fact] public void EventIdentity_Preserves_Supplied_Canonical_Identity(){var id=new CanonicalAstronomyEventIdentity("SolarEclipse","SolarEclipse","p","solar eclipse","EventIdentityContext");var r=new EventIdentitySourceAdapterV1().TryExtract(new(EventIdentity:id));Assert.Same(id, r.Candidate!.TypedValue.Value);}
    [Fact] public void EventWindow_Extracts_Local_And_Utc_Distinctly_And_Rejects_Invalid_Order(){var good=new EventWindowValue(DateTimeOffset.Parse("2026-01-01T00:00:00Z"),DateTimeOffset.Parse("2026-01-01T01:00:00Z"),DateTimeOffset.Parse("2026-01-01T02:00:00Z"),DateTimeOffset.Parse("2025-12-31T19:00:00-05:00"),DateTimeOffset.Parse("2025-12-31T21:00:00-05:00"),null,null,"America/New_York","local");Assert.Equal(SemanticSourceAdapterStatusV1.Resolved,new EventWindowSourceAdapterV1().TryExtract(new(ObservationMetadata:new(EventWindow:good))).Status);var bad=good with{StartUtc=DateTimeOffset.Parse("2026-01-01T03:00:00Z")};Assert.Equal(SemanticSourceAdapterStatusV1.InvalidValue,new EventWindowSourceAdapterV1().TryExtract(new(ObservationMetadata:new(EventWindow:bad))).Status);}
    [Fact] public void Objects_Do_Not_Infer_From_Title_And_Secondary_Missing_Is_ValueMissing(){var ctx=new SemanticSourceAdapterContextV1(ContentPlan:new(Title:"Venus meets Jupiter"),ProductionEventIntelligence:new());Assert.Equal(SemanticSourceAdapterStatusV1.ValueMissing,new AstronomicalObjectsSourceAdapterV1().TryExtract(ctx).Status);Assert.Equal(SemanticSourceAdapterStatusV1.ValueMissing,new SecondaryAstronomicalObjectsSourceAdapterV1().TryExtract(ctx).Status);}
    [Fact] public void AngularSeparation_Accepts_Normalized_Degrees_And_Rejects_Invalid_Ranges(){var a=new AngularSeparationSourceAdapterV1();Assert.Equal(SemanticSourceAdapterStatusV1.Resolved,a.TryExtract(new(ProductionEventIntelligence:new(AngularSeparation:new(1.5m,30,null,"close","conjunction",null)))).Status);Assert.Equal(SemanticSourceAdapterStatusV1.InvalidValue,a.TryExtract(new(ProductionEventIntelligence:new(AngularSeparation:new(181m,null,null,null,null,null)))).Status);}
    [Fact] public void Observation_Adapters_Validate_And_Do_Not_Fabricate_Current_Weather(){Assert.Equal(SemanticSourceAdapterStatusV1.Resolved,new ObservationDirectionSourceAdapterV1().TryExtract(new(ObservationMetadata:new(ObservationDirection:new("NE",45,10,"rising","northeast")))).Status);Assert.Equal(SemanticSourceAdapterStatusV1.InvalidValue,new ObservationLocationSourceAdapterV1().TryExtract(new(ObservationMetadata:new(ObservationLocation:new("bad",91,0,null,"UTC")))).Status);var r=new ObservationConditionsSourceAdapterV1().TryExtract(new(ObservationMetadata:new(ObservationConditions:new(80,"low horizon","twilight","bright","principle","rain"))));Assert.Null(((ObservationConditionsValue)r.Candidate!.TypedValue.Value).CurrentWeather);}
    [Fact] public void Meteor_FullMoon_Eclipse_Occultation_And_Safety_Rules(){Assert.Equal(120,((MeteorActivityValue)new MeteorActivitySourceAdapterV1().TryExtract(new(ProductionEventIntelligence:new(MeteorActivity:new("Gemini",null,null,120,null,null)))).Candidate!.TypedValue.Value).Zhr);Assert.Null(((MeteorActivityValue)new MeteorActivitySourceAdapterV1().TryExtract(new(ProductionEventIntelligence:new(MeteorActivity:new("Gemini",null,null,null,null,null)))).Candidate!.TypedValue.Value).Zhr);Assert.NotNull(((FullMoonObservationValue)new FullMoonObservationSourceAdapterV1().TryExtract(new(ObservationMetadata:new(FullMoonObservation:new(DateTimeOffset.Parse("2026-01-01T00:00:00Z"),null,null,100,null,"notes")))).Candidate!.TypedValue.Value).Moonrise);Assert.Equal("SolarEclipse",((EclipseCircumstancesValue)new EclipseCircumstancesSourceAdapterV1().TryExtract(new(ProductionEventIntelligence:new(EclipseCircumstances:new("SolarEclipse",null,null,null,.8m,.7m,null,null,null,ImmutableArray<DateTimeOffset>.Empty,"Solar")))).Candidate!.TypedValue.Value).EclipseType);Assert.Equal(SemanticSourceAdapterStatusV1.InvalidValue,new OccultationContactsSourceAdapterV1().TryExtract(new(ProductionEventIntelligence:new(OccultationContacts:new(DateTimeOffset.Parse("2026-01-01T02:00:00Z"),DateTimeOffset.Parse("2026-01-01T01:00:00Z"),null,null,null,"Moon","Mars")))).Status);Assert.True(((SafetyGuidanceValue)new SafetyGuidanceKnowledgeAdapterV1().TryExtract(new(AstronomyDomainKnowledge:new(SafetyGuidance:new("SolarEclipse","Use certified solar filters","ISO 12312-2",true,true)))).Candidate!.TypedValue.Value).DirectSolarViewing);}
    [Fact] public void Knowledge_Adapters_Preserve_Provenance_And_Constrain_Context_Types(){var prov=new SemanticSourceProvenanceV1("VerifiedObjectCatalog","Object","diameter",true);var ok=new ObjectKnowledgeValue("Mars",[new("diameter","6792 km",prov)]);var r=new ObjectKnowledgeSourceAdapterV1().TryExtract(new(AstronomyObjectKnowledge:new(ObjectKnowledge:ok)));Assert.Equal(prov,((ObjectKnowledgeValue)r.Candidate!.TypedValue.Value).Facts[0].Provenance);Assert.Equal(SemanticSourceAdapterStatusV1.ValueMissing,new ObservationEquipmentKnowledgeAdapterV1().TryExtract(new(AstronomyDomainKnowledge:new())).Status);Assert.Equal(SemanticSourceAdapterStatusV1.Resolved,new DomainScientificKnowledgeSourceAdapterV1().TryExtract(new(AstronomyDomainKnowledge:new(DomainKnowledge:new("mechanism","alignment","significance","principles")))).Status);Assert.Equal(SemanticSourceAdapterStatusV1.UnverifiedValue,new CulturalContextSourceAdapterV1().TryExtract(new(CulturalAstronomyKnowledge:new(CulturalContext:new("name","tradition","origin",.5m,"region","caution",false)))).Status);Assert.Equal(SemanticSourceAdapterStatusV1.Resolved,new EditorialContextSourceAdapterV1().TryExtract(new(EditorialIntent:new(EditorialContext:new("emphasis","tone","beat","closing",["warn"])))).Status);}
}
