using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Integration;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Graph;

public enum AstronomyKnowledgeGraphNodeKind { Entity = 1, Statement = 2 }
public enum AstronomyKnowledgeGraphRelationshipKind { RelatedTo = 1, DerivedFrom = 2, ParentOf = 3, Supersedes = 4, Contains = 5 }
public enum AstronomyKnowledgeGraphReferenceTargetKind { Entity = 1, Statement = 2 }
public enum AstronomyKnowledgeGraphConnectivityPolicy { IndependentComponentsAllowed = 1, ConnectedScopeRequired = 2 }
public enum AstronomyKnowledgeGraphDuplicateNodePolicy { IgnoreCompatible = 1, WarnCompatible = 2 }
public enum AstronomyKnowledgeGraphExternalReferencePolicy { AllowExplicitExternal = 1, RejectExternal = 2 }

public sealed record AstronomyKnowledgeGraphNode(string NodeId, AstronomyKnowledgeGraphNodeKind NodeKind, string? EntityKind = null)
{ public string NodeId { get; init; } = KnowledgeId.NormalizeToken(NodeId, nameof(NodeId), "Graph node ID", 256); }
public sealed record AstronomyKnowledgeGraphRelationship(string RelationshipId, AstronomyKnowledgeGraphRelationshipKind Kind, string SourceId, AstronomyKnowledgeGraphReferenceTargetKind SourceKind, string TargetId, AstronomyKnowledgeGraphReferenceTargetKind TargetKind)
{ public string RelationshipId { get; init; } = KnowledgeId.NormalizeToken(RelationshipId, nameof(RelationshipId), "Graph relationship ID", 256); public string SourceId { get; init; } = KnowledgeId.NormalizeToken(SourceId, nameof(SourceId), "Relationship source ID", 256); public string TargetId { get; init; } = KnowledgeId.NormalizeToken(TargetId, nameof(TargetId), "Relationship target ID", 256); }
public sealed record AstronomyKnowledgeGraphReference(string ReferenceId, AstronomyKnowledgeGraphReferenceTargetKind TargetKind, string TargetId, bool IsExternal = false)
{ public string ReferenceId { get; init; } = KnowledgeId.NormalizeToken(ReferenceId, nameof(ReferenceId), "Graph reference ID", 256); public string TargetId { get; init; } = KnowledgeId.NormalizeToken(TargetId, nameof(TargetId), "Graph reference target ID", 256); }

public sealed class AstronomyKnowledgeGraphValidationSet
{
    public AstronomyKnowledgeGraphValidationSet(IEnumerable<IAstronomyKnowledgeStatement>? statements = null, IEnumerable<AstronomyKnowledgeGraphNode>? nodes = null, IEnumerable<AstronomyKnowledgeGraphRelationship>? relationships = null, IEnumerable<AstronomyKnowledgeGraphReference>? references = null, IEnumerable<string>? rootIds = null, string? repositoryId = null, string? repositoryVersion = null)
    { Statements = Array.AsReadOnly((statements ?? []).Select(x => x ?? throw new ArgumentException("Statements cannot contain null entries.", nameof(statements))).ToArray()); Nodes = Array.AsReadOnly((nodes ?? []).Select(x => x ?? throw new ArgumentException("Nodes cannot contain null entries.", nameof(nodes))).ToArray()); Relationships = Array.AsReadOnly((relationships ?? []).Select(x => x ?? throw new ArgumentException("Relationships cannot contain null entries.", nameof(relationships))).ToArray()); References = Array.AsReadOnly((references ?? []).Select(x => x ?? throw new ArgumentException("References cannot contain null entries.", nameof(references))).ToArray()); RootIds = Array.AsReadOnly((rootIds ?? []).Select(x => KnowledgeId.NormalizeToken(x, nameof(rootIds), "Graph root ID", 256)).ToArray()); RepositoryId = repositoryId; RepositoryVersion = repositoryVersion; }
    public IReadOnlyList<IAstronomyKnowledgeStatement> Statements { get; } public IReadOnlyList<AstronomyKnowledgeGraphNode> Nodes { get; } public IReadOnlyList<AstronomyKnowledgeGraphRelationship> Relationships { get; } public IReadOnlyList<AstronomyKnowledgeGraphReference> References { get; } public IReadOnlyList<string> RootIds { get; } public string? RepositoryId { get; } public string? RepositoryVersion { get; }
}
public sealed record AstronomyKnowledgeGraphPolicy(AstronomyKnowledgeGraphConnectivityPolicy ConnectivityPolicy = AstronomyKnowledgeGraphConnectivityPolicy.IndependentComponentsAllowed, AstronomyKnowledgeGraphDuplicateNodePolicy DuplicateNodePolicy = AstronomyKnowledgeGraphDuplicateNodePolicy.IgnoreCompatible, AstronomyKnowledgeGraphExternalReferencePolicy ExternalReferencePolicy = AstronomyKnowledgeGraphExternalReferencePolicy.AllowExplicitExternal, bool RequireRepositoryRoot = false, bool RequireUniqueRoots = false);
public sealed class AstronomyKnowledgeGraphValidationContext
{
    public AstronomyKnowledgeGraphValidationContext(AstronomyKnowledgeValidationRunId validationRunId, DateTimeOffset validatedAtUtc, AstronomyKnowledgeValidationMode mode = AstronomyKnowledgeValidationMode.Standard, AstronomyKnowledgeValidationSeverity minimumSeverity = AstronomyKnowledgeValidationSeverity.Information, IReadOnlyList<string>? rootScopeIds = null, string? expectedRepositoryId = null, string? expectedRepositoryVersion = null, AstronomyKnowledgeGraphPolicy? policy = null)
    { if (!validationRunId.IsValid) throw new ArgumentException("Validation run ID is required.", nameof(validationRunId)); if (validatedAtUtc.Offset != TimeSpan.Zero) throw new ArgumentException("Validation timestamp must be UTC.", nameof(validatedAtUtc)); ValidationRunId = validationRunId; ValidatedAtUtc = validatedAtUtc; Mode = mode; MinimumSeverity = minimumSeverity; RootScopeIds = Array.AsReadOnly((rootScopeIds ?? []).ToArray()); ExpectedRepositoryId = expectedRepositoryId; ExpectedRepositoryVersion = expectedRepositoryVersion; Policy = policy ?? new AstronomyKnowledgeGraphPolicy(); }
    public AstronomyKnowledgeValidationRunId ValidationRunId { get; } public DateTimeOffset ValidatedAtUtc { get; } public AstronomyKnowledgeValidationMode Mode { get; } public AstronomyKnowledgeValidationSeverity MinimumSeverity { get; } public IReadOnlyList<string> RootScopeIds { get; } public string? ExpectedRepositoryId { get; } public string? ExpectedRepositoryVersion { get; } public AstronomyKnowledgeGraphPolicy Policy { get; }
}
public static class AstronomyKnowledgeGraphValidationCodes { public const string NodeIdentityDuplicate="graph.node.identity.duplicate"; public const string NodeIdentityConflict="graph.node.identity.conflict"; public const string StatementIdentityDuplicate="graph.statement.identity.duplicate"; public const string StatementSubjectMissing="graph.statement.subject.missing"; public const string ReferenceTargetMissing="graph.reference.target.missing"; public const string ReferenceTargetAmbiguous="graph.reference.target.ambiguous"; public const string ReferenceTypeInvalid="graph.reference.type.invalid"; public const string OrphanStatement="graph.orphan.statement"; public const string OrphanEntity="graph.orphan.entity"; public const string DisconnectedComponent="graph.connectivity.disconnected-component"; public const string CycleDetected="graph.cycle.detected"; public const string ForbiddenSelfReference="graph.cycle.self-reference.forbidden"; public const string DuplicateKnowledge="graph.duplicate.knowledge"; public const string ConflictingDuplicateKnowledge="graph.duplicate.knowledge.conflict"; public const string PayloadMissing="graph.payload.missing"; public const string PayloadDescriptorMissing="graph.payload.descriptor.missing"; public const string PayloadFamilyMismatch="graph.payload.family.mismatch"; public const string ProvenanceReferenceBroken="graph.provenance.reference.broken"; public const string VersionConflict="graph.version.conflict"; public const string RevisionOrderInvalid="graph.version.revision-order.invalid"; public const string RepositoryIdentityMismatch="graph.repository.identity.mismatch"; public const string RepositoryRootMissing="graph.repository.root.missing"; public const string RepositoryScopeConflict="graph.repository.scope.conflict"; }
public interface IAstronomyKnowledgeGraphValidationRule { string RuleId { get; } int Order { get; } IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyKnowledgeGraphValidationSet graph, AstronomyKnowledgeGraphValidationContext context); }
public sealed record AstronomyKnowledgeGraphValidationRuleDescriptor(string RuleId, Type RuleType, int Order);
public interface IAstronomyKnowledgeGraphValidationRuleRegistry { IReadOnlyList<AstronomyKnowledgeGraphValidationRuleDescriptor> Descriptors { get; } }
public sealed class AstronomyKnowledgeGraphValidationRuleRegistry(IEnumerable<AstronomyKnowledgeGraphValidationRuleDescriptor> descriptors) : IAstronomyKnowledgeGraphValidationRuleRegistry { public IReadOnlyList<AstronomyKnowledgeGraphValidationRuleDescriptor> Descriptors { get; } = Array.AsReadOnly(descriptors.GroupBy(d=>d.RuleId,StringComparer.Ordinal).Select(g=>g.First()).OrderBy(d=>d.Order).ThenBy(d=>d.RuleId,StringComparer.Ordinal).ToArray()); }
public interface IAstronomyKnowledgeGraphValidator { AstronomyKnowledgeValidationResult Validate(AstronomyKnowledgeGraphValidationSet graph, AstronomyKnowledgeGraphValidationContext context); }
public sealed class AstronomyKnowledgeGraphValidator(IEnumerable<IAstronomyKnowledgeGraphValidationRule> rules) : IAstronomyKnowledgeGraphValidator { private readonly IReadOnlyList<IAstronomyKnowledgeGraphValidationRule> ordered = Array.AsReadOnly(rules.GroupBy(r=>r.RuleId,StringComparer.Ordinal).Select(g=>g.First()).OrderBy(r=>r.Order).ThenBy(r=>r.RuleId,StringComparer.Ordinal).ToArray()); public AstronomyKnowledgeValidationResult Validate(AstronomyKnowledgeGraphValidationSet graph, AstronomyKnowledgeGraphValidationContext context) { ArgumentNullException.ThrowIfNull(graph); ArgumentNullException.ThrowIfNull(context); var issues=ordered.SelectMany(r=>r.Validate(graph,context)).Where(i=>i.Severity>=context.MinimumSeverity).OrderByDescending(i=>i.Severity).ThenBy(i=>i.Path,StringComparer.Ordinal).ThenBy(i=>i.RuleId,StringComparer.Ordinal).ThenBy(i=>i.Code,StringComparer.Ordinal); return new AstronomyKnowledgeValidationResult(issues, true); } }

public abstract class AstronomyGraphRuleBase : IAstronomyKnowledgeGraphValidationRule
{ public abstract string RuleId { get; } public abstract int Order { get; } public abstract IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyKnowledgeGraphValidationSet graph, AstronomyKnowledgeGraphValidationContext context); protected static AstronomyKnowledgeValidationIssue Issue(string code,AstronomyKnowledgeValidationSeverity s,string msg,string path,string rule,AstronomyKnowledgeDomain d=AstronomyKnowledgeDomain.Catalog,AstronomyKnowledgePayloadFamily f=AstronomyKnowledgePayloadFamily.CatalogReference)=>new(code,s,msg,path,rule,d,f); protected static bool Exists(AstronomyKnowledgeGraphValidationSet g,string id,AstronomyKnowledgeGraphReferenceTargetKind k)=>k==AstronomyKnowledgeGraphReferenceTargetKind.Statement?g.Statements.Any(s=>s.Id.Value==id):g.Nodes.Any(n=>n.NodeId==id&&n.NodeKind==AstronomyKnowledgeGraphNodeKind.Entity); protected static (AstronomyKnowledgeDomain,AstronomyKnowledgePayloadFamily) Meta(IAstronomyKnowledgeStatement s)=>s.Payload is ITypedAstronomyKnowledgePayload p?(p.Domain,p.Family):(AstronomyKnowledgeDomain.Catalog,AstronomyKnowledgePayloadFamily.CatalogReference); }
public sealed class AstronomyGraphNodeIdentityValidationRule: AstronomyGraphRuleBase { public const string Id="graph.node.identity"; public override string RuleId=>Id; public override int Order=>100; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyKnowledgeGraphValidationSet g,AstronomyKnowledgeGraphValidationContext c){foreach(var grp in g.Nodes.Select((n,i)=>(n,i)).GroupBy(x=>x.n.NodeId,StringComparer.Ordinal)){var kinds=grp.Select(x=>x.n.NodeKind+":"+x.n.EntityKind).Distinct(StringComparer.Ordinal).ToArray(); if(kinds.Length>1) yield return Issue(AstronomyKnowledgeGraphValidationCodes.NodeIdentityConflict,AstronomyKnowledgeValidationSeverity.Error,"Graph node identity has incompatible declarations.",$"$.nodes[{grp.Skip(1).First().i}]",RuleId); else if(grp.Count()>1&&c.Policy.DuplicateNodePolicy==AstronomyKnowledgeGraphDuplicateNodePolicy.WarnCompatible) yield return Issue(AstronomyKnowledgeGraphValidationCodes.NodeIdentityDuplicate,AstronomyKnowledgeValidationSeverity.Warning,"Graph node identity is declared more than once.",$"$.nodes[{grp.Skip(1).First().i}]",RuleId);}}}
public sealed class AstronomyGraphStatementIdentityValidationRule: AstronomyGraphRuleBase { public const string Id="graph.statement.identity"; public override string RuleId=>Id; public override int Order=>200; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyKnowledgeGraphValidationSet g,AstronomyKnowledgeGraphValidationContext c){foreach(var grp in g.Statements.Select((s,i)=>(s,i)).GroupBy(x=>new{x.s.Id,x.s.Version})) if(grp.Count()>1){var (d,f)=Meta(grp.First().s); yield return Issue(AstronomyKnowledgeGraphValidationCodes.StatementIdentityDuplicate,AstronomyKnowledgeValidationSeverity.Error,"Statement ID and revision are duplicated.",$"$.statements[{grp.Skip(1).First().i}]",RuleId,d,f);} for(var i=0;i<g.Statements.Count;i++) if(!Exists(g,g.Statements[i].PrimarySubject.EntityId,AstronomyKnowledgeGraphReferenceTargetKind.Entity)){var(d,f)=Meta(g.Statements[i]); yield return Issue(AstronomyKnowledgeGraphValidationCodes.StatementSubjectMissing,AstronomyKnowledgeValidationSeverity.Error,"Statement subject is not declared in the graph.",$"$.statements[{i}].primarySubject",RuleId,d,f);}}}
public sealed class AstronomyGraphReferenceIntegrityValidationRule: AstronomyGraphRuleBase { public const string Id="graph.reference.integrity"; public override string RuleId=>Id; public override int Order=>300; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyKnowledgeGraphValidationSet g,AstronomyKnowledgeGraphValidationContext c){for(var i=0;i<g.Relationships.Count;i++){var r=g.Relationships[i]; if(!Exists(g,r.SourceId,r.SourceKind)) yield return Issue(AstronomyKnowledgeGraphValidationCodes.ReferenceTargetMissing,AstronomyKnowledgeValidationSeverity.Error,"Relationship source target is missing.",$"$.relationships[{i}].source",RuleId); if(!Exists(g,r.TargetId,r.TargetKind)) yield return Issue(AstronomyKnowledgeGraphValidationCodes.ReferenceTargetMissing,AstronomyKnowledgeValidationSeverity.Error,"Relationship target is missing.",$"$.relationships[{i}].target",RuleId);} for(var i=0;i<g.References.Count;i++){var r=g.References[i]; if(r.IsExternal&&c.Policy.ExternalReferencePolicy==AstronomyKnowledgeGraphExternalReferencePolicy.AllowExplicitExternal) continue; var count=(r.TargetKind==AstronomyKnowledgeGraphReferenceTargetKind.Statement?g.Statements.Count(s=>s.Id.Value==r.TargetId):g.Nodes.Count(n=>n.NodeId==r.TargetId&&n.NodeKind==AstronomyKnowledgeGraphNodeKind.Entity)); if(count==0) yield return Issue(r.IsExternal?AstronomyKnowledgeGraphValidationCodes.ReferenceTypeInvalid:AstronomyKnowledgeGraphValidationCodes.ReferenceTargetMissing,AstronomyKnowledgeValidationSeverity.Error,"Graph reference target does not resolve.",$"$.references[{i}]",RuleId); else if(count>1) yield return Issue(AstronomyKnowledgeGraphValidationCodes.ReferenceTargetAmbiguous,AstronomyKnowledgeValidationSeverity.Error,"Graph reference target resolves ambiguously.",$"$.references[{i}]",RuleId);}}}
public sealed class AstronomyGraphPayloadCompletenessValidationRule(IAstronomyTypedPayloadRegistry registry): AstronomyGraphRuleBase { public const string Id="graph.payload.completeness"; public override string RuleId=>Id; public override int Order=>400; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyKnowledgeGraphValidationSet g,AstronomyKnowledgeGraphValidationContext c){for(var i=0;i<g.Statements.Count;i++){var s=g.Statements[i]; if(s.Payload is null){yield return Issue(AstronomyKnowledgeGraphValidationCodes.PayloadMissing,AstronomyKnowledgeValidationSeverity.Error,"Statement payload is missing.",$"$.statements[{i}].payload",RuleId); continue;} if(s.Payload is ITypedAstronomyKnowledgePayload p){ if(!registry.TryGetByPayloadType(p.GetType(),out var d)) yield return Issue(AstronomyKnowledgeGraphValidationCodes.PayloadDescriptorMissing,AstronomyKnowledgeValidationSeverity.Error,"Payload descriptor is missing.",$"$.statements[{i}].payload",RuleId,p.Domain,p.Family); else if(d.Domain!=p.Domain||d.Family!=p.Family) yield return Issue(AstronomyKnowledgeGraphValidationCodes.PayloadFamilyMismatch,AstronomyKnowledgeValidationSeverity.Error,"Payload descriptor metadata does not match payload metadata.",$"$.statements[{i}].payload",RuleId,p.Domain,p.Family);}}}}
public sealed class AstronomyGraphDuplicateKnowledgeValidationRule: AstronomyGraphRuleBase { public const string Id="graph.duplicate-knowledge.integrity"; public override string RuleId=>Id; public override int Order=>500; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyKnowledgeGraphValidationSet g,AstronomyKnowledgeGraphValidationContext c){foreach(var grp in g.Statements.Select((s,i)=>(s,i)).GroupBy(x=>x.s.PrimarySubject.EntityId+"|"+x.s.Payload.GetType().FullName+"|"+x.s.Kind)){if(grp.Count()<2)continue; var arr=grp.ToArray(); var(d,f)=Meta(arr[1].s); yield return Issue(arr.Select(x=>x.s.Payload).Distinct().Count()==1?AstronomyKnowledgeGraphValidationCodes.DuplicateKnowledge:AstronomyKnowledgeGraphValidationCodes.ConflictingDuplicateKnowledge,AstronomyKnowledgeValidationSeverity.Warning,"Duplicate logical knowledge assertion detected.",$"$.statements[{arr[1].i}]",RuleId,d,f);}}}
public sealed class AstronomyGraphProvenanceValidationRule: AstronomyGraphRuleBase { public const string Id="graph.provenance.integrity"; public override string RuleId=>Id; public override int Order=>600; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyKnowledgeGraphValidationSet g,AstronomyKnowledgeGraphValidationContext c){foreach(var issue in new AstronomyGraphReferenceIntegrityValidationRule().Validate(new AstronomyKnowledgeGraphValidationSet(references:g.References.Where(r=>r.ReferenceId.StartsWith("provenance.",StringComparison.Ordinal))),c)) yield return new AstronomyKnowledgeValidationIssue(AstronomyKnowledgeGraphValidationCodes.ProvenanceReferenceBroken, issue.Severity, issue.Message, issue.Path, RuleId, issue.Domain, issue.Family);}}
public sealed class AstronomyGraphVersionConsistencyValidationRule: AstronomyGraphRuleBase { public const string Id="graph.version.consistency"; public override string RuleId=>Id; public override int Order=>700; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyKnowledgeGraphValidationSet g,AstronomyKnowledgeGraphValidationContext c){foreach(var grp in g.Statements.Select((s,i)=>(s,i)).GroupBy(x=>x.s.Id)){var revs=grp.Select(x=>x.s.Version.Revision).OrderBy(x=>x).ToArray(); if(revs.Distinct().Count()!=revs.Length){var first=grp.First(); var(d,f)=Meta(first.s); yield return Issue(AstronomyKnowledgeGraphValidationCodes.VersionConflict,AstronomyKnowledgeValidationSeverity.Error,"Statement revision is duplicated.",$"$.statements[{first.i}]",RuleId,d,f);} if(revs.Length>0&&revs[0]!=1){var first=grp.First(); var(d,f)=Meta(first.s); yield return Issue(AstronomyKnowledgeGraphValidationCodes.RevisionOrderInvalid,AstronomyKnowledgeValidationSeverity.Error,"Statement revisions must start at revision 1.",$"$.statements[{first.i}].version",RuleId,d,f);}}}}
public sealed class AstronomyGraphCycleValidationRule: AstronomyGraphRuleBase { public const string Id="graph.cycle.integrity"; public override string RuleId=>Id; public override int Order=>800; static bool Forbidden(AstronomyKnowledgeGraphRelationshipKind k)=>k is AstronomyKnowledgeGraphRelationshipKind.DerivedFrom or AstronomyKnowledgeGraphRelationshipKind.ParentOf or AstronomyKnowledgeGraphRelationshipKind.Supersedes or AstronomyKnowledgeGraphRelationshipKind.Contains; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyKnowledgeGraphValidationSet g,AstronomyKnowledgeGraphValidationContext c){var edges=g.Relationships.Select((r,i)=>(r,i)).Where(x=>Forbidden(x.r.Kind)).ToArray(); foreach(var e in edges) if(e.r.SourceId==e.r.TargetId) yield return Issue(AstronomyKnowledgeGraphValidationCodes.ForbiddenSelfReference,AstronomyKnowledgeValidationSeverity.Error,"Forbidden relationship self-reference.",$"$.relationships[{e.i}]",RuleId); foreach(var e in edges){var seen=new HashSet<string>(StringComparer.Ordinal); var stack=new Stack<string>(); stack.Push(e.r.TargetId); while(stack.Count>0){var n=stack.Pop(); if(!seen.Add(n))continue; if(n==e.r.SourceId){yield return Issue(AstronomyKnowledgeGraphValidationCodes.CycleDetected,AstronomyKnowledgeValidationSeverity.Error,"Forbidden relationship cycle detected.",$"$.relationships[{e.i}]",RuleId); break;} foreach(var next in edges.Where(x=>x.r.SourceId==n).OrderBy(x=>x.r.TargetId,StringComparer.Ordinal)) stack.Push(next.r.TargetId);}}}}
public sealed class AstronomyGraphOrphanValidationRule: AstronomyGraphRuleBase { public const string Id="graph.orphan.integrity"; public override string RuleId=>Id; public override int Order=>900; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyKnowledgeGraphValidationSet g,AstronomyKnowledgeGraphValidationContext c){var refs=new HashSet<string>(g.Relationships.SelectMany(r=>new[]{r.SourceId,r.TargetId}).Concat(g.Statements.Select(s=>s.PrimarySubject.EntityId)).Concat(g.RootIds).Concat(c.RootScopeIds),StringComparer.Ordinal); var sev=c.Mode==AstronomyKnowledgeValidationMode.Standard?AstronomyKnowledgeValidationSeverity.Warning:AstronomyKnowledgeValidationSeverity.Error; for(var i=0;i<g.Nodes.Count;i++) if(!refs.Contains(g.Nodes[i].NodeId)) yield return Issue(AstronomyKnowledgeGraphValidationCodes.OrphanEntity,sev,"Graph entity node is not referenced.",$"$.nodes[{i}]",RuleId); for(var i=0;i<g.Statements.Count;i++) if(!refs.Contains(g.Statements[i].Id.Value)&&!g.RootIds.Contains(g.Statements[i].Id.Value)) yield return Issue(AstronomyKnowledgeGraphValidationCodes.OrphanStatement,sev,"Graph statement is not reachable from a root or relationship.",$"$.statements[{i}]",RuleId);}}
public sealed class AstronomyGraphConnectivityValidationRule: AstronomyGraphRuleBase { public const string Id="graph.connectivity.integrity"; public override string RuleId=>Id; public override int Order=>1000; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyKnowledgeGraphValidationSet g,AstronomyKnowledgeGraphValidationContext c){if(c.Policy.ConnectivityPolicy!=AstronomyKnowledgeGraphConnectivityPolicy.ConnectedScopeRequired) yield break; var roots=(c.RootScopeIds.Count>0?c.RootScopeIds:g.RootIds).ToArray(); if(roots.Length==0){yield return Issue(AstronomyKnowledgeGraphValidationCodes.DisconnectedComponent,AstronomyKnowledgeValidationSeverity.Error,"Connected graph validation requires at least one root.","$.roots",RuleId); yield break;} var all=g.Nodes.Select(n=>n.NodeId).Concat(g.Statements.Select(s=>s.Id.Value)).Distinct(StringComparer.Ordinal).ToArray(); var seen=new HashSet<string>(roots,StringComparer.Ordinal); bool changed; do{changed=false; foreach(var r in g.Relationships) if(seen.Contains(r.SourceId)&&seen.Add(r.TargetId)||seen.Contains(r.TargetId)&&seen.Add(r.SourceId)) changed=true;}while(changed); foreach(var id in all.Where(x=>!seen.Contains(x)).OrderBy(x=>x,StringComparer.Ordinal).Take(1)) yield return Issue(AstronomyKnowledgeGraphValidationCodes.DisconnectedComponent,AstronomyKnowledgeValidationSeverity.Error,"Graph contains a disconnected component.","$.relationships",RuleId);}}
public sealed class AstronomyGraphRepositoryConsistencyValidationRule: AstronomyGraphRuleBase { public const string Id="graph.repository.consistency"; public override string RuleId=>Id; public override int Order=>1100; public override IEnumerable<AstronomyKnowledgeValidationIssue> Validate(AstronomyKnowledgeGraphValidationSet g,AstronomyKnowledgeGraphValidationContext c){if(c.ExpectedRepositoryId is not null && !StringComparer.Ordinal.Equals(c.ExpectedRepositoryId,g.RepositoryId)) yield return Issue(AstronomyKnowledgeGraphValidationCodes.RepositoryIdentityMismatch,AstronomyKnowledgeValidationSeverity.Error,"Graph repository identity does not match the expected repository.","$.repositoryId",RuleId); if(c.Policy.RequireRepositoryRoot && g.RootIds.Count==0) yield return Issue(AstronomyKnowledgeGraphValidationCodes.RepositoryRootMissing,AstronomyKnowledgeValidationSeverity.Error,"Graph repository root is required.","$.roots",RuleId); if(c.Policy.RequireUniqueRoots && g.RootIds.Distinct(StringComparer.Ordinal).Count()!=g.RootIds.Count) yield return Issue(AstronomyKnowledgeGraphValidationCodes.RepositoryScopeConflict,AstronomyKnowledgeValidationSeverity.Error,"Graph repository roots must be unique.","$.roots",RuleId); if(c.ExpectedRepositoryVersion is not null && !StringComparer.Ordinal.Equals(c.ExpectedRepositoryVersion,g.RepositoryVersion)) yield return Issue(AstronomyKnowledgeGraphValidationCodes.RepositoryScopeConflict,AstronomyKnowledgeValidationSeverity.Error,"Graph repository version does not match the expected version.","$.repositoryVersion",RuleId);}}

public static class AstronomyKnowledgeGraphValidationRegistrationExtensions
{ public static IServiceCollection AddAstronomyKnowledgeGraphValidation(this IServiceCollection services){ArgumentNullException.ThrowIfNull(services); services.AddAstronomyKnowledgeValidation(); services.TryAddSingleton<IAstronomyTypedPayloadRegistry>(_=>new AstronomyTypedPayloadRegistry(AstronomyBuiltInTypedPayloadDescriptors.BuiltIn)); Add<AstronomyGraphNodeIdentityValidationRule>(services,AstronomyGraphNodeIdentityValidationRule.Id,100); Add<AstronomyGraphStatementIdentityValidationRule>(services,AstronomyGraphStatementIdentityValidationRule.Id,200); Add<AstronomyGraphReferenceIntegrityValidationRule>(services,AstronomyGraphReferenceIntegrityValidationRule.Id,300); Add<AstronomyGraphPayloadCompletenessValidationRule>(services,AstronomyGraphPayloadCompletenessValidationRule.Id,400); Add<AstronomyGraphDuplicateKnowledgeValidationRule>(services,AstronomyGraphDuplicateKnowledgeValidationRule.Id,500); Add<AstronomyGraphProvenanceValidationRule>(services,AstronomyGraphProvenanceValidationRule.Id,600); Add<AstronomyGraphVersionConsistencyValidationRule>(services,AstronomyGraphVersionConsistencyValidationRule.Id,700); Add<AstronomyGraphCycleValidationRule>(services,AstronomyGraphCycleValidationRule.Id,800); Add<AstronomyGraphOrphanValidationRule>(services,AstronomyGraphOrphanValidationRule.Id,900); Add<AstronomyGraphConnectivityValidationRule>(services,AstronomyGraphConnectivityValidationRule.Id,1000); Add<AstronomyGraphRepositoryConsistencyValidationRule>(services,AstronomyGraphRepositoryConsistencyValidationRule.Id,1100); services.TryAddSingleton<IAstronomyKnowledgeGraphValidationRuleRegistry>(p=>new AstronomyKnowledgeGraphValidationRuleRegistry(p.GetServices<AstronomyKnowledgeGraphValidationRuleDescriptor>())); services.TryAddSingleton<IAstronomyKnowledgeGraphValidator,AstronomyKnowledgeGraphValidator>(); return services;} static void Add<T>(IServiceCollection s,string id,int order) where T:class,IAstronomyKnowledgeGraphValidationRule { s.TryAddEnumerable(ServiceDescriptor.Singleton<IAstronomyKnowledgeGraphValidationRule,T>()); var d=new AstronomyKnowledgeGraphValidationRuleDescriptor(id,typeof(T),order); if(!s.Any(x=>x.ServiceType==typeof(AstronomyKnowledgeGraphValidationRuleDescriptor)&&Equals(x.ImplementationInstance,d))) s.AddSingleton(d); } }
