using System.Collections.Immutable;
using System.Text.Json.Serialization;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Contracts;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Adapters.Contracts;
using Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Sources.Contracts;

namespace Astronomy.MediaFactory.Infrastructure.Production.Narration.Semantics.Resolution.V1.Contracts;

public enum SemanticRequirementLevelV1 { Optional, Required, CertifiedRequired }
public enum SemanticMissingValueBehaviorV1 { OmitOptional, BlockRequired, FutureUnavailable }
public enum SemanticResolutionStatusV1 { Resolved, ResolvedByCombination, UnavailableOptional, MissingRequiredValue, InvalidRequiredValue, ConflictBlocked, NoApprovedSource, NoRegisteredAdapter, InsufficientEvidence, PolicyRejected, ArchitectureError }
public enum SemanticCandidateDispositionV1 { Eligible, Missing, SourceUnavailable, Invalid, Unverified, UnsupportedSourceShape, RejectedByPolicy, CapabilityMismatch, SourceNotApproved, EvidenceCategoryRejected, InsufficientEvidence, CompatibilityOnlyRejected, IncompleteProvenance, TypeIncompatible, FamilyIncompatibleCandidate }
public enum SemanticConflictStatusV1 { Agreement, EquivalentNormalized, Complementary, MaterialDisagreement, UnitNormalizableAgreement, ProvenanceDuplicate, SameSourceDuplicate, EquallyTrustedCompetition, IncompatibleValueTypes }
public enum SemanticTieBreakReasonV1 { HigherEvidenceStrength, SourcePriority, ProvenanceCompleteness, NonCompatibilitySource, StructuredCompleteness, Confidence, AdapterIdOrdinal, CandidateIdOrdinal, SingleCandidate, PolicySelected, NoSelection, StructuredCombination }
public enum SemanticResolutionTraceStageV1 { PolicyLoaded, AdaptersDiscovered, AdapterInvoked, CandidateCollected, CandidateRejected, CandidateEvaluated, ConflictDetected, CandidateSelected, StructuredFieldsCombined, ResolutionCompleted }

public sealed record SemanticResolutionRequestV1(SemanticCapabilityId CapabilityId, bool Required, SemanticRequirementLevelV1 RequirementLevel, SemanticMissingValueBehaviorV1 MissingValueBehavior, SemanticEvidenceStrengthV1 MinimumEvidenceStrength, ImmutableArray<SemanticEvidenceCategoryV1> AllowedEvidenceCategories, SemanticSourceAdapterContextV1 AdapterContext, string? FamilyIdForDiagnostics=null, string? FormatForDiagnostics=null, string? BeatIdForDiagnostics=null, string? CorrelationId=null)
{ public SemanticResolutionRequestV1(SemanticCapabilityId capabilityId,bool required,SemanticRequirementLevelV1 requirementLevel,SemanticMissingValueBehaviorV1 missingValueBehavior,SemanticEvidenceStrengthV1 minimumEvidenceStrength,IEnumerable<SemanticEvidenceCategoryV1> allowedEvidenceCategories,SemanticSourceAdapterContextV1 adapterContext,string? familyIdForDiagnostics=null,string? formatForDiagnostics=null,string? beatIdForDiagnostics=null,string? correlationId=null) : this(capabilityId,required,requirementLevel,missingValueBehavior,minimumEvidenceStrength,allowedEvidenceCategories.ToImmutableArray(),adapterContext,familyIdForDiagnostics,formatForDiagnostics,beatIdForDiagnostics,correlationId){} }

public sealed record SemanticCandidateScoreV1(ImmutableArray<string> Components)
{ public SemanticCandidateScoreV1(IEnumerable<string> components):this(components.ToImmutableArray()){} }
public sealed record SemanticCandidateEvaluationV1(string CandidateId, SemanticCapabilityId CapabilityId, string AdapterId, string SourceId, bool Eligible, SemanticCandidateDispositionV1 Disposition, SemanticEvidenceStrengthV1 EvidenceStrength, int SourcePriority, decimal Confidence, string ConfidenceBand, bool ProvenanceComplete, bool PolicyApproved, bool CompatibilityOnly, ImmutableArray<string> ValidationIssues, ImmutableArray<string> EvaluationWarnings, SemanticCandidateScoreV1 DeterministicScoreComponents, string? RejectionReason);
public sealed record SemanticConflictV1(string ConflictId, SemanticCapabilityId CapabilityId, ImmutableArray<string> CandidateIds, SemanticConflictStatusV1 ConflictType, bool Material, bool Resolvable, string ResolutionRule, string DiagnosticCode, string DiagnosticMessage)
{ public SemanticConflictV1(string conflictId,SemanticCapabilityId capabilityId,IEnumerable<string> candidateIds,SemanticConflictStatusV1 conflictType,bool material,bool resolvable,string resolutionRule,string diagnosticCode,string diagnosticMessage):this(conflictId,capabilityId,candidateIds.Order(StringComparer.Ordinal).ToImmutableArray(),conflictType,material,resolvable,resolutionRule,diagnosticCode,diagnosticMessage){} }
public sealed record SemanticConflictSetV1(SemanticCapabilityId CapabilityId, ImmutableArray<SemanticConflictV1> Conflicts)
{ public bool HasBlockingMaterialConflict => Conflicts.Any(c=>c.Material&&!c.Resolvable); public SemanticConflictSetV1(SemanticCapabilityId capabilityId,IEnumerable<SemanticConflictV1> conflicts):this(capabilityId,conflicts.OrderBy(c=>c.ConflictId,StringComparer.Ordinal).ToImmutableArray()){} }
public sealed record SemanticCandidateSelectionV1(SemanticResolutionStatusV1 Status, SemanticSourceCandidateV1? SelectedCandidate, ImmutableArray<SemanticSourceCandidateV1> RejectedCandidates, ImmutableArray<SemanticTieBreakReasonV1> TieBreakReasons, string ResolutionPolicy, string? DiagnosticCode, string? DiagnosticMessage, bool Combined=false);
public sealed record SemanticResolutionTraceEntryV1(SemanticResolutionTraceStageV1 Stage, string Code, string Message, string? AdapterId=null, string? CandidateId=null);
public sealed record SemanticCandidateCollectionV1(SemanticCapabilityId CapabilityId,string? SourcePolicyId,string? SourcePolicyVersion,ImmutableArray<SemanticSourceAdapterResultV1> AdapterResults,ImmutableArray<SemanticSourceCandidateV1> Candidates,ImmutableArray<SemanticSourceRejectionV1> Rejections,ImmutableArray<string> MissingApprovedAdapterIds,ImmutableArray<string> InvokedAdapterIds,ImmutableArray<string> SkippedAdapterIds,ImmutableArray<string> CollectionWarnings,ImmutableArray<string> CollectionErrors,ImmutableArray<string> DeterministicInvocationOrder, SemanticSourcePolicyV1? SourcePolicy);
public sealed record ResolvedSemanticFactV1(SemanticCapabilityId CapabilityId, SemanticResolutionStatusV1 Status, bool Required, SemanticSourceValueV1? TypedValue, string? CanonicalValue, string? SpeakableValue, string? WinningCandidateId, string? WinningAdapterId, string? WinningSourceId, SemanticEvidenceCategoryV1? EvidenceCategory, SemanticEvidenceStrengthV1 EvidenceStrength, decimal Confidence, ImmutableArray<SemanticSourceProvenanceV1> Provenance, ImmutableArray<string> CombinedSourceIds, ImmutableArray<SemanticSourceCandidateV1> RejectedCandidates, ImmutableArray<SemanticConflictV1> Conflicts, string ResolutionPolicy, ImmutableArray<SemanticTieBreakReasonV1> TieBreakReasons, ImmutableArray<string> Warnings, string DiagnosticCode, string DiagnosticMessage);
public sealed record SemanticResolutionDiagnosticsV1(SemanticCapabilityId CapabilityId,bool Required,string? PolicyVersion,int CandidateCount,int EligibleCandidateCount,int RejectedCandidateCount,ImmutableArray<string> InvokedAdapterIds,ImmutableArray<string> MissingApprovedAdapterIds,ImmutableArray<SemanticCandidateEvaluationV1> CandidateEvaluations,ImmutableArray<SemanticConflictV1> Conflicts,string? SelectedCandidateId,SemanticResolutionStatusV1 ResolutionStatus,string ResolutionPolicy,ImmutableArray<SemanticTieBreakReasonV1> TieBreakReasons,ImmutableArray<string> BlockingErrors,ImmutableArray<string> Warnings,ImmutableArray<SemanticResolutionTraceEntryV1> TraceEntries);
public sealed record SemanticResolutionResultV1(ResolvedSemanticFactV1 Fact, SemanticResolutionDiagnosticsV1 Diagnostics);
