using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.TypedDomains.Temporal;
using Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
namespace Astronomy.MediaFactory.Core.KnowledgeFoundation.Validation.Temporal;
public static class AstronomyTemporalValidationRegistrationExtensions
{
 public static IServiceCollection AddAstronomyTemporalValidation(this IServiceCollection services){ArgumentNullException.ThrowIfNull(services); services.AddAstronomyKnowledgeValidation();
 services.AddAstronomyKnowledgeValidationRule<AstronomyTemporalPatternValidationRule,AstronomyTemporalPatternPayload>(AstronomyTemporalPatternValidationRule.Id,AstronomyKnowledgeDomain.Temporal,AstronomyKnowledgePayloadFamily.TemporalCycle,100);
 services.AddAstronomyKnowledgeValidationRule<AstronomyTemporalReferenceContextValidationRule,AstronomyTemporalPatternPayload>(AstronomyTemporalReferenceContextValidationRule.Id,AstronomyKnowledgeDomain.Temporal,AstronomyKnowledgePayloadFamily.TemporalCycle,200);
 services.AddAstronomyKnowledgeValidationRule<AstronomyRecurrenceValidationRule,AstronomyTemporalPatternPayload>(AstronomyRecurrenceValidationRule.Id,AstronomyKnowledgeDomain.Temporal,AstronomyKnowledgePayloadFamily.TemporalCycle,300);
 services.AddAstronomyKnowledgeValidationRule<AstronomyCyclePeriodValidationRule,AstronomyTemporalPatternPayload>(AstronomyCyclePeriodValidationRule.Id,AstronomyKnowledgeDomain.Temporal,AstronomyKnowledgePayloadFamily.TemporalCycle,400);
 services.AddAstronomyKnowledgeValidationRule<AstronomyTemporalAnchorValidationRule,AstronomyTemporalPatternPayload>(AstronomyTemporalAnchorValidationRule.Id,AstronomyKnowledgeDomain.Temporal,AstronomyKnowledgePayloadFamily.TemporalCycle,500);
 services.AddAstronomyKnowledgeValidationRule<AstronomyTemporalPhaseValidationRule,AstronomyTemporalPatternPayload>(AstronomyTemporalPhaseValidationRule.Id,AstronomyKnowledgeDomain.Temporal,AstronomyKnowledgePayloadFamily.TemporalCycle,600);
 services.AddAstronomyKnowledgeValidationRule<AstronomyTemporalOccurrenceValidationRule,AstronomyTemporalPatternPayload>(AstronomyTemporalOccurrenceValidationRule.Id,AstronomyKnowledgeDomain.Temporal,AstronomyKnowledgePayloadFamily.TemporalCycle,700);
 services.AddAstronomyKnowledgeValidationRule<AstronomySeasonalPatternValidationRule,AstronomyTemporalPatternPayload>(AstronomySeasonalPatternValidationRule.Id,AstronomyKnowledgeDomain.Temporal,AstronomyKnowledgePayloadFamily.TemporalCycle,800);
 services.AddAstronomyKnowledgeValidationRule<AstronomyTemporalApplicabilityValidationRule,AstronomyTemporalPatternPayload>(AstronomyTemporalApplicabilityValidationRule.Id,AstronomyKnowledgeDomain.Temporal,AstronomyKnowledgePayloadFamily.TemporalCycle,900); return services;}
}
